<?php

/**
 * @file
 * Allows domain language restriction.
 */

use Drupal\Core\Url;
use Drupal\domain\DomainInterface;
use Drupal\domain\DomainNegotiatorInterface;

/**
 * Implements hook_language_switch_links_alter().
 */
function domain_language_language_switch_links_alter(array &$links, $type, $path) {
  if ($type == 'language_interface') {
    /** @var DomainNegotiatorInterface $negotiator */
    $negotiator = \Drupal::service('domain.negotiator');

    /** @var DomainInterface $domain */
    if ($domain = $negotiator->getActiveDomain()) {
      $name = 'domain.language.' . $domain->getOriginalId() . '.language.negotiation';
      $languages = \Drupal::configFactory()->get($name)->get('languages');

      // Restrict to those explicitly defined.
      if (!empty($languages)) {
        $links = array_intersect_key($links, $languages);
      }
    }
  }
}

/**
 * Implements hook_domain_operations().
 */
function domain_language_domain_operations(DomainInterface $domain) {
  // Add aliases to the list.
  $id = $domain->id();
  $operations['domain_language'] = [
    'title' => t('Languages'),
    'url' => Url::fromRoute('domain_language.admin', ['domain' => $id]),
    'weight' => 70,
  ];
  return $operations;
}
