<?php

/**
 * @file
 * UIkit GUI.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uikit_gui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.uikit_gui':
      return t('
        <p>The GUI will speed up design and development of websites considerably and providing a rapid and streamlined workflow for adding features like slideshows, accordions, tabs, grid stacks, animations all from a single back-end page.</p>
      ');
  }
}
