<?php

/**
 * @file
 * Primary module hooks for Snippet metatag module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\snippet_manager\SnippetInterface;

/**
 * Implements hook_entity_type_build().
 */
function snippet_metatag_entity_type_build(array &$entity_types) {
  $entity_types['snippet']->setFormClass('metatag_edit', 'Drupal\snippet_metatag\Form\MetatagForm');
  $entity_types['snippet']->setLinkTemplate('metatag-form', '/admin/structure/snippet/{snippet}/metatags');
}

/**
 * Implements hook_metatag_route_entity().
 */
function snippet_metatag_metatag_route_entity(RouteMatchInterface $route_match) {
  if (strpos($route_match->getRouteName(), 'entity.snippet.page.') === 0) {
    return $route_match->getParameter('snippet');
  }
}

/**
 * Implements hook_metatags_alter().
 */
function snippet_metatag_metatags_alter(array &$metatags, array $context) {
  if ($context['entity'] instanceof SnippetInterface) {
    $snippet_metatags = $context['entity']->getThirdPartySetting('snippet_metatag', 'metatags');
    if (is_array($snippet_metatags)) {
      $metatags = $snippet_metatags + $metatags;
    }
  }
}
