<?php

/**
 * @file
 * Custom view filters.
 */

/**
 * Implements hook_views_data_alter().
 */
function custom_view_filters_views_data_alter(array &$data) {

  $data['node_field_data']['custom_az_filter'] = [
    'title' => t('Custom AZ filter'),
    'filter' => [
      'title' => t('Custom AZ filter'),
      'help' => t('Filter nodes given A-Z'),
      'field' => 'title',
      'id' => 'custom_az_filter',
    ],
  ];

  $data['node_field_data']['nodes_granular_dates'] = [
    'title' => t('Node granular date filter'),
    'filter' => [
      'title' => t('Node granular date filter'),
      'help' => t('Node granular date filter.'),
      'field' => 'title',
      'id' => 'node_granular_date_filter',
    ],
  ];

}
