<?php

/**
 * @file
 *  Adds some bonus features to the replicate and replicate UI modules in D8.
 */

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function replicate_bonus_form_replicate_ui__settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $config = \Drupal::configFactory()->get('replicate_ui.settings');
  $form['unpublished_state'] = [
    '#type' => 'checkbox',
    '#title' => t('Set cloned nodes as unpublished'),
    '#default_value' => $config->get('unpublished_state'),
    '#description' => t('If checked, the cloned nodes will be set as unpublished.'),
  ];
  $form['#submit'][] = 'replicate_bonus_form_replicate_ui__settings_submit';
}

/**
 * Additional submit handler for replicate form to save the unpublished state configuration.
 */
function replicate_bonus_form_replicate_ui__settings_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state) {
  \Drupal::configFactory()->getEditable('replicate_ui.settings')
    ->set('unpublished_state', $form_state->getValue('unpublished_state'))
    ->save(TRUE);
}

/**
 * Implements hook_form_alter().
 */
function replicate_bonus_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'node_') === 0 && strpos($form_id, '_replicate_form') !== FALSE) {
    // Add an additional submit handler that will alter the redirect of the form.
    $form['actions']['submit']['#submit'][] = 'replicate_bonus_node_form_submit';
  }
}

/**
 * Submit handler for redirecting to the replicated node edit form after replicating.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function replicate_bonus_node_form_submit($form, FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  if (!empty($node)) {
    if ($node instanceof \Drupal\node\NodeInterface) {
      $redirect = $form_state->getRedirect();
      $form_state->setRedirect('entity.node.edit_form', $redirect->getRouteParameters());
    }
  }
}
