<?php

use Drupal\Core\Url;

/**
 * @file
 * Primary module hooks for Trackduck module.
 *
 */
function trackduck_integration_page_attachments(array &$attachments) {
  $src = '//cdn.trackduck.com/toolbar/prod/td.js';
  $user = \Drupal::currentUser();
  $trackduck = \Drupal::configFactory()->get('trackduck_integration.settings');

  if($user->hasPermission('use trackduck_integration') && $trackduck->get('enable')){
    $attachments['#attached']['html_head'] = [
      [
        [
          '#tag' => 'script',
          '#attributes' => [
            'src' => Url::fromUri($src)->toString(),
            'async' => TRUE,
            'data-trackduck-id' => $trackduck->get('key'),
          ],
        ],
        'trackduck_integration',
      ],
    ];
  }
}
