<?php

/**
 * @file
 * Contains an example for the overview_field module.
 */

/**
 * Implements hook_overview_field_options_alter().
 *
 * Add an option to the overview field.
 */
function overview_field_example_overview_field_options_alter(&$options) {
  $options['recent_content'] = t('Show a list of the recent content on the site');
}

/**
 * Implements hook_overview_field_output_alter().
 */
function overview_field_example_overview_field_output_alter($key, &$output) {
  if ($key == 'recent_content') {
    $output = overview_field_load_view('content_recent', 'block_1');
  }
}
