<?php

/**
 * @file
 * Contains pagedesigner_media.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pagedesigner_media_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the pagedesigner_media module.
        case 'help.page.pagedesigner_media':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Pagedesigner media integration') . '</p>';
            return $output;
        default:
    }
}
