<?php

/**
 * @file
 * Module for Boxout.
 */

use Drupal\editor\Entity\Editor;

/**
 * Implements hook_preprocess_page().
 */
function boxout_ckeditor_css_alter(array &$css, Editor $editor) {
  $css[] = drupal_get_path('module', 'boxout') . '/css/boxout.css';
}

/**
 * Implements hook_preprocess_page().
 */
function boxout_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'boxout/boxout';
}
