<?php

function paypal_marketing_solutions_page_attachments(array &$attachments) {
    $config = \Drupal::service('config.factory')->getEditable('paypal_marketing_solutions.settings');
    $cid = $config->get('id');
    if (!empty($cid)) {
        $attachments['#attached']['drupalSettings']['paypal_marketing_solutions']['cid'] = $cid;
        $attachments['#attached']['library'][] = 'paypal_marketing_solutions/paypal_marketing_solutions_beg';
    }
}

function paypal_marketing_solutions_twigpaypal_marketing_solutions_theme() {
    return [
        'paypal_admin' => [
            'variables' => ['img_path' => file_create_url(
                drupal_get_path('module', 'paypal_marketing_solutions') . '/images/expand-icon.png'
            )],
        ],
    ];
}
