<?php

/**
 * @file
 * Extended Path Aliases.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function path_alias_xt_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.path_alias_xt':
      $output = '<p>';
      $output .= t('Installation instructions are in the README.txt file. Further documentation is on the <a href="@path_alias_xt">Extended Path Aliases</a> project page.',
        ['@path_alias_xt' => Url::fromUri('http://drupal.org/project/path_alias_xt')->toString()]);
      $output .= '</p>';

      return ['#markup' => $output];
  }
}
