<?php
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @file
 * The Headline Group module provides new field types. This field provides a
 * mechanism to add subheads and "superheads" -- text above a headline -- to
 * headlines in a semantic and flexible manner.
 */

/**
 * Implements hook_help().
 */
function headline_group_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.headline_group':
      $readme = __DIR__ . '/README.txt';
      $text = file_get_contents($readme);
      $output = '';

      // If the Markdown module is installed, use it to render the README.
      if ($text && \Drupal::moduleHandler()->moduleExists('markdown') === TRUE) {
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        $output = $filter->process($text, 'en');
      }
      // Else the Markdown module is not installed output the README as text.
      else if ($text) {
        $output = '<pre>' . $text . '</pre>';
      }

      // Add a link to the Drupal.org project.
      $output .= '<p>';
      $output .= t('Visit the <a href=":project_link">project pages</a> on Drupal.org for more information.',[
        ':project_link' => 'https://www.drupal.org/project/headline_group'
        ]);
      $output .= '</p>';

      return $output;
  }

}
