<?php

/**
 * @file
 * Holds hooks for the Private Message Flood Protection module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function private_message_flood_form_private_message_form_alter(array &$form, FormStateInterface $formState) {
  // Adds a custom validation handler to the form.
  array_unshift($form['#validate'], 'private_message_flood_form_private_message_form_validate');
}

/**
 * Custom validation handler for private message form.
 *
 * Checks if a user has reached their flood limit.
 */
function private_message_flood_form_private_message_form_validate(array $form, FormStateInterface $formState) {
  if (\Drupal::service('private_message_flood.service')->checkUserFlood()) {
    $formState->setError($form['message'], t('Sorry, you have reached your limit for posting. Please try again later.'));
  }

}
