<?php

/**
 * @file
 * Primary module hooks for Image Hover Effects module.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function image_hover_effects_theme($existing, $type, $theme, $path) {
  return [
    'image_hover_effects_image_formatter' => [
      'variables' => [
        'item' => NULL,
        'item_attributes' => NULL,
        'url' => NULL,
        'image_style' => NULL,
        'link_attributes' => NULL,
      ],
    ],
    'image_hover_effects_responsive_image_formatter' => array(
      'variables' => array(
        'item' => NULL,
        'item_attributes' => NULL,
        'url' => NULL,
        'responsive_image_style_id' => NULL,
        'link_attributes' => NULL,
      ),
    ),
  ];
}

/**
 * Prepares variables for image formatter templates.
 */
function template_preprocess_image_hover_effects_image_formatter(&$variables) {
  module_load_include('inc', 'image', 'image.field');
  template_preprocess_image_formatter($variables);
  $variables['link_attributes'] = new Attribute($variables['link_attributes']);
}

/**
 * Prepares variables for responsive image formatter templates.
 */
function template_preprocess_image_hover_effects_responsive_image_formatter(&$variables) {
  template_preprocess_responsive_image_formatter($variables);
  $variables['link_attributes'] = new Attribute($variables['link_attributes']);
}
