<?php

/**
 * @file
 * Main module functions.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\ds_chains\ChainsUi;

/**
 * Implements hook_form_FORM_ID_alter() for entity_view_display_edit_form().
 */
function ds_chains_form_entity_view_display_edit_form_alter(&$form, FormStateInterface $form_state) {
  \Drupal::classResolver()->getInstanceFromDefinition(ChainsUi::class)->alterFieldUiManageDisplay($form, $form_state);
}
