<?php

/**
 * @file
 * Contains smsc.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function smsc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the smsc module.
    case 'help.page.smsc':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide integration for &lt;a href=&quot;https://github.com/awd-studio/smsc&quot; target=&quot;_blank&quot;&gt;SMSC library&lt;/a&gt;.') . '</p>';
      return $output;

    default:
  }
}
