<?php

/**
 * @file
 * Contains bring_postal_code.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\bring_postal_code\LookupTools;

/**
 * Implements hook_form_alter().
 *
 * Add the javascript to chosen forms.
 */
function bring_postal_code_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $ids = \Drupal::config('bring_postal_code.settings')->get('form_ids');
  /** @var \Drupal\bring_postal_code\LookupTools $lookupTools */
  $lookupTools = \Drupal::service('bring_postal_code.lookuptools');
  foreach (preg_split("/\r\n|\n|\r/", $ids) as $id) {
    if ($id == $form_id) {
      $lookupTools->attach($form);
    }
  }
}
