<?php

/**
 * @file
 * Contains webform_quiz.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Routing\RouteMatchInterface;

require_once __DIR__ . '/includes/webform_quiz.theme.inc';
require_once __DIR__ . '/includes/webform_quiz.webform.inc';

/**
 * Implements hook_help().
 */
function webform_quiz_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_quiz module.
    case 'help.page.webform_quiz':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Build awesome quizzes using the webform module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_type_alter().
 *
 * Use custom classes for webform and webform submissions so we can
 * modify the form/view builder to be a quiz.
 */
function webform_quiz_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['webform'])) {
    $webform_entity_type = $entity_types['webform'];

    if ($webform_entity_type instanceof EntityTypeInterface) {
      $webform_entity_type->setFormClass('webform_quiz_settings', '\Drupal\webform_quiz\EntitySettings\WebformQuizWebformSettingsForm');
      $webform_entity_type->setFormClass('webform_quiz_add_form', '\Drupal\webform_quiz\EntitySettings\WebformQuizAddForm');
    }
  }
}
