<?php

/**
 * @file raygun.module
 *
 * Allows all errors and exceptions to be sent to Raygun.io so they are tracked
 * on their dashboard.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function raygun_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the redirect_after_logout module.
    case 'help.page.raygun':
      return check_markup(file_get_contents(drupal_get_path('module', 'raygun') . '/README.txt'));
    }
}

/**
 * Error handler for Raygun.io.
 */
function raygun_error_handler($errno, $errstr, $errfile, $errline ) {
  global $raygunClient;
  $raygunClient->SendError($errno, $errstr, $errfile, $errline);
}

/**
 * Exception handler for Raygun.io.
 */
function raygun_exception_handler($exception) {
  global $raygunClient;
  $raygunClient->SendException($exception);
}

/**
 * Fatal handler for Raygun.io.
 */
function raygun_fatal_error() {
  global $raygunClient;
  $last_error = error_get_last();

  if (!is_null($last_error)) {
    $errno = $last_error['type'];
    $errstr = $last_error['message'];
    $errfile = $last_error['file'];
    $errline = $last_error['line'];
    $raygunClient->SendError($errno, $errstr, $errfile, $errline);
  }
}
