<?php

/**
 * @file
 * Dashboard connector module file.
 */

use Drupal\dashboard_connector\Dashboard;

/**
 * Implements hook_cron().
 */
function dashboard_connector_cron() {
  $config = \Drupal::config('dashboard_connector.settings');
  if (!$config->get('enabled')) {
    return;
  }

  $state = \Drupal::state();
  $last_updated = $state->get('dashboard_connector_last_updated');
  // Only send every 4 hours.
  if (isset($last_updated) && time() - $last_updated < 60 * 60 * 4) {
    return;
  }

  try {
    $snapshot = Dashboard::snapshotBuilder()->buildSnapshot();
    Dashboard::connector()->sendSnapshot($snapshot);
    \Drupal::logger('dashboard_connector')->info('Successfully sent status snapshot');
  }
  catch (\Exception $e) {
    watchdog_exception('dashboard_connector', $e);
  }

  $state->set('dashboard_connector_last_updated', time());
}
