<?php

/**
 * @file
 * Provides some entity sync examples.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function odoo_api_entity_sync_example_user_insert(EntityInterface $entity) {
  /** @var \Drupal\user\UserInterface $user */
  $user = $entity;
  odoo_api_entity_sync_example_sync_user($user);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function odoo_api_entity_sync_example_user_update(EntityInterface $entity) {
  /** @var \Drupal\user\UserInterface $user */
  $user = $entity;
  odoo_api_entity_sync_example_sync_user($user);
}

/**
 * Triggers delayed user sync.
 *
 * @param \Drupal\user\UserInterface $user
 *   The user entity.
 */
function odoo_api_entity_sync_example_sync_user(UserInterface $user) {
  /** @var \Drupal\odoo_api_entity_sync\SyncManagerInterface $sync_service */
  $sync_service = \Drupal::service('odoo_api_entity_sync.sync');
  $sync_service->delayedSync($user->getEntityTypeId(), 'res.partner', 'company', $user->id());
  $sync_service->delayedSync($user->getEntityTypeId(), 'res.partner', 'default', $user->id());
}
