<?php

/**
 * @file
 * Webform Mass Email module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_mass_email_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'webform.config.mass_email':
      return '<p>' . t('This page allows administrators to manage settings for Webform Mass Email module.') . '</p>';
  }
}

/**
 * Implements hook_queue_info_alter().
 */
function webform_mass_email_queue_info_alter(&$queues) {
  // Set cron time based on module settings.
  $config = \Drupal::config('webform_mass_email.settings');
  $queues['webform_mass_email']['cron']['time'] = $config->get('cron');
}

/**
 * Implements hook_mail().
 */
function webform_mass_email_mail($key, &$message, $params) {
  // Sends the given message.
  switch ($key) {
    case 'mass_email':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      // Send this as HTML if set so on the admin page.
      if ($params['html']) {
        $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      }
      break;
  }
}
