<?php

/**
 * @file
 */

$otherAddress = [
  81 => (object) [
    "code" => "81",
    "name" => "香港特别行政区",
    "childs" => [
      (object) [
        "code" => "810200",
        "name" => "九龙",
        "childs" => [
          (object) [
            "code" => "810205",
            "name" => "观塘",
          ],
          (object) [
            "code" => "810204",
            "name" => "黄大仙",
          ],
          (object) [
            "code" => "810201",
            "name" => "九龙城",
          ],
          (object) [
            "code" => "810203",
            "name" => "深水埗",
          ],
          (object) [
            "code" => "810202",
            "name" => "油尖旺",
          ],

        ],
      ],
      (object) [
        "code" => "810100",
        "name" => "香港岛",
        'childs' => [
          (object) [
            "code" => "810103",
            "name" => "东区",
          ],
          (object) [
            "code" => "810104",
            "name" => "南区",
          ],
          (object) [
            "code" => "810102",
            "name" => "湾仔",
          ],
          (object) [
            "code" => "810101",
            "name" => "中西",
          ],

        ],
      ],
      (object) [
        "code" => "810300",
        "name" => "新界",
        "childs" => [
          (object) [
            "code" => "810301",
            "name" => "北区",
          ],
          (object) [
            "code" => "810302",
            "name" => "大埔",
          ],
          (object) [
            "code" => "810308",
            "name" => "葵青",
          ],
          (object) [
            "code" => "810309",
            "name" => "离岛",
          ],
          (object) [
            "code" => "810307",
            "name" => "荃湾",
          ],
          (object) [
            "code" => "810303",
            "name" => "沙田",
          ],
          (object) [
            "code" => "810306",
            "name" => "屯门",
          ],
          (object) [
            "code" => "810304",
            "name" => "西贡",
          ],
          (object) [
            "code" => "810305",
            "name" => "元朗",
          ],
        ],
      ],
    ],
  ],
];

$otherAddress[82] = (object) [
  "code" => "82",
  "name" => "澳门特别行政区",
  "childs" => [
    (object) ["code" => "8201", "name" => "澳门半岛"],
    (object) ["code" => "8202", "name" => "离岛"],
  ],
];

$otherAddress[71] = (object) [
  "code" => "71",
  "name" => "台湾省",
  "childs" => [
    (object) [
      "code" => "7128",
      "name" => "连江",
      "childs" => [
        (object) ["code" => "712806", "name" => "北竿"],
        (object) ["code" => "712808", "name" => "东引"],
        (object) ["code" => "712807", "name" => "莒光"],
        (object) ["code" => "712805", "name" => "南竿"],

      ],
    ],
    (object) [
      "code" => "7102",
      "name" => "高雄",
      "childs" => [
        (object) ["code" => "710246", "name" => "阿莲"],
        (object) ["code" => "710255", "name" => "大寮"],
        (object) ["code" => "710243", "name" => "大社"],
        (object) ["code" => "710258", "name" => "大树"],
        (object) ["code" => "710254", "name" => "凤山"],
        (object) ["code" => "710244", "name" => "冈山"],
        (object) ["code" => "710253", "name" => "湖内"],
        (object) ["code" => "710264", "name" => "甲仙"],
        (object) ["code" => "710241", "name" => "苓雅"],
        (object) ["code" => "710256", "name" => "林园"],
        (object) ["code" => "710261", "name" => "六龟"],
        (object) ["code" => "710245", "name" => "路竹"],
        (object) ["code" => "710267", "name" => "茂林"],
        (object) ["code" => "710260", "name" => "美浓"],
        (object) ["code" => "710251", "name" => "弥陀"],
        (object) ["code" => "710266", "name" => "那玛夏"],
        (object) ["code" => "710262", "name" => "内门"],
        (object) ["code" => "710257", "name" => "鸟松"],
        (object) ["code" => "710249", "name" => "桥头"],
        (object) ["code" => "710268", "name" => "茄萣"],
        (object) ["code" => "710259", "name" => "旗山"],
        (object) ["code" => "710242", "name" => "仁武"],
        (object) ["code" => "710263", "name" => "杉林"],
        (object) ["code" => "710265", "name" => "桃源"],
        (object) ["code" => "710247", "name" => "田寮"],
        (object) ["code" => "710248", "name" => "燕巢"],
        (object) ["code" => "710252", "name" => "永安"],
        (object) ["code" => "710250", "name" => "梓官"],
        (object) ["code" => "710205", "name" => "鼓山"],
        (object) ["code" => "710210", "name" => "楠梓"],
        (object) ["code" => "710202", "name" => "前金"],
        (object) ["code" => "710207", "name" => "前镇"],
        (object) ["code" => "710206", "name" => "旗津"],
        (object) ["code" => "710203", "name" => "芩雅"],
        (object) ["code" => "710208", "name" => "三民"],
        (object) ["code" => "710211", "name" => "小港"],
        (object) ["code" => "710201", "name" => "新兴"],
        (object) ["code" => "710204", "name" => "盐埕"],
        (object) ["code" => "710209", "name" => "左营"],

      ],
    ],
    (object) [
      "code" => "7126",
      "name" => "花莲",
      "childs" => [
        (object) ["code" => "712623", "name" => "丰滨"],
        (object) ["code" => "712621", "name" => "凤林"],
        (object) ["code" => "712628", "name" => "富里"],
        (object) ["code" => "712622", "name" => "光复"],
        (object) ["code" => "712615", "name" => "花莲"],
        (object) ["code" => "712627", "name" => "卓溪"],
        (object) ["code" => "712619", "name" => "吉安"],
        (object) ["code" => "712624", "name" => "瑞穗"],
        (object) ["code" => "712620", "name" => "寿丰"],
        (object) ["code" => "712616", "name" => "新城"],
        (object) ["code" => "712618", "name" => "秀林"],
        (object) ["code" => "712617", "name" => "太鲁"],
        (object) ["code" => "712625", "name" => "万荣"],
        (object) ["code" => "712626", "name" => "玉里"],

      ],
    ],
    (object) [
      "code" => "7119",
      "name" => "嘉义",
      "childs" => [
        (object) ["code" => "711901", "name" => "东区"],
        (object) ["code" => "711902", "name" => "西区"],
        (object) ["code" => "711922", "name" => "阿里山"],
        (object) ["code" => "711926", "name" => "鹿草"],
        (object) ["code" => "711936", "name" => "布袋"],
        (object) ["code" => "711933", "name" => "大林"],
        (object) ["code" => "711924", "name" => "大埔"],
        (object) ["code" => "711929", "name" => "东石"],
        (object) ["code" => "711919", "name" => "番路"],
        (object) ["code" => "711923", "name" => "中埔"],
        (object) ["code" => "711921", "name" => "竹崎"],
        (object) ["code" => "711930", "name" => "六脚"],
        (object) ["code" => "711920", "name" => "梅山"],
        (object) ["code" => "711932", "name" => "民雄"],
        (object) ["code" => "711928", "name" => "朴子"],
        (object) ["code" => "711925", "name" => "水上"],
        (object) ["code" => "711934", "name" => "溪口"],
        (object) ["code" => "711931", "name" => "新港"],
        (object) ["code" => "711927", "name" => "太保"],
        (object) ["code" => "711935", "name" => "义竹"],

      ],
    ],
    (object) [
      "code" => "7107",
      "name" => "基隆",
      "childs" => [
        (object) ["code" => "710705", "name" => "安乐"],
        (object) ["code" => "710706", "name" => "暖暖"],
        (object) ["code" => "710707", "name" => "七堵"],
        (object) ["code" => "710701", "name" => "仁爱"],
        (object) ["code" => "710702", "name" => "信义"],
        (object) ["code" => "710704", "name" => "中山"],
        (object) ["code" => "710703", "name" => "中正"],

      ],
    ],
    (object) [
      "code" => "7105",
      "name" => "金门",
      "childs" => [
        (object) ["code" => "710510", "name" => "金城"],
        (object) ["code" => "710508", "name" => "金湖"],
        (object) ["code" => "710509", "name" => "金宁"],
        (object) ["code" => "710507", "name" => "金沙"],
        (object) ["code" => "710511", "name" => "烈屿"],
        (object) ["code" => "710512", "name" => "乌坵"],
      ],
    ],
    (object) [
      "code" => "7115",
      "name" => "苗栗",
      "childs" => [
        (object) ["code" => "711531", "name" => "大湖"],
        (object) ["code" => "711530", "name" => "公馆"],
        (object) ["code" => "711524", "name" => "后龙"],
        (object) ["code" => "711519", "name" => "竹南"],
        (object) ["code" => "711536", "name" => "卓兰"],
        (object) ["code" => "711527", "name" => "苗栗"],
        (object) ["code" => "711522", "name" => "南庄"],
        (object) ["code" => "711521", "name" => "三湾"],
        (object) ["code" => "711534", "name" => "三义"],
        (object) ["code" => "711523", "name" => "狮潭"],
        (object) ["code" => "711535", "name" => "西湖"],
        (object) ["code" => "711532", "name" => "泰安"],
        (object) ["code" => "711533", "name" => "铜锣"],
        (object) ["code" => "711525", "name" => "通霄"],
        (object) ["code" => "711520", "name" => "头份"],
        (object) ["code" => "711529", "name" => "头屋"],
        (object) ["code" => "711526", "name" => "苑里"],
        (object) ["code" => "711528", "name" => "造桥"],
      ],
    ],
    (object) [
      "code" => "7106",
      "name" => "南投",
      "childs" => [
        (object) ["code" => "710616", "name" => "草屯"],
        (object) ["code" => "710617", "name" => "国姓"],
        (object) ["code" => "710615", "name" => "中寮"],
        (object) ["code" => "710625", "name" => "竹山"],
        (object) ["code" => "710621", "name" => "集集"],
        (object) ["code" => "710626", "name" => "鹿谷"],
        (object) ["code" => "710620", "name" => "名间"],
        (object) ["code" => "710614", "name" => "南投"],
        (object) ["code" => "710618", "name" => "埔里"],
        (object) ["code" => "710619", "name" => "仁爱"],
        (object) ["code" => "710622", "name" => "水里"],
        (object) ["code" => "710624", "name" => "信义"],
        (object) ["code" => "710623", "name" => "鱼池"],
      ],
    ],
    (object) [
      "code" => "7127",
      "name" => "澎湖",
      "childs" => [
        (object) ["code" => "712711", "name" => "白沙"],
        (object) ["code" => "712710", "name" => "七美"],
        (object) ["code" => "712712", "name" => "湖西"],
        (object) ["code" => "712707", "name" => "马公"],
        (object) ["code" => "712708", "name" => "西屿"],
        (object) ["code" => "712709", "name" => "望安"],

      ],
    ],
    (object) [
      "code" => "7124",
      "name" => "屏东",
      "childs" => [
        (object) ["code" => "712442", "name" => "长治"],
        (object) ["code" => "712447", "name" => "潮州"],
        (object) ["code" => "712463", "name" => "车城"],
        (object) ["code" => "712461", "name" => "春日"],
        (object) ["code" => "712455", "name" => "东港"],
        (object) ["code" => "712459", "name" => "枋寮"],
        (object) ["code" => "712460", "name" => "枋山"],
        (object) ["code" => "712440", "name" => "高树"],
        (object) ["code" => "712465", "name" => "恒春"],
        (object) ["code" => "712444", "name" => "竹田"],
        (object) ["code" => "712457", "name" => "佳冬"],
        (object) ["code" => "712438", "name" => "九如"],
        (object) ["code" => "712451", "name" => "崁顶"],
        (object) ["code" => "712449", "name" => "来义"],
        (object) ["code" => "712439", "name" => "里港"],
        (object) ["code" => "712454", "name" => "林边"],
        (object) ["code" => "712443", "name" => "麟洛"],
        (object) ["code" => "712456", "name" => "琉球"],
        (object) ["code" => "712437", "name" => "玛家"],
        (object) ["code" => "712466", "name" => "满州"],
        (object) ["code" => "712464", "name" => "牡丹"],
        (object) ["code" => "712453", "name" => "南州"],
        (object) ["code" => "712445", "name" => "内埔"],
        (object) ["code" => "712434", "name" => "屏东"],
        (object) ["code" => "712435", "name" => "三地门"],
        (object) ["code" => "712462", "name" => "狮子"],
        (object) ["code" => "712452", "name" => "新埤"],
        (object) ["code" => "712458", "name" => "新园"],
        (object) ["code" => "712448", "name" => "泰武"],
        (object) ["code" => "712446", "name" => "万丹"],
        (object) ["code" => "712450", "name" => "万峦"],
        (object) ["code" => "712436", "name" => "雾台"],
        (object) ["code" => "712441", "name" => "盐埔"],
      ],
    ],
    (object) [
      "code" => "7101",
      "name" => "台北",
      "childs" => [
        (object) ["code" => "710109", "name" => "北投"],
        (object) ["code" => "710105", "name" => "大安"],
        (object) ["code" => "710102", "name" => "大同"],
        (object) ["code" => "710111", "name" => "南港"],
        (object) ["code" => "710110", "name" => "内湖"],
        (object) ["code" => "710107", "name" => "信义"],
        (object) ["code" => "710108", "name" => "士林"],
        (object) ["code" => "710104", "name" => "松山"],
        (object) ["code" => "710106", "name" => "万华"],
        (object) ["code" => "710112", "name" => "文山"],
        (object) ["code" => "710103", "name" => "中山"],
        (object) ["code" => "710101", "name" => "中正"],
      ],
    ],
    (object) [
      "code" => "7125",
      "name" => "台东",
      "childs" => [
        (object) ["code" => "712521", "name" => "卑南"],
        (object) ["code" => "712528", "name" => "长滨"],
        (object) ["code" => "712527", "name" => "成功"],
        (object) ["code" => "712525", "name" => "池上"],
        (object) ["code" => "712531", "name" => "达仁"],
        (object) ["code" => "712530", "name" => "大武"],
        (object) ["code" => "712526", "name" => "东河"],
        (object) ["code" => "712523", "name" => "关山"],
        (object) ["code" => "712524", "name" => "海端"],
        (object) ["code" => "712529", "name" => "金峰"],
        (object) ["code" => "712519", "name" => "兰屿"],
        (object) ["code" => "712522", "name" => "鹿野"],
        (object) ["code" => "712518", "name" => "绿岛"],
        (object) ["code" => "712517", "name" => "台东"],
        (object) ["code" => "712532", "name" => "太麻里"],
        (object) ["code" => "712520", "name" => "延平"],
      ],
    ],
    (object) [
      "code" => "7103",
      "name" => "台南",
      "childs" => [
        (object) ["code" => "710369", "name" => "安定"],
        (object) ["code" => "710359", "name" => "白河"],
        (object) ["code" => "710356", "name" => "北门"],
        (object) ["code" => "710366", "name" => "大内"],
        (object) ["code" => "710360", "name" => "东山"],
        (object) ["code" => "710347", "name" => "关庙"],
        (object) ["code" => "710349", "name" => "官田"],
        (object) ["code" => "710340", "name" => "归仁"],
        (object) ["code" => "710358", "name" => "后壁"],
        (object) ["code" => "710351", "name" => "佳里"],
        (object) ["code" => "710354", "name" => "将军"],
        (object) ["code" => "710361", "name" => "六甲"],
        (object) ["code" => "710363", "name" => "柳营"],
        (object) ["code" => "710348", "name" => "龙崎"],
        (object) ["code" => "710350", "name" => "麻豆"],
        (object) ["code" => "710345", "name" => "南化"],
        (object) ["code" => "710344", "name" => "楠西"],
        (object) ["code" => "710353", "name" => "七股"],
        (object) ["code" => "710346", "name" => "仁德"],
        (object) ["code" => "710365", "name" => "善化"],
        (object) ["code" => "710367", "name" => "山上"],
        (object) ["code" => "710362", "name" => "下营"],
        (object) ["code" => "710352", "name" => "西港"],
        (object) ["code" => "710341", "name" => "新化"],
        (object) ["code" => "710368", "name" => "新市"],
        (object) ["code" => "710357", "name" => "新营"],
        (object) ["code" => "710355", "name" => "学甲"],
        (object) ["code" => "710364", "name" => "盐水"],
        (object) ["code" => "710339", "name" => "永康"],
        (object) ["code" => "710343", "name" => "玉井"],
        (object) ["code" => "710342", "name" => "左镇"],
        (object) ["code" => "710306", "name" => "安南"],
        (object) ["code" => "710305", "name" => "安平"],
        (object) ["code" => "710304", "name" => "北区"],
        (object) ["code" => "710302", "name" => "东区"],
        (object) ["code" => "710303", "name" => "南区"],
        (object) ["code" => "710301", "name" => "中西"],
      ],
    ],
    (object) [
      "code" => "7104",
      "name" => "台中",
      "childs" => [
        (object) ["code" => "710451", "name" => "大安"],
        (object) ["code" => "710444", "name" => "大肚"],
        (object) ["code" => "710449", "name" => "大甲"],
        (object) ["code" => "710432", "name" => "大里"],
        (object) ["code" => "710442", "name" => "大雅"],
        (object) ["code" => "710438", "name" => "东势"],
        (object) ["code" => "710435", "name" => "丰原"],
        (object) ["code" => "710439", "name" => "和平"],
        (object) ["code" => "710436", "name" => "后里"],
        (object) ["code" => "710446", "name" => "龙井"],
        (object) ["code" => "710448", "name" => "清水"],
        (object) ["code" => "710445", "name" => "沙鹿"],
        (object) ["code" => "710443", "name" => "神冈"],
        (object) ["code" => "710437", "name" => "石冈"],
        (object) ["code" => "710431", "name" => "太平"],
        (object) ["code" => "710441", "name" => "潭子"],
        (object) ["code" => "710450", "name" => "外埔"],
        (object) ["code" => "710433", "name" => "雾峰"],
        (object) ["code" => "710447", "name" => "梧栖"],
        (object) ["code" => "710434", "name" => "乌日"],
        (object) ["code" => "710440", "name" => "新社"],
        (object) ["code" => "710405", "name" => "北区"],
        (object) ["code" => "710406", "name" => "北屯"],
        (object) ["code" => "710402", "name" => "东区"],
        (object) ["code" => "710403", "name" => "南区"],
        (object) ["code" => "710408", "name" => "南屯"],
        (object) ["code" => "710404", "name" => "西区"],
        (object) ["code" => "710407", "name" => "西屯"],
        (object) ["code" => "710401", "name" => "中区"],
      ],
    ],
    (object) [
      "code" => "7114",
      "name" => "桃园",
      "childs" => [
        (object) ["code" => "711422", "name" => "八德"],
        (object) ["code" => "711423", "name" => "大溪"],
        (object) ["code" => "711425", "name" => "大园"],
        (object) ["code" => "711424", "name" => "复兴"],
        (object) ["code" => "711419", "name" => "观音"],
        (object) ["code" => "711421", "name" => "龟山"],
        (object) ["code" => "711414", "name" => "中坜"],
        (object) ["code" => "711416", "name" => "龙潭"],
        (object) ["code" => "711426", "name" => "芦竹"],
        (object) ["code" => "711415", "name" => "平镇"],
        (object) ["code" => "711418", "name" => "新屋"],
        (object) ["code" => "711420", "name" => "桃园"],
        (object) ["code" => "711417", "name" => "杨梅"],
      ],
    ],
    (object) [
      "code" => "7111",
      "name" => "新北",
      "childs" => [
        (object) ["code" => "711155", "name" => "八里"],
        (object) ["code" => "711132", "name" => "板桥"],
        (object) ["code" => "711156", "name" => "淡水"],
        (object) ["code" => "711139", "name" => "贡寮"],
        (object) ["code" => "711144", "name" => "中和"],
        (object) ["code" => "711131", "name" => "金山"],
        (object) ["code" => "711152", "name" => "林口"],
        (object) ["code" => "711153", "name" => "芦洲"],
        (object) ["code" => "711141", "name" => "坪林"],
        (object) ["code" => "711137", "name" => "平溪"],
        (object) ["code" => "711136", "name" => "瑞芳"],
        (object) ["code" => "711149", "name" => "三重"],
        (object) ["code" => "711157", "name" => "三芝"],
        (object) ["code" => "711146", "name" => "三峡"],
        (object) ["code" => "711134", "name" => "深坑"],
        (object) ["code" => "711135", "name" => "石碇"],
        (object) ["code" => "711158", "name" => "石门"],
        (object) ["code" => "711138", "name" => "双溪"],
        (object) ["code" => "711147", "name" => "树林"],
        (object) ["code" => "711133", "name" => "汐止"],
        (object) ["code" => "711140", "name" => "新店"],
        (object) ["code" => "711150", "name" => "新庄"],
        (object) ["code" => "711151", "name" => "泰山"],
        (object) ["code" => "711145", "name" => "土城"],
        (object) ["code" => "711130", "name" => "万里"],
        (object) ["code" => "711154", "name" => "五股"],
        (object) ["code" => "711142", "name" => "乌来"],
        (object) ["code" => "711148", "name" => "莺歌"],
        (object) ["code" => "711143", "name" => "永和"],

      ],
    ],
    (object) [
      "code" => "7113",
      "name" => "新竹",
      "childs" => [
        (object) ["code" => "711302", "name" => "北区"],
        (object) ["code" => "711301", "name" => "东区"],
        (object) ["code" => "711303", "name" => "香山"],
        (object) ["code" => "711320", "name" => "宝山"],
        (object) ["code" => "711325", "name" => "北埔"],
        (object) ["code" => "711319", "name" => "芎林"],
        (object) ["code" => "711326", "name" => "峨眉"],
        (object) ["code" => "711318", "name" => "关西"],
        (object) ["code" => "711323", "name" => "横山"],
        (object) ["code" => "711315", "name" => "湖口"],
        (object) ["code" => "711314", "name" => "竹北"],
        (object) ["code" => "711321", "name" => "竹东"],
        (object) ["code" => "711324", "name" => "尖石"],
        (object) ["code" => "711316", "name" => "新丰"],
        (object) ["code" => "711317", "name" => "新埔"],
        (object) ["code" => "711322", "name" => "五峰"],

      ],
    ],
    (object) [
      "code" => "7112",
      "name" => "宜兰",
      "childs" => [
        (object) ["code" => "711221", "name" => "大同"],
        (object) ["code" => "711223", "name" => "冬山"],
        (object) ["code" => "711217", "name" => "壮围"],
        (object) ["code" => "711216", "name" => "礁溪"],
        (object) ["code" => "711219", "name" => "罗东"],
        (object) ["code" => "711225", "name" => "南澳"],
        (object) ["code" => "711220", "name" => "三星"],
        (object) ["code" => "711224", "name" => "苏澳"],
        (object) ["code" => "711215", "name" => "头城"],
        (object) ["code" => "711222", "name" => "五结"],
        (object) ["code" => "711214", "name" => "宜兰"],
        (object) ["code" => "711218", "name" => "员山"],
        (object) ["code" => "711226", "name" => "钓鱼"],

      ],
    ],
    (object) [
      "code" => "7121",
      "name" => "云林",
      "childs" => [
        (object) ["code" => "712125", "name" => "褒忠"],
        (object) ["code" => "712136", "name" => "北港"],
        (object) ["code" => "712133", "name" => "莿桐"],
        (object) ["code" => "712122", "name" => "大埤"],
        (object) ["code" => "712126", "name" => "东势"],
        (object) ["code" => "712130", "name" => "斗六"],
        (object) ["code" => "712121", "name" => "斗南"],
        (object) ["code" => "712135", "name" => "二仑"],
        (object) ["code" => "712132", "name" => "古坑"],
        (object) ["code" => "712123", "name" => "虎尾"],
        (object) ["code" => "712138", "name" => "口湖"],
        (object) ["code" => "712131", "name" => "林内"],
        (object) ["code" => "712128", "name" => "仑背"],
        (object) ["code" => "712129", "name" => "麦寮"],
        (object) ["code" => "712137", "name" => "水林"],
        (object) ["code" => "712139", "name" => "四湖"],
        (object) ["code" => "712134", "name" => "西螺"],
        (object) ["code" => "712127", "name" => "台西"],
        (object) ["code" => "712124", "name" => "土库"],
        (object) ["code" => "712140", "name" => "元长"],
      ],
    ],
    (object) [
      "code" => "7117",
      "name" => "彰化",
      "childs" => [
        (object) ["code" => "711744", "name" => "北斗"],
        (object) ["code" => "711750", "name" => "大城"],
        (object) ["code" => "711741", "name" => "大村"],
        (object) ["code" => "711749", "name" => "二林"],
        (object) ["code" => "711752", "name" => "二水"],
        (object) ["code" => "711751", "name" => "芳苑"],
        (object) ["code" => "711728", "name" => "芬园"],
        (object) ["code" => "711732", "name" => "福兴"],
        (object) ["code" => "711734", "name" => "和美"],
        (object) ["code" => "711729", "name" => "花坛"],
        (object) ["code" => "711727", "name" => "彰化"],
        (object) ["code" => "711748", "name" => "竹塘"],
        (object) ["code" => "711731", "name" => "鹿港"],
        (object) ["code" => "711746", "name" => "埤头"],
        (object) ["code" => "711739", "name" => "埔心"],
        (object) ["code" => "711742", "name" => "埔盐"],
        (object) ["code" => "711735", "name" => "伸港"],
        (object) ["code" => "711737", "name" => "社头"],
        (object) ["code" => "711733", "name" => "线西"],
        (object) ["code" => "711740", "name" => "溪湖"],
        (object) ["code" => "711747", "name" => "溪州"],
        (object) ["code" => "711730", "name" => "秀水"],
        (object) ["code" => "711743", "name" => "田中"],
        (object) ["code" => "711745", "name" => "田尾"],
        (object) ["code" => "711738", "name" => "永靖"],
        (object) ["code" => "711736", "name" => "员林"],
      ],
    ],


  ],
];
