<?php

use Drupal\Core\Url;

function structured_data_toolbar_alter(&$items)
{
  $user = \Drupal::currentUser();

  if ($user->hasPermission('manage page structured data json'))
  {
    $page_meta = \Drupal\structured_data\Core\Helper::getCurrentPageMeta(TRUE);

    $querystring = \Drupal::getContainer()->get('request_stack')->getCurrentRequest()->getQueryString();
    if (!empty($querystring))
    {
      $page_meta['url'] = $page_meta['url'] + '?' + $querystring;
    }
    $page_meta['url'] = base64_encode($page_meta['url']);
    $page_meta['url'] = str_replace('/', '|', $page_meta['url']);

    $links = array(
      'sd_json' => array(
        'title' => t('Page Json'),
        'url' => Url::fromRoute('structured_data.page.json', ['sd_route_name' => $page_meta['route_name'], 'sd_url' => $page_meta['url'], 'sd_bundle' => $page_meta['bundle'], 'sd_entity_id' => $page_meta['entity_id']]),
        'attributes' => array(
          'title' => t('Page structured data json'),
          'class' => ['structured-data-page-json-link'],
          'data-url-template' => Url::fromRoute('structured_data.page.json', ['sd_route_name' => $page_meta['route_name'], 'sd_url' => '--template--', 'sd_bundle' => $page_meta['bundle'], 'sd_entity_id' => $page_meta['entity_id']])->toString(),
        ),
        '#cache' => [
          'contexts' => ['user', 'url'],
        ],
      ),
    );

    $items['shortcuts']['tray']['shortcuts']['#links'] += $links;
  }
}

function structured_data_page_attachments_alter(array &$attachments)
{
  $page_meta = \Drupal\structured_data\Core\Helper::getCurrentPageMeta();
  $obj = \Drupal\structured_data\Core\Helper::getPageJson($page_meta);

  if (!empty($obj))
  {
    $tag = [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#attributes' => [
        'type' => 'application/ld+json',
      ],
      '#value' => $obj->json,
    ];

    $attachments['#attached']['html_head'][] = [$tag, 'structured_data_json'];
  }

  $user = \Drupal::currentUser();
  if ($user->hasPermission('manage page structured data json'))
  {
    $attachments['#attached']['library'][] = 'structured_data/toolbar';
  }
}
