<?php

/**
 * @file
 * Contains media_entity_soundcloud.module.
 */

/**
 * Implements hook_theme().
 */
function media_entity_soundcloud_theme($existing, $type, $theme, $path) {
  return [
    'media_soundcloud_embed' => [
      'variables' => [
        'source_id' => NULL,
        'width' => NULL,
        'height' => NULL,
        'type' => NULL,
        'options' => [],
      ],
      'file' => 'media_entity_soundcloud.theme.inc',
    ],
  ];
}
