<?php

namespace Drupal\tmgmt_geartranslations\Geartranslations;
use Drupal\tmgmt\TMGMTException;

/**
 * GearTranslations exception (API)
 *
 * Handle exceptions generated by the GearTranslations API.
 */

class APIException extends TMGMTException {}
