<?php

/**
 * @file
 * Contains layout_builder_tray_resize.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function layout_builder_tray_resize_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the layout_builder_tray_resize module.
    case 'help.page.layout_builder_tray_resize':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides resizing options for the Layout builder tray.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function layout_builder_tray_resize_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'layout_builder_tray_resize/resizer';
}
