<?php

/**
 * @file
 * Allows site administrators to send PR of changed configuration.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function config_pr_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.config_pr':
      $filepath = dirname(__FILE__) . '/README.md';
      if (file_exists($filepath)) {
        $output = nl2br(file_get_contents($filepath));
      }
      return $output;

    case 'config_pr.pull_request':
      $output = '';
      $output .= '<p>' . t('Select the configurations you want to include in the Pull request.') . ' ';
      $output .= t('Visit the <a href=":url">configuration page</a>.', [':url' => Url::fromRoute('config_pr.settings')->toString()]) . '</p>';

      return $output;

    case 'config_pr.settings':
      $uid = \Drupal::currentUser()->id();
      $output = '';
      $output .= '<p>' . t('Select configurations and generate Pull Requests on the  <a href=":url">Pull Requests page</a>.', [':url' => Url::fromRoute('config_pr.pull_request')->toString()]) . '</p>';
      $output .= '<p>' . t('Configure the Authentication token <a target="_blank" href="/user/:uid/edit">on the user page</a>.', [':uid' => $uid]) . '</p>';

      return $output;
  }
}
