<?php

/**
 * @file
 * Block Group module hooks.
 */

use Drupal\blockgroup\Entity\BlockGroupContent;

/**
 * Implements hook_help().
 */
function blockgroup_help($route_name) {
  switch ($route_name) {
    // Main module help for the blockgroup module.
    case 'help.page.blockgroup':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add block groups to block configuration page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_system_info_alter().
 */
function blockgroup_system_info_alter(&$info, $file, $type) {
  if ($type == 'theme') {
    $info['regions'] += blockgroup_region_list();
  }
}

/**
 * Load all the block groups.
 *
 * @return array
 *   Returns the created block groups.
 */
function blockgroup_region_list() {
  $regions = [];
  /** @var \Drupal\blockgroup\BlockGroupContentInterface[] $blockgroups */
  $blockgroups = BlockGroupContent::loadMultiple();
  foreach ($blockgroups as $blockgroup) {
    $regions[$blockgroup->id()] = (string) t('Block group: @label', [
      '@label' => $blockgroup->label(),
    ]);
  }

  return $regions;
}
