<?php

/**
 * @file
 * Provides Mason examples.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_mason_skins_info().
 *
 * To provide own skins, simply provide the legit class namespace, and the class
 * must implement \Drupal\mason\MasonSkinInterface.
 *
 * @see \Drupal\mason\MasonSkinInterface
 */
function mason_example_mason_skins_info() {
  return '\Drupal\mason_example\MasonExampleSkin';
}

/**
 * Implements hook_help().
 */
function mason_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.mason_example':
      return check_markup(file_get_contents(dirname(__FILE__) . '/README.txt'));
  }
}
