<?php

/**
 * @file
 * Module file for go_back.
 *
 * Module for add node and his display in a block.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function go_back_theme($existing, $type, $theme, $path) {
  return [
    'block__goback' => [
      'variables' => [
        'link' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_help().
 */
function go_back_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the Go Back module.
    case 'help.page.go_back':
      $output = '';
      $output .= '<h3>' . t('About Go Back') . '</h3>';
      $output .= '<p>' . t('Allows you to add a block to any type of content.') . '</p>';
      $output .= '<p>' . t('This block adds a button that allows us to return to the previous page that we visited on the site or customize the page where we want it to redirect.') . '</p>';
      return $output;

    default:
  }
}
