<?php

/**
 * @file
 * Contact optional outgoing mail module file.
 */

/**
 * {@inheritdoc}
 */use Drupal\Core\Form\FormStateInterface;

/**
 * {@inheritdoc}
 */
function contact_optional_outgoing_mail_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id !== 'contact_form_add_form' && $form_id !== 'contact_form_edit_form') {
    return;
  }

  // Make 'recipients' optional.
  $form['recipients']['#required'] = FALSE;

  // Add two validators. See the function definitions below.
  array_unshift($form['#validate'], '_contact_optional_outgoing_mail_form_validate');
  $form['#validate'][] = '_contact_optional_outgoing_mail_form_validate_after';
}

/**
 * {@inheritdoc}
 */
function _contact_optional_outgoing_mail_form_validate(array &$form, FormStateInterface $form_state) {
  if (empty($form_state->getValue('recipients'))) {
    // If no recipients are entered, we'll set a dummy value, so we will pass
    // Drupal\contact\ContactFormEditForm:validateForm validation.
    $form_state->setValue('recipients', 'contact_optional_outgoing_mail@contact_optional_outgoing_mail.com');
  }
}

/**
 * {@inheritdoc}
 */
function _contact_optional_outgoing_mail_form_validate_after(array &$form, FormStateInterface $form_state) {
  $recipients = $form_state->getValue('recipients');
  if (count($recipients) === 1 && $recipients[0] === 'contact_optional_outgoing_mail@contact_optional_outgoing_mail.com') {
    // If our dummy value is set as the recipient, we'll remove it.
    $form_state->setValue('recipients', []);
  }
}
