<?php

/**
 * @file
 * Module files.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function abtestui_google_analytics_form_abtestui_test_alter(&$form, FormStateInterface $form_state, $form_id) {
  $modulePath = drupal_get_path('module', 'abtestui_google_analytics');

  // Header.
  $configFactory = \Drupal::configFactory();
  $analyticsConfig = $configFactory->get('google_analytics.settings');
  if (empty($analyticsConfig->get('account'))) {
    $gaAccountId = '<a href="' . Url::fromRoute('google_analytics.admin_settings_form')->toString() . '">' . t('Set up') . '</a>';
  }
  else {
    $gaAccountId = '#' . $analyticsConfig->get('account');
  }

  $form['info_bar']['ab_test_tool_help']['link']['#url'] = Url::fromUri("base:/$modulePath/help/ab-test-tool-help.html");
  $form['info_bar']['ga_check_results'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => [
        'ga-check-results',
      ],
    ],
    'link' => [
      '#title' => t('How to check the results in Google Analytics'),
      '#type' => 'link',
      '#url' => Url::fromUri("base:/$modulePath/help/check-ga-results.html"),
      '#options' => [
        'attributes' => [
          'class' => [
            'help-modal',
          ],
        ],
      ],
    ],
  ];
  $form['info_bar']['ga_account'] = [
    '#markup' => '<span class="ga-info"><span class="label">'
    . t('Google Analytics ID:')
    . ' </span><span class="ga-value">' . $gaAccountId . '</span></span>',
  ];

  $analyticsUrl = NULL;
  if (!empty($form['tid']['#value'])) {
    /** @var \Drupal\abtestui\Service\TestStorage $testStorage */
    $testStorage = \Drupal::service('abtestui.test_storage');
    $test = $testStorage->load($form['tid']['#value']);
    $analyticsUrl = empty($test['analytics_url']) ? NULL : $test['analytics_url'];
  }

  // Note: I don't want to fully refactor this, so schema and save will happen
  // happen in the base module.
  $analyticsElement = [
    'analytics_url' => [
      '#type' => 'url',
      '#title' => t('Analytics Report URL'),
      '#size' => 128,
      // Theoretical max around 16383 (TEXT field type, UTF8MB4).
      '#maxlength' => 1023,
      '#default_value' => $analyticsUrl,
      '#placeholder' => t('Add the URL of your custom Analytics report for easier access'),
    ],
  ];

  // We do this so the analytics form element gets added before the 'name'
  // as otherwise the form design will break.
  $keys = \array_keys($form);
  $index = \array_search('name', $keys, TRUE);
  if ($index !== FALSE) {
    $form = array_merge(
      \array_slice($form, 0, $index, TRUE),
      $analyticsElement,
      \array_slice($form, $index, NULL, TRUE));
  }
}
