<?php

/**
 * @file
 * Xero Contact Sync module
 *
 * Synchronizes users in Drupal with Contacts in xero.com.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\user\UserInterface;
use Drupal\xero_contact_sync\XeroContactSyncEntityOperations;
use Drupal\xero_contact_sync\XeroContactSyncEntityTypeInfo;

/**
 * Implements hook_entity_base_field_info().
 */
function xero_contact_sync_entity_base_field_info(EntityTypeInterface $entity_type) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(XeroContactSyncEntityTypeInfo::class)
    ->entityBaseFieldInfo($entity_type);
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function xero_contact_sync_user_insert(UserInterface $user) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(XeroContactSyncEntityOperations::class)
    ->insert($user);
}
