<?php

/**
 * @file
 * Contains update_runnner.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\update_runner\CronOperations;
use Drupal\update_runner\UpdateInfo;
use Drupal\update_runner\UpdateRunnerMail;

const UPDATE_RUNNER_JOB_NOT_PROCESSED = 0;
const UPDATE_RUNNER_JOB_PROCESSED = 1;
const UPDATE_RUNNER_JOB_FAILED = 2;

/**
 * Implements hook_help().
 */
function update_runner_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the update_runner module.
    case 'help.page.update_runner':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Update runner') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_update_status_alter().
 */
function update_runner_update_status_alter(&$projects) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(UpdateInfo::class)
    ->updateStatusAlter($projects);
}

/**
 * Implements hook_cron().
 */
function update_runner_cron() {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(CronOperations::class)
    ->cron();
}

/**
 * Implements hook_mail().
 */
function update_runner_mail($key, &$message, $params) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(UpdateRunnerMail::class)
    ->mailDefinition($key, $message, $params);
}
