<?php

/**
 * @file
 * Contains webform_as_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_as_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_as_block module.
    case 'help.page.webform_as_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module exposes open webforms as blocks.') . '</p>';
      return $output;

    default:
  }
}
