<?php

/**
 * @file
 * Contains regex_redirect.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function regex_redirect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the regex_redirect module.
    case 'help.page.regex_redirect':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<pre>' . file_get_contents(__DIR__ . '/README.md') . '</pre>';
      return $output;

    default:
  }
}

/**
 * Return the valid status codes.
 *
 * @param int $code
 *   The redirect status code.
 *
 * @return array|mixed
 *   The list of valid redirect status codes.
 */
function regex_redirect_status_code_options($code = NULL) {
  $codes = [
    301 => t('301 Moved Permanently'),
  ];
  return isset($codes[$code]) ? $codes[$code] : $codes;
}

/**
 * Return the language code of the current interface language.
 *
 * @return string
 *   The interface language code.
 */
function regex_redirect_language_code_default() {
  $current_language_code = \Drupal::languageManager()->getCurrentLanguage()->getId();
  return $current_language_code;
}

/**
 * Ajax callback for the redirect link widget.
 */
function regex_redirect_source_link_get_status_messages(array $form, FormStateInterface $form_state) {
  return $form['regex_redirect_source']['widget'][0]['status_box'];
}
