<?php

/**
 * @file
 * A block module that adds Albacross script to footer area.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function albacross_drupal_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'helo.page.albacross_drupal':
      return t('
        <h2>Albacross</h2>
        <p>This plugin is called to ease your integration with
        Albacross services, you only need to insert your Tracking ID
        on the settings page of plugin, and then it will do the magic.</p>
      ');
  }
}

/**
 * Implements hook_page_attachments().
 */
function albacross_drupal_page_attachments(array &$page) {

  $config = \Drupal::config('albacross_drupal.settings');

  if (!empty($config->get('albacross_drupal.trackID'))) {
    $page['#attached']['html_head'][] = [
      [
        '#tag' => 'script',
        '#value' => "_nQc = '" . $config->get('albacross_drupal.trackID') . "';
          _nQs = 'Drupal-Module';
          _nQsv = '1.0.0';
          _nQt = new Date().getTime();
          (function() {
            var no = document.createElement('script'); no.type = 'text/javascript'; no.async = true;
            no.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'serve.albacross.com/track.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(no, s);
        })();",
      ],
      'albacross-define',
    ];
  }
}
