<?php

/**
 * @file
 * Contains coil.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function coil_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the coil module.
    case 'help.page.coil':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Coil implementation for Drupal') . '.</p>';
      $output .= '<p>' . t('To activate your coil account, go to <a href="@c">settings</a> and save you coil pointer.',['@c' => '/admin/coil']) . '</p>';
      $output .= '<p>' . t('More info at <a href="@c">Coil.com</a>.',['@c' => 'https://coil.com']) . ';</p>';
      $output .= '<p>' . t('If this module is useful, please consider small tip at <b>@d</b>.',['@d' => '$twitter.xrptipbot.com/arrea_systems']) . '</p>';
      $output .= '<p>' . t('Thank you') . '.</p>';
      return $output;

    default:
  }
}


/**
 * Implementation theme_preprocess_html().
 */
function coil_preprocess_html(&$variables) {

    $pointer = \Drupal::config('coil.settings')->get('coil_pointer');
    $coil = [
            '#tag' => 'meta',
            '#attributes' => [
                'name' => 'monetization',
                'content' => '$twitter.xrptipbot.com/' . $pointer,
            ],
        ];
    $variables['page']['#attached']['html_head'][] = [$coil, 'coil'];
}
