<?php

/**
 * @file
 * Module file for pager.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\CurrentRouteMatch;

/**
 * Implements hook_help().
 */
function pager_help($route_name, CurrentRouteMatch $route_match) {
  switch ($route_name) {
    case 'help.page.pager':
      $txt = file_get_contents(drupal_get_path('module', 'pager') . '/README.txt');
      return str_replace("\n", "\n<br />", Html::escape($txt));
  }
  return '';
}

/**
 * Implements hook_theme().
 */
function pager_theme() {
  return [
    'pager_block' => [
      'template'  => 'pager--block',
      'variables' => [
        'data' => [],
      ],
    ],
    'pager_wings' => [
      'template'  => 'pager--wings',
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}
