<?php

/**
 * @file
 * This module holds functions of Financial Calculators.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function financial_help($route_name,RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.financial':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide the useful financial calculator tools for loans, car/auto loans, compound interest, savings, mortgages and more. Module can be useful for Banking/Financial website and educational website.') . '</p>';
      return $output;

    default:
  }
}
