<?php

/**
 * @file
 * Primary module hooks for debug_bar module.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_attachments().
 */
function debug_bar_page_attachments(array &$page) {
  if (\Drupal::currentUser()->hasPermission('view debug bar')) {
    $page['#attached']['library'][] = 'debug_bar/debug_bar';
  }
}

/**
 * Implements template_preprocess_links().
 */
function debug_bar_preprocess_links(&$variables) {
  // Add CSS classes to 'li' elements based on the associative key. We duplicate
  // the code from Stable theme to make sure the classes appear on non Stable
  // based themes.
  // @see template_preprocess_links().
  if (isset($variables['attributes']['id']) && $variables['attributes']['id'] == 'debug-bar') {
    foreach ($variables['links'] as $key => $value) {
      $variables['links'][$key]['attributes']->addClass(Html::getClass($key));
    }
    // Turn keys to integers so Stable theme will not add the same classes.
    $variables['links'] = array_values($variables['links']);
  }
}
