<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function entity_bs_accordion_tab_formatter_theme() {
  $config = \Drupal::config('entity_bs_accordion_tab_formatter.settings');
  return [
    'entity_bs_tab_formatter' => [
      'variables' => ['tabs' => NULL, 'attributes' => NULL],
      'template' => $config->get('bootstrap_version') . '/entity-bs-tab-formatter',
    ],
    'entity_bs_accordion_formatter' => [
      'variables' => ['tabs' => NULL, 'attributes' => NULL],
      'template' => $config->get('bootstrap_version') . '/entity-bs-accordion-formatter',
    ],
  ];
}
