<?php

/**
 * Implements hook_page_attachments().
 */
function smart_content_datalayer_page_attachments(array &$attachments) {
  // Initialize the dataLayer array.
  if (empty($attachments['#attached'])) {
    $attachments['#attached'] = [];
  }
  if (empty($attachments['#attached']['html_head'])) {
    $attachments['#attached']['html_head'] = [];
  }
  $attachments['#attached']['html_head'][] = [
    [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => 'window.dataLayer = window.dataLayer || [];',
    ],
    'datalayers-js',
  ];
  // Add custom JS to push variation info to dataLayer array.
  $attachments['#attached']['library'][] = 'smart_content_datalayer/datalayer_command';
}
