<?php

use Drupal\Core\Render\Element;

/**
 * @file
 * Defines various hooks for Alexanders.
 */

/**
 * Implements hook_theme().
 */
function alexanders_theme($existing, $type, $theme, $path) {
  return [
    'alexanders_order' => [
      'render element' => 'elements',
    ],
    'alexanders_order__admin' => [
      'base hook' => 'alexanders_order',
      'render element' => 'elements',
    ],
    'alexanders_order__user' => [
      'base hook' => 'alexanders_order',
      'render element' => 'elements',
    ],
    'alexanders_order_edit_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Prepares variables for order templates.
 *
 * Default template: alexanders-order.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing rendered fields.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_alexanders_order(array &$variables) {
  /** @var \Drupal\alexanders\Entity\AlexandersOrder $order */
  $order = $variables['elements']['#alexanders_order'];

  $variables['order_entity'] = $order;

  $variables['due'] = $order->getDue();
  $variables['order_number'] = $order->id();
  $variables['rush'] = $order->getRush();

}
