<?php

/**
 * @file
 * Enable whiteboard support in Drupal.
 */

use Drupal\whiteboard\Whiteboard;

/**
 * Implements hook_permission().
 */
function whiteboard_permission() {
  return array(
    'see any whiteboard' => array(
      'title' => t('See all whiteboards'),
      'description' => t('Allows user to see any whiteboard'),
    ),
    'write any whiteboard' => array(
      'title' => t('Draw and save to any whiteboard '),
      'description' => t('Allows the role to see and save marks to the database'),
    ),
  );
}

/**
 * Checks if $account has access to $whiteboard.
 */
function whiteboard_user_has_access($whiteboard, $access_type = 'read', $account = NULL) {
  if ($account === NULL) {
    $user = \Drupal::currentUser();
    $account = $user;
  }
  return $whiteboard->userHasAccess($account, $access_type);
}

/**
 * Implements hook_theme().
 */
function whiteboard_theme() {
  return array(
    'whiteboard' => array(
      'variables' => array('whiteboard' => NULL),
      'function' => 'theme_whiteboard_whiteboard',
    ),
  );
}

/**
 * Theme a whiteboard.
 *
 * @ingroup themeable
 */
function theme_whiteboard_whiteboard($variables) {
  // Client side use only                   
  $whiteboard = $variables['whiteboard'];
  $output = '<div id="whiteboard-container">';

  $output .= '
    <div id="whiteboard-meta">
      <input type="text" id="whiteboard-color" value="#99BBFF" />
      <input type="text" id="whiteboard-penwidth" value="3" />
      <input type="text" id="whiteboard-tension" value="0" />
    </div>';

  $output .= '
    <div id="whiteboard-top">
      X <input type="text" value="0" id="mousieX" size="4" />
      Y <input type="text" value="0" id="mousieY" size="4" />
      <input type="button" id="whiteboard-clear-points" value="Clear Points" />
      <input type="button" id="whiteboard-clear-board" value="Clear Board" />
      <input type="button" id="whiteboard-penwidth-fine" src="/img/fine.png" />
      <input type="button" id="whiteboard-penwidth-thick" src="/img/thick.png" />
      <input type="button" id="whiteboard-penwidth-blunt" src="/img/blunt.png" />
      <input type="button" id="whiteboard-black" src="/img/black.png" />
      <input type="button" id="whiteboard-blue" src="/img/blue.png" />
      <input type="button" id="whiteboard-green" src="/img/green.png" />
      <input type="button" id="whiteboard-red" src="/img/red.png" />
      <input type="button" id="whiteboard-hex" src="/img/color.png" />
      <input type="button" id="whiteboard-eraser" src="/img/eraser.png" />
    </div>';

  $output .= '<div id="whiteboard">' . $whiteboard->marks . '</div>';

  $output .= '
    <div id="whiteboard-side">
      <input type="button" id="whiteboard-cartecian" src="/img/cartecian.png" />
      <input type="button id="whiteboard-default" src="/img/default.png" />
      <input type="button" id="whiteboard-show-grid"  src="/img/grid.png" />
      <input type="button" id="whiteboard-hide-grid" src="/img/hide-grid.png" />
      <input type="button" id="whiteboard-show-range" src="/img/show-range.png" />
      <input type="button" id="whiteboard-hide-range" src="/img/hide-range.png" />
    </div>';

  $output .= '
    <div id="whiteboard-ellipse-container">
      <input type="text" id="whiteboard-ellipse-width" value="200" size="4" />
      <input type="text" id="whiteboard-ellipse-height" value="100" size="4" />
      <input type="button id="whiteboard-ellipse-cancel" value="Cancel" />
      <input type="button" id="whiteboard-ellipse-submit" value="Submit" />
    </div>';

  $output .= '
  <div id="whiteboard-arc-container">
    <input type="text" id="whiteboard-arc-width" value="200" size="4" />
    <input type="text" id="whiteboard-arc-height" value="100" size="4" />
    <input type="text" id="whiteboard-arc-angle" value="0" size="4" />
    <input type="text" id="whiteboard-arc-length" value="200" size="4" />
    <input type="button" id="whiteboard-arc-cancel" value="Cancel" />
    <input type="button" id="whiteboard-arc-submit" value="Submit" />
  </div>';

  $output .= '
  <div id="whiteboard-rectangle-container">
    <input type="text" id="whiteboard-rectangle-width" value="200" size="4" />
    <input type="text" id="whiteboard-rectangle-height" value="100" size="4" />
    <input type="button" id="whiteboard-rectangle-cancel" value="Cancel" />
    <input type="button" id="whiteboard-rectangle-submit" value="Submit" />
  </div>';

  $output .= '
  <div id="whiteboard-circle-container">
    <input type="text" id="whiteboard-circle-radius" value="150" size="4" />
    <input type="button" id="whiteboard-circle-cancel" value="Cancel" />
    <input type="button" id="whiteboard-circle-submit" value="Submit" />            
  </div>';

  $output .= '
  <div id="whiteboard-color-container">
    <input type="text" id="whiteboard-color-code" value="#777777" size="7" />
    <input type="button" id="whiteboard-color-cancel" value="Cancel" />
    <input type="button" id="whiteboard-color-submit" value="Submit" />
  </div>';

  $output .= '
  <div id="whiteboard-bottom-container">
    <input type="button" id="whiteboard-line" src="/img/line.png" />
    <input type="button" id="whiteboard-polyline" src="/img/polyline.png" />
    <input type="button" id="whiteboard-polygon" src="/img/polygon.png" />
    <input type="button" id="whiteboard-arc" src="/img/arc.png" />
    <input type="button" id="whiteboard-curve" src="/img/curve.png" />
    <input type="button" id="whiteboard-closed-curve" src="/img/closed-curve.png" />
    <input type="button" id="whiteboard-bezier" src="/img/bezier.png" />
    <input type="button" id="whiteboard-circle" src="/img/circle.png" />
    <input type="button" id="whiteboard-ellipse" src="/img/ellipse.png" />
    <input type="button" id="whiteboard-rectangle" src="/img/rectangle.png" />
  </div>';

  $output .= '<div id="whiteboard-status-container"><span id="whiteboard-status"></span></div>';

  $output .= '
  <div id="whiteboard-save">
    <input type="button" id="whiteboard-save" value="Save Whiteboard" />
  </div>';

  $output .= '</div>';
  return $output;
}

