<?php

/**
 * @file
 * Date recur opening hours.
 */

/**
 * Implements hook_theme().
 */
function date_recur_opening_hours_theme($existing, $type, $theme, $path) : array {
  $info['date_recur_opening_hours_list'] = [
    'variables' => [
      'time_separator' => ' — ',
      'date_ranges' => NULL,
    ],
  ];

  return $info;
}

/**
 * Prepares variables for language content settings table templates.
 *
 * Default template: date-recur-opening-hours-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - date_ranges: an array containing DrupalDateTime values, whos keys must
 *     consist of 'start' and 'end'.
 */
function template_preprocess_date_recur_opening_hours_list(array &$variables) : void {
  $variables['date_ranges'] = array_map(
    function ($dateRange) {
      /** @var \Drupal\Core\Datetime\DrupalDateTime $start */
      /** @var \Drupal\Core\Datetime\DrupalDateTime $end */
      ['start' => $start, 'end' => $end] = $dateRange;

      $row = [];
      $row['days'] = $start->format('l');
      $row['start_time'] = $start->format('g:ia');
      $row['end_time'] = $end->format('g:ia');

      return $row;
    },
    $variables['date_ranges']
  );
}
