<?php

/**
 * @file
 * Contains user_attendance.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user_attendance\Entity\UserAttendanceType;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\user\UserInterface;
use Drupal\user_attendance\Form\UserAttendanceCheckboxForm;

/**
 * Implements hook_help().
 */
function user_attendance_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_attendance module.
    case 'help.page.user_attendance':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to register attendance of users by using a custom entity for check in and out moments by timestamp') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_attendance_theme() {
  $theme = [];
  $theme['user_attendance'] = array(
    'render element' => 'elements',
    'file' => 'user_attendance.page.inc',
    'template' => 'user_attendance',
  );
  $theme['user_attendance_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'user_attendance.page.inc',
  ];
  $theme['user_attendance_status'] = [
    'variables' => ['user' => NULL, 'bundle' => NULL],
    'template' => 'user_attendance_status',
  ];

  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function user_attendance_theme_suggestions_user_attendance(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#user_attendance'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'user_attendance__' . $sanitized_view_mode;
  $suggestions[] = 'user_attendance__' . $entity->bundle();
  $suggestions[] = 'user_attendance__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'user_attendance__' . $entity->id();
  $suggestions[] = 'user_attendance__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function user_attendance_entity_extra_field_info() {
  $extra = [];
  $description = t('User attendance checkbox form.');

  /** @var \Drupal\user_attendance\Entity\UserAttendanceTypeInterface $bundle */
  foreach (UserAttendanceType::loadMultiple() as $bundle) {
    $extra['user']['user']['display']['attendance_switch_' . $bundle->id()] = [
      'label' => t('Attendance Switch Form'),
      'description' => $description,
      'weight' => 100,
    ];

    $extra['user']['user']['display']['attendance_status_' . $bundle->id()] = [
      'label' => t('Attendance Status'),
      'description' => $description,
      'weight' => 100,
    ];
  }

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function user_attendance_user_view(array &$build, UserInterface $user, EntityViewDisplayInterface $display, $view_mode) {
  /** @var \Drupal\user_attendance\Entity\UserAttendanceTypeInterface $bundle */
  foreach (UserAttendanceType::loadMultiple() as $bundle) {
    $field = 'attendance_switch_' . $bundle->id();
    if ($display->getComponent($field)) {
      $build[$field] = \Drupal::formBuilder()->getForm(UserAttendanceCheckboxForm::class, $user, $bundle);
    }

    $field = 'attendance_status_' . $bundle->id();
    if ($display->getComponent($field)) {
      $build[$field] = [
        '#theme' => 'user_attendance_status',
        '#user' => $user,
        '#bundle' => $bundle,
      ];
    }
  }
}
