<?php

/**
 * @file
 * Contains commerce_ccavenue.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_ccavenue_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_ccavenue module.
    case 'help.page.commerce_ccavenue':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrates CCAvenue Payment Gateway with Drupal Commerce.') . '</p>';
      return $output;

    default:
  }
}
