<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function onelogin_integration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case "help.page.onelogin_integration":
      return '<p>' . t("Allows Drupal to function as a SAML Service Provider. This means that users can authenticate to Drupal (without a username or password) via OneLogin or a third party SAML Identity Provider (IdP)") . '</p>';
  }
}

/**
 * Implements hook_user_logout().
 */
function onelogin_integration_user_logout() {
  $made_sso_login = isset($_COOKIE['Drupal_visitor_onelogin_integration_login']) && $_COOKIE['Drupal_visitor_onelogin_integration_login'];
  if ($made_sso_login) {
    user_cookie_delete('Drupal_visitor_onelogin_integration_login');
  }
}

/**
 * Implements hook_form_alter().
 */
function onelogin_integration_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'user_login_form':
      user_login_form_alter($form);
      break;

    case 'user_form':
      hide_drupal_user_fields($form);
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function onelogin_integration_form_user_login_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  user_login_form_alter($form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function onelogin_integration_form_user_login_alter(&$form, FormStateInterface $form_state, $form_id) {
  user_login_form_alter($form);
}

/**
 * Alters the user login form.
 *
 * @param array $form
 *   The form itself.
 */
function user_login_form_alter(array &$form) {
  $show_saml_link = \Drupal::config('onelogin_integration.settings')->get('saml_link');

  if ($show_saml_link) {
    // Add a "Log in using SAML" link to the user-login form.
    $form['onelogin_integration_login_links'] = [
      '#type' => 'item',
      '#markup' => Link::fromTextAndUrl(t('Log in using SAML'), Url::fromRoute('onelogin_integration.sso', [], ['absolute' => TRUE, 'query' => drupal_get_destination(), 'external' => TRUE]))->toString(),
      '#attributes' => ['class' => 'onelogin_integration_login-links'],
      '#weight' => 1,
    ];

    $form['links']['#weight'] = 2;

    $register_link = \Drupal::config('onelogin_integration.settings')->get('create_new_account');
    $reset_password_link = \Drupal::config('onelogin_integration.settings')->get('request_new_password');

    if (!empty($register_link)) {
      $form['links']['#markup'] = str_replace(Url::fromUri('user/register', ['absolute' => FALSE]), $register_link, $form['links']['#markup']);
    }
    if (!empty($reset_password_link)) {
      $form['links']['#markup'] = str_replace(Url::fromUri('user/password', ['absolute' => FALSE]), $reset_password_link, $form['links']['#markup']);
    }
  }
}

/**
 * Hides some of the user fields on the user edit page.
 *
 * @param array $form
 *   The user form.
 */
function hide_drupal_user_fields(array &$form) {
  $made_sso_login = isset($_COOKIE['Drupal_visitor_onelogin_integration_login']) && $_COOKIE['Drupal_visitor_onelogin_integration_login'];

  if ($made_sso_login) {
    // If the disable current password fields settings is set in the module and
    // the user is NOT an administrator, hide the fields.
    $current_pass_disabled = \Drupal::config('onelogin_integration.settings')->get('current_pass_disabled');
    $email_field_disabled = \Drupal::config('onelogin_integration.settings')->get('email_field_disabled');

    if ($current_pass_disabled) {
      $form['account']['current_pass']['#access'] = FALSE;
    }
    if ($email_field_disabled) {
      $form['account']['mail']['#disabled'] = TRUE;
    }
    // Disable password by default.
    $form['account']['pass']['#access'] = FALSE;
  }
}
