<?php

use Drupal\image\Entity\ImageStyle;

function custom_header_image_theme() {
  return [
    'image_srcset' => [
      'variables' => [
        'styles' => [],
        'sizes' => [],
        'uri' => NULL,
        'alt' => '',
        'title' => NULL,
        'attributes' => [],
      ],
    ]
  ];
}

function template_preprocess_image_srcset(&$variables) {
  $srcset = [];
  foreach ($variables['styles'] as $style_name) {
    $style = ImageStyle::load($style_name);
    $uri = $style->buildUri($variables['uri']);
    $style->createDerivative($variables['uri'], $uri);
    $url = $style->buildUrl($uri);

    // The image.factory service will check if our image is valid.
    /** @var \Drupal\Core\Image\ImageInterface $image */
    $image = \Drupal::service('image.factory')->get($uri);
    if ($image->isValid()) {
      $srcset[] = "$url {$image->getWidth()}w";
    }
    else {
      $srcset[] = "$url";
    }
  }
  if ($srcset) {
    $variables['attributes']['srcset'] = implode(",\n", $srcset);
    if (!empty($variables['sizes'])) {
      $variables['attributes']['sizes'] = implode(", ", $variables['sizes']);
    }
    $variables['image'] = [
      '#theme' => 'image',
      '#attributes' => $variables['attributes'],
    ];
    drupal_set_message(t('@foo', ['@foo' => print_r($variables['image'], TRUE)]));

  }
}
