<?php

/**
 * @file
 * Contains vimeo_upload.module.
 */

use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Serialization\Json;

/**
 * Define the Vimeo Upload library location.
 */
define('VIMEO_UPLOAD_LIBRARY_URI', 'https://github.com/websemantics/vimeo-upload');

/**
 * Implements hook_help().
 */
function vimeo_upload_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vimeo_upload module.
    case 'help.page.vimeo_upload':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Javascript based upload to get a video URL straight from Vimeo, without having to upload the file on Drupal first.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function vimeo_upload_theme() {
  return [
    'vimeo_upload' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 *
 * @todo alter media widget type in a new hook.
 */
function vimeo_upload_field_widget_video_embed_field_textfield_form_alter(&$element, FormStateInterface &$form_state, $context) {
  // Appends the link to the upload controller for each element.
  // @todo improve this by uploading straight on the field widget
  // @todo pass then the Vimeo URL to the field value.
  $link = Link::createFromRoute(
    t('Upload on Vimeo'),
    'vimeo_upload.upload',
    [],
    [
      'attributes' => [
        'class' => 'use-ajax',
        'data-dialog-type' => 'modal',
        'data-dialog-options' => Json::encode(
          [
            'height' => 400,
            'width' => 480,
          ]),
      ],
      'attached' => [
        'library' => [
          'core/drupal.dialog.ajax',
        ],
      ],
    ]);
  $link = $link->toRenderable();

  $element['vimeo_upload_link'] = [
    '#type' => 'item',
    '#markup' => \Drupal::service('renderer')->renderRoot($link),
  ];
}
