<?php

/**
 * @file
 * Primary module hooks for Test Output Viewer module.
 */

/**
 * Implements hook_theme().
 */
function test_output_viewer_theme() {
  return [
    'test_output' => [
      'variables' => ['foo' => NULL],
    ],
  ];
}

/**
 * Prepares variables for test-output template.
 *
 * Default template: test-output.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_test_output(array &$variables) {
  $variables['foo'] = 'bar';
}
