<?php

/**
 * @file
 * Module file for headbar.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function headbar_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
     case 'help.page.headbar':
      return '<h3>' . t('Introduction') . '</h3>' . '<p>' . t('This module provides a bar which will appear on the header of the page after given time.') . '</p>' . '<h3>' . t('Installation') . '</h3>' . '<p>' . t('To install, copy the headbar directory and all its contents to your modules directory. To enable the module go to Administer > Modules, and enable "HeadBar".').'</p>'.'<h3>'.t('Configuration').'</h3>'.'<p>'.t('Go to <a href=":link">configuration page </a>. Add the text message which will appear on the headbar, Color and Delay time. Go to block page <a href=":block">block configuration</a> enable "Headbar" block in any of the theme region. Go to permissions page <a href=":permissions">permissions configuration</a> and configure permissions for the "HeadBar" visibility and administration.' , [':link' =>\Drupal::url('headbar.configure'), ':block' =>\Drupal::url('block.admin_display'), ':permissions' =>\Drupal::url('user.admin_permissions')]).'</p>';
  }
}

/**
 * Implements hook_theme().
 */
function headbar_theme() {
  $templates = [
    'headbar_block' => [
      'template' => 'headbar-block',
    ],
  ];
  return $templates;
}


/**
 * Implements hook_preprocess_HOOK(&$variables).
 *
 * For headbar-block.tpl.php.
 */
function headbar_preprocess_headbar_block(&$variables) {
  global $base_url;
  $headbar_module_path = $base_url . '/' . drupal_get_path('module', 'headbar');
  $headbar_text = \Drupal::config('headbar.configure')->get('msg_text');
  $variables['headbar_text'] = [
    '#markup' => $headbar_text,
  ];
  $variables['headbar_module_path'] = $headbar_module_path;
}
