<?php

/**
 * @file
 * Defines chartist theme.
 */

/**
 * Implements hook_theme().
 */
function chartist_theme() {
  return [
    'chartist' => [
      'variables' => [
        'title' => '',
        'chart_type' => 'Line',
        'data' => [],
        'settings' => [],
        'classes' => [],
        'wrapper_class' => '',
        'element_prefix' => '',
        'element_suffix' => '',
        'html' => FALSE,
        'attached' => [
          'library' => [
            'chartist',
          ],
        ],
      ],
      'file' => 'includes/chartist.theme.inc',
    ],
  ];
}
