<?php

/**
 * @file
 * Code for the Nyan cat progress bar module.
 */

/**
 * Implements hook_init().
 */
function nyan_init() {
  drupal_add_css(drupal_get_path('module', 'nyan') . '/css/nyan.css');
  drupal_add_js(array(
    'nyan' => array(
      'enabled' => config('nyan.settings')->get('enabled'),
      'ogg' => url(drupal_get_path('module', 'nyan') . '/audio/nyancat.ogg'),
      'mp3' => url(drupal_get_path('module', 'nyan') . '/audio/nyancat.mp3'),
      'controls_visible' => config('nyan.settings')->get('controls.visible'),
      'volume_default' => config('nyan.settings')->get('volume.default'),
    ),
  ), 'setting');
}

/**
 * Implements hook_permission().
 */
function nyan_permission() {
  return array(
    'administer nyan' => array(
      'title' => t('Administer the <em>Nyan cat</em> progress bar.'),
      'description' => t('Give this access to anyone that should be able to administer the settings to the Nyan cat progress bar.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function nyan_menu() {
  // The former nyan/change route is only defined in YAML because it just
  // returns some stuff and then exits.
  // This route needs to be defined in both places, because it provides a
  // menu link in the UI.
  $items['admin/config/system/nyan'] = array(
    'title' => 'Nyan cat progress bar',
    'description' => 'Customize the Nyan cat progress bar to your site.',
    // @todo This ugliness copy/pasted from user module, because otherwise no
    // link appears in the admin panel. It will go away once
    // http://drupal.org/node/1845402 is resolved.
    'page callback' => 'NOT_USED',
    'access arguments' => array('administer nyan'),
  );

  return $items;
}

/**
 * Implements hook_js_alter().
 */
function nyan_js_alter(&$javascript) {
  // Swap out progress.js to use our version of the library.
  $javascript['core/misc/progress.js'] = drupal_js_defaults(drupal_get_path('module', 'nyan') . '/js/progress.js');
}
