<?php

/**
 * @file
 * Adds D500px Block theme integrations.
 */

/**
 * Implements hook_theme().
 */
function d500px_block_theme() {
  return [
    'd500px_block_photo' => [
      'variables' => [],
    ],
    'd500px_block_photos' => [
      'variables' => [],
    ],
  ];
}

// @codingStandardsIgnoreStart
/**
 * Implements hook_requirements().
 */
// Function d500px_block_requirements() {
// TODO Add hook_requirements to check if
// Api keys and other settings have been set.
// }.
// @codingStandardsIgnoreEnd