<?php
/*
Use {{ kint(form) }} at the bottom in node-edit-form.html.twig(this file should be in your theme folder) to get form id. and change for id in custom_title.module file at  if ($form_id == "your_form_id")
*/


function custom_title_page_attachments_alter(&$page) { 
  $page['#attached']['library'][] = 'custom_title/modulestyle';
}

function custom_title_form_alter(&$form, &$form_state, $form_id) { 
 $uniq = date("Y-m-d-H-i-s"); // This is node create/published date
 $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
 $name = $user->get('name')->value;
 if ($form_id == "your_form_id") { // Change here id of your form.
	$form['title']['widget'][0]['value']['#default_value'] = 'Question asked at date '.$uniq;
  }

}
?>