<?php

/**
 * @file
 * Contains fieldclone.module..
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\fieldclone\FieldCloner;

/**
 * Implements hook_entity_prepare_form().
 * 
 * @param \Drupal\Core\Entity\EntityInterface $entity
 * @param $operation
 * @param FormStateInterface $form_state
 */
function fieldclone_entity_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
  FieldCloner::prepareEntity($entity);
}
