<?php
use Drupal\Core\Site\Settings;

function available_updates_slack_cron() {
  // Check if slack_notification settings is set to `true`
  if (Settings::get('slack_notification') === true) {
    // Update Settings
    $update_config = \Drupal::config('update.settings');
    // Calculate if cron should run
    $frequency = $update_config->get('check.interval_days');
    $interval = 60 * 60 * 24 * $frequency;
    $last_check = \Drupal::state()->get('update.last_check') ?: 0;
    // Get the Slack Notification Service
    /** @var Drupal\available_updates_slack\SlackNotificationServiceInterface $slack_notification_service */
    $slack_notification_service = \Drupal::service('available_updates_slack.slack_notification_service');
    try {
      /** @var array $updates */
      if ((\Drupal::time()->getRequestTime() - $last_check) > $interval && $updates = $slack_notification_service->getUpdates()) {
        $slack_notification_service->notify($updates);
      }
    } catch(\Exception $ex) { // If an exception occurs, lets catch it and log the message
      \Drupal::logger('SlackUpdatesNotifier[cron]')->error($ex->getMessage());
    }

  }
}
