<?php

/**
 * @file
 *
 */

use Drupal\Core\Form\FormStateInterface;

// @todo:
function colors_get_info($entity = NULL) {
  $config = NULL;
  if ($entity) {
    $config = \Drupal::configFactory()->getEditable($entity);
  }
  $config = (!$entity || !$config)  ? \Drupal::configFactory()->getEditable('colors.settings') : $config;

   return $config;
}

/**
 * Retrieves the color palette for a particular theme.
 */
function colors_get_palette($config) {
  return $config->get('palette');
}

function colors_get_enabled($entity) {
  $configs = [];
  foreach (\Drupal::configFactory()->listAll("colors.$entity.") as $key) {
    $config = \Drupal::configFactory()->getEditable($key);
       if ($config->get('enabled')) {
      $configs[] = $config;
    }
  }
  return $configs;
}

function colors_load_colorpicker() {
  return array(
    'color_picker' => array(
      '#prefix' => '<div id="colors-colorpicker">',
      '#suffix' => '</div>',
    ),
  );
}

function colors_get_weights(FormStateInterface $form_state) {
  $entities = $form_state->getValue('entities');
  $values = [];
  foreach (array_values($entities) as $value) {
    $values[] = $value['weight'];
  }
  return array_combine(array_keys($entities), $values);
}
