<?php

/**
 * @file
 * Install, uninstall and update hooks for CARTO Sync module.
 */

/**
 * Implements hook_requirements().
 */
function carto_sync_requirements($phase) {
  $requirements = [];
  if ($phase == 'install') {
    if (!class_exists('\League\Csv\Writer')) {
      $requirements['carto_sync_csv_library'] = [
        'description' => t("CARTO Sync requires the League/Csv library."),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }
  return $requirements;
}
