<?php

/**
 * @file
 * Enables wipe of search index.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function searchindex_wipe_form_search_admin_settings_alter(&$form, FormStateInterface $form_state) {
  if (\Drupal::currentUser()->hasPermission('wipe search index')) {
    $form['status']['clear_index'] = array(
      '#value' => t('Wipe Index'),
      '#type' => 'submit',
      '#submit' => array('searchindex_wipe_all'),
      '#description' => t('Drops all the index build by search module'),
    );
  }
}

/**
 * Redirect to confirmation link.
 */
function searchindex_wipe_all(&$form, FormStateInterface $form_state) {
  $url = new Url('searchindex_wipe.reindex_confirm');
  $form_state->setRedirectUrl($url);
}

/**
 * Helper function to truncate search related tables.
 */
function searchindex_wipe_truncate_table() {
  // Taken code from drupal_uninstall_schema.
  $schema = drupal_get_module_schema('search');
  foreach ($schema as $table_name => $table) {
    // Truncate search related tables.
    db_truncate($table_name)->execute();
  }
  drupal_set_message(t('Search Index Cleared, Please rebuilt the index by running cron.'));
}
