<?php

/**
 * @file
 * A collection of module hooks for the flot_axislabels_examples module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_foo_BAR_ID_bar() for xyz_bar().
 */
function flot_axislabels_examples_flot_examples_toc_alter(&$item_list) {
  $options = [
    ':one' => Url::fromRoute('flot_axislabels_examples.example')->toString(),
  ];
  $item_list[] = t('<a href=":one">Axis Labels</a> (with flot_axislabels plugin)', $options);
}
