<?php

/**
 * @file
 * Drupal Module: Acquia Content Hub - Subscriber.
 *
 * Subscriber imports content from Content Hub services to your Drupal site.
 */

use Acquia\ContentHubClient\ContentHubClient;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_delete().
 *
 * @throws \Exception
 */
function acquia_contenthub_subscriber_entity_delete(EntityInterface $entity) {
  /* @var \Drupal\acquia_contenthub\Client\ClientFactory $factory */
  $factory = \Drupal::service('acquia_contenthub.client.factory');
  $client = $factory->getClient();
  if ($client) {
    _acquia_contenthub_subscriber_delete_entity($entity, $client);
  }
}

/**
 * Delete subscriber entities from the interest list and tracking table.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The entity to remove.
 * @param \Acquia\ContentHubClient\ContentHubClient $client
 *   The client connection to the ContentHub service.
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function _acquia_contenthub_subscriber_delete_entity(EntityInterface $entity, ContentHubClient $client) {
  $uuid = $entity->uuid();
  /** @var \Drupal\acquia_contenthub_subscriber\SubscriberTracker $tracker */
  $tracker = \Drupal::service('acquia_contenthub_subscriber.tracker');
  if ($tracker->isTracked($uuid)) {
    $tracker->delete($uuid);

    // Clean up the interest list.
    $settings = $client->getSettings();
    $webhook_uuid = $settings->getWebhook('uuid');
    $client->deleteInterest($uuid, $webhook_uuid);
  }
}
