<?php

/**
 * @file
 * Provides hook implementations for Stop Spam Registrations module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function stop_spam_regs_form_user_register_form_alter(&$form, &$form_state) {

  // Add one more validation callback for user registration.
  $form['#validate'][] = 'stop_spam_regs_registration_validate';
}

/**
 * Check if submitted email domain matches anyone from our spam list.
 */
function stop_spam_regs_registration_validate($form, FormStateInterface &$form_state) {

  // Check if user mail is present in form.
  // Some contrib modules may remove it.
  $email = $form_state->getValue('mail');
  if (!empty($email)) {
    $email_domain = \Drupal\Component\Utility\Unicode::substr($email, strrpos($email, '@') + 1);
    $config = \Drupal::config('stop_spam_regs.settings');
    $settings = $config->get();
    $spam_list = !empty($settings['stop_spam_regs_spam_list']) ? $settings['stop_spam_regs_spam_list'] : array();
    if (in_array($email_domain, $spam_list)) {
      $form_state->setErrorByName('mail', t('E-mail domain %domain in our black list. Please, use another to register.', array('%domain' => $email_domain)));
    }
  }
}
