<?php

/**
 * @file
 * Install, update and uninstall functions for the frameprevention module.
 */

/**
 * Implements hook_uninstall().
 */
function frameprevention_uninstall() {
  \Drupal::config('frameprevention.settings')->clear('frameprevention_enabled')->save();
  \Drupal::config('frameprevention.settings')->clear('frameprevention_x_frame_options')->save();
  \Drupal::config('frameprevention.settings')->clear('frameprevention_pages')->save();
}
