<?php

/**
 * @file
 * Contains idproof.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_help().
 */
function idproof_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the idproof module.
    case 'help.page.idproof':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The ID Proof Field Types module has a single custom field focussing on ID proof. This Field can be attached to most content where there is a need of ID proof type field. It basically provides 3 fields in a combo set. First one is a select field that lists most basic ID proofs and a "Other" option. Second is a dependent text field, which is dependent on first field i.e select field. If user chooses Other then this field is meant to be filled. Third is also a text field meant to be for ID proof details.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<h5>' . t('Creating a ID proof Field :') . '</h5>';
      $output .= '<p>' . t('On the Manage fields page for your entity type, you can add, configure ID Proof Field. Click on Add Field then form the Add new field dropdown select "ID Proof" and provide a Label along with a unique machine name of your choice. ID proof field type combines most used ID proof you may not face any problem. If you don\'t have desired ID proof in the list you can choose Other and fill ID proof details. We have also provided some basic validation to it. It might come handy while user is in a hurry makes a mistake.' ) . '</p>';
      $output .= '<h5>' . t('Re-using fields :') . '</h5>';
      $output .= '<p>' . t('Once you have created a field, you can use it again in other sub-types of the same entity type. For instance, if you create a field for the form content type, you can also use it for the another content type. If there are fields available for re-use, after clicking Add field from the Manage fields page, you will see a list of available fields for re-use. After selecting a field for re-use, you can configure the sub-type-level settings. ') . '</p>';
      $output .= '<h5>' . t('Exposed Filter :') . '</h5>';
      $output .= '<p>' . t('In view you can use this field as exposed or hidden filter. When exposed it provides select field among which you can filter and search.') . '</p>';

      return $output;

    default:
  }
}

/**
   * Implements hook_form_alter().
   *
   */
  function idproof_form_alter(&$form, FormStateInterface $form_state, $form_id) {
     //Alter Exposed TextField Filter to Select Field Filter.
     if ($form_id == 'views_exposed_form')
     {
       foreach ($form as $key => $value) {
         if (strpos($key, 'idproof') !== false)
         {
           $form[$key][$key]['#type'] = 'select';
           $form[$key][$key]['#multiple'] = FALSE;
           $form[$key][$key]['#empty_option'] = t('-Any-');
           $form[$key][$key]['#options'] = [
             'Adhaar(UID)' => 'Adhaar(UID)',
             'Passport' => 'Passport',
             'Driving License' => 'Driving License',
             'Income Tax PAN Card' => 'Income Tax PAN Card',
              'Photo Identity Card (of Central Govt. /PSU or State Govt.)' => 'Photo Identity Card (of Central Govt. /PSU or State Govt.)',
             'Current  passbook of Post Office / any scheduled Bank, having Photo' => 'Current  passbook of Post Office / any scheduled Bank, having Photo',
             'Election Commission ID Card' => 'Election Commission ID Card',
             'Ration Card with Photo' => 'Ration Card with Photo',
             'Photo Identity Card issued by Govt. recognize Educational Institutions (for students only)' => 'Photo Identity Card issued by Govt. recognize Educational Institutions (for students only)',
             'Birth Certificate' => 'Birth Certificate',
             'Marriage Certificate' => 'Marriage Certificate',
             'Other' => 'Other',
           ];
           $form[$key][$key]['#size'] = "NULL";
         }
       }
     }
  }
