#! /usr/bin/env bash

# Colors
RED='\033[1;31m'
GREEN='\033[1;32m'
PURPLE='\033[1;34m'
NC='\033[0m'

# Sass Include Directory
CONFIG='sass_config'

#
# Watch function
#
load_plugin manuel-contrib-watch
load_plugin manuel-contrib-concurrent

timestamp () {
  date +"%T"
}

function watch {
  declare -A actions=(
    [".*\.scss$"]="manuel sass"
  )
  manuel_watch .
}

# Sass Compile
function sass {
  printf "${GREEN}[$(timestamp)] Cleaning up existing CSS files.${NC}\n"
  find . -name "*.css" -type f -delete
  find . -name "*.map" -type f -delete
  printf "${GREEN}[$(timestamp)] Compiling SASS.${NC}\n"
  for f in $(find $THEMES_FOLDER $MODULES_FOLDER -name '[^_]*.scss'); do
    dir=$(dirname $f)
    name=$(basename $f)
    name=$(echo $name | cut -f 1 -d '.')
    #sassc -I $CONFIG -t expanded -m -l $f $dir/$name.css
    sassc -I $CONFIG -t compressed $f $dir/$name.css
    #npx postcss $dir/$name.css --use autoprefixer --use postcss-inline-svg -r
    echo -e "${PURPLE}[$(timestamp)]${NC} $dir/$name.css is" `stat --printf="%s" $dir/$name.css` "bytes."
  done
  printf "${GREEN}[$(timestamp)] SASS files compiled.${NC}\n"
}

# Many Tasks
function build {
  tasks=("sass")
  manuel_concurrent $tasks
}
