<?php

/**
 * @file
 * Provide scroll to top link.
 */

/**
 * Implementation of hook_preprocess_page().
 */
function scroll_to_top_preprocess_page(&$variables) {
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  $config = \Drupal::config('scroll_to_top.settings');
  $admin_theme = \Drupal::config('system.theme')->get('admin');
  if ($config->get('scroll_to_top_enable_admin_theme')==TRUE || ($config->get('scroll_to_top_enable_admin_theme')==FALSE && ($theme != $admin_theme))) {
 
 //functies drupal_add_css() en drupal_add_js() wordn nu opgehaald uit de library scroll_to_top.librarues.yml
   $variables['#attached']['library'][] = 'scroll_to_top/scroll_to_top';

  //building the css style (= variable_get vervangen door $config->get)
  

    // Display label
    if ($config->get('scroll_to_top_display_text') == FALSE) {
      $display = "span#link {display : none;}";
    } else {
      $display = "";
    }
    
    
    $position = $config->get('scroll_to_top_position');
    $css_position = "";
    // Button position
    if ($position == 1) {
      $css_position = "#back-top { right:40px; }";
    }

    if ( $position == 3) {
      $css_position = "#back-top { left:50%;margin:0px;}";
    }

    // background color on hover
    $bgcolor = "#back-top span#button { background-color: " . $config->get('scroll_to_top_bg_color_out') . ";}";
    $bgcolor .= " #back-top span#button:hover {opacity:1;filter:alpha(opacity = 1);background-color: " . $config->get('scroll_to_top_bg_color_hover') . ";}";

//problemen gehad met opbouwen css. eerste lijn wordt niet meegenomen... => is enige manier dat  dit werkt ...
    $css = "#back-top { }";
    $css .= $css_position;
    $css .= $bgcolor;
    $css .= $display;

    $variables['#attached']['html_head'][] = [[
        '#tag' => 'style',
        '#value' => '.'.$css.'',
    ], 'scroll_to_top_new_css'];

    $variables['#attached']['drupalSettings']['scroll_to_top']['label'] = $config->get( 'scroll_to_top_label');
 }
}