<?php

/**
 * @author Adrian Marin (https://drupal.org/u/amarincolas)
 *
 * @file
 * Adds a new set of pager items to the full pager.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function extra_pagination_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.extra_pagination':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extra Pagination is a very simple module that provides a new set of pager items between the last visible pager link and the maximum pager number. This is mainly done for SEO reasons to make us reach any page in 3-4 clicks maximum. Suggestions and feature requests are welcome.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme_registry_alter
 */
function extra_pagination_theme_registry_alter(&$theme_registry) {
  $theme_registry['pager']['path'] = drupal_get_path('module', 'extra_pagination') . '/templates';
}

/**
 * Implements template_preprocess_pager().
 */
function extra_pagination_preprocess_pager(&$variables) {
  $element = $variables['pager']['#element'];
  $parameters = $variables['pager']['#parameters'];
  $quantity = $variables['pager']['#quantity'];
  $route_parameters = $variables['pager']['#route_parameters'] ?? [];
  global $pager_page_array, $pager_total;

  // Nothing to do if there is only one page.
  if ($pager_total[$element] <= 1) {
    return;
  }

  // Calculate various markers within this pager piece:
  // Middle is used to "center" pages around the current page.
  $pager_middle = ceil($quantity / 2);
  // current is the page we are currently paged to.
  $pager_current = $pager_page_array[$element] + 1;
  // last is the last page listed by this pager piece (re quantity).
  $pager_last = $pager_current + $quantity - $pager_middle;
  // max is the maximum page number.
  $pager_max = $pager_total[$element];
  // End of marker calculations.

  require_once "includes/pager.inc";
  $variables['items']['extra'] = pager_extra_pages($pager_last, $pager_max, $route_parameters, $parameters, $element);
}
