<?php

/**
 * @file
 * Hooks to add ghostery link into a menu.
 */

/**
 * Implements hook_menu_links_discovered_alter().
 */
function ghostery_menu_links_discovered_alter(array &$links) {
  Drupal::service('ghostery.adchoices_link_insert')->insert($links);
}

/**
 * Implements hook_preprocess_menu().
 */
function ghostery_preprocess_menu(&$variables, $hook) {
  Drupal::service('ghostery.adchoices_link_alter')->alter($variables);
}
