<?php

/**
 * @file
 * Hook implementation for the Drulma companion module.
 */

/**
 * Implements hook_themes_installed().
 *
 * Add container class to blocks that do not have it.
 */
function drulma_companion_themes_installed(array $themeList) {
  foreach ($themeList as $theme) {
    // The installed theme is drulma or has drulma as a base theme.
    if ($theme === 'drulma' || in_array('drulma', array_keys(\Drupal::service('theme_handler')->getTheme($theme)->base_themes ?? []), TRUE)) {
      foreach ([
        'branding',
        'footer',
        'powered',
        'messages',
      ] as $blockId) {
        $block = \Drupal::service('entity_type.manager')->getStorage('block')->load($theme . '_' . $blockId);
        if ($block) {
          $third_party_settings = $block->get('third_party_settings');
          if (!$third_party_settings) {
            $third_party_settings = [
              "block_class" => [
                "classes" => "container",
              ],
            ];
            $block->set('third_party_settings', $third_party_settings);
            $dependencies = $block->get('dependencies');
            $dependencies['module'][] = 'block_class';
            $block->set('dependencies', $dependencies);
            $block->save();
          }
        }
      }
    }
  }
}
