<?php

namespace Drupal\tmgmt_wordbee\Beebox;
use Drupal\tmgmt\TMGMTException;

/**
 * BeeboxException
 *
 * Handle exceptions generated by the BeeBox API.
 *
 * @version 1.0
 * @author lpercetti
 */

class BeeboxException extends \Exception {
    /**
     * BeeBox Exception
     * @param mixed $message The main message
     * @param array $details The details
     * @param int $code The code
     * @param \Exception $previous 
     * @throws TMGMTException 
     */
    public function __construct($message = "", $details = null, $code = 0, \Exception $previous = NULL) {
        throw new TMGMTException($message, $details, $code);
    }
}