<?php

/**
 * @file
 * Core functionality for Spaces Enforced! module.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function spaces_enforced_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  $account = \Drupal::currentUser();
  $config = \Drupal::config('spaces_enforced.settings');
  $defchar = $config->get('spaces_enforced_defchar');
  $occurence = $config->get('spaces_enforced_occurence');
  if ($account->id() == 0) {
    $form['account']['name']['#description'] = (!$defchar) ? str_replace('Spaces are allowed', 'Spaces must be used', $form['account']['name']['#description']) : t('You must include at least @occurence @defchar in your username', array('@occurence' => $occurence, '@defchar' => ($defchar && $defchar == ' ') ? str_replace($defchar, ' ', '<space>') : $defchar));
    $form['account']['name']['#attributes'] = array('alt' => t('Spaces are allowed; punctuation is not allowed except for periods, hyphens, apostrophes, and underscores.'));
    $form['#validate'] = array('spaces_enforced_validate_register_form');
  }
}

/**
 * Registration validation function.
 */
function spaces_enforced_validate_register_form($form, $form_state) {
  $name = $form_state->getValue('name');
  $config = \Drupal::config('spaces_enforced.settings');
  $defchar = $config->get('spaces_enforced_defchar');
  $occurence = $config->get('spaces_enforced_occurence');
  if (substr_count($name, $defchar) < $occurence) {
    $form_state->setErrorByName('name', t('You have to use at least @occurence @defchar in your username.', array('@occurence' => $occurence, '@defchar' => ($defchar) ? str_replace($defchar, ' ', '<space>') : $defchar)));
  }
}
