<?php

/**
 * @file
 * Contact default fields override module file.
 */

use Drupal\Core\Field\Entity\BaseFieldOverride;
use Drupal\contact\Entity\ContactForm;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\contact\MessageForm;

/**
 * {@inheritdoc}
 */
function contact_default_fields_override_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  if ($entity_type->id() !== 'contact_message' || $bundle === NULL) {
    return [];
  }

  $contactForm = ContactForm::load($bundle);
  $fields = [];

  $settings = $contactForm->getThirdPartySettings('contact_default_fields_override');

  foreach (contact_default_fields_override_get_fields_to_override() as $field_to_override) {
    $field = BaseFieldOverride::createFromBaseFieldDefinition($base_field_definitions[$field_to_override], $bundle);

    if (isset($settings[$field_to_override . '_label'])) {
      $field->setLabel($settings[$field_to_override . '_label']);
    }

    if (isset($settings[$field_to_override . '_description'])) {
      $field->setDescription($settings[$field_to_override . '_description']);
    }

    if (isset($settings[$field_to_override . '_required'])) {
      $field->setRequired($settings[$field_to_override . '_required']);
    }

    $fields[$field_to_override] = $field;
  }

  return $fields;
}

/**
 * Determines which fields are overridable.
 *
 * See \Drupal\contact\Entity\Message::baseFieldDefinitions for all available
 * options.
 *
 * @return string[]
 *   The fields to override.
 */
function contact_default_fields_override_get_fields_to_override() {
  $overidable_fields = [
    'name',
    'mail',
    'subject',
    'message',
  ];

  Drupal::moduleHandler()
    ->invokeAll('contact_default_fields_override_alter', [&$overidable_fields]);

  return $overidable_fields;
}

/**
 * {@inheritdoc}
 *
 * We override the fields here again because name and mail are not created
 * using the BaseFieldOverride defined in
 * contact_default_fields_override_entity_bundle_field_info.
 */
function contact_default_fields_override_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (get_class($form_state->getFormObject()) !== MessageForm::class) {
    return;
  }
  /* @var Drupal\contact\Entity\ContactForm $contactForm */
  $contactForm = $form_state->getFormObject()->getEntity()->getContactForm();

  $settings = $contactForm->getThirdPartySettings('contact_default_fields_override');

  foreach (contact_default_fields_override_get_fields_to_override() as $field_to_override) {
    if (!isset($form[$field_to_override])) {
      continue;
    }
    if (isset($settings[$field_to_override . '_label'])) {
      $form[$field_to_override]['#title'] = $settings[$field_to_override . '_label'];
    }

    if (isset($settings[$field_to_override . '_description'])) {
      $form[$field_to_override]['#description'] = $settings[$field_to_override . '_description'];
    }

    if (isset($settings[$field_to_override . '_required'])) {
      $form[$field_to_override]['#required'] = $settings[$field_to_override . '_required'];
    }
  }
}
