<?php

/**
 * @file
 * Contains views_feed_link_field_alter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_feed_link_field_alter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the allowed_languages module.
    case 'help.page.views_feed_link_field_alter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Views Feed Link Field Alter extends the existing RssFields Row Plugin and alters:') . '</p>';
      $output .= '<ul>';
      $output .= '<li>' . t('channel link') . '</li>';
      $output .= '<li>' . t('item link') . '</li>';
      $output .= '<li>' . t('item GUID link') . '</li>';
      $output .= '</ul>';
      return $output;
  }
  return NULL;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function views_feed_link_field_alter_preprocess_views_view_rss(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  /** @var \Drupal\views\Plugin\views\style\StylePluginBase $style */
  $style = $view->getStyle();

  $options = [];
  if ($style->usesRowPlugin()) {
    /** @var \Drupal\views\Plugin\views\row\RowPluginBase $row_plugin */
    $row_plugin = $view->rowPlugin;
    $options = $row_plugin->options;
  }
  if ($options['custom_path_alter']) {
    $link_display_id = $view->display_handler->getLinkDisplay();
    /** @var \Drupal\views\Plugin\views\display\DisplayPluginBase $display */
    if ($link_display_id && ($display = $view->displayHandlers->get($link_display_id)) && $display->isEnabled()) {
      $url = $view->getUrl(NULL, $link_display_id);
    }

    /** @var \Drupal\Core\Url $url */
    if (!empty($url)) {
      $custom_domain = $options['custom_path_domain'];
      $url_string = $custom_domain . $url->toString();

      $variables['link'] = $url_string;
    }
  }
}
