<?php

function ae_theme($existing, $type, $theme, $path) {
  return [
      'signup' => [
        'variables' => [
            'socials' => [],
            'fields' => [],
            'general_settings' => [],
            'basic_options' => [],
            'email_options' => [],
            'text_options' => [],
            'performance_options' => []
        ],
      ],
      'setting' => [
          'variables' => [
              'heading' => 'Default Value'
          ]
      ],
      'register' => [

      ]
  ];
}

function ae_user_login($account) {
    drupal_set_message("New user created and logged in");
}
