<?php

use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @file
 * This module adds the "access asgument" parameter to each permission.
 *
 * Permission row in admin permissions page (admin/people/permissions).
 *  */

/**
 * Implements hook_help().
 */
function access_arguments_list_help($route_name, RouteMatchInterface $route_match) {
  $output = file_get_contents(drupal_get_path('module', 'access_arguments_list') . '/README.md');
  switch ($route_name) {
    case "help.page.access_arguments_list":
      return '<pre>' . $output . '</pre>';
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function access_arguments_list_form_user_admin_permissions_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  $form['#attached']['library'][] = 'access_arguments_list/permissions_form';
  $permissions = $form['permissions'];

  foreach ($permissions as $aal => $one_permission) {
    if (array_key_exists('description', $one_permission) and array_key_exists('#type', $one_permission['description']) and $one_permission['description']['#type'] == 'inline_template') {

      $item_id = str_replace(' ', '_', $aal);

      $formatted_description = new TranslatableMarkup($form['permissions'][$aal]['description']['#context']['description'].
      '<div id="@item_id" class="access_arguments_item"> <i>Access Argument: </i><strong>@permission_name</strong>'
      ,
      array('@item_id' => $item_id, '@permission_name' => $aal)
      );
      $form['permissions'][$aal]['description']['#context']['description'] = $formatted_description;
    }
  }
}

