<?php

/**
 * @file
 * Support for Soundcloud posts as media entities in Lightning.
 */

use Drupal\lightning_core\OverrideHelper as Override;
use Drupal\lightning_media_soundcloud\Plugin\MediaEntity\Type\Soundcloud;

/**
 * Implements hook_media_entity_type_info_alter().
 */
function lightning_media_soundcloud_media_entity_type_info_alter(array &$types) {
  $types['soundcloud']['input_match'] = [
    'constraint' => 'SoundcloudEmbedCode',
    'field_types' => [
      'string',
      'string_long',
    ],
  ];
  $types['soundcloud']['preview'] = TRUE;

  Override::pluginClass($types['soundcloud'], Soundcloud::class);
}
