<?php

/**
 * @file
 * Main file for the happy_new_year module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Datetime\DrupalDateTime;

/**
 * Implements hook_help().
 */
function happy_new_year_help($route_name, RouteMatchInterface $route_match) {
  return '';
}

/**
 * Implements hook_page_attachments().
 */
function happy_new_year_page_attachments(array &$attachments) {
  $route = \Drupal::routeMatch()->getRouteObject();
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute($route);

  if (!$is_admin) {
    $config = \Drupal::config('happy_new_year.settings');
    $period = $config->get('happy_new_year_period');

    if ($period) {
      $date_start = strtotime(date('Y') . '-' . date('n-j',strtotime($config->get('happy_new_year_start'))));
      $date_end = strtotime(date('Y') + 1 . '-' . date('n-j',strtotime($config->get('happy_new_year_end'))));
      $request_time = \Drupal::time()->getCurrentTime();

      if (!($request_time >= $date_start && $request_time <= $date_end)) {
        return;
      }
    }

    $garland = $config->get('happy_new_year_garland');
    $snow = $config->get('happy_new_year_snow');
    $snowcolor = $config->get('happy_new_year_snowcolor');
    $minified = $config->get('happy_new_year_minified');
    $is_garland_fixed = $config->get('happy_new_year_garland_fixed');

    if ($minified) {
      $snowLibrary = 'happy_new_year/snowstorm-min';
    }
    else {
      $snowLibrary = 'happy_new_year/snowstorm';
    }

    if ($garland) {
      $attachments['#attached']['library'][] = 'happy_new_year/garland';
      if ($is_garland_fixed) {
        $attachments['#attached']['drupalSettings']['fixed_garland'] = $is_garland_fixed;
      }
    }

    if ($snow) {
      $attachments['#attached']['library'][] = 'happy_new_year/snow';
      $attachments['#attached']['library'][] = $snowLibrary;
      $attachments['#attached']['drupalSettings']['happy_new_year']['snowcolor'] = $snowcolor;
    }
  }
}
