<?php

/**
 * @file
 * Defines necessary menu's, Permissions, age-calculator form & ajax callbacks.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_help().
 */
function unix_time_conversion_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.unix_time_conversion':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Unix time conversion provides blocks as a user interface for date-to-timestamp & vice-versa conversions.').' </p>';
      
      return $output;    
  }
}

