<?php

/**
 * @file
 * This module emails exceptions to admin users.
 */

/**
 * Implements hook_mail().
 */
function exception_mailer_mail($key, &$message, $params) {
  if ($key === "notify_exception") {
    $body =
    t('An exception has occurred.

    Exception: @exception

    Exception message: @message

    Thank you.', ['@exception' => $params['exception'], '@message' => $params['message']]);
    $message['subject'] = t('An exception occurred (@exception)', ['@exception' => $params['exception']]);
    $message['body'][] = $body;
  }
}
