<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function file_download_token_webform_form_webform_settings_confirmation_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $webform = $form_state->getFormObject()->getEntity();
  $settings = $webform->getThirdPartySettings('file_download_token_webform');

  $form['download_token'] = [
    '#type' => 'details',
    '#title' => t('Download token'),
    '#weight' => 10,
    '#open' => TRUE
  ];

  $default_file = NULL;
  if (isset($settings['download_token_file'])) {
    $default_file = \Drupal::entityTypeManager()->getStorage('file')->load($settings['download_token_file']);
  }

  $form['download_token']['download_token_file'] = [
    '#type' => 'entity_autocomplete',
    '#target_type' => 'file',
    '#default_value' => $default_file,
    '#description' => t('Specify a file that can be downloaded by inserting a tokenized link as a token (e.g. in an email handler).'),
  ];

  $form['actions']['submit']['#submit'][] = 'webform_form_file_download_token_submit';
}

/**
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function webform_form_file_download_token_submit($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if ($file_id = $form_state->getValue('download_token_file')) {
    /** @var \Drupal\webform\WebformInterface $webform */
    $webform = $form_state->getFormObject()->getEntity();
    $webform->setThirdPartySetting('file_download_token_webform', 'download_token_file', $file_id);
    $webform->save();
  }
}
