<?php

/**
 * @file
 * Contains custom_db_table_views.module.
 */

/**
 * Implements hook_help().
 */

function custom_db_table_views_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_db_table_views module.
    case 'help.page.custom_db_table_views':
      $output = '<pre>' . file_get_contents(drupal_get_path('module', 'custom_db_table_views') . '/README.txt') . '</pre>';
      return $output;


  }
}
