<?php

/**
 * @file
 * Renders the EFF Day of Action Banner on all pages.
 */

/**
 * Implements hook_page_attachments().
 */
function eff_action_page_attachments(array &$page) {
  $config['disableDate'] = \Drupal::config('eff_action.settings')->get('disable_date');
  $config['debug'] = \Drupal::config('eff_action.settings')->get('debug');
  if ($config['disableDate'] || $config['debug']) {
    $page['#attached']['drupalSettings']['effAction']['bannerConfig'] = $config;
    $page['#attached']['library'][] = 'eff_action/eff_action';
  }
  $page['#attached']['library'][] = 'eff_action/day_of_action';
}
