<?php

/**
 * @file
 * Altruja Module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function altruja_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.altruja':
      return t('
        <h2>Altruja online donations integration for Drupal.</h2>
        <h3>Instructions</h3>
        <p>Visit the altruja settings page</p>
      ');
  }
}

/**
 * Implements hook_preprocess_html().
 */
function altruja_preprocess_html(&$variables) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  $config = \Drupal::config('altruja.settings');
  if (!$is_admin && !empty($config->get('altruja.src'))) {
    $variables['#attached']['library'][] = 'altruja/altruja';
    $variables['page_top'][] = [
      '#type' => 'item',
      '#markup' => $config->get('altruja.link'),
      '#weight' => -10,
    ];
  }
}

/**
 * Implements hook_library_info_build().
 */
function altruja_library_info_build() {
  $config = \Drupal::config('altruja.settings');
  $libraries = [];
  if (empty($config->get('altruja.src'))) {
    return $libraries;
  }
  $libraries['altruja'] = [
    'header' => TRUE,
    'js' => [
      $config->get('altruja.src') => [],
    ],
  ];
  return $libraries;
}
