<?php

/**
 * @file
 * Module file for Normalize grid height.
 */

/**
 * Implements hook_page_attachments().
 */
function gridheightnormalizer_page_attachments(array &$page) {
  $config = \Drupal::config('gridheightnormalizer.settings');
  // Attaching js file to the page.
  $page['#attached']['library'][] = 'gridheightnormalizer/gridheightnormalizer-js';
  // Getting grid height selector and pass to the js.
  $page['#attached']['drupalSettings']['grid_selectors'] = $config->get('grid_height_equalizer_selectors', '');
}
