<?php

use Drupal\themekey\Entity\ThemeKeyRule;

/**
 * Implements hook_theme().
 */
function themekey_theme() {
  return array(
    'themekey_rule_chain_table' => array(
      'render element' => 'form',
      'file' => 'themekey.admin.inc',
      'function' => 'theme_themekey_rule_chain_table',
    ),
  );
}

/**
* Menu argument loader. Returns a ThemeKey Rule entity
*
* @param $id
* @return \Drupal\Core\Entity\EntityInterface|static
 */
function themekey_rule_load($id) {
  return ThemeKeyRule::load($id);
}
