<?php

/**
 * Implements hook_theme().
 */
function amp_video_embed_field_formatter_theme($existing, $type, $theme, $path) {
  return [
    'amp_video_embed_iframe' => [
      'variables' => [
        'url' => '',
        'video_embed_id' => '',
        'provider' => '',
        'query' => [],
        'attributes' => [],
        'fragment' => '',
      ],
    ],
    'amp_video_embed_not_compatible_provider' => [
      'variables' => [],
    ],
  ];
}
