<?php

use Drupal\contact_scheduler\ContactSchedulerContactFormHandler;
use Drupal\contact_scheduler\ContactSchedulerMessageFormHandler;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function contact_scheduler_theme($existing, $type, $theme, $path) {
  return [
    'contact_scheduler_message' => [
      'variables' => [
        'message' => NULL,
      ],
      'file' => 'contact_scheduler.theme.inc',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter() for contact_form_form().
 */
function contact_scheduler_form_contact_form_form_alter(&$form, FormStateInterface $form_state) {
  // Alter the contact form to add scheduler form elements.
  $contact_form_handler = new ContactSchedulerContactFormHandler();
  $contact_form_handler->alter($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function contact_scheduler_form_contact_message_form_alter(&$form, &$form_state, $form_id) {
  // Alter the message to add the schedule message.
  $message_form_handler = new ContactSchedulerMessageFormHandler();
  $message_form_handler->alter($form, $form_state);
}
