<?php
/**
 * @file
 * Install, uninstall and update the Openstat module.
 */

use \Drupal\Component\Utility\String;

/**
 * Implements hook_install().
 */
function openstat_install() {
  // Get Openstat counter ID.
  $counter_id = String::checkPlain(openstat_get_countet_id());

  // Save counter ID.
  if (!empty($counter_id)) {
    $config = \Drupal::config('openstat.settings');
    $config
      ->set('id', $counter_id)
      ->save();
  }
}
