<?php

/**
 * @file
 * Contains hook implementation to add MIME-based attachment to email.
 */

/**
 * Implements hook_mail_alter().
 *
 * Check if attachment was specified in message params.
 *
 * @param array $message
 */
function email_attachment_mail_alter(&$message) {
  if (!empty($message['params']['attachment']) || !empty($message['params']['attachments'])) {
    _convert_to_multipart($message);
  }
}

/**
 * Do the actual work.
 *
 * @param array $message
 *   From hook.
 */
function _convert_to_multipart(array &$message) {
  $params = $message['params'];
  $uid = "qd-" . md5("Drupal" . uniqid(time(), TRUE));

  $aHeaders = &$message['headers'];
  $sOrigContentType = $aHeaders['Content-Type'];
  $aHeaders['Content-Type'] = "multipart/mixed; boundary=\"$uid\"";

  $lines = "This is a multi-part message in MIME format.\r\n";
  $lines .= "--$uid\r\n";
  $lines .= "Content-Type: $sOrigContentType \r\n\r\n";
  $lines .= wordwrap(implode('', $message['body'])) . "\r\n\r\n";

  if (!empty($params['attachments'])) {
    if (!is_array($params['attachments'])) {
      throw new \InvalidArgumentException('[attachments] doesn’t have the right structure.');
    }
    foreach ($params['attachments'] as $aAttachment) {
      $lines .= _add_attachment($uid, $aAttachment);
    }
  }
  if (!empty($params['attachment'])) {
    $lines .= _add_attachment($uid, $params['attachment']);
  }
  $lines .= "--$uid--";

  $message['body'] = [$lines];
}

/**
 * @param string $uid the MIME separator
 * @param array $aAttachment a structure on what to attach
 *
 * @return string
 */
function _add_attachment($uid, $aAttachment): string {
  $sFileContent = $aAttachment['filecontent'];
  if (!$sFileContent) {
    throw new \InvalidArgumentException('Attachment doesn’t have the right structure.');
  }
  $sChunkedAttachment = chunk_split(base64_encode($sFileContent));
  $sMailAttachmentFriendlyName = basename($aAttachment['filename']);

  $lines = "--$uid\r\n";
  $lines .= "Content-Type: $aAttachment[filemime];
            name=\"" . $sMailAttachmentFriendlyName . "\"\r\n";
  $lines .= "Content-Transfer-Encoding: base64\r\n";
  $lines .= "Content-Disposition: attachment;
            filename=\"" . $sMailAttachmentFriendlyName . "\"\r\n\r\n";
  $lines .= $sChunkedAttachment . "\r\n\r\n";

  return $lines;
}
