[[guide_local_development]]
=== Goals

The purpose of this guide is to assist you with creating and installing a new Drupal application on your local machine for the purpose of development. Installing Drupal using the following instructions will give you a starting point for a website that can be deployed to a production environment. The intended audience for this guide is a developer.

[TIP]
Evaluating Drupal? <<guide_evaluator, Create a disposable Drupal demo application>> to evaluate Drupal's capabilities and codebase.

[[prereqs]]
=== Prerequisites

* You should be comfortable using a command-line terminal. See link:https://drupalize.me/videos/moving-around-command-line?p=1149[Moving Around the Command Line video tutorial].
* Sufficient system privileges to download and install new software.
* link:https://ddev.readthedocs.io/en/latest/[DDEV] is a link:https://www.docker.com/[Docker]-based tool that provides a preconfigured local development environment for Drupal. link:https://store.docker.com/search?type=edition&offering=community[Download the Docker community edition] for your OS before attempting to install DDEV.

[[ddev]]
=== Local development with DDEV

This guide provides instructions for installing link:https://www.drupal.org/docs/8/system-requirements[Drupal's system requirements] by using a free, cross-platform local development solution, link:https://ddev.readthedocs.io/en/latest/[DDEV]. Many viable link:https://www.drupal.org/docs/develop/local-server-setup[local development environment solutions] exist. Note: DDEV requires Docker.



Execute the following command to install DDEV:
....
curl -L https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | bash
....

For more information, view the link:https://ddev.readthedocs.io/en/latest/#installation[DDEV installation documentation].

[[create_application]]
=== Create a new Drupal application

Use link:https://getcomposer.org/download/[Composer] to install Drupal, which enables you to install and update dependencies (modules, themes, profiles, libraries, etc.) also with Composer. It is best practice to link:https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies[ensure that your entire Drupal application is managed with Composer] in order to facilitate manageable upgrades.

Use the commands listed below to create a new Drupal application via Composer. Replace `my_site_name` with the machine-friendly (no spaces or special punctuation) name for your new application and execute the commands.

....
# Replace my_site_name!
export SITE_NAME=my_site_name
composer create-project drupal-composer/drupal-project:8.x-dev --stability dev --no-interaction $SITE_NAME
cd $SITE_NAME
....

This will create a new directory and populate it with Drupal (and its dependencies).

[[config_local_serve_app]]
=== Configure your local development environment to serve your application

You now have a Drupal codebase. Next, you will need to configure your local development environment to serve that new codebase. At minimum, this requires creating a new database for Drupal and configuring the web server to serve Drupal content at a particular URL.

Run the following command (assumes DDEV):

....
ddev config --docroot web --projectname $SITE_NAME --projecttype drupal8
....

This will configure your new Drupal application to work with DDEV and will store the generated configuration in a new `.ddev` subdirectory.

Next, start the DDEV container

....
ddev start
....

You now have a web server and database server configured and running.

[[install_drupal]]
=== Install Drupal

Next, you must install Drupal, which populates your Drupal application's new database.

Using DDEV and Drush (a command-line utility for Drupal, that comes installed with DDEV), execute the command below. Replace `my-password` with the password that you would like to use for the link:https://www.drupal.org/docs/user_guide/en/user-admin-account.html[admin (user 1) account].

....
ddev exec drush site-install --account-name=admin --account-pass=my-password
....

(If you've manually configured your local development environment, visit your new Drupal site and follow the in-browser wizard.)

Drupal is now installed.

[[login]]
=== Login

Visit your new Drupal site and login.

If necessary, execute `ddev describe` to view the URL of your site. Copy and paste that URL into your web browser to visit it.

Login to the site using the `--account-name` and `--account-pass` you specified in the previous section (<<install_drupal>>).

[[next_steps]]
=== Next steps

What now?

Learn how you can begin to extend and customize your new Drupal application. Visit the link:https://www.drupal.org/docs/user_guide/en/index.html[Drupal 8 User Guide] and read the following chapters:

* link:https://www.drupal.org/docs/user_guide/en/config-chapter.html[Chapter 4. Basic Site Configuration]
* link:https://www.drupal.org/docs/user_guide/en/content-chapter.html[Chapter 5. Basic Page Management]
* link:https://www.drupal.org/docs/user_guide/en/content-structure-chapter.html[Chapter 6. Setting Up Content Structure]

[[appendix]]
=== Appendix

We chose to use DDEV for this local development guide because it met the following criteria:

1. Must be free and open source, without tying users into a proprietary product or service.
1. Must be well maintained, with long term support.
1. Must follow Drupal best practices.
1. Must be compatible with MacOS, Windows, and Linux.
1. Must be as simple as possible
  * Fewest pre-requisites
  * Fewest manual steps

To suggest a different local development solution, please create an issue in the link:https://www.drupal.org/project/issues/official_docs?categories=All[Official Docs issue queue].
