<?php

/**
 * @file
 * Contains libraries_debug.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function libraries_debug_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the libraries_debug module.
    case 'help.page.libraries_debug':
      $output = '';
      $output .= '<h3>' . t('Libraries Debug') . '</h3>';
      $output .= '<p>' . t('Show libraries been load it on every page request.') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_preprocess_page().
 */
function libraries_debug_preprocess_page(&$variables) {
  if (\Drupal::moduleHandler()->moduleExists('kint')) {
    $libraries = $variables['page']['#attached']['library'];
    $items = array();
    foreach ($libraries as $key) {
      $getValues = explode( '/', $key );
      $extension = $getValues[0];
      $libraryName = $getValues[1];
      $lib = \Drupal::service('library.discovery')->getLibraryByName($extension, $libraryName);
      $items[$key] = $lib;
    }
    kint($items);
  }
}

