<?php

/**
 * @file
 * Navigation trail module.
 */

/**
 * Implements hook_menu().
 */
function navigation_trail_menu() {
  $items = array();
  $items['admin/reports/trails'] = array(
    'title' => 'Trails',
    'description' => 'View the list of available trails to run.',
    'page callback' => 'navigation_trail_list',
    'access arguments' => array('access trail list'),
  );
  $items['trail/%trail'] = array(
    'title' => 'Start trail',
    'page callback' => 'navigation_trail_start',
    'page arguments' => array(1),
    'access arguments' => array('run trail'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function navigation_trail_permission() {
  return array(
    'access trail list' => array(
      'title' => t('Access trail list'),
    ),
    'run trail' => array(
      'title' => t('Run trail'),
    ),
  );
}

/**
 * Fetches a trail object from the database.
 *
 * @param $trailid
 *
 * @return object
 */
function trail_load($trailid) {
  $trails = module_invoke_all('navigation_trail');
  $trail = array();
  if (array_key_exists($trailid, $trails)) {
    $trail = $trails[$trailid];
    $trail['trailid'] = $trailid;
  }
  return $trail;
}

/**
 * View trail list
 */
function navigation_trail_list() {
  $trails = module_invoke_all('navigation_trail');
  $trail_list = array();
  foreach ($trails as $trailid => $trail_info) {
    $trail_list[] = l($trail_info['title'], 'trail/' . $trailid, array(
      'attributes' => array('title' => $trail_info['description']),
    ));
  }

  return array(
    '#theme' => 'item_list',
    '#items' => $trail_list,
  );
}

/**
 * Launches a trail.
 *
 * @param $trail
 */
function navigation_trail_start($trail) {
  $trail_paths = array();
  if (!empty($trail)) {
    $path_list = explode("\n", trim($trail['trail']));
    $trail_query = array('trailid' => $trail['trailid']);
    drupal_alter('navigation_trail', $path_list);
    foreach ($path_list as $path) {
      $path = trim($path);
      // Generate urls for the variants.
      foreach ($trail['options'] as $option) {
        $trail_paths[] = url($path, array('query' => $option + $trail_query));
      }
    }
    // Redirect to the report page if user has access, otherwise, redirect to frontpage.
    if (user_access('access trail list')) {
      $trail_paths[] = url('admin/reports/trails');
    }
    else {
      $trail_paths[] = url('<front>');
    }
    $json = json_encode($trail_paths, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT);
    drupal_add_js("localStorage.setItem('drupal.navigation.trail', JSON.stringify(" . $json . ") )", 'inline');
    $_GET['trailid'] = $trail['trailid'];
    return t('Trail is starting soon');
  }
  return t('Trail is empty, please fix it.');
}


/**
 * Change data injected in the JS.
 *
 * @param $data
 * @param $config
 */
function navigation_trail_navigation_timing_data_alter(&$data, &$config) {
  if (!empty($_GET['trailid'])) {
    // Always log timings if inside of a trail.
    $data['trailid'] = $_GET['trailid'];
  }
}

/**
 * Implements hook_rebuild().
 *
 * Refresh the variable containing the js to log navigation timing data.
 */
function navigation_trail_rebuild() {
  $js_file = drupal_get_path('module', 'navigation_trail') . '/navigation_trail.min.js';
  variable_set('navigation_trail_js', file_get_contents($js_file));
}

/**
 * Allow a piece of JS to be inserted in the loggin script.
 *
 * - Do not use comments
 * - Return minified JS
 *
 * @return {String}
 */
function navigation_trail_navigation_timing_inject_js() {
  if (!empty($_GET['trailid'])) {
    return variable_get('navigation_trail_js', '');
  }
}

/**
 * Implements hook_navigation_log_default_alter().
 */
function navigation_trail_navigation_log_default_alter(&$default) {
  $default['trailid'] = NULL;
}

/**
 * Implements hook_navigation_trail().
 */
function navigation_trail_navigation_trail() {
  $trails = array();
  $trails['core'] = array(
    'title' => 'Core paths',
    'description' => 'List most core pages',
    'options' => array(
      array(),
      array('no_js' => 1),
      array('no_css' => 1),
      array('no_js' => 1, 'no_css' => 1),
    ),
    'trail' => '
      admin
      user
      filter/tips
      node/add
      node/add/article
      node/add/page
      admin/appearance
      admin/config
      admin/content
      admin/modules
      admin/index
      admin/people
      admin/reports
      admin/structure
      admin/tasks
      admin/people/create
      admin/structure/block
      admin/content/comment
      admin/content/node
      admin/config/content
      admin/structure/types
      admin/config/development
      user/1/edit
      node/1/edit
      node/1/view
      user/1/view
      admin/modules/list
      admin/people/people
      admin/appearance/list
      admin/config/media
      admin/structure/menu
      admin/config/people
      admin/people/permissions
      admin/reports/dblog
      admin/config/regional
      admin/people/roles
      admin/config/search
      admin/appearance/settings
      admin/reports/status
      admin/config/system
      admin/reports/access-denied
      admin/reports/page-not-found
      admin/modules/uninstall
      admin/config/user-interface
      admin/config/services
      admin/config/workflow
      admin/config/people/accounts
      admin/config/system/actions
      admin/structure/block/add
      admin/structure/types/add
      admin/structure/menu/add
      admin/appearance/settings/bartik
      admin/config/system/cron
      admin/config/regional/date-time
      admin/reports/event/1
      admin/config/media/file-system
      admin/appearance/settings/global
      admin/config/people/ip-blocking
      admin/config/media/image-toolkit
      admin/structure/types/list
      admin/modules/list/confirm
      admin/structure/menu/list
      admin/config/development/logging
      admin/config/development/maintenance
      admin/config/development/performance
      admin/content/comment/new
      admin/config/services/rss-publishing
      admin/config/regional/settings
      admin/structure/menu/settings
      admin/appearance/settings/seven
      admin/config/system/site-information
      admin/appearance/settings/stark
      admin/config/content/formats
      admin/content/comment/approval
      admin/modules/uninstall/confirm
      admin/config/content/formats/filtered_html
      admin/config/content/formats/add
      admin/structure/block/list/bartik
      admin/structure/menu/manage/management
      admin/structure/types/manage/article
      admin/people/roles/edit/administrator
      admin/config/regional/date-time/formats
      admin/config/content/formats/list
      admin/config/system/actions/manage
      admin/config/people/accounts/settings
      admin/structure/block/list/seven
      admin/structure/block/list/stark
      admin/config/regional/date-time/types
      admin/structure/block/list/seven/add
      admin/config/regional/date-time/types/add
      admin/config/regional/date-time/formats/add
      admin/structure/menu/manage/management/add
      admin/structure/block/manage/system/main
      admin/structure/types/manage/article/delete
      admin/structure/menu/manage/management/delete
      admin/config/regional/date-time/formats/add
      admin/structure/menu/manage/main-menu
      admin/structure/menu/manage/management
      admin/structure/menu/manage/navigation
      admin/structure/menu/manage/user-menu
      admin/help
      admin/reports/fields
      admin/structure/taxonomy
      admin/reports/search
      admin/help/block
      admin/help/color
      admin/structure/taxonomy/tags
      admin/structure/taxonomy/add
      admin/config/media/image-styles
      admin/structure/taxonomy/list
      admin/config/search/settings
      admin/config/user-interface/shortcut
      admin/config/search/path
      admin/config/search/path/add
      admin/config/user-interface/shortcut/add-set
      admin/config/media/image-styles/add
      admin/structure/taxonomy/tags/add
      admin/config/search/settings/reindex
      admin/structure/taxonomy/tags/edit
      admin/structure/taxonomy/tags/list
      admin/config/search/path/list
      admin/config/media/image-styles/list
      admin/config/people/accounts/display
      admin/config/people/accounts/fields
      admin/structure/block/list/stark/add
      admin/config/user-interface/shortcut/shortcut-set-1/add-link
      admin/config/people/accounts/display/default
      admin/config/user-interface/shortcut/shortcut-set-1/delete
      admin/config/user-interface/shortcut/shortcut-set-1/edit
      admin/config/media/image-styles/edit/large
      admin/config/user-interface/shortcut/shortcut-set-1/links
      node/add
      admin/content
      admin/structure/taxonomy/tags/display
      admin/structure/taxonomy/tags/fields
      admin/structure/types/manage/tags/fields
      admin/structure/types/manage/article/display/default
      admin/structure/types/manage/article/comment/display/default',
  );

  return $trails;
}
