<?php
/**
 * @file
 */

use Drupal\views\Views;

/**
 * Intermediary access callback function getting view arguments
 * and calling real function specified in view definition.
 */
function views_access_callback_access_callback($view_name, $display_id, $access_callback) {
  // Init view.
  $view = Views::getView($view_name);
  $view->setDisplay($display_id);
  $view->initHandlers();

  // Find the values for any arguments embedded in the path via '%'.
  $i = 0;
  foreach (explode('/', $view->display_handler->getOption('path')) as $element) {
    if ($element == '%') {
      $view->args[] = arg($i);
    }
    $i++;
  }
  // Now handle any implicit arguments from the end of the path.
  $num_arguments = count($view->argument);
  while (count($view->args) < $num_arguments) {
    $view->args[] = arg($i);
    $i++;
  }

  $result = FALSE;
  if (function_exists($access_callback)) {
    $result = call_user_func_array($access_callback, $view->args);
  }
  return $result;
}
