<?php

/**
 * @file
 * Contains smooth_mouse_scrolling.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function smooth_mouse_scrolling_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the smooth_mouse_scrolling module.
    case 'help.page.smooth_mouse_scrolling':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Smooth mouse scrolling module is using the scrollSpeed jQuery plugin that provides smooth vertical scrolling as you scroll up/down the webpage with mouse wheel.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function smooth_mouse_scrolling_page_attachments(array &$page) {
  $smoth_config = \Drupal::config('smooth_mouse_scrolling.settings');
  $step = $smoth_config->get('step');
  $speed = $smoth_config->get('speed');
  $page['#attached']['library'][] = 'smooth_mouse_scrolling/scrool-speed';
  $page['#attached']['drupalSettings']['smooth_scroll']['scrool_speed']['step'] = $step;
  $page['#attached']['drupalSettings']['smooth_scroll']['scrool_speed']['speed'] = $speed;
}