<?php
/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function zsm_spectra_reporter_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.zsm_spectra_reporter':
            $ret = '<h2>' . t('ZSM: Spectra Reporter Plugin') . '</h2>';
            $ret .= '<h3>' . t('Todo: Add help') . '</h3>';
            return $ret;
    }
}

