<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function google_plus_login_form_user_form_alter(array &$form) {
  $is_managed_by_google_plus = (bool) Drupal::service('externalauth.authmap')
    ->get(
      Drupal::currentUser()->getAccount()->id(),
      'google_plus_login'
    );

  if (!$is_managed_by_google_plus) {
    return; // bail, this account is not managed by this module.
  }

  $config = Drupal::service('config.factory')->get('google_plus_login.settings');

  if ($config->get('disable_mail_field')) {
    $form['account']['mail']['#disabled'] = TRUE;
  }

  if ($config->get('disable_current_pass_field')) {
    $form['account']['current_pass']['#disabled'] = TRUE;
  }

  if ($config->get('disable_pass_field')) {
    $form['account']['pass']['#disabled'] = TRUE;
  }
}
