<?php

/**
 * Implements hook_requirements().
 */
function commerce_payplug_requirements($phase) {
  $requirements = [];
  if ($phase == 'install') {
    if (!class_exists('\Payplug\Payplug')) {
      $requirements['payplug_library'] = [
        'description' => t('Commerce Payplug requires the payplug library.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}
