<?php

/**
 * @file
 * Provides Maptiler map layers to the Leaflet module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\leaflet_maptiler\LeafletOperations;
use Drupal\leaflet_maptiler\LibraryOperations;

/**
 * Implements hook_help().
 */
function leaflet_maptiler_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the leaflet_maptiler module.
    case 'help.page.leaflet_maptiler':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds Maptiler map styles to Leaflet.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_leaflet_map_info().
 */
function leaflet_maptiler_leaflet_map_info() {
  return \Drupal::classResolver()
    ->getInstanceFromDefinition(LeafletOperations::class)
    ->leafletMapInfo();
}

/**
 * Implements hook_library_info_alter().
 */
function leaflet_maptiler_library_info_alter(&$libraries, $extension) {
  return \Drupal::classResolver()
    ->getInstanceFromDefinition(LibraryOperations::class)
    ->libraryInfoAlter($libraries, $extension);
}
