query EntityDefinition($name: String!) {
  definition: entityDefinition(name: $name) {
    label
    fields {
      id
      label
      description
      type
      required
      multiple
      maxNumItems
      status
      defaultValue
      isReference
      isHidden
      weight
      settings
    }
  }
}
