<?php

/**
 * @file
 * Module file for Micro Simple Sitemap module.
 */

use Drupal\micro_site\Entity\SiteInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function micro_simple_sitemap_site_insert(SiteInterface $site) {
  drupal_register_shutdown_function('_micro_simple_sitemap_site_post_insert', $site);
}

/**
 * Helper function to create a variant after a micro site is created.
 *
 * @param \Drupal\micro_site\Entity\SiteInterface $site
 *   The micro site entity.
 *
 * @throws \Drupal\Component\Plugin\Exception\PluginException
 */
function _micro_simple_sitemap_site_post_insert(SiteInterface $site) {
  /** @var \Drupal\micro_simple_sitemap\MicroSimpleSitemapManagerInterface $microSitemapManager */
  $microSitemapManager = \Drupal::service('micro_simple_sitemap.manager');
  $microSitemapManager->createSitemapVariant($site);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * @throws \Drupal\Component\Plugin\Exception\PluginException
 */
function micro_simple_sitemap_site_update(SiteInterface $site) {
  /** @var \Drupal\micro_simple_sitemap\MicroSimpleSitemapManagerInterface $microSitemapManager */
  $microSitemapManager = \Drupal::service('micro_simple_sitemap.manager');
  $sitemap_variants = $microSitemapManager->getSitemapVariants('micro_site');
  $variant_name = $microSitemapManager->getVariantName($site);
  if (!isset($sitemap_variants[$variant_name])) {
    $microSitemapManager->createSitemapVariant($site);
  }

  // If the site is unpublished the variant xml sitemap route has a 403.
  if ($site->isPublished()) {
    $microSitemapManager->publishSitemapVariant($site);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * @throws \Drupal\Component\Plugin\Exception\PluginException
 */
function micro_simple_sitemap_site_delete(SiteInterface $site) {
  /** @var \Drupal\micro_simple_sitemap\MicroSimpleSitemapManagerInterface $microSitemapManager */
  $microSitemapManager = \Drupal::service('micro_simple_sitemap.manager');
  $microSitemapManager->removeSitemapVariant($site);
}

/**
 * Implements hook_simple_sitemap_url_generators_alter().
 */
function micro_simple_sitemap_simple_sitemap_url_generators_alter(array &$definitions) {
  $definitions['entity_menu_link_content']['class'] = 'Drupal\micro_simple_sitemap\Plugin\simple_sitemap\UrlGenerator\DefaultEntityMenuLinkContentUrlGenerator';
  $definitions['entity']['class'] = 'Drupal\micro_simple_sitemap\Plugin\simple_sitemap\UrlGenerator\DefaultEntityUrlGenerator';
}

/**
 * Implements hook_update_dependencies().
 */
function micro_simple_sitemap_update_dependencies() {
  $dependencies['micro_simple_sitemap'][8301] = array(
    'simple_sitemap' => 8217,
  );
}
