<?php

/**
 * @file
 * SVG Icon module file.
 */

/**
 * Implements hook_theme().
 */
function svg_icon_theme($existing, $type, $theme, $path) {
  return [
    'svg_icon_admin' => [
      'template' => 'svg-icon-admin',
      'path' => $path . '/templates',
      'variables' => [
        'label' => '',
        'wrapper_attributes' => '',
        'svg_attributes' => '',
        'icon_url' => '',
      ],
    ],
    'svg_icon' => [
      'template' => 'svg-icon',
      'path' => $path . '/templates',
      'variables' => [
        'wrapper_attributes' => '',
        'svg_attributes' => '',
        'icon_url' => '',
        'use_canvas' => '',
      ],
    ],
  ];
}
