<?php

/**
 * @file
 * This module allows to add twitter profile settings.
 */

/**
 * Implements hook_page_attachments().
 */
function ckeditor_tweetthis_page_attachments(&$page) {
  $page['#attached']['library'][] = 'ckeditor_tweetthis/common-styling';
  $config = \Drupal::config('ckeditor_tweetthis.settings');
  $twitter_profile = $config->get('site_twitter_profile');
  $page['#attached']['drupalSettings']['twitterprofiler'] = $twitter_profile;
  $config = \Drupal::config('system.site');
  $sitename = $config->get('name');
  $page['#attached']['drupalSettings']['sitename'] = $sitename;
}
