<?php

use Drupal\file\Entity\File;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;

/**
 * @file
 * Contains file_entity_reference_image_formatter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function file_entity_reference_image_formatter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the file_entity_reference_image_formatter module.
    case 'help.page.file_entity_reference_image_formatter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Image Field formatter for File entity references') . '</p>';
      return $output;

    default:
  }
}
