<?php

/**
 * @file
 * Contains entity_role_view_mode_switcher.module.
 */

use Drupal\entity_role_view_mode_switcher\Util\ViewModeSwitcher;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view_mode_alter().
 */
function entity_role_view_mode_switcher_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  $view_mode = ViewModeSwitcher::switchViewModes($entity, $view_mode, \Drupal::currentUser()->getRoles());
}
