<?php

/**
 * @file
 * Common API for Local Tamper module.
 */

/**
 * Implements hook_locale_translation_projects_alter().
 *
 * Adds a number of projects to the project list for interface translable
 * projects. Added projects all have existing translations at
 * localize.drupal.org.
 */
function locale_tamper_locale_translation_projects_alter(&$projects) {
  $tamper_projects = _locale_tamper_projects();
  $projects += $tamper_projects;
}

/**
 * Returns an array of project data.
 */
function _locale_tamper_projects() {
  return array(
    'better_formats' => array(
      'name' => 'better_formats',
      'info' => array(
        'name' => 'Better Formats',
        'description' => 'Enhances the core input format system by managing input format defaults and settings.',
        'core' => '7.x',
        'configure' => 'admin/config/content/formats',
        'version' => '7.x-1.0-beta1',
        'project' => 'better_formats',
        'datestamp' => 1343262404,
        'dependencies' => array(
        ),
        'package' => 'Other',
        'php' => '5.2.4',
        'files' => array(
        ),
        'bootstrap' => 0,
        '_info_file_ctime' => 1349879175,
      ),
      'datestamp' => 1343262404,
      'includes' => array(
        'better_formats' => 'Better Formats',
      ),
      'project_type' => 'module',
      'project_status' => TRUE,
    ),
    'ckeditor_link' => array(
      'name' => 'ckeditor_link',
      'info' => array(
        'name' => 'CKEditor Link',
        'description' => 'Easily create links to Drupal internal paths through CKEditor.',
        'package' => 'User interface',
        'core' => '7.x',
        'configure' => 'admin/config/content/ckeditor_link',
        'version' => '7.x-2.2',
        'project' => 'ckeditor_link',
        'datestamp' => 1325952038,
        'dependencies' => array(
        ),
        'php' => '5.2.4',
        'files' => array(
        ),
        'bootstrap' => 0,
        '_info_file_ctime' => 1349879175,
      ),
      'datestamp' => 1325952038,
      'includes' => array(
        'ckeditor_link' => 'CKEditor Link',
      ),
      'project_type' => 'module',
      'project_status' => TRUE,
    ),
    'compact_forms' => array(
      'name' => 'compact_forms',
      'info' => array(
        'name' => 'Compact Forms',
        'description' => 'Overlays form fields with their respective labels using JavaScript.',
        'package' => 'User interface',
        'core' => '7.x',
        'configure' => 'admin/config/user-interface/compact_forms',
        'version' => '7.x-1.0',
        'project' => 'compact_forms',
        'datestamp' => 1294554354,
        'dependencies' => array(
        ),
        'php' => '5.2.4',
        'files' => array(
        ),
        'bootstrap' => 0,
        '_info_file_ctime' => 1349879175,
      ),
      'datestamp' => 1294554354,
      'includes' => array(
        'compact_forms' => 'Compact Forms',
      ),
      'project_type' => 'module',
      'project_status' => TRUE,
    ),
    'context' => array(
      'name' => 'context',
      'info' => array(
        'name' => 'Context',
        'dependencies' => array(
          0 => 'ctools',
        ),
        'description' => 'Provide modules with a cache that lasts for a single page request.',
        'package' => 'Context',
        'core' => '7.x',
        'files' => array(
          0 => 'context.module',
          1 => 'tests/context.test',
          2 => 'tests/context.conditions.test',
          3 => 'tests/context.reactions.test',
        ),
        'version' => '7.x-3.0-beta4',
        'project' => 'context',
        'datestamp' => 1344786407,
        'php' => '5.2.4',
        'bootstrap' => 0,
        '_info_file_ctime' => 1349879175,
      ),
      'datestamp' => 1344786407,
      'includes' => array(
        'context' => 'Context',
        'context_ui' => 'Context UI',
      ),
      'project_type' => 'module',
      'project_status' => TRUE,
    ),
    'ctools' => array(
      'name' => 'ctools',
      'info' => array(
        'name' => 'Chaos tools',
        'description' => 'A library of helpful tools by Merlin of Chaos.',
        'core' => '7.x',
        'package' => 'Chaos tool suite',
        'files' => array(
          0 => 'includes/context.inc',
          1 => 'includes/math-expr.inc',
          2 => 'includes/stylizer.inc',
        ),
        'version' => '7.x-1.2',
        'project' => 'ctools',
        'datestamp' => 1345319204,
        'dependencies' => array(
        ),
        'php' => '5.2.4',
        'bootstrap' => 0,
        '_info_file_ctime' => 1349879175,
      ),
      'datestamp' => 1345319204,
      'includes' => array(
        'ctools' => 'Chaos tools',
      ),
      'project_type' => 'module',
      'project_status' => TRUE,
    ),
    'delta' => array(
      'name' => 'delta',
      'info' => array(
        'name' => 'Delta API',
        'description' => 'The Delta module is an advanced manipulation of the Theme Settings API to allow for customization/configuration of theme settings based on node types, context, or groups of paths.',
        'package' => 'Theme Tools',
        'core' => '7.x',
        'version' => '7.x-3.0-beta11',
        'dependencies' => array(
          0 => 'ctools',
        ),
        'project' => 'delta',
        'datestamp' => 1343161343,
        'php' => '5.2.4',
        'files' => array(
        ),
        'bootstrap' => 0,
        '_info_file_ctime' => 1349879176,
      ),
      'datestamp' => 1343161343,
      'includes' => array(
        'delta' => 'Delta API',
        'delta_blocks' => 'Delta Blocks',
        'delta_ui' => 'Delta UI',
      ),
      'project_type' => 'module',
      'project_status' => TRUE,
    ),
    'wysiwyg' => array(
      'name' => 'wysiwyg',
      'info' => array(
        'name' => 'Wysiwyg',
        'description' => 'Allows to edit content with client-side editors.',
        'package' => 'User interface',
        'core' => '7.x',
        'configure' => 'admin/config/content/wysiwyg',
        'files' => array(
          0 => 'wysiwyg.module',
          1 => 'tests/wysiwyg.test',
        ),
        'version' => '7.x-2.1+28-dev',
        'project' => 'wysiwyg',
        'datestamp' => 1342141777,
        'dependencies' => array(
        ),
        'php' => '5.2.4',
        'bootstrap' => 0,
        '_info_file_ctime' => 1349879184,
      ),
      'datestamp' => 1342141777,
      'includes' => array(
        'wysiwyg' => 'Wysiwyg',
      ),
      'project_type' => 'module',
      'project_status' => TRUE,
    ),
  );
}
