<?php

/**
 * Implements hook_theme().
 */
function link_formatter_theme() {
  return [
    'link_formatter_display' => [
      'variables' => ['value' => NULL, 'width' => NULL, 'width_units' => NULL, 'height' => NULL, 'height_units' => NULL],
      'template' => 'link-formatter-display',
    ],
  ];
}

function check_headers($url) {
  $url_headers = get_headers($url);
  foreach ($url_headers as $key => $value) {
    $x_frame_options_deny = strpos(strtolower($url_headers[$key]), strtolower('X-Frame-Options: DENY'));
    $x_frame_options_sameorigin = strpos(strtolower($url_headers[$key]), strtolower('X-Frame-Options: SAMEORIGIN'));
    $x_frame_options_allow_from = strpos(strtolower($url_headers[$key]), strtolower('X-Frame-Options: ALLOW-FROM'));
    if ($x_frame_options_deny !== FALSE || $x_frame_options_sameorigin !== FALSE || $x_frame_options_allow_from !== FALSE) {
      return FALSE;
    }
  }
  return TRUE;
}
