<?php

/**
 * @file
 * Module implementation file.
 */

/**
 * Implements hook_path_update().
 */
function decoupled_router_path_update($path) {
  \Drupal::service('decoupled_router.cache_invalidation')
    ->invalidateByPath($path);
}

/**
 * Implements hook_path_insert().
 */
function decoupled_router_path_insert($path) {
  \Drupal::service('decoupled_router.cache_invalidation')
    ->invalidateByPath($path);
}

/**
 * Implements hook_path_delete().
 */
function decoupled_router_path_delete($path) {
  \Drupal::service('decoupled_router.cache_invalidation')
    ->invalidateByPath($path);
}
