<?php

/**
 * @file
 * Implements a select list widget that lets a user provide an alternate option.
 */


/**
 * Implements hook_validation_constraint_alter().
 *
 * @param &$definitions
 *   An associative array of definitions and classes that use them.
 */
function cck_select_other_validation_constraint_alter(&$definitions) {
  $definition = &$definitions['AllowedValues'];
  // DrupalWTF: Obliterating core/Symfony functionality is the only way to
  // bypass it.
  $definition['class'] = 'Drupal\cck_select_other\Validation\Plugin\Validation\Constraint\SelectOtherAllowedValuesConstraint';
  $definition['provider'] = 'cck_select_other';
}
