<?php

/**
 * @file
 * Marketo subscribe module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function marketo_subscribe_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the marketo_subscribe module.
    case 'help.page.marketo_subscribe':
      return t('<h3>:about</h3><p>:description</p>', [
        ':about' => 'About',
        ':description' => 'Provides a block where users can fill in their email
        address which will be stored in Marketo..',
      ]);

    default:
  }
}
