<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\group\Entity\GroupType;

/**
 * Implements hook_ENTITY_TYPE_view_alter() for group_content.
 */
function gcontact_group_content_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($display->getComponent('contact')) {
    $user = $entity->getEntity();

    // Link to the user's contact form.
    $url = Url::fromRoute('entity.user.contact_form', ['user' => $user->id()]);

    // Check access.
    if ($url->access()) {
      $text = t('Contact @name', ['@name' => $user->label()]);
      $renderable_link = Link::fromTextAndUrl($text, $url);
      $build['contact_link'] = $renderable_link->toRenderable();
    }

  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function gcontact_entity_extra_field_info() {
  $extra = [];

  // Add each profile type as an extra field for display. Enabled by default.
  foreach (GroupType::loadMultiple() as $group_type) {
    $plugin = $group_type->getContentPlugin('group_membership');
    $extra['group_content'][$plugin->getContentTypeConfigId()]['display']['contact'] = array(
      'label' => t('Contact link'),
      'description' => t("Display a link to the member's contact form."),
      'weight' => 10,
      'visible' => TRUE,
    );
  }

  return $extra;
}
