<?php

/**
 * @file
 * Hooks for otp_sms module.
 */

use Drupal\otp_sms\OtpSmsUserLoginFormAlter;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Form ID: 'user_login_form'.
 */
function otp_sms_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(OtpSmsUserLoginFormAlter::class)
    ->formAlter($form, $form_state);
}
