<?php

/**
 * Implementation of hook_form_alter().
 */
function select_remix_form_alter(&$form, $form_state, $form_id) {
  select_remix_cck_form_alter($form, $form_id);
  select_remix_node_form_alter($form, $form_id); 
}

function select_remix_cck_form_alter(&$form, $form_id) {
  // Check this is a CCK field with widget set to 'select'.
  if ($form_id != 'content_field_edit_form' && $form['basic']['widget_type']['#type'] != 'select') return;
  
  $type = $form['type_name']['#value'];
  $fields = content_fields();
  $field = $form['#field']['field_name'];
  $allowed_values = content_allowed_values($fields[$field]);
  
  if (empty($allowed_values)) {
    return;
  }

  $selected = variable_get('select_remix_'. $type .'_'. $field, array());
 
  $form['widget']['select_remix'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Hide Options'),
    '#description' => t('Select which options to hide for this content type.'),
    '#options' => $allowed_values,
    '#default_value' => $selected,
  );

  $form['#submit'][] = 'select_remix_cck_form_alter_submit';
  
}

function select_remix_node_form_alter(&$form, $form_id) {
  if ($form['#id'] != 'node-form') return;

  $types = _content_type_info();
  $type = $form['type']['#value']; 
  $fields = $types['content types'][$type]['fields'];

  foreach ($fields as $field_name => $field) {
    if ($field['widget']['type'] == 'optionwidgets_select') {
      $hide = variable_get('select_remix_'. $type .'_'. $field_name, array());
  
      if (!empty($hide)) {
         select_remix_hide_field_options($form, $field, $hide);
      }
    }
  }
  
}

function select_remix_hide_field_options(&$form, $field, $hide) {
  $fields = content_fields();
  $allowed_values = content_allowed_values($field);
  $field_name = $field['field_name'];

  if (empty($allowed_values)) return;

  foreach ($allowed_values as $name => $value) {
    if (!isset($hide[$name]) || empty($hide[$name])) {
      $options[$name] = "$name|$value";
    }
  } 

  $options = implode("\r\n", $options);
  $form['#field_info'][$field_name]['allowed_values'] = $options;
}  


function select_remix_cck_form_alter_submit($form, &$form_state) {
  $hiden = FALSE;
  $type = $form_state['values']['type_name'];
  $field = $form_state['values']['field_name'];
  $options = $form_state['values']['select_remix'];

  foreach ($options as $option) {
    if (!empty($option)) {
      $hiden = TRUE;
    }
  }
  
  if ($hiden) {
    variable_set('select_remix_'. $type .'_'. $field, $options);
  }
  else {
    variable_del('select_remix_'. $type .'_'. $field);
  }
}

