<?php

/**
 * @file
 * Contains \Drupal\password_eye\password_eye.install.
 */

/**
 * Implements hook_install().
 */
function password_eye_install() {
  // Set default values for config which require dynamic values.
  \Drupal::configFactory()->getEditable('pwd_eye.settings')
    ->set('pwd_eye.form_id_pwd', 'user_login_form')
    ->save();
}

/**
 * Implements hook_uninstall().
 */
function pasword_eye_uninstall() {
  \Drupal::configFactory()->getEditable('pwd_eye.settings')->delete();

}
