<?php
/**
 * @file
 */

/**
 * Implements hook_page_attachments().
 *
 * Insert JavaScript to the appropriate scope/region of the page.
 */
function wechat_share_advance_page_attachments(array &$page) {
  $http_host = \Drupal::request()->getSchemeAndHttpHost();
  $current_uri = \Drupal::request()->getRequestUri();
  $current_uri_arr = explode('#', $current_uri);
  $url = $http_host . $current_uri_arr[0];
  $config = \Drupal::config('wechat.default');
  $we_obj = _wechat_init_obj();
  $time_stamp = \Drupal::time()->getCurrentTime();
  $sign_package = $we_obj->getJsSign($url, $time_stamp, '', $config->get('appid'));
  $debug_mode = \Drupal::config('wechat_share_advance.adminsettings')->get('debug_mode');
  if (!empty($debug_mode)) {
    $debug_mode = TRUE;
  }
  else {
    $debug_mode = FALSE;
  }
  $page['#attached']['drupalSettings']['wechat_share_advance']['sign_package'] = $sign_package;
  $page['#attached']['drupalSettings']['wechat_share_advance']['debug_mode'] = $debug_mode;
  $page['#attached']['library'][] = 'wechat_share_advance/wechat.jweixin';
  $page['#attached']['library'][] = 'wechat_share_advance/wechat.shareEvent';
}
