<?php

/**
 * @file
 * Contains craftyclicks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function craftyclicks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the craftyclicks module.
    case 'help.page.craftyclicks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates addressfield to use with craftyclicks service (https://craftyclicks.com)') . '</p>';
      return $output;

    default:
  }
}
