<?php

/**
 * @file
 * Hook implementations for the facets_custom_label module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function facets_custom_label_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the facets_custom_label module.
    case 'help.page.facets_custom_label':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Customizes facet labels by setting a mapping of raw or display values => display value.') . '</p>';
      return $output;
  }
}
