<?php
use Drupal\group\Entity\Group;

function registry_examples_groupes_install() {
  
  $type = 'organisation';
  
  $betrieb = Group::create([
    'type' => $type,
    'label' => 'GDI-DE Betriebsstelle(BKG)',
    'field_abkurzung' => 'bst',
    'field_adresszusatz' => '',
    'field_bundesland' => 'Hessen',
    'field_internetauftritt' => 'redmine.gdi-de.org',
    'field_postleitzahl' => '60598',
    'field_stadt' => 'Frankfurt am Main',
    'field_strasse_und_hausnummer' => 'Richard-Strauss-Allee 11',
  ]);
  $betrieb->save();
  
  $betrieb = Group::create([
    'type' => $type,
    'label' => 'Koordinierungsstelle GDI-DE',
    'field_abkurzung' => 'kst',
    'field_adresszusatz' => '',
    'field_bundesland' => 'Hessen',
    'field_internetauftritt' => 'www.gdi-de.org',
    'field_postleitzahl' => '60598',
    'field_stadt' => 'Frankfurt am Main',
    'field_strasse_und_hausnummer' => 'Richard-Strauss-Allee 11',
  ]);
  $betrieb->save();
}

function registry_examples_groupes_uninstall() {
   
}

