<?php

/**
 * @file
 * Contains cacherefs.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Clear cache refs callback.
 */
function cacherefs_clear($node) {
  $bundle_fields = \Drupal::entityManager()->getFieldDefinitions('node', $node->getType());

  foreach ($bundle_fields as $name => $bundle_field) {
    if (strpos($name, 'field_') !== FALSE && $bundle_field->getType() == 'entity_reference') {
      $entref_fields[] = $name;
    }
  }

  foreach ($entref_fields as $entref_field) {
    $ctags[] = 'node:' . $node->get($entref_field)->target_id;
  }

  \Drupal::service('cache_tags.invalidator')->invalidateTags($ctags);
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function cacherefs_node_insert(EntityInterface $node) {
  cacherefs_clear($node);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function cacherefs_node_update(EntityInterface $node) {
  cacherefs_clear($node);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function cacherefs_node_delete(EntityInterface $node) {
  cacherefs_clear($node);
}
