<?php

/**
 * @file
 * Contains commerce_webpay_by.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_webpay_by_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_webpay_by module.
    case 'help.page.commerce_webpay_by':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Commerce integration into Webpay.by payment gateway') . '</p>';
      return $output;

    default:
  }
}
