<?php

/**
 * @file
 * CKAN Connect module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ckan_connect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ckan_connect':
      $output = '<p>' . t('The <a href=":ckan_connect_url">CKAN Connect</a> module connects to a CKAN endpoint providing a wrapper around the CKAN Action API.', [':ckan_connect_url' => 'https://www.drupal.org/project/ckan_connect']) . '</p>';
      return $output;
  }
}
