<?php

/**
 * @file
 * Contains cision_feeds.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cision_feeds_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cision_feeds module.
    case 'help.page.cision_feeds':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Import feeds from cision') . '</p>';
      return $output;

    default:
  }
}
