<?php

/**
 * Describe data tables and fields (or the equivalent) to Views.
 * @see hook_views_data_alter()
 */
function views_menu_relationship_views_data() {
  $data = array();
  $data['menu_tree'] = array();
  $data['menu_tree']['table'] = array();
  $data['menu_tree']['table']['group'] = t('Menu');
  $data['menu_tree']['table']['provider'] = 'views_menu_relationship';

  $data['menu_tree']['node_to_menu_tree'] = array(
    'title' => t('Menu tree'),
    'help' => t('Menu tree.'),
    'real field' => "CONCAT('node=', node_field_data.nid)",
    'relationship' => array(
      'title' => t('Menu tree'),
      'label' => t('Menu tree'),
      'base' => 'menu_tree',
      'id' => 'standard',
      'base field' => 'route_param_key',
    ),
  );

  $data['menu_tree']['weight'] = array(
    'title' => t('Weight'),
    'help' => t('Menu weight.'),
    'field' => array(
      'id' => 'numeric',
    ),

    'sort' => array(
      'id' => 'standard',
    ),
  );

  return $data;
}


/**
 * Implements hook_entity_update().
 */
function views_menu_relationship_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'menu_link_content') {
    $uri = $entity->link->uri;
    if ($uri && substr($uri, 0, 7) == 'entity:') {
      $uri_exploded = explode(':', $uri);
      $entity_info = explode('/', $uri_exploded[1]);
      Cache::invalidateTags([$entity_info[0] . ':' . $entity_info[1]]);
    }
  }
}
