<?php

/**
 * @file
 * Hooks Implementation for the block_ipaddress module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function block_ipaddress_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.block_ipaddress':
      $output = '';
      $output .= '<h3>' . t("About") . '</h3>';
      $output .= '<p>' . t("This module helps to create Ip Address specific Blocks. It Add IP Address setting to block and manages IP Address specific display of block.") . '</p>';
      $output .= '<h3>' . t("Uses") . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t("Block will be only visible for the selected IP Address. It detects and gets User's IP Address information and based on this it manages block visibility.") . '</dt>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function block_ipaddress_page_attachments_alter(array &$page) {
  $page['#attached']['library'][] = 'block_ipaddress/block_ipaddress';

}
