<?php

/**
 * @file
 * Comscore module.
 */

use Drupal\comscore_direct\ComscoreEvent;
use Drupal\comscore_direct\ComscoreEvents;
use Drupal\comscore_direct\ComscoreInformation;
use Drupal\comscore_direct\InlineScript;
use Drupal\Core\Url;

/**
 * Implements hook_page_attachments().
 */
function comscore_direct_page_attachments(array &$attachments) {
  $route_match = \Drupal::routeMatch();
  if ($route_match->getRouteObject()->getOption('_admin_route')) {
    return;
  }

  $options = ['absolute' => TRUE];
  $current_url = Url::fromRoute('<current>', [], $options)->toString(TRUE)->getGeneratedUrl();
  $comscore_information = ComscoreInformation::fromConfig(\Drupal::config('comscore_direct.settings'), $current_url);

  /** @var \Symfony\Component\EventDispatcher\EventDispatcherInterface $event_dispatcher */
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch(ComscoreEvents::RENDER, new ComscoreEvent($comscore_information));

  $inline_script = (new InlineScript());
  $script = $inline_script->getScriptRenderable($comscore_information);
  $noscript = $inline_script->getNoScriptRenderable($comscore_information);
  $attachments['#attached']['html_head'][] = [
    $script,
    'comscore_tracking_script',
  ];
  $attachments['#attached']['html_head'][] = [
    $noscript,
    'comscore_tracking_noscript',
  ];
}
