<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Created by PhpStorm.
 * User: WesselVrolijks
 * Date: 10/01/2018
 * Time: 16:57
 */

function twizo_init(){
}

function twizo_form_alter(&$form, FormStateInterface $form_state, $form_id){
    switch($form_id){
        case 'user_login_block':
        case 'user_login':
        case 'user_login_form':
            // Prevents login even if submit button is placed
            $form['#submit'][] = 'twizo_unload_user';

            // Deletes original form button.
            unset($form['actions']['submit']);

            // Adds ajax submit button.
            $form['twizo_login']['ajax-submit'] = array(
                '#type' => 'button',
                '#value' => t('Log in'),
                '#ajax' => array(
                    'callback' => '\Drupal\twizo\Controller\UserLoginController::validateLogin',
                    'wrapper' => 'twizo_ajax_login',
                    'method' => 'replace',
                    'effect' => 'fade',
                ),
            );
            // Inject .js files for Twizo widget
            $form['#attached']['library']['twizo_external'] = 'twizo/twizo_widget_external_js';
            $form['#attached']['library']['twizo_widget_handler'] = 'twizo/twizo_widget_handler';
        break;
    }
}

function twizo_unload_user(){
    return false;
}