<?php

/**
 * @file
 * Contains migrate_hierarchical_taxonomy.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_hierarchical_taxonomy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_hierarchical_taxonomy module.
    case 'help.page.migrate_hierarchical_taxonomy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate Hierarchical Taxonomy Unlimited Level') . '</p>';
      return $output;

    default:
  }
}
