<?php

/**
 * @file
 * Contains commerce_colissimo_shipping.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_colissimo_shipping_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_colissimo module.
    case 'help.page.commerce_colissimo_shipping':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Defines shipping method') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function commerce_colissimo_shipping_theme() {
  return [
    'colissimo_shipping_maps' => [
      'variables' => [
        'description' => null,
        'width' => null,
        'height' => null,
      ],
      'template' => 'colissimo_maps',
      'render element' => 'children',
    ],
  ];
}
