<?php

/**
 * @file
 * Module file for yasm.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function yasm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.yasm':
      $text = file_get_contents(dirname(__FILE__) . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        $output = '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.md file.
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $filter = \Drupal::service('plugin.manager.filter')->createInstance('markdown', ['settings' => $settings]);
        $output = $filter->process($text, 'en');
      }
      return $output;
  }
}
