<?php

/**
 * @file
 * Enables functionality for google standout.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function google_standout_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.google_standout':
      $output = t('This module add google standout tag to your site pages');
      return $output;
  }
}

/**
 * Implements hook_page_attachments().
 */
function google_standout_page_attachments(array &$page) {
  global $base_url;
  $node = \Drupal::routeMatch()->getParameter('node');
  // Get enable content type from configuration.
  $get_standout_var = (\Drupal::config('google_standout.settings')->get('google_standout'));
  if (count($get_standout_var) && isset($node)) {
    // Get configuration type from configuration.
    $get_type = $node->getType();
    if (in_array($get_type, $get_standout_var)) {
      $path = \Drupal::service('path.alias_manager')->getAliasByPath('/node/' . $node->id());
      $standout_path = $base_url . $path;
      $google_standout_config = (\Drupal::config('google_standout.settings')->get('google_standout_config'));
      if ($google_standout_config == 0) {
        $head_elements = [
          '#tag' => 'link',
          '#attributes' => [
            'rel' => 'standout',
            'href' => $standout_path,
          ],
        ];
      }
      if ($google_standout_config == 1) {
        $head_elements = [
          '#tag' => 'meta',
          '#attributes' => [
            'name' => 'standout',
            'content' => $standout_path,
          ],
        ];
      }
      $page['#attached']['html_head'][] = [$head_elements, 'standout'];
    }
  }
}
