<?php

/**
 * @file
 * Contains chart_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function chart_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chart_block module.
    case 'help.page.chart_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides jqPlot chart blocks.') . '</p>';
      return $output;

    default:
  }
}
