<?php

/**
 * @file
 * Hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function waterwheel_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    case 'help.page.waterwheel':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Waterwheel module is a Drupal SDK for JavaScript developers building Drupal-backed applications. With the Waterwheel module, you can employ schema discovery to facilitate client-side validation. It is a connector module to whaterwheel.js which helps JavaScript developers communitacte with Drupal.  For more information, see the <a href=":waterwheel">online documentation for the Waterwheel module</a>.', array(':waterwheel' => 'https://www.drupal.org/node/2800853')) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Server side') . '</dt>';
      $output .= '<dd>' . t(" Waterwheel.js can be used on the server side to make API calls within Node.js during server-side execution of a Javascript framework.") . '</dd>';
      $output .= '<dt>' . t('Client side') . '</dt>';
      $output .= '<dd>' . t(" Waterwheel.js can also be used on the client side to make asynchronous API calls after the browser loads the bundled library.") . '</dd>';
      $output .= '<dt>' . t('Universally') . '</dt>';
      $output .= '<dd>' . t(" Waterwheel.js can be used universally - the code to provision data is shared across client and server.") . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}
