<?php

/**
 * @file
 * Installation and schema related functions for the Git Issues module.
 */

/**
 * Implements hook_requirements().
 */
function git_issues_requirements($phase) {
  $requirements = [];
  // Non extra requirements detected by now.
  return $requirements;
}

/**
 * Implements hook_uninstall().
 */
function git_issues_uninstall() {
  \Drupal::service('config.factory')
    ->getEditable('git_issues.settings')
    ->delete();
}
