<?php

/**
 * @file
 * Defines functionalies for Git Issues module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_toolbar_alter().
 */
function git_issues_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'git_issues/toolbar';
}

/**
 * Implements hook_page_attachments().
 */
function git_issues_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'git_issues/label_filter';
}

/**
 * Implements hook_theme().
 */
function git_issues_theme($existing, $type, $theme, $path) {
  return [
    'issue_view' => [
      'render element' => 'custom_page',
      'path' => $path . '/templates',
      'template' => 'issue-view-page',
      'variables' => [
        'issue' => 'issue vars',
        'comments' => 'comments',
        'actions' => 'state actions',
        'edit' => TRUE,
      ],
    ],
  ];
}

/**
 * Implements hook_help().
 */
function git_issues_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.git_issues':
      return t('<p>The Git Issues module provides a GitHub core API layer for managing git issues from your Drupal website.</p>
      <p>Visit the <a href=":project_page">project page on Drupal.org</a> for more details.</p>',
        [
          ':project_page' => 'https://www.drupal.org/project/git_issues',
        ]);
  }
}
