<?php

/**
 * @file
 * Install, uninstall functions for the hunter test module.
 */

/**
 * Implements hook_install().
 */
function hunter_test_install() {
  if (!theme_exists('amazeui')) {
    drupal_set_message(t('Please download and enabled the <a href=":url">Amaze UI</a> theme at first.', array(':url' => 'https://www.drupal.org/project/amazeui')), 'error');
  }
  \Drupal::configFactory()->getEditable('system.site')->set('page.front', '/home')->save(TRUE);
}

/**
 * Implements hook_uninstall().
 */
function hunter_test_uninstall() {
  \Drupal::configFactory()->getEditable('system.site')->set('page.front', '/node')->save(TRUE);
}

/**
 * Check if theme is enabled.
 */
function theme_exists($theme_name) {
  if(\Drupal::service('theme_handler')->hasUi($theme_name)){
    \Drupal::service('theme_handler')->install(array($theme_name));
    return TRUE;
  }
  return FALSE;
}
