<?php

/**
 * @file
 * Implememnts hook_form_BASE_FORM_ID_alter.
 */

/**
 * Node forms.
 */
function edit_form_warn_form_node_form_alter(&$form, &$form_state, $form_id) {
  // Add the library to warn before leaving the edit page.
  $form['#attached']['library'][] = 'edit_form_warn/node-form';
}

/**
 * Media forms.
 */
function edit_form_warn_form_media_form_alter(&$form, &$form_state, $form_id) {
  // Add the library to warn before leaving the edit page.
  $form['#attached']['library'][] = 'edit_form_warn/node-form';
}

/**
 * Block forms.
 */
function edit_form_warn_form_block_content_form_alter(&$form, &$form_state, $form_id) {
  // Add the library to warn before leaving the edit page.
  $form['#attached']['library'][] = 'edit_form_warn/node-form';
}
