<?php

use Drupal\views\ViewExecutable;
use Drupal\link_header_pager\Plugin\views\pager\LinkHeaderPagerInterface;
use Drupal\views\Plugin\views\cache\CachePluginBase;

/**
 * Implements hook_views_post_execute().
 */
function link_header_pager_views_post_execute(ViewExecutable $view) {
  if (empty($view->pager) || !($view->pager instanceof LinkHeaderPagerInterface)) {
    return;
  }
  Drupal::service('link_header_pager.add_headers')->setPager($view->pager);
}
