<?php

/**
 * @file
 * Add Follow and Unfollow button functionality on content, taxonomy and user.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\SafeMarkup;

/**
 * Implements hook_help().
 */
function follow_unfollow_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.follow_unfollow':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('User can follow and unfollow particular node, taxonomy and user page so that they track the statistics of user following particular content.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function follow_unfollow_theme($existing, $type, $theme, $path) {
  return [
    'follow_unfollow_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function follow_unfollow_mail($key, &$message, $params) {
  $config = \Drupal::config('follow_unfollow.admin.settings');
  switch ($key) {
    case 'follow':
      $subject = $config->get('follow_unfollow_email.follow.subject');
      $body = $config->get('follow_unfollow_email.follow.body');

      $message['subject'] = SafeMarkup::format($subject, $params);
      $message['body'][] = SafeMarkup::format($body, $params);

      break;

    case 'unfollow':
      $subject = $config->get('follow_unfollow_email.unfollow.subject');
      $body = $config->get('follow_unfollow_email.unfollow.body');

      $message['subject'] = SafeMarkup::format($subject, $params);
      $message['body'][] = SafeMarkup::format($body, $params);

      break;
  }
}
