<?php

/**
 * @file
 * Contains algolia_search_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function algolia_search_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the algolia_search_custom module.
    case 'help.page.algolia_search_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Algolia Search custom module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function algolia_search_custom_theme($existing, $type, $theme, $path) {
  return [
    'asc_search_page' => [
      'variables' => [],
    ],
    'algolia_block' => [
      'variables' => [
        'form' => NULL,
        'path' => drupal_get_path('module', 'algolia_search_custom') . '/templates',
        'topSearches' => NULL,
        'bandeauUrl' => NULL,
      ],
    ],
  ];
}
