<?php

/**
 * @file
 * Implements hook_help().
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Markup;

/**
 * {@inheritdoc}
 */
function invitereferrals_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case "help.page.invitereferrals":
      return '<p>' . t("<b>About</b></br>
      Design and launch customer referral campaigns within minutes.</br>
      Visit http://www.invitereferrals.com for more information</br>
      </br><b>invitereferrals Module set up</b></br>
      1. Activate the plugin through the 'Modules' section in Drupal. </br>
      2. Visit your invitereferrals option 'Configure' to configure the settings</br>
      3. Get Secret Key and brandid as explained in the following steps</br>
      Go to www.invitereferrals.com and login (using information from registration)</br>
      Go to the Website Integration section on sidebar</br>
      Note the BrandID and Secret Key</br>
      5. Test your installation</br>      
      </br><b>Key features for your readers:</b></br>
      InviteReferrals is the simplest tool to design and launch Customer Referral Campaigns within minutes. Select from multiple campaigns and languages.</br>
      Besides on website as referral widget, you also get a Facebook Customer Referral Campaign timeline app.</br>") . '</p>';

  }
}

/**
 * {@inheritdoc}
 */
function invitereferrals_page_bottom(array &$page_bottom) {
  $mode = 'parent';
  $moduleHandler = \Drupal::service('module_handler');
  if ($moduleHandler->moduleExists('overlay')) {
    $mode = overlay_get_mode();
  }

  if ($mode != 'child') {
    $config = \Drupal::config('invitereferrals.settings');

    if ($config->get('invitereferrals_enable_rewards')) {
      $secretkey = $config->get('invitereferrals_secret_key', '');
      $brandID = $config->get('invitereferrals_brandID', '');

      global $user;

      $t = time();
      $bid = $brandID;
      $secKey = $secretkey;
      if (isset($user->uid) && 0 != $user->uid) {
        // The user email id.
        $setUserEmail = $user->mail;
      }
      else {
        $setUserEmail = '';
      }
      /* Optional parameters if passing email id as well */
      if (isset($user->uid) && 0 != $user->uid) {
        // First name of customer.
        $fname = $user->name;
      }
      else {
        $fname = '';
      }
      $md5SecretKey = strtoupper(md5($secKey . '|' . $bid . '|' . $t . '|' . $setUserEmail));
      $invitereferralsScript = "<script>var invite_referrals = window.invite_referrals || {}; (function() { 
      invite_referrals.auth = {
      bid_e : '" . $md5SecretKey . "',
      bid : '" . $bid . "', email : '" . $setUserEmail . "',
      t : '" . $t . "', userParams : {'fname' : '" . $fname . "' }};
      var script = document.createElement('script');script.async = true;
      script.src = 'http://' + 'cdn.invitereferrals.com/js/invite-referrals-1.0.js';
      var entry = document.getElementsByTagName('script')[0];entry.parentNode.insertBefore(script, entry); })();</script>";

      $page_bottom['mymodule'] = [
        '#markup' => Markup::create($invitereferralsScript),
      ];
    }
  }
}
