<?php

/**
 * @file
 * Contains install and update functions for Commerce Pay.JP.
 */

/**
 * Implements hook_requirements().
 */
function commerce_payjp_requirements($phase) {
  $requirements = [];
  if ($phase == 'install') {
    if (!class_exists('\Payjp\Payjp')) {
      $requirements['commerce_payjp_library'] = [
        'description' => t('Commerce Pay.JP requires the payjp/payjp-php library.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}
