<?php

/**
 * @file
 * Contains entity_overlay.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_overlay_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_overlay module.
    case 'help.page.entity_overlay':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Display a content entity as an overlay.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function entity_overlay_theme() {
  return [
    'entity_overlay_list_item' => [
      'variables' => [
        'entity_view' => NULL,
        'entity_id' => NULL,
        'entity_type_id' => NULL,
        'entity_overlay_link' => NULL,
        'display_link' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}
