<?php

/**
 * Implements hook_theme_suggestions_page_alter() to set 4xx template suggestions.
 */
function fourxx_templates_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  // get the route
  $route_name = \Drupal::routeMatch()->getRouteName();
  $route_parts = explode('.', $route_name);

  // is it system.4xx ? 
  if (count($route_parts) == 2 && $route_parts[0] === 'system') {
    $code = $route_parts[1];
    if (is_numeric($code) && $code >= 400 and $code < 500) {
      // suggest template page--4xx.html.twig (e.g., page--404.html.twig)
      $suggestions[] = 'page__' . $route_parts[1];
    }
  }
}

/**
 * Implements hook_module_implements_alter() to make sure our suggestions have priority.
 */
function fourxx_templates_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'theme_suggestions_page_alter') {
    // Move my_module_form_alter() to the end of the list.
    // \Drupal::moduleHandler()->getImplementations()
    // iterates through $implementations with a foreach loop which PHP iterates
    // in the order that the items were added, so to move an item to the end of
    // the array, we remove it and then add it.
    $group = $implementations['fourxx_templates'];
    unset($implementations['fourxx_templates']);
    $implementations['fourxx_templates'] = $group;
  }
}