<?php

/**
 * @file
 * Contains search_api_best_bets.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function search_api_best_bets_theme() {
  return array(
    'search_api_best_bets_formatter' => array(
      'variables' => array('query_text' => NULL, 'exclude' => NULL),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter() for 'field_config_edit_form'.
 */
function search_api_best_bets_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state) {
  if ($form_state->getFormObject()->getEntity()->getType() == 'search_api_best_bets') {
    // Hide the required and default value fields.
    $form['required']['#access'] = FALSE;
    $form['required']['#disabled'] = TRUE;
    $form['default_value']['#access'] = FALSE;
    $form['default_value']['#disabled'] = TRUE;
  }
}

/**
 * Prepares variables for best bets formatter field templates.
 **
 * Default template: search-api-best-bets-formatter.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - query_text: The query text added in UI.
 *   - exclude: The boolean value of exclude.
 */
function template_preprocess_search_api_best_bets_formatter(&$variables) {
  $variables['exclude_formatted'] = $variables['exclude'] ? t('Yes') : t('No');
}

/**
 * Implements hook_preprocess_HOOK() for search-api-page-result.html.twig
 * template.
 */
function search_api_best_bets_preprocess_search_api_page_result(&$variables) {
  /* @var $item \Drupal\search_api\Item\ItemInterface */
  $item = $variables['item'];

  // Add extra attributes if the result item is elevated.
  $variables['elevated'] = FALSE;
  if ($item->getExtraData('elevated')) {
    $variables['title_attributes']['class'][] = 'search-api-elevated';
    $variables['content_attributes']['class'][] = 'search-api-elevated';
    $variables['elevated'] = TRUE;
  }

}
