<?php

/**
 * @file
 * Contains role_paywall.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\Entity\NodeType;

/**
 * Implements hook_help().
 */
function role_paywall_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the role_paywall module.
    case 'help.page.role_paywall':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Introduces a paywall to fields content based on roles.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_field_access().
 */
function role_paywall_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  $manager = \Drupal::service('role_paywall');
  return $manager->getFieldAccessResult($operation, $field_definition, $account, $items);
}

function role_paywall_entity_extra_field_info() {
  $manager = \Drupal::service('role_paywall');

  $paywall = [];
  foreach ($manager->getPaywallBundles() as $bundle) {
    $paywall['node'][$bundle]['display']['paywall'] = [
      'label' => 'Paywall',
      'description' => 'Place the paywall block',
      'weight' => 100,
      'visible' => TRUE,
    ];

  }
  return $paywall;

}

function role_paywall_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if (!$display->getComponent('paywall')) {
    return;
  }
  $manager = \Drupal::service('role_paywall');

  if (in_array($entity->id(), $manager->getPaywallNodes())) {
    $barrier = $manager->getBarrier();
    $build['paywall'] = [
      '#markup' => $barrier,
      '#cache' => [
        'contexts' => [
          'user.roles',
        ],
        'tags' => [
          'config:paywall.settings',
        ],
      ],
    ];
    // @todo article_test module may not be enabled.
    $build['paywall']['#attached']['library'][] = 'role_paywall_article_test/isEmailRegistered.ajax';
  }
}
