<?php

/**
 * @file
 * This file provides an install hook that adds multiple custom links.
 */

use Drupal\menu_link_content\Entity\MenuLinkContent;

/**
 * Implements hook_install().
 */
function hn_test_menu_install() {

  $first_menu_link = MenuLinkContent::create([
    'menu_name' => 'main',
    'title' => 'Custom menu link',
    'link' => 'internal:/internal-node-link',
  ]);

  $first_menu_link->save();

  MenuLinkContent::create([
    'menu_name' => 'main',
    'title' => 'Nested menu link',
    'link' => 'http://external.link',
    'parent' => $first_menu_link->getPluginId(),
  ])->save();

}
