<?php

/**
 * @file
 * Contains password_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function password_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the password_field module.
    case 'help.page.password_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('module that saves password') . '</p>';
      return $output;

    default:
  }
}



