<?php

/**
 * @file
 * An example module of how to post an invoice from an ubercart order
 * with line items. This doesn't do very much error checking to see
 * if the invoice might already exist, and can be improved greatly.
 * Not to be used with production sites.
 */

/**
 * Implements of hook_uc_order().
 *
 * @param string $op
 *   The operation string.
 * @param \Drupal\uc_order\Entity\Order $order
 *   The order object.
 * @param mixed $arg2
 *   Secondary argument.
 */
function uc_xero_example_uc_order($op, $order, $arg2) {
  if ($op === 'update') {
    if ($order->getStatus() === 'pending') {

      $typedDataManager = \Drupal::typedDataManager();
      $list_definition = $typedDataManager->createListDataDefinition('xero_invoice');
      $invoices = $typedDataManager->create($list_definition, 'xero_invoice');

      $values = [
        'Contact' => [
          'Name' => $order->getUser()->getAccountName(),
          'EmailAddress' => $order->getEmail(),
        ],
        'Type' => 'ACCREC',
        'Date' => date('Y-m-d'),
        'DueDate' => date('Y-m-d', time() + 1296000), // NET15
        'LineAmountTypes' => 'NoTax',
        'Status' => 'SUBMITTED',
        'Reference' => 'ORDER-' . $order->getOriginalId(),
        'LineItems' => [],
      ];

      foreach ($order->getLineItems() as $i => $line_item) {
        $values['LineItems'][$i]['LineItem'] = [
          'Description' => $line_item->title,
          'LineAmount' => $line_item->amount,
          'AccountCode' => 200,
        ];
      }

      $invoices->appendItem($values);

      /** @var \Drupal\xero\XeroQuery $query */
      $query = \Drupal::service('xero.query');
      $query
        ->setType('xero_invoice')
        ->setData($invoices)
        ->setMethod('post');

      $result = $query->execute();

      // Do something with $result.
    }
  }
}
