<?php

/**
 * @file
 * Base file for the data_api module.
 */

/**
 * Return a Data object for working with data.
 *
 * @param string|null $entity_type
 *   The entity type if any that will be passed to the instance.  This setting
 *   is what helps us get the proper field values and translations from
 *   entities.
 *
 * @return \AKlump\Data\DataInterface
 *   An instance of \AKlump\Data\DataInterface
 */
function data_api($entity_type = NULL) {
  $objects = &drupal_static(__FUNCTION__, []);
  if (empty($objects[$entity_type])) {
    $data = \Drupal::service('data_api');
    \Drupal::moduleHandler()->alter('data_api_object', $data);
    $objects[$entity_type] = clone $data;
    $objects[$entity_type]->setEntityType($entity_type);
  }

  return $objects[$entity_type];
}
