<?php

/**
 * @file
 * Commerce product reservation module.
 *
 * @author eirik@nymedia.no
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function commerce_product_reservation_form_commerce_order_item_add_to_cart_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\commerce_product_reservation\CartFormHandler $handler */
  $handler = \Drupal::service('commerce_product_reservation.cart_form_handler');
  $handler->handleCartFormAlter($form, $form_state, $form_id);
}
