<?php

/**
 * @file
 * Provide a scrolling number widget for integers.
 *
 * SpinInt provides a simple number scroller for integer numbers with an up
 * arrow and a down arrow. If a max or min value is set on the field then the
 * spinner will respect these. If both max and min are set the spinner with
 * cycle through numbers if clicked past a limit.
 */

/**
 * Implements hook_theme().
 */
function spinint_theme() {
  return array(
    'spinint' => array(
      'template' => 'spinint',
      'variables' => array(
        'instance' => NULL,
        'value' => NULL,
      ),
    ),
  );
}
