<?php

/**
 * @file
 * Contains charting.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function charting_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the charting module.
    case 'help.page.charting':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allow integrate charts in content in a practical way.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function charting_theme() {
  return [
    'easy_pie_chart_percent_field_formatter' => [
      'variables' => [
        'id' => NULL,
        'percent' => NULL,
        'value' => NULL,
      ],
      'template' => 'easy-pie-chart-percent-field-formatter',
    ],
    'percent_bar_field_formatter' => [
      'variables' => [
        'id' => NULL,
        'percent' => NULL,
        'value' => NULL,
      ],
      'template' => 'percent-bar-field-formatter',
    ],
    'views_style_charting_chart' => [
      'variables' => [
        'id' => NULL,
        'view' => NULL,
      ],
    ],
  ];
}

/**
 * Prepares variables for views-style-charting-chart.html.twig template.
 */
function charting_preprocess_views_style_charting_chart(&$variables) {
  $handler = $variables['view']->style_plugin;

  // Fetch wrapper classes from handler options.
  if ($handler->options['wrapper_class']) {
    $wrapper_class = explode(' ', $handler->options['wrapper_class']);
    $variables['attributes']['class'] = array_map('\Drupal\Component\Utility\Html::cleanCssIdentifier', $wrapper_class);
  }

  template_preprocess_views_view_unformatted($variables);
}
