<?php

/**
 * @file
 * Contains install and update routines for Openportal Core module.
 */

/**
 * Implements hook_install().
 */
function openportal_core_install() {
  // Make sure the theme is installed.
  $theme_handler = \Drupal::service('theme_handler');
  $theme_handler->install(['adminimal_theme']);

  // Set adminimal_theme as the admin theme.
  $config = \Drupal::service('config.factory')->getEditable('system.theme');
  $config->set('admin', 'adminimal_theme')->save();

}
