<?php
/**
 * Created by PhpStorm.
 * User: will
 * Date: 5/29/18
 * Time: 8:57 AM
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Form\FormStateInterface;

function byu_feature_card_paragraphs_theme() {
  $theme['paragraph__byu_feature_card'] = [
    'template' => 'paragraph--byu-feature-card'
  ];
  return $theme;
}

function template_preprocess_paragraph__byu_feature_card(&$variables) {
  $variables['paragraph'] = $variables['elements']['#paragraph'];
  $variables += array('content' => array());
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

function byu_feature_card_paragraphs_form_alter(&$form, FormStateInterface $formState, $formId) {
  $fields = [];
  foreach (Element::children($form) as $field) {
    $fields[] = $field;
  }

  foreach ($fields as $field) {
    foreach ($form[$field]['widget'] as $i => $tempVar) {
      if (is_numeric($i) && isset($form[$field]['widget'][$i]['subform']['field_byu_card_container']['widget']['add_more'])) {
        $form[$field]['widget'][$i]['subform']['field_byu_card_container']['widget']['add_more']['add_more_select']['#options'] += ['byu_feature_card' => 'BYU Feature Card'];
      }
    }
  }
}