<?php

/**
 * @file
 * Contains ckeditor_apester.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ckeditor_apester_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ckeditor_apester module.
    case 'help.page.ckeditor_apester':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module create a Plugin on Ckeditor to show apester') . '</p>';
      return $output;

    default:
  }
}


function ckeditor_apester_form_alter(&$form, $form_state, $form_id) {
//  $form['#attached'] = [
//    'library' => [
//        'ckeditor_apester/apester'
//    ],
//  ]
}

/**
 * Implements hook_page_attachments_alter().
 */
function ckeditor_apester_page_attachments_alter(&$page) {
  $page['#attached']['library'][] = 'ckeditor_apester/apester';
}