<?php

/**
 * @file
 * Module installation code.
 */

/**
 * Implements hook_uninstall().
 */
function static_root_page_uninstall() {
  $config = \Drupal::configFactory()->getEditable('language.types');
  $language_types = \Drupal::languageManager()->getLanguageTypes();
  foreach ($language_types as $type) {
    $config->clear('negotiation.' . $type . '.enabled.static-root-page');
  }
  $config->save();
}
