<?php

/**
 * @file
 * This module add node tags.
 */

use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_presave().
 */
function intelligent_tools_duplicate_rate_node_presave(EntityInterface $node) {
  if ($node->is_new) {
    $new_flag = TRUE;
  }
  else {
    $new_flag = FALSE;
  }
  $config = \Drupal::config('intelligent_tools.settings');
  $flag = FALSE;
  $content_type_node = $config->get('intelligent_tools_duplicate_rate_content');
  $address_web = $config->get('intelligent_tools_duplicate_rate_ip');
  $content_type_node = strtolower($content_type_node);
  $content_type_node_array = explode(" ", $content_type_node);
  $content_type_field = $config->get('intelligent_tools_duplicate_rate_field');
  $content_type_field_array = explode(" ", $content_type_field);
  $node_main_flag = FALSE;
  foreach ($content_type_node_array as $key => $value) {
    if (($node_main_flag == FALSE)&&($node->getType() == $value)) {
      $node_main_flag = TRUE;
      $main_key = $key;
    }
  }
  $content_type_field = $content_type_field_array[$main_key];
  if ($node_main_flag == TRUE) {
    $body = $node->get($content_type_field)->getValue()[0]['value'];
    $dup_rate = duplicate_rate_api($body, $address_web);
    $dup_rate = number_format((float) $dup_rate['dupl_rate'], 2, '.', '');$nid = $node->id();
    if ($nid == '') {
      drupal_set_message('Duplicity percentage:' . $dup_rate);
    }
  }
}

/**
 * Separate duplicate rate api function.
 */
function duplicate_rate_api($body, $address_web) {
  $body = preg_replace('/ +/', ' ', preg_replace('/[^A-Za-z0-9 ]/', ' ', urldecode(html_entity_decode(strip_tags($body)))));
  try {
    $client = new Client(['base_uri' => $address_web]);
    $response = $client->request('POST', '', [
      'form_params' => [
        'text' => $body,
      ],
    ]);
    $dup_rate_json = json_decode($response->getBody()->getContents());
  }
  catch (GuzzleException $e) {
    \Drupal::logger('intelligent_tools')->error($e->getMessage());
    drupal_set_message($e->getMessage(), 'error');
  }
  foreach ($dup_rate_json as $key => $value) {
    $dup_rate = $value;
  }
  return ['dupl_rate' => $dup_rate];
}
