<?php
define('EQSF_TYPE_END', 'end_date');
define('EQSF_TYPE_START', 'start_date');

use Drupal\eqsf\EqsfCron;

/**
 * Implements hook_cron()..
 */
function eqsf_cron() {
  _eqsf_publish_unpublish();
 _eqsf_cleanup_executed_schemas();
}

/**
 * Implements hook_cronapi().
 */
function eqsf_cronapi($op, $job = NULL) {
  $items['eqsf_publish_unpublish'] = array(
    'title'     => 'Do the publication actions.',
    'callback'  => '_eqsf_publish_unpublish',
    'scheduler' => array(
      'name'    => 'crontab',
      'crontab' => array(
        'rules' => array('*/1 * * * *'),
      ),
    ),
  );

  $items['eqsf_recalculate_infinite_cron'] = array(
    'title'     => 'Cleanup old actions',
    'callback'  => '_eqsf_cleanup_executed_schemas',
    'scheduler' => array(
      'name'    => 'crontab',
      'crontab' => array(
        'rules' => array('0 0 * * *'),
      ),
    ),
  );
  return $items;
}

/**
 *  publish or unpublish entity
 */
function _eqsf_publish_unpublish() {
  $c = new EqsfCron();
  $c->runCron();
}

/**
 *  extension to remove old items in queue
 */

function _eqsf_cleanup_executed_schemas() {
  $c = new EqsfCron();
  $c->cleanup();
}