<?php

use Drupal\Core\Url;
use Drupal\x_reference\Entity\XReferenceType;

/**
 * @file
 * Module file for "x_reference".
 */

/**
 * Prepares variables for list of available x_reference type templates.
 *
 * Default template: x-reference-add-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: An array of content types.
 *
 * @see x_reference_add_page()
 */
function template_preprocess_x_reference_add_list(&$variables) {
  $variables['types'] = [];
  if (!empty($variables['content'])) {
    /** @var XReferenceType $type */
    foreach ($variables['content'] as $type) {
      $typeId = $type->id();
      $variables['types'][$typeId] = [
        'type' => $typeId,
        'add_link' => \Drupal::l($typeId, new Url('x_reference.x_reference_add', ['x_reference_type' => $typeId])),
      ];
    }
  }
}
