<?php

/**
 * @file
 * Block In Page Not Found Module.
 */

/**
 * Implements hook_help().
 */use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Function block_in_page_not_found_help.
 */
function block_in_page_not_found_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.block_in_page_not_found':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Block In Page not found module ability to place a block in 404 page or page not found') . '</p>';
      $output .= '</dl>';
      return $output;

    break;

  }
}
