/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/'use strict';

(function (Drupal, drupalTranslations, wp) {
  if (!drupalTranslations) {
    return false;
  }

  var translations = {
    '': {
      lang: 'pt',
      plural_forms: 'nplurals=2; plural=(n != 1)'
    }
  };

  Object.entries(drupalTranslations.strings['']).map(function (t) {
    translations[t[0]] = t[1];
  });

  wp.i18n.setLocaleData(translations);

  console.log(wp.i18n);
})(Drupal, drupalTranslations, wp);