/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/'use strict';

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

(function (Drupal, drupalSettings) {
  function addQueryArgs(url, args) {
    var qs = Object.keys(args).map(function (key) {
      return key + '=' + encodeURIComponent(args[key]);
    });

    if (url === 'edit.php') {
      if (args.post_type && args.post_type === 'wp_block') {
        return drupalSettings.path.baseUrl + 'admin/content/reusable-blocks';
      }
    }
    return url + (qs ? '?' + qs.join('&') : '');
  }

  window.wp = window.wp || {};
  window.wp.url = _extends({}, window.wp.url, { addQueryArgs: addQueryArgs });
})(Drupal, drupalSettings);