<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * implimentation of hook_form_alter()
 */

function cron_time_form_alter(&$form, FormStateInterface $form_state, $form_id) {
	if ($form_id == 'system_cron_settings') {

		$config = \Drupal::config('cron_time.settings');
		$cronTime = $config->get('custom_cron_time');

		$form['cron']['interval']['#options'][$cronTime] = 'Cron Time';
		$form['cron']['custom_cron_time'] = array(
			'#type' => 'textfield',
			'#title' => t('Cron Time'),
			'#description' => t('Now the cron time will execute after 1 minute, as we hardcoded the duration (60 second = 1 minute)'),
			'#default_value' => $config->get('custom_cron_time'),
			'#id' => 'edit-cron-time',
			'#states' => array(
				'required' => array(
					':input[name="interval"]' => array('value' => $cronTime),
				),	
				'visible' => array(
					':input[name="interval"]' => array('value' => $cronTime),
				),	
			),
		);
		
		$form['#submit'][] = 'custom_cron_time_callback';

	}
}

function custom_cron_time_callback(array &$form, FormStateInterface $form_state) {
	
	\Drupal::service('config.factory')
		->getEditable('cron_time.settings')
		->set('custom_cron_time', $form_state->getValue('custom_cron_time'))
		->save();

		drupal_get_messages('status');
    drupal_set_message('Update cron time.');

}	

