<?php

/**
 * @file
 * Contains icons_icomoon.module..
 */

/**
 * Implements hook_library_info_build().
 */
function icons_icomoon_library_info_build() {
  $libraries = [];

  /** @var \Drupal\Core\Entity\EntityTypeManagerInterface $entityTypeManager */
  $query = \Drupal::entityQuery('icon_set')
    ->condition('plugin', 'icomoon');

  $ids = $query->execute();

  /** @var \Drupal\Core\Entity\EntityTypeManagerInterface $entityTypeManager */
  $entityTypeManager = \Drupal::service('entity_type.manager');
  $iconSetStorage = $entityTypeManager->getStorage('icon_set');

  /** @var \Drupal\icons\Entity\IconSetInterface[] $icon_sets */
  $icon_sets = $iconSetStorage->loadMultiple($ids);

  // Add a library whose information changes depending on certain conditions.
  foreach ($icon_sets as $icon_set) {
    /** @var \Drupal\icons_icomoon\Plugin\IconLibrary\IcoMoon $plugin */
    $plugin = $icon_set->getPlugin();
    $path = $plugin->getLibraryPath();
    $libraries[$icon_set->id()] = [
      'css' => [
        'base' => [
          $plugin->getLibraryBasePath($path) . '/style.css' => [],
        ],
      ],
    ];
  }
  return $libraries;
}
