<?php

/**
 * @file
 * Contains commerce_export.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_migrate_csv_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_export module.
    case 'help.page.commerce_migrate_csv_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Commerce Migrate CSV Example module imports products and product variations from an example CSV file.') . '</p>';
      return $output;
  }
}
