<?php

/**
 * Implements hook_form_alter().
 */
function hide_preview_form_alter(&$form, $form_state, $form_id)
{
    $config = Drupal::config('hide_preview.settings');
    $formNames = $config->get('hide_preview.form_names');

    foreach ($formNames as $name) {
        // check if it is a regexp or a simple string
        if (@preg_match($name, $form_id, $matches) !== false) {
            if (count($matches)) {
                $form['actions']['preview']['#access'] = false;
            }
        } else if (strpos($form_id, 'contact_message_') !== false) {
            $form['actions']['preview']['#access'] = false;
        }
    }
}