<?php

/**
 * @file
 * Contains videobackground.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function videobackground_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'videobackground.admin_settings':
      return t('Easy as hell module for play video background.By using this module 
                user can play the uploaded video in the background of the 
                selected CSS selectors on whole page. This module has lot of 
                features like Volume control, looping, Resizing (resizes if the 
                window resizes), PlaybackRate and starts automatically.');
  }
}

/**
 * Implements hook_page_attachments().
 */
function videobackground_page_attachments(array &$attachments) {
  if (\Drupal::currentUser()->hasPermission('use video background')) {
    videobackground_attach($attachments);
  }
}

/**
 * Adds video background.
 *
 * @param array $attachments
 *   Add attachments to selectors.
 */
function videobackground_attach(array &$attachments) {
  $config = \Drupal::config('videobackground.settings');
  $video_location = [
    'mp4' => $config->get('mp4'),
    'ogv' => $config->get('ogv'),
    'webm' => $config->get('webm'),
    'poster' => $config->get('poster'),
  ];

  $options = [
    // Video backgrounds options.
    'volume' => $config->get('volume'),
    'playbackRate' => $config->get('playbackrate'),
    'muted' => $config->get('muted'),
    'loop' => $config->get('loop'),
    'autoplay' => $config->get('autoplay'),
    // Similar to the CSS `background-position` property.
    'position' => $config->get('position'),
    // Poster image type. "detect" — auto-detection;
    // "none" — no poster; "jpg", "png", "gif",... - extensions.
    'posterType' => $config->get('postertype'),
    // Auto-resizing, read: https://github.com/VodkaBears/Vide#resizing
    'resizing' => $config->get('resizing'),
    // Allow custom background-color for Vide div.
    'bgColor' => $config->get('bgcolor'),
     // Add custom CSS class to Vide div.
    'className' => $config->get('classname'),
  ];

  $attachments['#attached']['library'][] = 'videobackground/videobackground';
  // Adding settings.
  $whitechars = ["\r\n", "\r", "\n"];
  $attachments['#attached']['drupalSettings']['video_background'] = [
    'include' => str_replace($whitechars, ',', $config->get('included_selectors')),
    'path' => $video_location,
    'options' => $options,
  ];
}
