<?php

/**
 * @file
 * Contains entity_modifier_viewmode.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_modifier_view_mode_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_modifier_viewmode module.
    case 'help.page.entity_modifier_viewmode':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Viewmode field for entity modifier') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function entity_modifier_view_mode_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  if (empty($entity->modifiers['view_mode'])) {
    return;
  }

  $view_mode = $entity->modifiers['view_mode']->get('field_view_mode')->getValue()[0]['value'];
}


