<?php

/**
 * @file
 * Contains flashpoint.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function flashpoint_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the flashpoint module.
    case 'help.page.flashpoint':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Flashpoint Education') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function flashpoint_theme() {
  return [
    'flashpoint' => [
      'render element' => 'children',
    ],
  ];
}
