<?php

/**
 * @file
 * Install, update and uninstall functions for the dcat_export module.
 */

/**
 * Change xml setting to rdf.
 */
function dcat_export_update_8001() {
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('dcat_export.settings');

  $formats = $config->get('formats');

  if (in_array('xml', $formats)) {
    unset($formats['xml']);
    $formats = ['rdf' => 'rdf'] + $formats;
    $config->set('formats', $formats);
    $config->save();
  }
}
