<?php

/**
 * @file
 * Contains dtuber.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function dtuber_theme() {
  return array(
    'dtuber_field_formatter' => array(
      'variables' => array('options' => NULL),
      'template' => 'dtuber-field-formatter',
    ),
  );
}

/**
 * Implements hook_help().
 */
function dtuber_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.dtuber':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dtuber aka "Drupal YouTuber" - Uploads Video to a YouTube Channel. Provides a new Field type, that can be attached to a Content-type.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt><h6>' . t('Installation') . '</h6></dt>';
      $output .= '<dd>' . t('1. Install Google Client API Library via composer using command "composer require google/apiclient:^2.0" in your project root.') . '</dd>';
      $output .= '<dd>' . t('2. Clone/Download module to /modules directory') . '</dd>';
      $output .= '<dd>' . t('3. If you are installing the DTuber module via composer using command "composer require drupal/dtuber" then you don&apos;t need to install Google Client API Library separately.') . '</dd>';
      $output .= '<dd>' . t('4. Enable DTuber module (via drush or by Drupal&apos;s Extend page)') . '</dd>';
      $output .= '<dt><h6>' . t('Configure') . '</h6></dt>';
      $output .= '<dd>' . t('1. Create an application at @developer_console & @enable_youtube_api.', ['@developer_console' => Link::fromTextAndUrl(t('Google Developer Console'), Url::fromUri('http://console.developers.google.com'))->toString(), '@enable_youtube_api' => Link::fromTextAndUrl(t('Enable YouTube Data API'), Url::fromUri('https://console.developers.google.com/apis/library/youtube.googleapis.com/?id=125bab65-cfb6-4f25-9826-4dcc309bc508&project=forward-pad-135123'))->toString()]) . '</dd>';
      $output .= '<dd>' . t('2. Navigate to @credentials & then "OAuth 2.0 client IDs" where you get the Client ID, Client Secret ID & Set Redirect uri to as given in DTuber @configuration_link.', ['@credentials' => Link::fromTextAndUrl(t('Credentials'), Url::fromUri('https://console.developers.google.com/apis/credentials?project=forward-pad-135123'))->toString(), '@configuration_link' => Link::fromTextAndUrl(t('Configuration page'), Url::fromRoute('dtuber.configform'))->toString()]). '</dd>';
      $output .= '<dd>' . t('2. Set Client ID, Client Secret ID in DTuber @configuration_link as mentioned in @credentials.', ['@configuration_link' => Link::fromTextAndUrl(t('Configuration page'), Url::fromRoute('dtuber.configform'))->toString(), '@credentials' => Link::fromTextAndUrl(t('Credentials'), Url::fromUri('https://console.developers.google.com/apis/credentials?project=forward-pad-135123'))->toString()]) . '</dd>';
      $output .= '<dd>' . t('4. Create Youtube channel & Switch to Config page, Click "Authorize" button.') . '</dd>';
      $output .= '<dd>' . t('5. Redirects to Google authentication page, That will ask for your YouTube channel&apos;s permission then please "Click Allow" to grant the permission to upload video to YouTube.') . '</dd>';
      $output .= '<dd>' . t('6. It redirects back to Dtuber Config page.') . '</dd>';
      $output .= '<dt><h6>' . t('Test') . '</h6></dt>';
      $output .= '<dd>' . t('1. Goto Administration > Content Type > Manage Fields.') . '</dd>';
      $output .= '<dd>' . t('2. Add new Field : Dtuber - Upload to YouTube.') . '</dd>';
      $output .= '<dd>' . t('3. Add a new Content.') . '</dd>';
      $output .= '<dd>' . t('4. Upload video to the added Field. Click Save.') . '</dd>';
      $output .= '<dd>' . t('5. Video will get uploaded to YouTube channel as configured in Admin page.') . '</dd>';
      $output .= '<dt><h6>' . t('Alternate way to test module') . '</h6></dt>';
      $output .= '<dd>' . t('Another way to test Video Uploads. Goto : @configuration_testform, Fill in fields and submit form. <br/> Check your YouTube Channel for latest updated Video.', ['@configuration_testform' => Link::fromTextAndUrl(t('Test DTuber'), Url::fromRoute('dtuber.testform'))->toString()]) . '</dd>';
      $output .= '</dl>';

      return $output;
  }
}
