<?php

/**
 * @file
 * Contains decoupled_quiz.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;

define('DECOUPLED_QUIZ_QUIZ_ENTITY', 'quiz');

define('DECOUPLED_QUIZ_QUESTION_ENTITY', 'question');

define('DECOUPLED_QUIZ_ANSWER_ENTITY', 'answer');

/**
 * Implements hook_help().
 */
function decoupled_quiz_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the decoupled_quiz module.
    case 'help.page.decoupled_quiz':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Headless quizzes, surveys &amp; etc') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function decoupled_quiz_theme() {
  $theme = [];

  $theme['quiz'] = [
    'render element' => 'elements',
    'file' => 'quiz.page.inc',
    'template' => 'quiz',
  ];
  $theme['quiz_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'quiz.page.inc',
  ];
  $theme['question'] = [
    'render element' => 'elements',
    'file' => 'question.page.inc',
    'template' => 'question',
  ];
  $theme['question_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'question.page.inc',
  ];
  $theme['answer'] = [
    'render element' => 'elements',
    'file' => 'answer.page.inc',
    'template' => 'answer',
  ];
  $theme['answer_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'answer.page.inc',
  ];
  $theme['result'] = [
    'render element' => 'elements',
    'file' => 'result.page.inc',
    'template' => 'result',
  ];
  $theme['result_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'result.page.inc',
  ];
  return $theme;

}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function decoupled_quiz_theme_suggestions_quiz(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#quiz'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'quiz__' . $sanitized_view_mode;
  $suggestions[] = 'quiz__' . $entity->bundle();
  $suggestions[] = 'quiz__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'quiz__' . $entity->id();
  $suggestions[] = 'quiz__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function decoupled_quiz_theme_suggestions_question(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#question'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'question__' . $sanitized_view_mode;
  $suggestions[] = 'question__' . $entity->bundle();
  $suggestions[] = 'question__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'question__' . $entity->id();
  $suggestions[] = 'question__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function decoupled_quiz_theme_suggestions_answer(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#answer'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'answer__' . $sanitized_view_mode;
  $suggestions[] = 'answer__' . $entity->bundle();
  $suggestions[] = 'answer__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'answer__' . $entity->id();
  $suggestions[] = 'answer__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_entity_operation_alter().
 */
function decoupled_quiz_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'quiz') {
    if (\Drupal::service('router.route_provider')->getRouteByName('entity.quiz.flow.form')) {
      $operations['manage-flows'] = [
        'title' => t('Manage Flows'),
        'weight' => 50,
        'url' => Url::fromRoute('entity.quiz.flow.form',
          [
            'quiz' => $entity->id(),
          ],
          [
            'query' => [
              'destination' => \Drupal::request()->getRequestUri(),
            ],
          ]
        ),
      ];
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function decoupled_quiz_theme_suggestions_result(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#result'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'result__' . $sanitized_view_mode;
  $suggestions[] = 'result__' . $entity->bundle();
  $suggestions[] = 'result__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'result__' . $entity->id();
  $suggestions[] = 'result__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
