<?php

/**
 * @file
 * Contains webform_extra_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\webform_extra_field\Form\WebformExtraFieldSettingsForm;

/**
 * Implements hook_help().
 */
function webform_extra_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_extra_field module.
    case 'help.page.webform_extra_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides an extra field to place a webform under manage display.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_extra_field_display_info_alter().
 */
function webform_extra_field_extra_field_display_info_alter(array &$info) {
  $config = \Drupal::getContainer()
    ->get('config.factory')
    ->get('webform_extra_field.settings')
    ->get(WebformExtraFieldSettingsForm::EXTRA_FIELD_ADMIN);

  if ($config) {
    foreach ($config as $entity_type_id => $bundles) {
      foreach ($bundles as $bundle_id => $bundle) {
        if ($bundle) {
          $info['webform_extra_field_display']['bundles'][] = $entity_type_id . '.' . $bundle_id;
        }
      }
    }
  }

}
