<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Form;
use Drupal\Core\Ajax;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\CommandInterface;
use Drupal\Core\Ajax\ChangedCommand;
use Drupal\Core\Ajax\CssCommand;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Form\FormBase;

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function auto_tagging_suggestions_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, '_form') !== FALSE && strpos($form_id, 'node_') !== FALSE) {
    $form['auto_tagging_suggestions'] = array(
      '#type' => 'fieldset',
      '#title' => t('Auto Tagging Suggestions'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#group' => 'advanced',
      '#weight' => -10,
    );

    $from_fields[] = $to_fields[] = "Select";
    $fields = \Drupal::entityManager()->getFieldStorageDefinitions('node');
    foreach ($fields as $key => $value) {
      if ($value->getType() == "text_with_summary") {
        $from_fields[$key] = $key;
      }
      if($value->getType() == "entity_reference" && $value->getSetting('target_type') == "taxonomy_term") {
        $to_fields[$key] = $key;
      }
    }

    $form['auto_tagging_suggestions']['from'] = array(
      '#type' => 'select',
      '#title' => t('From'),
      '#options' => $from_fields,
    );
    $form['auto_tagging_suggestions']['to'] = array(
      '#type' => 'select',
      '#title' => t('To'),
      '#options' => $to_fields,
      '#ajax' => array(
        'callback' => 'auto_tagging_suggestions_to_callback',
        'wrapper' => 'to-div',
        'event' => 'change',
      ),
    );
    $form['auto_tagging_suggestions']['submit'] = array(
      '#type' => 'button',
      '#value' => t('Suggest & Fill'),
//      '#ajax' => array(
//        'callback' => 'auto_tagging_suggestions_submit_callback',
//        'wrapper' => 'ajax_callback',
//        'method' => 'replace',
//        'effect' => 'fade',
//      ),
      '#executes_submit_callback' => TRUE,
      '#prefix' => '<div id="to-div">',
      '#suffix' => '</div>',
    );
  }
}
//function auto_tagging_suggestions_submit_callback(&$form, FormStateInterface $form_state) {
////  $response = new AjaxResponse();
//
//}
function auto_tagging_suggestions_to_callback(&$form, FormStateInterface $form_state) {
  $response = new AjaxResponse();
  $response->addCommand(new Drupal\Core\Ajax\ReplaceCommand("#to-div", render($form)));
  return $response;
//  return array(
//    '#type' => 'ajax',
//    '#commands' => array(
//      ajax_command_replace("#to-div", render($form['auto_tagging_suggestions']['submit'])),
//      ajax_command_replace("#to-div1", render($form['auto_tagging_suggestions']['reset']))
//    )
//  );
}