<?php

/**
 * Implements hook_help().
 */
function beer_o_clock_help($path, $arg) {
  switch ($path) {
    case 'admin/help#beer_o_clock':
      return '<p>' . t("Provides an easy way to produce a page that will simply tell you whether it is beer o'clock yet or not. Beer o'clock can be configured in the administration settings for the site to suit your particular company/workplace.") . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function beer_o_clock_theme() {
  return [
    'beer_o_clock_block' => [
      'variables' => [
        'message' => '',
        'not_message' => '',
        'display' => 'beer',
        'isItBeerOClock' => FALSE,
      ],
    ],
  ];
}

function theme_beer_o_clock_block($variables) {
    return "<div align='center'>" . filter_xss_admin($variables['message']) . "</div>" . "<BR/> <div align='center' id= 'boc_timer'> </div>";
}
