<?php

/**
 * Implements hook_requirements().
 */
function webform_submission_files_download_requirements($phase) {
  $requirements = [];
  if ($phase == 'install') {
    if (!class_exists('\PclZip')) {
      $requirements['pclzip_library'] = [
        'description' => t('Download requires the pclzip/pclzip library.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}

/**
 * Implements hook_entity_operation().
 */
function webform_submission_files_download_entity_operation(\Drupal\Core\Entity\EntityInterface $entity) {
  $operations = array();

  if($entity->getEntityTypeId() == 'webform_submission') {
    $operations['files_download'] = array(
      'title' => t('Files download'),
      'url' => \Drupal\Core\Url::fromRoute('entity.webform_submission.files_download', ['webform'=> $entity->webform_id->target_id, 'webform_submission'=>$entity->id()]),
      'weight' => 50,
    );
  }

  return $operations;
}
