<?php

use Drupal\cb\Entity\Breadcrumb;
use Drupal\comment\Entity\Comment;

/**
 * Implements hook_breadcrumb_token_types().
 */
function cb_breadcrumb_token_types($route) {
  $types = [];

  switch ($route->getPath()) {
    case '/private/message/{ptalk_message}/delete':
    case '/private/message/{ptalk_message}/restore':
      $types = ['ptalk_thread'];
      break;
    case '/comment/reply/{entity_type}/{entity}/{field_name}/{pid}':
      $types = ['node', 'comment'];
      break;
  }

  return $types;
}

/**
 * Implements hook_breadcrumb_token_data().
 */
function cb_breadcrumb_token_data($route_match) {
  $data = [];

  switch ($route_match->getRouteObject()->getPath()) {
    case '/private/message/{ptalk_message}/delete':
    case '/private/message/{ptalk_message}/restore':
      $data['ptalk_thread'] = $route_match->getParameter('ptalk_message')->getThread();
      break;
    case '/comment/reply/{entity_type}/{entity}/{field_name}/{pid}':
      $data['comment'] = Comment::load($route_match->getRawParameter('pid'));
      break;
  }

  return $data;
}

/**
 * Loads cb_breadcrumb entity by pattern of the property path.
 *
 * @param $pattern
 *   The pattern outline of the breadcrumb path.
 *
 * @return
 *   A cb_breadcrumb entity or NULL.
 */
function cb_breadcrumbs_load_by_path($pattern) {
  $query = db_select('cb_breadcrumb_field_data', 'cb')
    ->fields('cb', ['bid'])
    ->condition('enabled', 1)
    ->condition('paths', "%{$pattern}\r\n%", 'LIKE');

  $bids = $query
    ->execute()
    ->fetchCol();

  return Breadcrumb::loadMultiple($bids);
}
