<?php

/**
 * @file
 * Views Published or Roles module file.
 */

/**
 * Implements hook_views_data_alter().
 */
function views_published_or_roles_views_data_alter(&$data) {

  // Published status or has role.
  $data['node']['status_has_role'] = [
    'title' => t('Published or has role'),
    'help' => t('Filters out unpublished nodes if the current user cannot view them.'),
    'filter' => [
      'field' => 'status',
      'id' => 'status_has_role',
      'title' => t('Published or has role'),
      'no group by' => TRUE,
    ],
  ];

  // Current user has roles.
  $data['node']['current_user_has_roles'] = [
    'title' => t('Current user has roles'),
    'help' => t("Filters by current user's roles"),
    'filter' => [
      'field' => 'status',
      'id' => 'current_user_has_roles',
      'title' => t('Current user has roles'),
      'no group by' => TRUE,
    ],
  ];
}
