<?php

/**
 * @file
 * This module redirect user to frontpage.
 */

use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_user_login().
 */
function login_redirect_to_front_user_login($account) {

  // Get the current route name.
  $route_name = \Drupal::routeMatch()->getRouteName();
  // Get destination.
  $destination = \Drupal::request()->query->get('destination');

  // Make sure it's not the reset form and not the reset login link.
  if ($route_name != 'user.reset.form' && $route_name != 'user.reset.login' && $route_name != 'user.login.http' && !$destination) {

    // Get the url to the front page.
    $url = Url::fromRoute('<front>');

    // Create the response.
    $response = new RedirectResponse($url->toString());

    // Send the response.
    $response->send();
  }
}

/**
 * Implements hook_help().
 */
function login_redirect_to_front_help($route_name, RouteMatchInterface $route_match) {
  return '';
}
