<?php

use \Drupal\Core\Url;

/**
 * @file
 * Drupal integration with the Vegas jQuery Plugin.
 */

/**
 * Implements hook_help().
 */
function vegas_help($path, $arg) {
  switch ($path) {
    case 'admin/help#vegas':
      return '<p>'. t('Uses the <a href="@vegas">Vegas jQuery Plugin</a> to provide beautiful background images and slideshows.', array('@vegas' => 'http://github.com/jaysalvat/vegas')) .'</p>';
    case 'admin/appearance/vegas':
      return '<p>'. t('Set up beautiful background images and slideshows by uploading images, and configuring the fade and delay effects with the <a href="@vegas">Vegas jQuery Plugin</a>.', array('@vegas' => 'http://github.com/jaysalvat/vegas')) .'</p>';
  }
}


function vegas_page_attachments_alter(array &$attachments) {

  $current_url = Url::fromRoute('<current>');

  $vegas = \Drupal::service('vegas');

  if ($vegas->isVegasEnabledPath($current_url)) {

    $config = \Drupal::config('vegas.settings');

    // Load all the images to be added to Vegas.
    $backgrounds = array();

    $fade = $config->get('vegas_fade');

    for ($i = 0; $i < 10; $i++) {

      $fid = $config->get('vegas_images_' . $i);

      if (!empty($fid[0])) {
        $image = file_load($fid[0]);
        if ($image) {
          $background = array(
            'src' => file_create_url($image->getFileUri()),
          );
          if (!empty($fade)) {
            $background['fade'] = intval($fade);
          }
          $backgrounds[] = $background;
        }
      }
    }

    // If there are images to show, then load the Vegas JavaScript as well.
    if (!empty($backgrounds)) {

      // See if we are to shuffle the backgrounds.
      if ($config->get('vegas_shuffle')) {
        shuffle($backgrounds);
      }

      // Prepare the JavaScript settings.
      $settings = array(
        'slides' => $backgrounds,
      );

      // Load up the delay amount.
      $delay = $config->get('vegas_delay');
      $settings['delay'] = intval($delay);

      // Load the overlay, if possible.
      $fid = $config->get('vegas_overlay');

      if (!empty($fid[0])) {
        $image = file_load($fid[0]);

        if ($image) {
          $settings['overlay'] = file_create_url($image->getFileUri());
        }
      }

      // Unconditionally attach an asset to the page.
      $attachments['#attached']['library'][] = 'vegas/vegas';
      $attachments['#attached']['drupalSettings']['vegas']['settings'] = $settings;

    }
  }
}
