<?php

/* @file
 *Module file for miniOrange SAML Module.
 */

function miniorange_saml_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] = 'miniorange_saml/miniorange_saml.admin';
}
function miniorange_saml_form_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id) {
    global $base_url;
    $enable_saml_login = \Drupal::config('miniorange_saml.settings')->get('miniorange_saml_enable_login');
    if($enable_saml_login) {
        if ($form_id == 'user_login_block' || $form_id == 'user_login_form') {
          $saml_login_url = $base_url . '/samllogin';
          $idp_name = \Drupal::config('miniorange_saml.settings')->get('miniorange_saml_idp_name');
          $form['loginurl']= array(array(
            '#markup' => '<a href="'. $saml_login_url .'">Login using ' . $idp_name . '</a>'
          ));
        }
    }
}

