<?php

/**
 * @file
 * Contains extended_label.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Field\FieldConfigInterface;

/**
 * Implements hook_help().
 */
function extended_label_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.extended_label':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A longer extended field label to replace the short label.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_field_label_alter().
 */
function extended_label_form_field_label_alter(&$field_label, &$field_definition) {
  if (method_exists($field_definition, 'getThirdPartySetting')) {
    $extended_label = $field_definition->getThirdPartySetting('extended_label', 'extended_label', '');
    $extended_format = $field_definition->getThirdPartySetting('extended_label', 'extended_format', NULL);
    if ($extended_label !== '') {
      $extended_label = check_markup($extended_label, $extended_format);
      $field_label = $extended_label;
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function extended_label_theme_suggestions_fieldset_alter(array &$suggestions, array &$variables) {
  if (isset($variables['element']['#title_display']) && stristr($variables['element']['#title_display'], '-extended-') !== FALSE) {
    $suggestions[] = 'fieldset__extended';
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function extended_label_theme_suggestions_form_element_label_alter(array &$suggestions, array &$variables) {
  if (isset($variables['element']['#title_display']) && stristr($variables['element']['#title_display'], '-extended-') !== FALSE) {
    $suggestions[] = 'form_element_label__extended';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function extended_label_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $field_config = $form_state->getFormObject()->getEntity();
  $extended_label = $field_config->getThirdPartySetting('extended_label', 'extended_label', '');
  $extended_format = $field_config->getThirdPartySetting('extended_label', 'extended_format', NULL);

  $form['extended_label_details'] = [
    '#type' => 'details',
    '#title' => t('Extended label'),
    '#open' => ($extended_label !== ''),
    '#weight' => $form['label']['#weight'] + 1,
  ];

  $form['extended_label_details']['extended_label'] = [
    '#type' => 'text_format',
    '#description' => t('An optional bigger label that will be shown instead of the above short label. Leave blank to use the normal short label.'),
    '#default_value' => $extended_label,
    '#format' => !empty($extended_format) ? $extended_format : filter_fallback_format(),
  ];

  $form['actions']['submit']['#submit'][] = 'extended_label_form_field_config_edit_form_submit';
}

/**
 * Custom field_config_edit_form_submit.
 */
function extended_label_form_field_config_edit_form_submit(array &$form, FormStateInterface $form_state) {
  $form_state_values = $form_state->getValues();
  if (isset($form_state_values['extended_label']['value'])) {
    $field_config = $form_state->getFormObject()->getEntity();
    $field_config->setThirdPartySetting('extended_label', 'extended_label', $form_state_values['extended_label']['value'])
      ->setThirdPartySetting('extended_label', 'extended_format', $form_state_values['extended_label']['format'])
      ->save();
  }
}

/**
 * Fetch the field definitions.
 */
function extended_label_fetch_field_definitions($entity_type, $bundle, $field_definitions = NULL) {
  if ($field_definitions === NULL) {
    $entity_manager = \Drupal::entityManager();
    $field_definitions = $entity_manager->getFieldDefinitions($entity_type, $bundle);
  }

  $field_definitions = array_filter($field_definitions, function ($field_definition) {
    return $field_definition instanceof FieldConfigInterface;
  });

  uasort($field_definitions, ['\Drupal\Core\Config\Entity\ConfigEntityBase', 'sort']);

  return $field_definitions;
}

/**
 * Implements hook_form_alter().
 */
function extended_label_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['#entity_builders'])) {
    $storage = $form_state->getStorage();
    if (!isset($storage['form_display'])) {
      return;
    }

    $form_display = $storage['form_display'];
    $field_definitions = extended_label_fetch_field_definitions($form_display->getTargetEntityTypeId(), $form_display->getTargetBundle());
    $has_extended = FALSE;
    foreach ($field_definitions as $field_name => $field_definition) {
      $extended_label = $field_definition->getThirdPartySetting('extended_label', 'extended_label', '');

      $extended_format = $field_definition->getThirdPartySetting('extended_label', 'extended_format', '');
      if (empty($extended_format)) {
        $extended_format = filter_fallback_format();
      }

      if ($extended_label !== '') {
        $extended_label = check_markup($extended_label, $extended_format);

        if (isset($form[$field_name]['widget'][0]['value'])) {
          $form[$field_name]['widget'][0]['value']['#title'] = $extended_label;
          $form[$field_name]['widget'][0]['value']['#title_display'] = empty($form[$field_name]['widget'][0]['value']['#title_display']) ? '-extended-' : $form[$field_name]['widget'][0]['value']['#title_display'] . '-extended-';
        }
        elseif (isset($form[$field_name]['widget'][0]['#title'])) {
          $form[$field_name]['widget'][0]['#title'] = $extended_label;
          $form[$field_name]['widget'][0]['#title_display'] = empty($form[$field_name]['widget'][0]['#title_display']) ? '-extended-' : $form[$field_name]['widget'][0]['#title_display'] . '-extended-';
        }
        elseif (isset($form[$field_name]['widget']['value'])) {
          $form[$field_name]['widget']['value']['#title'] = $extended_label;
          $form[$field_name]['widget']['value']['#title_display'] = empty($form[$field_name]['widget']['value']['#title_display']) ? '-extended-' : $form[$field_name]['widget']['value']['#title_display'] . '-extended-';
        }
        elseif (isset($form[$field_name]['widget'])) {
          $form[$field_name]['widget']['#title'] = $extended_label;
          $form[$field_name]['widget']['#title_display'] = empty($form[$field_name]['widget']['#title_display']) ? '-extended-' : $form[$field_name]['widget']['#title_display'] . '-extended-';
        }

        $form[$field_name]['#attributes']['class'][] = 'extended-label';

        $has_extended = TRUE;
      }
    }

    if ($has_extended) {
      $form['#attached']['library'][] = 'extended_label/extended_label_form';
    }
  }
}
