<?php

/**
 * Implements hook_cron().
 */
function imageproperty_check_cron() {
  $body = "";
  $body .= t("This mail is to inform you that there are some images which exceed
  the maximum memory size specified for each image style.Large size images
  increase the loading time of the page which also hampers the performance of
  site. ");
  $body .= nl2br("\n");
  //imageproperty_check_record();
  $imagepropertyCheckController = new \Drupal\imageproperty_check\Controller\imagepropertyCheckController();
      $imagepropertyCheckController->imagepropertyCheckReports();
  $query = db_select('imageproperty_check', 'ip')
          ->fields('ip', array(
            'image_id',
            'image_name',
            'image_size',
            'image_path',
            ))
          ->execute()
          ->fetchAllAssoc('image_id');
  $header = array(
    t('Image id'),
    t('Image name'),
    t('Image size'),
    t('Image path'),
  );
  if ($query) {
    $to = "";
    $from = "neetumorwani@qed42.com";
    //$from = variable_get('site_mail');
    foreach ($query as $row) {
      $rows[] = array(
        'image_id' => $row->image_id,
        'image_name' => $row->image_name,
        'image_size' => $row->image_size,
        'image_path' => $row->image_path,
      );
    }
    if(Drupal::moduleHandler()->moduleExists('mimemail') && Drupal::moduleHandler()->moduleExists('htmlmail')) {
      $body .= theme('table', array(
        'header' => $header,
        'rows' => $rows,
        'attributes' => array('style' => 'width:600px'),
        ));
    }
    else {
      foreach ($rows as $value) {
        $body .= "Image Name : " . $value['image_name'] . nl2br("\n");
        $body .= "Image Size : " . $value['image_size'] . nl2br("\n");
        $body .= "Image Path : " . $value['image_path'] . nl2br("\n");
        $body .= nl2br("\n");
      }
    }

    $params = array(
      'body' => $body,
      'subject' => t('Warning message for large memory size images'),
    );
    // Cron functionality to be implemented.
     $key_mail = 'imageproperty_check_mail_key';
    $admins = db_select('users_roles', 'ur');
    $admins->innerJoin('users_field_data', 'u', 'u.uid=ur.uid');
    $admins->fields('u', array('mail'))
            ->condition('rid', 'administrator');
    $result = $admins->execute()->fetchAll();
    foreach ($result as $key => $value) {
      $to = $result[$key]->mail;
      $message['body'][] = "Dear !username\n\nThere is new content available on the site.";
      //Send mail only if difference between the last cron execution time and current time is greater than the time specified by the user.
      //If the value is not set to anything than the email will be set everytime we run cron manually, else mail will be sent only after the specified time limit

      \Drupal::service('plugin.manager.mail')->mail('imageproperty_check', $key, $to, 'en', $params, $from, TRUE);
    }
  }
}

function imageproperty_check_mail($key, &$message, $params) {
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['body'];
}