<?php

/**
 * @file
 * Module file for yasm_charts.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function yasm_charts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.yasm_charts':
      $text = file_get_contents(dirname(__FILE__) . "/README.txt");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        $output = '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $filter = \Drupal::service('plugin.manager.filter')->createInstance('markdown', ['settings' => $settings]);
        $output = $filter->process($text, 'en');
      }
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function yasm_charts_theme() {
  return [
    'yasm_chart' => [
      'template' => 'yasm_chart',
      'variables' => [
        'library' => '',
        'categories' => [],
        'seriesData' => [],
        'options' => [],
        'id' => '',
      ],
    ],
  ];
}

/**
 * Implements template_preprocess_yasm_chart().
 */
function template_preprocess_yasm_chart(&$variables) {
  // Charts override settings applied at this point.
  $chartOverrideOptions = [];
  try {
    $chartOverridePluginManager = \Drupal::service('plugin.manager.charts_override');
    $plugin_definition = $chartOverridePluginManager->getDefinition($variables['library'] . '_overrides');
    if (!empty($plugin_definition)) {
      $chartOverridePlugin = $chartOverridePluginManager->createInstance($variables['library'] . '_overrides');
      $chartOverrideOptions = $chartOverridePlugin->chartOverrides($variables['options']);
    }
  }
  catch (PluginNotFoundException $e) {
    \Drupal::service('messenger')->addMessage(t('Exception: @error', ['@error' => $e->getMessage()]));
  }

  $plugin = \Drupal::service('plugin.manager.charts')->createInstance($variables['library']);
  $plugin->buildVariables($variables['options'], $variables['categories'], $variables['seriesData'], [], $variables, $variables['id'], $chartOverrideOptions);
}
