<?php

/**
 * @file
 * Contains cdek_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cdek_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cdek_api':
      $output = '<p>' . t('This module provides basic integration with the CDEK Delivery Service API.') . '</p>';
      $output .= '<p>' . t('Please visit the <a href=":cdek">CDEK site</a> for more information about the service. This module won\'t do much by itself - it is intended for developers.', [':cdek' => 'https://www.cdek.ru']);
      $output .= '<br />' . t('For additional information, see the <a href=":online">online documentation for CDEK API</a>.', [':online' => 'https://www.drupal.org/docs/8/modules/cdek-api']) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function cdek_api_preprocess_container__cdek_select(&$variables) {
  $element = $variables['element'];
  $variables['attributes'] = [];

  // Set the correct html ID.
  if (isset($element['#id'])) {
    $variables['attributes']['id'] = $element['#id'];
  }
  $variables['attributes']['class'][] = 'form-cdek-select';
}
