<?php

/**
 * @file
 * Contains altering_entity_routes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_help().
 */
function altering_entity_routes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the altering_entity_routes module.
    case 'help.page.altering_entity_routes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Altering eck entity existing defaults routes！This is a custom module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function altering_entity_routes_theme() {
  return [
    'altering_entity_routes' => [
      'render element' => 'children',
    ],
  ];
}


