<?php

/**
 * @file
 * File Chooser Field module - Drupal 8 version.
 * Author: Minnur Yunusov
 * mmyunusov@gmail.com
 */

/**
 * Implements hook_file_chooser_field_plugins().
 */
function file_chooser_field_file_chooser_field_plugins() {
  return [
    'dropbox' => [
      'name'         => t('Dropbox JavaScript Chooser API'),
      'phpClassName' => 'DropboxChooserAPI',
    ],
    'google_drive' => [
      'name'         => t('Google Picker API'),
      'phpClassName' => 'GooglePickerAPI',
    ],
    'box' => [
      'name'         => t('Box File Picker'),
      'phpClassName' => 'BoxPickerAPI',
    ],
    'one_drive' => [
      'name'         => t('OneDrive'),
      'phpClassName' => 'OneDriveAPI',
    ],
    'example' => [
      'name'         => t('Example'),
      'phpClassName' => 'Example',
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function file_chooser_field_theme() {
  return [
    'file_chooser_field' => [
      'variables' => [
        'label'      => NULL,
        'class'      => NULL,
        'attributes' => [],
      ],
      'template'  => 'file-chooser-field',
    ]
  ];
}
