<?php

/**
 * @file
 * Contains ckeditor_abbreviation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ckeditor_abbreviation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ckeditor_abbreviation':
      $output = '';
      $output .= '<h3>' . t('CKEditor Abbreviation') . '</h3>';
      $output .= '<p>' . t('The module adds a CKEditor abbreviation button to the editor toolbar and a link to its context menu (only available if you select an existing abbr tag in the editor content).') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Settings') . '</dt>';
      $output .= '<dd>' . t('In the <a href=":text-formats">text formats</a> that use ckeditor, move the icon into the active toolbar.', [':text-formats' => \Drupal::url('filter.admin_overview')]) . '</dd>';
      $output .= '</dl>';
      return $output;

    default:
  }
}
