<?php

/**
 * @file
 * Contains post_append.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param $route_match
 * @return mixed
 */
function post_append_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the emergency_alert module.
    case 'help.page.post_append':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Used to append text to a node using REST state POST.') . '</p>';
      return $output;
    default:
      return null;
  }
}

/**
 * Implements hook_theme().
 */
function post_append_theme() {
  return [
    'post_append' => [
      'render element' => 'children',
    ],
  ];
}
