<?php

/**
 * @file
 * Contains teachest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function teachest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the teachest module.
    case 'help.page.teachest':
      $output = '';
      $output .= '<h3>' . t('About TeaChest') . '</h3>';
      $output .= '<p>' . t('TeaChest is a Drupal 8 module for content as a service.') . '</p>';
      return $output;

    default:
  }
}
