<?php

/**
 * @file
 * Contains entity_tools.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_tools_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_tools module.
    case 'help.page.entity_tools':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Facade for entities and fields.') . '</p>';
      return $output;

    default:
  }
}
