<?php

/**
 * @file
 * Module file for Stock Photo Pixabay Provider.
 *
 * Pixabay stock photos Media source provider.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for stock_photo_search_settings.
 */
function pixabay_form_stock_photo_search_settings_alter(&$form, FormStateInterface $form_state, $form_id) {

  $config = \Drupal::configFactory()->getEditable('stock_photo_search.settings');

  $form['pixabay'] = [
    '#type' => 'details',
    '#title' => t('Pixabay'),
    '#description' => '',
    '#open' => TRUE,
    '#group' => 'settings',
  ];

  $form['pixabay']['pixabay_api_key'] = [
    '#type' => 'textfield',
    '#title' => t('Pixabay Api Key'),
    '#required' => TRUE,
    '#default_value' => $config->get('pixabay_api_key'),
    '#size' => 40,
  ];

  $form['pixabay']['pixabay_num_results'] = [
    '#type' => 'number',
    '#title' => t('Number of results'),
    '#required' => TRUE,
    '#default_value' => $config->get('pixabay_num_results'),
  ];

  $form['pixabay']['pixabay_lang'] = [
    '#title' => t('Select language for querys'),
    '#type' => 'select',
    '#options' => [
      'en' => t('English'),
      'es' => t('Spanish'),
      'bg' => t('Bulgarian'),
      'zh' => t('Chinese'),
      'cs' => t('Czech'),
      'da' => t('Danish'),
      'nl' => t('Dutch'),
      'fi' => t('Finnish'),
      'fr' => t('French'),
      'de' => t('German'),
      'el' => t('Greek'),
      'hu' => t('Hungarian'),
      'id' => t('Indonesian'),
      'it' => t('Italian'),
      'ja' => t('Japanese'),
      'ko' => t('Korean'),
      'no' => t('Norwegian'),
      'pl' => t('Polish'),
      'pt' => t('Portuguese'),
      'ro' => t('Romanian'),
      'ru' => t('Russian'),
      'sk' => t('Slovak'),
      'sv' => t('Swedish'),
      'th' => t('Thai'),
      'tr' => t('Turkish'),
      'vi' => t('Vietnamese'),
    ],
    '#default_value' => $config->get('pixabay_lang'),
  ];

  $form['pixabay']['info'] = [
    '#type' => 'item',
    '#markup' => t('You can get this data from <a href="https://pixabay.com/api/docs/" target="_blank">https://pixabay.com/api/docs/</a>.'),
  ];

  $form['#submit'][] = 'pixabay_form_submit';
}

/**
 * Submit form.
 */
function pixabay_form_submit(array &$form, FormStateInterface $form_state) {

  $config = \Drupal::configFactory()->getEditable('stock_photo_search.settings');

  $config
    ->set('pixabay_api_key', $form_state->getValue('pixabay_api_key'))
    ->set('pixabay_num_results', $form_state->getValue('pixabay_num_results'))
    ->set('pixabay_lang', $form_state->getValue('pixabay_lang'))
    ->save();

  $form_state->setRebuild();
}
