<?php

/**
 * @file
 * Contains underscore_handle.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function underscore_handle_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the underscore_handle module.
    case 'help.page.underscore_handle':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This Module prevents field machine name from ending (_) underscore. For example, 
when you have brackets at the end of a label, e.g., "Address (2)", 
you end up with a trailing "_" character — field_address_2_.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function underscore_handle_form_field_ui_field_storage_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#validate'][] = 'underscore_handle_form_validate';
}

/**
 * Form validation handler for field_ui_field_storage_add_form().
 */
function underscore_handle_form_validate(&$form, FormStateInterface $form_state) {
  $end_underscore_config    = \Drupal::config('underscore_handle.underscoresetting')->get('end_underscore');
  $double_underscore_config = \Drupal::config('underscore_handle.underscoresetting')->get('double_underscore');

  $field_machine_name                 = $form_state->getValue('field_name');
  $rtrim_field_machine_name           = rtrim($form_state->getValue('field_name'), "_");
  $explode_field_machine_name         = explode("__", $field_machine_name);
  $double_underscore_array_frist_item = array_pop($explode_field_machine_name);

  if (!empty($end_underscore_config) && $field_machine_name !== $rtrim_field_machine_name) {
    $form_state->setErrorByName('field_name', t('Field machine name should not end with hyphen'));
  }
  // Validation for double underscore in field name.
  if (!empty($double_underscore_config) && $double_underscore_array_frist_item !== $field_machine_name) {
    $form_state->setErrorByName('field_name', t('Field machine name should not contain two or more underscore'));
  }
}
