<?php

/**
 * @file
 * Contains scrollup.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function scrollup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.scrollup':
      $output = '';
      $output .= '<h3>' . t('Scrollup') . '</h3>';
      $output .= '<p>' . t('Scroll Up to the page. Provide advanced configuration for administrator to manage behaviour of scrolling.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_install().
 */
function scrollup_install() {
  $defaultThemeName = \Drupal::config('system.theme')->get('default');
  \Drupal::configFactory()->getEditable('scrollup.settings')
    ->set('scrollup_position', 1)
    ->set('scrollup_button_bg_color', '#CCCCCC')
    ->set('scrollup_button_hover_bg_color', '#000000')
    ->set('scrollup_title', 'Scroll up')
    ->set('scrollup_window_position', '600')
    ->set('scrollup_speed', '0')
    ->set('scrollup_themename', [$defaultThemeName])
    ->save();
}

/**
 * Implements hook_preprocess_page().
 */
function scrollup_preprocess_page(&$variables) {

  $config = \Drupal::config('scrollup.settings');
  $theme_selected = $config->get('scrollup_themename');
  $active_theme = \Drupal::service('theme.manager')->getActiveTheme()->getName();
  if (array_keys($theme_selected, $active_theme)) {
    $variables['#attached']['library'][] = 'scrollup/scrollup';
    $variables['#attached']['drupalSettings']['scrollup_position'] = $config->get('scrollup_position');
    $variables['#attached']['drupalSettings']['scrollup_button_bg_color'] = $config->get('scrollup_button_bg_color');
    $variables['#attached']['drupalSettings']['scrollup_button_hover_bg_color'] = $config->get('scrollup_button_hover_bg_color');
    $variables['#attached']['drupalSettings']['scrollup_title'] = $config->get('scrollup_title');
    $variables['#attached']['drupalSettings']['scrollup_window_position'] = $config->get('scrollup_window_position');
    $variables['#attached']['drupalSettings']['scrollup_speed'] = $config->get('scrollup_speed');
    $variables['#attached']['drupalSettings']['scrollup_themename'] = $config->get('scrollup_themename');
  }

}
