<?php

/**
 * @file
 * Contains upgrade_tool.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function upgrade_tool_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the upgrade_tool module.
    case 'help.page.upgrade_tool':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide Upgrade path tool.') . '</p>';
      return $output;

    default:
  }
}
