<?php

/**
 * Implements hook_gutenberg_blocks_alter().
 */
function gutenberg_cloud_gutenberg_blocks_alter(array &$js_files_edit, array &$css_files_edit, array &$css_files_view) {
  $config_cloud = \Drupal::service('config.factory')
    ->getEditable('gutenberg_cloud.blocks')->get();

  foreach ($config_cloud as $block) {
    if ($block['edit_css']) {
      $css_files_edit[] = 'https://cdn.jsdelivr.net/npm/' . $block['name'] . '@' . $block['version'] . '/' . $block['edit_css'];
    }
    if ($block['js']) {
      $js_files_edit[] = 'https://cdn.jsdelivr.net/npm/' . $block['name'] . '@' . $block['version'] . '/' . $block['js'];
    }
    if ($block['view_css']) {
      $css_files_view[] =  'https://cdn.jsdelivr.net/npm/' . $block['name'] . '@' . $block['version'] . '/' . $block['view_css'];
    }
  }
}
