<?php

/**
 * @file
 * Shows QR code for individual Hawk Credentials.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hawk_auth_qr_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'hawk_auth.user_credential':
      $output = '<p>' . t('You can use the "View QR" link besides every every credential in order to
                           display the QR code which can be scanned in a compatible application and easily
                           add the credential to the application') . '</p>';
      return $output;
  }
}
