<?php

/**
 * @file
 * Contains media_entity_kaltura.module.
 */

/**
 * Implements hook_theme().
 */
function media_entity_kaltura_theme($existing, $type, $theme, $path) {
  return [
    'media_kaltura_embed' => [
      'variables' => [
        'playerId' => NULL,
        'partnerId' => NULL,
        'entryId' => NULL,
        'uiConfId' => NULL,
        'flashVars' => NULL,
        'width' => NULL,
        'height' => NULL,
      ],
      'file' => 'media_entity_kaltura.theme.inc',
    ],
  ];
}
