<?php

/**
 * @file
 * Contains senhaunicausp.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function senhaunicausp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the senhaunicausp module.
    case 'help.page.senhaunicausp':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Senha Única USP') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function senhaunicausp_theme() {
  return [
    'senhaunicausp' => [
      'render element' => 'children',
    ],
  ];
}
