<?php

/**
 * @file
 * Contains pagedesigner_image.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pagedesigner_image_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the pagedesigner_image module.
        case 'help.page.pagedesigner_image':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Pagedesigner image extension') . '</p>';
            return $output;

        default:
    }
}