<?php

/**
 * @file
 * Contains api_ai_webhook.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function api_ai_webhook_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the api_ai_webhook module.
    case 'help.page.api_ai_webhook':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('API.AI Webhook implementation') . '</p>';
      return $output;

    default:
  }
}
