<?php

/**
 * @file
 * Hook implementation file for Hierarchical Term Formatter.
 */

/**
 * Implements hook_theme().
 */
function hierarchical_term_formatter_theme($existing, $type, $theme, $path) {
  return [
    'hierarchical_term_formatter' => [
      'variables' => [
        'terms' => [],
        'wrapper' => '',
        'separator' => ' » ',
        'link' => FALSE,
      ],
      'file' => 'hierarchical_term_formatter.theme.inc',
    ],
  ];
}
