<?php

/**
 * @file
 * Contains simple_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simple_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simple_content module.
    case 'help.page.simple_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function simple_content_theme() {
  $theme = [];
  $theme['simple_content'] = [
    'render element' => 'elements',
    'file' => 'simple_content.page.inc',
    'template' => 'simple_content',
  ];
  $theme['simple_content_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'simple_content.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function simple_content_theme_suggestions_simple_content(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#simple_content'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'simple_content__' . $sanitized_view_mode;
  $suggestions[] = 'simple_content__' . $entity->bundle();
  $suggestions[] = 'simple_content__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'simple_content__' . $entity->id();
  $suggestions[] = 'simple_content__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
