<?php

/**
 * @file
 * Contains field_group_access.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function field_group_access_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.field_group_access':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add permissions for editing and viewing field groups.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_field_group_pre_render_alter().
 */
function field_group_access_field_group_pre_render_alter(&$element, &$group, &$rendering_object) {
  $user = \Drupal::currentUser();

  $view_all_permission = 'view all field group fields';
  $view_permission = 'view ' . $group->entity_type . '.' . $group->bundle . '.' . $group->mode . '.' . $group->group_name;

  if (!$user->hasPermission($view_all_permission)
    && !$user->hasPermission($view_permission)) {
    $element['#access'] = FALSE;
    return;
  }

  $edit_all_permission = 'edit all field group fields';
  $edit_permission = 'edit ' . $group->entity_type . '.' . $group->bundle . '.' . $group->mode . '.' . $group->group_name;

  if (!$user->hasPermission($edit_all_permission)
    && !$user->hasPermission($edit_permission)) {
    $element['#attributes']['class'][] = 'field-group-disabled';
    if (!in_array('field_group_access/field_group_access', $rendering_object['#attached']['library'])) {
      $rendering_object['#attached']['library'][] = 'field_group_access/field_group_access';
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function field_group_access_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['#entity_builders'])) {
    $form['#attached']['library'][] = 'field_group_access/field_group_access';
  }
}
