<?php

/**
 * @file
 * This module holds functions for puppeteer screenshots.
 */

 use Drupal\views\ViewExecutable;
 use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function web_page_archive_puppeteer_render_theme() {
  return [
    'web_page_archive_puppeteer_render_template' => [
      'variables' => ['left' => NULL, 'right' => NULL],
    ],
  ];
}

/**
 * Implements hook_views_pre_render().
 */
function web_page_archive_puppeteer_render_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'web_page_archive_run_comparison_summary')) {
    $view->element['#attached']['library'][] = 'web_page_archive_puppeteer_render/wpa-slider';
  }
}
