<?php

/**
 * @file
 * Simple Tweets module main file.
 */

use \Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simple_tweets_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.simple_tweets':
        $file_path = dirname(__FILE__) . '/README.txt';
      if (file_exists($file_path)) {
        $readme = file_get_contents($file_path);
      }
      if (!isset($readme)) {
        return NULL;
      }
      if (Drupal::moduleHandler()->moduleExists('markdown')) {
        $filters = \Drupal::moduleHandler()->invoke('markdown', 'filter_info');
        $info = $filters['filter_markdown'];

        if (function_exists($info['process callback'])) {
          $output = $info['process callback']($readme, NULL);
        }
        else {
          $output = '<pre>' . $readme . '</pre>';
        }
      }
      else {
        $output = '<pre>' . $readme . '</pre>';
      }
      return $output;
  }
}
