<?php

use Drupal\file\Entity\File;

/**
 * Implements template_preprocess_image_formatter().
 */
function animated_gif_preprocess_image_formatter(&$variables) {
  $image = $variables['item'];
  $imageValues = $image->getValue();
  $file = File::load($imageValues['target_id']);

  if ($file && $file->getMimeType() == 'image/gif') {
    $variables['image']['#theme'] = 'image';
    unset($variables['image']['#style_name']);
    unset($variables['image_style']);
  }

}