<?php

/**
 * @file
 * Contains visualn_subdrawers.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function visualn_subdrawers_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the visualn_subdrawers module.
    case 'help.page.visualn_subdrawers':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows to create user-defined drawers (subdrawers) via UI') . '</p>';
      return $output;

    default:
  }
}
