<?php

use Drupal\group\Entity\GroupContent;
use Drupal\smallads\Entity\SmalladType;

/**
 * Implements hook_smallad_create().
 *
 * @todo this isn't good enough because it assumes the form is on a group route.
 */
function smallads_group_smallad_create($entity) {
//  $params = \Drupal::routeMatch()->getParameters();
//  if ($params->has('group')) {
//    $entity->group = $params->get('group');
//  }
}

/**
 * Implements hook_smallad_insert().
 */
function smallads_group_smallad_insert($entity) {
  if (isset($entity->group)) {
    $props = [
      'type' => $entity->group->getGroupType()->id().'-smallad-'.$entity->bundle(),
      'gid' => $entity->group->id(),
      'entity_id' => $entity->id(),
    ];
    GroupContent::create($props)->save();
  }
}
/**
 * Implements hook_entity_type_alter().
 */
function smallads_group_entity_type_alter(&$entity_types) {
  $entity_types['smallad']->setLinkTemplate('add-form', '/group/{group}/ad/add/{smallad_type}');
  $entity_types['smallad']->setAccessClass('\Drupal\smallads_group\SmalladGroupAccessControlHandler');
}

/**
 * Implmements hook_menu_links_discovered_alter().
 * Remove the links from the account menu.
 */
function smallads_group_menu_links_discovered_alter(&$links) {
  foreach (SmalladType::loadMultiple() as $type) {
    unset($links['smallads.autolinks:'.$type->id().'.add_form.link']);
  }
}

/**
 * Implmements hook_menu_local_actions_alter().
 *
 * Remove the local actions from the smallads module, coz they are replaced herein.
 */
function smallads_group_menu_local_actions_alter(&$definitions) {
  unset($definitions['smallads.autolinks:offer.add_form.action']);
  unset($definitions['smallads.autolinks:want.add_form.action']);
}