<?php

/**
 * @file
 * Contains rest_menu_detail.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rest_menu_detail_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rest_menu_detail module.
    case 'help.page.rest_menu_detail':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Menu information as REST response.') . '</p>';
      return $output;

    default:
  }
}
