<?php

/**
 * @file
 * Contains description_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function description_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.description_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a description only (no input) field on forms.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function description_field_form_field_storage_config_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('description_field.default')->alterFieldStorageConfigEditForm($form, $form_state, $form_id);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function description_field_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('description_field.default')->alterFieldConfigEditForm($form, $form_state, $form_id);
}
