<?php

/**
 * @file
 * Module file for the one time password module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\one_time_password\UserFieldAttach;
use Drupal\one_time_password\UserLoginEnforce;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function one_time_password_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(UserFieldAttach::class)
    ->entityBaseFieldInfoAlter($fields, $entity_type);
}

/**
 * Implements hook_entity_field_access().
 */
function one_time_password_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  return \Drupal::classResolver()
    ->getInstanceFromDefinition(UserFieldAttach::class)
    ->entityFieldAccess($operation, $field_definition, $account, $items);
}

/**
 * Implements hook_form_user_login_form_alter().
 */
function one_time_password_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(UserLoginEnforce::class)
    ->formUserLoginFormAlter($form, $form_state);
}

/**
 * Implements hook_theme().
 */
function one_time_password_theme() {
  return [
    'one_time_password_setup_instructions' => [
      'variables' => [],
    ],
    'one_time_password_enable_instructions' => [
      'variables' => [],
    ],
  ];
}
