<?php

/**
 * @file
 * Contains tint.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tint_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tint module.
    case 'help.page.tint':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integration with the TINT social feed platform.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tint_theme() {
  return [
    'tint' => [
      'template' => 'tint',
      'variables' => [
        'strip_tint_html' => NULL,
      ],
    ],
  ];
}
