<?php

/**
 * @file
 * Contains taxonomy_moderator.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function taxonomy_moderator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the taxonomy_moderator module.
    case 'help.page.taxonomy_moderator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create a approval process to publish taxonomy terms') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function taxonomy_moderator_theme() {
  return [
    'taxonomy_moderator' => [
      'render element' => 'children',
    ],
  ];
}
