<?php

/**
 * @file
 * Hook to define custom view field.
 */

/**
 * Implements hook_views_data_alter().
 */
function commerce_approve_views_data_alter(array &$data) {
  $data['commerce_order_item']['commerce_approve']['field'] = [
    'title' => t('Order Item Approval'),
    'help'  => t('Displays required checkbox if order item requires manual approval.'),
    'id'    => 'commerce_approve',
  ];
}
