<?php

/**
 * @file
 * Development Roles Users module.
 */

use Drupal\dev_roles_users\Controller\DevRolesUsersController;

/**
 * Implements hook_user_role_insert().
 */
function dev_roles_users_user_role_insert($role) {

  $rid = $role->id();

  $role_data = user_role_load($rid);
  // Include a new user if a role was created.
  $user_from_role = DevRolesUsersController::getUserFromRole($role_data);

  // Make sure to create only if user does not exist.
  if (!user_load_by_name($user_from_role['name'])) {
    DevRolesUsersController::insertUserByInfo($user_from_role);
  }
}
