<?php

/**
 * @file
 * Contains real_estate_kickstart.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function real_estate_kickstart_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the real_estate_kickstart module.
    case 'help.page.real_estate_kickstart':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demo.') . '</p>';
      return $output;

    default:
  }
}
