<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function chessboard_filter_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    case 'help.page.chessboard_filter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Chessboard Filter module adds a chessboard diagram filter to your site, for use with <a href="@filter">text formats</a> This filter adds the ability to use chessboard diagrams in any text field that uses a text format (such as the body of a content item or the text of a comment).', array('@filter' => \Drupal::url('help.page', array('name' => 'chessboard_filter')))) . '</p>';
      $output .= '<p>' . \Drupal::l(t('About text formats'), Url::fromRoute('filter.tips_all')) . '</p>';
      break;

    default:
      $output = '';
      break;
  }

  return $output;
}
