<?php

/**
 * @file
 * Contains install and update functions for Drutopia Core.
 */

/**
 * Enable dependent module Video Embed Field.
 */
function drutopia_core_update_8101() {
  \Drupal::service('module_installer')->install(['video_embed_field']);
}

/**
 * Enable dependent module FAQ Field.
 */
function drutopia_core_update_8102() {
  \Drupal::service('module_installer')->install(['faqfield']);
}
