<?php

/**
 * @file
 * Primarily Drupal hooks.
 */

/**
 *  Implements hook_theme().
 */
function bootstrap_colors_theme() {
  return array(
    'bootstrap_colors' => array(
      'variables' => array('form' => NULL),
    ),
  );
}

/**
 * hook_page_attachments_alter()
 */
function bootstrap_colors_page_attachments_alter(array &$page) {
  $config = \Drupal::config('bootstrap_colors.settings');
  $page['#attached']['drupalSettings']['bootstrap_colors'] = array(
    "primary_shade" => $config->get('primary_shade'),
    "accent_shade" => $config->get('accent_shade')
  );
}
