<?php

/**
 * @file
 * Add hooks into entity embed.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_form_alter().
 */
function accessible_media_embed_form_alter(&$form, $form_state, $form_id) {
  if ($form_id === "entity_embed_dialog") {
    if ($form_state->get('step') == 'embed') {
      // Entity element is calculated on every AJAX request/submit.
      // See ::buildForm().
      $entity_element = $form_state->get('entity_element');
      $form['attributes']['data-media-alt'] = array(
        '#title' => t('Descriptive text (alt) for media'),
        '#description' => "This will override the default set on the media.<br>For more information on useful descriptive text see <a href='https://www.w3.org/WAI/tutorials/images/' target='_blank'>https://www.w3.org/WAI/tutorials/images/</a>",
        '#type' => 'textfield',
        '#default_value' => isset($entity_element['data-media-alt']) ? Html::decodeEntities($entity_element['data-media-alt']) : '',
        '#element_validate' => array('::escapeValue'),
      );
      $form['attributes']['data-media-alt-decorative'] = array(
        '#title' => t('In this context the media is decorative so use an empty alt tag, even if alt text exists on the source entity'),
        '#description' => "For more information on what makes an image decorative see <a href='https://www.w3.org/WAI/tutorials/images/' target='_blank'>https://www.w3.org/WAI/tutorials/images/</a>",
        '#type' => 'checkbox',
        '#default_value' => empty($entity_element['data-media-alt-decorative']) ? FALSE : TRUE,
      );
    }
  }
}

/**
 * Implements hook_media_embed_alter().
 */
function accessible_media_embed_media_embed_alter(&$build, $entity, $context) {
  // The media alt text is double-encoded, so decode it here.
  if (isset($context['data-media-alt'])) {
    $context['data-media-alt'] = Html::decodeEntities($context['data-media-alt']);
  }
  // Maintain data-media-alt if it is there.
  if (isset($context['data-media-alt'])) {
    $build['#attributes']['data-media-alt'] = $context['data-media-alt'];
  }
  if (!empty($context['data-media-alt-decorative'])) {
    $build['#attributes']['data-media-alt-decorative'] = $context['data-media-alt-decorative'];
  }
}
