<?php

/**
 * @file
 * Contains teaserver.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function teaserver_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the teaserver module.
    case 'help.page.teaserver':
      $output = '';
      $output .= '<h3>' . t('About TeaServer') . '</h3>';
      $output .= '<p>' . t('TeaServer is a versatile Drupal 8 module for content as a service.') . '</p>';
      return $output;

    default:
  }
}
