<?php

/**
 * @file
 * Contains views_dynamic_title.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_help().
 */
function views_dynamic_title_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the views_dynamic_title module.
    case 'help.page.views_dynamic_title':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dynamic title for Views pages, based on filters and pagination') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_post_render().
 */
function views_dynamic_title_views_post_render(ViewExecutable $view) {
  if (is_a($view->display_handler, '\Drupal\views\Plugin\views\display\Page')) {

    $title = $view->getTitle();
    $suffix = '';

    // get a list of exposed filters
    $exposed = [];
    $filters = [];
    $default_values = [];

    foreach ($view->filter as $k => $f) {
      if ($f->isExposed()) {
        $info = $f->exposedInfo();
        $exposed[$info['value']] = $info['label'];
        $filters[$info['value']] = $f;
        if ($f->value) {
          $default_values[$info['value']] = $f->value;
        }
      }
    }

    // get the current inputs
    $inputs = $view->getExposedInput();
    $common_keys = array_intersect(array_keys($exposed), array_keys($inputs));
    
    // add in the default values if they're not passed
    foreach ($default_values as $k => $v) {
      if (!in_array($k, $common_keys)) {
        $common_keys[] = $k;
        $inputs[$k] = $v;
      }
    }
    

    $filter_title = [];
    $val_lookup = [];
    foreach ($common_keys as $k) {
      // arrayify
      $inputs[$k] = is_array($inputs[$k])? $inputs[$k] : [$inputs[$k]];

      $val_str = [];
      $val_links = [];
      foreach ($inputs[$k] as $v) {
        $tmp = _views_dynamic_title_prettify_val($v, $filters[$k]);
        if ($tmp) {
          if (isset($tmp['name']) && !empty(trim($tmp['name']))) {
            $val_str[$v] = $tmp['name'];
            $val_links[$v] = $tmp['link'];
          }
        }
      }
      if ($val_str) {
        $val_lookup[$k]['name'] = $val_str; 
        $val_lookup[$k]['link'] = $val_links;
        $filter_title[] = sprintf('%s: %s', rtrim($exposed[$k], ':'), implode(', ', $val_str));
      }
    }

    if (count($filter_title)) {
      $suffix .= ' ' . implode(' | ', $filter_title);
    }

    // add page
    $page = $view->getCurrentPage();
    if ($page > 0) {
      // page index is 0-based
      $suffix .= sprintf(" (page %d)", $page + 1);
    }

    if (!empty($suffix)) {
      $title .= ' - ' . $suffix;
    }

    // Set the view title.
    $view->setTitle($title);

    // store info
    $view->dynamic_applied_filters = [
      'inputs' => $inputs,
      'values' => $val_lookup,
      'keys' => $exposed,
    ];

    // Set the route title.
    $route = \Drupal::routeMatch()->getCurrentRouteMatch()->getRouteObject();
    $route->setDefault('_title', $title);
  }
}

/**
 * Clean up the exposed filter value for some cases
 *
 * @param [type] $val
 * @param [type] $filter
 * @return string
 */
function _views_dynamic_title_prettify_val($val, $filter) {
  $name = '';
  $link = FALSE;

  // strip out 'All' filter value
  if ($val == 'All') {
    return [];
  }

  // taxonomy term
  if (is_a($filter, '\Drupal\taxonomy\Plugin\views\filter\TaxonomyIndexTid')
    || $filter->table == 'taxonomy_term_hierarchy') {
    $term = Term::load($val);
    if ($term) {
      $name = $term->getName();
      $link = $term->toUrl();
    }
  }

  return [
    'name' => $name,
    'link' => $link,
  ];
}