<?php

/**
 * @file
 * Module file for weather_city.
 *
 * Module for add node and his display in a block.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function weather_city_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the Weather City module.
    case 'help.page.weather_city':
      $output = '';
      $output .= '<h3>' . t('About Weather City') . '</h3>';
      $output .= '<p>' . t('Add a block with a weather forecasts.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function weather_city_theme($existing, $type, $theme, $path) {
  return [
    'block__weather' => [
      'variables' => [
        'id' => NULL,
        'link' => NULL,
      ],
    ],
  ];
}
