/**
* DO NOT EDIT THIS FILE.
* THIS FILE IS COMPILED AUTOMATICALLY FROM ITS ES6 SOURCE.
* @preserve
**/'use strict';

(function ($, Drupal) {
  'use strict';

  if (!Drupal.settings.plusDrupalLoader || !Drupal.settings.plusDrupalLoader.length) {
    Drupal.warning(Drupal.t('There were no files to load. This is usually an indication that the Drupal rendering process has been corrupted.'));
    return;
  }

  Promise.all(Drupal.settings.plusDrupalLoader.map(function (file) {
    return Drupal.addToDom(file, { async: false });
  })).catch(function (error) {
    return error instanceof Error && Drupal.fatal(error);
  }).done(function () {
    Drupal.behaviorsQueue = Drupal.AsyncQueue.create(Drupal.behaviors, function behaviorsQueueCallback(success) {
      if (success === false) {
        return new Error(Drupal.t('Drupal behavior "@id" failed to @type @context.', {
          '@id': this.__asyncQueueId__,
          '@type': this.__asyncQueueMethod__ === 'detach' ? Drupal.t('detach from') : Drupal.t('attach onto'),
          '@context': Drupal.sanitizeObject(this.__asyncQueueArguments__[0])
        }));
      }
      return success;
    });

    Drupal.holdBehaviors(false);

    if ($ && typeof $.holdReady === 'function') {
      $.holdReady(false);
    }
  });
})(window.jQuery, window.Drupal);