<?php

/**
 * Implements hook_theme().
 */
function pcr_theme($existing, $type, $theme, $path) {
  return [
    'elements__pretty_options' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_element_info_alter().
 */
function pcr_element_info_alter(array &$type) {
  $class = 'Drupal\pcr\Plugin\Field\FieldWidget\PrettyOptionsWidget';
  if ($type['checkboxes']) {
    $type['checkboxes']['#process'][] = [$class, 'processPrettyElements'];
  }
  if ($type['radios']) {
    $type['radios']['#process'][] = [$class, 'processPrettyElements'];
  }
}

/**
 * Prepares variables for elements__pretty_options templates.
 *
 * Default template: elements--pretty-options.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_elements__pretty_options(&$variables) {
  $variables['element_title'] = $variables['element']['#title']->__toString();
}
