<?php

/**
 * @file
 * Contains paragraphs_access.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\paragraphs\ParagraphInterface;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_field_widget_info_alter().
 */
function paragraphs_access_field_widget_info_alter(array &$info) {
  // Override Widget class to allow for content replacement.
  $info["paragraphs"]["class"] = '\Drupal\paragraphs_access\ParagraphsWidget';
  $info["entity_reference_paragraphs"]["class"] = '\Drupal\paragraphs_access\InlineParagraphsWidget';
}
