<?php

/**
 * @file
 * A plugin that flushes facebook's cache.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function facebook_flush_cache_help($route_name, RouteMatchInterface $route_match) {

  if ($route_name === 'help.page.facebook_flush_cache') {

    $output = '<h3>' . t('Use case') . '</h3>';

    $output .= '<p>' . t('Have you ever tried to share content from your site and realised there is no image being pulled through as one has been added after publication? Or perhaps the headline has changed and the Facebook preview shows an earlier version.') . '</p>';

    $output .= '<h3>' . t('This module') . '</h3>';

    $output .= '<p>' . t('Instructs Facebook to scrape a new copy of the node.<br>You can simply click on the "Clear facebook cache" in the local menu tasks or use views bulk operations of mass executions.') . '</p>';

    $output .= '<h3>' . t('Rules integration') . '</h3>';

    $output .= '<p>' . t("Includes a sub module that allows for rules integration so we a node is updated it will automatically flush Facebook's cache") . '</p>';

    return $output;

  }

}
