<?php

/**
 * @file
 * Overlay panel module file.
 */

define('OVERLAY_PANEL_MODULE_PATH', drupal_get_path('module', 'overlay_panel'));

/**
 * Implements hook_page_bottom().
 */
function overlay_panel_page_bottom(&$page_bottom) {
  $page_bottom['#attached']['library'][] = 'overlay_panel/common';
  $page_bottom['overlay_panel']['#markup'] = '<div class="overlay-panel-call-wrap login-head"><a href="#" class="overlay-panel-call login-head__btn"></a></div><div class="login-panel">
    <div class="login-panel__blackout"></div>
    <div class="login-panel__container">

        <div class="login-panel__wrap">
          <a href="#" class="login-panel__close"><img src="/modules/custom/overlay_panel/images/close.png"/></a>
          <div class="login-panel__info"></div>
        </div>
    </div>
</div>
';
}
