<?php

/**
 * @file
 * Allows users to drag and place blocks from a dialog into the page.
 */

/**
 * Implements hook_page_attachments().
 */
function block_sidekick_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'block_sidekick/block_sidekick.default';
  $sidekickService = \Drupal::service('block_sidekick.service');
  $theme = $sidekickService->getTheme();
  $attachments['#attached']['drupalSettings']['block_sidekick']['theme_info'] = $theme;
  $attachments['#attached']['drupalSettings']['block_sidekick']['blocks'] = $sidekickService->getBlocks();
  $attachments['#attached']['drupalSettings']['block_sidekick']['regionIds'] = $sidekickService->getRegionElementIds($theme['name']);
}
