<?php

use Drupal\Component\Serialization\Json;
/**
 * @file
 * The magic of finding the users' location happens here :).
 */

/**
 * Implements hook_boot().
 */
function freegeoip_boot() {
  // Only do a check when the session variable is not set.
  if (!isset($_SESSION['freegeoip'])) {
    $user_ip = freegeoip_get_user_ip();

    if (variable_get('geoip_url')) {
      $url = variable_get('geoip_url') . '/json/' . $user_ip;
    }
    else {
      $url = 'http://freegeoip.net/json/' . $user_ip;
      variable_set('geoip_url', 'http://freegeoip.net');
    }

    $geoip_data = freegeoip_get_geoip_data($url);
    if ($geoip_data) {
      $_SESSION['freegeoip'] = $geoip_data;
    }
    else {
      $country_name = variable_get('freegeoip_default_country', 'india');
      $_SESSION['freegeoip'] = array('country_name' => $country_name);
    }
  }
}

/**
 * Get the country name of the user.
 */
function freegeoip_get_geoip_data($url) {

  $request = Drupal::httpClient()->get($url);
  $response = $request->getBody();
  $response_content = $response->getContents();

  $data = Json::decode($response_content);
  // If cannot determine the country code.
  if ($data['type'] == 'error') {
    return FALSE;
  }
  return $data;
}

/**
 * Get user IP.
 */
function freegeoip_get_user_ip() {
  return Drupal::request()->getClientIp();
}
