<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_field_formatter_info_alter().
 */
function marketo_form_field_field_formatter_info_alter(array &$info) {
  $info['string']['field_types'][] = 'marketo_form_field';
}

/**
 * Implements hook_field_widget_info_alter().
 */
function marketo_form_field_field_widget_info_alter(array &$info) {
  $info['string_textfield']['field_types'][] = 'marketo_form_field';
}
