<?php

/**
 * @file
 * Blackfire module code.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function blackfire_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the blackfire module.
    case 'help.page.blackfire':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Blackfire module provides Drupal integration for the <a href=":url">Blackfire.io</a> profiling tool.',
          [':url' => 'https://blackfire.io']) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Keeping track of your Blackfire profiles') . '</dt>';
      $output .= '<dd>' . t('The Blackfire module keeps a list of all your <a href=":url">Blackfire profiles</a> on this site.',
          [':url' => Url::fromRoute('blackfire.profile.list')->toString()]) . '</dd>';
      $output .= '<dt>' . t('Profiling uncached results') . '</dt>';
      $output .= '<dd>' . t('If you want to perform the uncached performance of a page, the <a href=":url">Settings</a> page allows you to turn off some caching during profiles.',
          [':url' => Url::fromRoute('blackfire.settings')->toString()]) . '</dd>';
      $output .= '</dl>';
      return $output;

    case 'blackfire.profile.list':
      $output = '';
      $output .= '<p>' . t('Blackfire profiles of this site are listed here. You can visit a profile at Blackfire by clicking the <em>Profile</em> link. You can also <a href=:settings>modify Blackfire settings</a>.',
          [':settings' => Url::fromRoute('blackfire.settings')->toString()]) . '</p>';
      $output .= '<p>' . t('Note that profiles will be missing from this list if they were served from the cache.') . '</p>';
      return $output;

    case 'blackfire.settings':
      $output = '';
      $output .= '<p>' . t('These settings allow you to change how your site behaves when being profiled. You can also <a href=:url>view Blackfire logs</a>.', [
          ':url' => Url::fromRoute('blackfire.profile.list')->toString()]) . '</p>';
      return $output;
  }
}
