<?php

/**
 * @file
 * Code for the FAPI error messages module.
 */

/**
 * Implements hook_element_info_alter().
 */
function fapi_error_messages_element_info_alter(array &$info) {
  // Overwrite core validations.
  if (isset($info['number'])) {
    // Remove only core validation.
    $info['number']['#element_validate'] = array_filter(
      $info['number']['#element_validate'],
      function ($val) {
        return $val[0] !== 'Drupal\Core\Render\Element\Number';
      }
    );
    $info['number']['#element_validate'][] = ['Drupal\fapi_error_messages\Validate\ValidateNumberConstraint', 'validate'];
  }
}
