<?php

/**
 * @file
 * Contains freshdesk_sso.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function freshdesk_sso_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the freshdesk_sso module.
    case 'help.page.freshdesk_sso':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Single sign on integration for Freshdesk') . '</p>';
      return $output;

    default:
  }
}

