<?php

/**
 * @file
 * Contains pagedesigner_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pagedesigner_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pagedesigner_block module.
    case 'help.page.pagedesigner_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pagedesigner block integration') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_system_info_alter().
 *
 * Adds a region to the block layout for placing blocks to be used in the
 * pagedesigner.
 */
function pagedesigner_block_system_info_alter(&$info, $file, $type)
{
    if ($type == 'theme') {
        $info['regions'] += ['pagedesigner' => (string) t('Pagedesigner region')];
    }
}
