<?php

/**
 * @file
 * Contains ckeditor_blockquote_attribution.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ckeditor_blockquote_attribution_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ckeditor_blockquote_attribution module.
    case 'help.page.ckeditor_blockquote_attribution':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('CKEditor button that inserts a blockquote along with HTML 5 figure and citation markup.') . '</p>';
      return $output;

    default:
  }
}
