<?php

/**
 * Implements hook_page_attachments().
 * @param $page
 */
function headroomjs_page_attachments(&$page) {
  // @todo: if not in admin and if current theme and if enabled, apply headroom

  $config = \Drupal::config('headroomjs.settings');

  if ($config->get('enable')) {
    $settings = [];
    $settings['offset'] = $config->get('offset');
    $settings['tolerance'] = $config->get('tolerance');
    $settings['tolerance_up'] = $config->get('tolerance_up');
    $settings['tolerance_down'] = $config->get('tolerance_down');
    $settings['selector'] = $config->get('selector');
    $settings['initial_class'] = $config->get('initial_class');
    $settings['pinned_class'] = $config->get('pinned_class');
    $settings['unpinned_class'] = $config->get('unpinned_class');
    $settings['top_class'] = $config->get('top_class');
    $settings['not_top_class'] = $config->get('not_top_class');

    $page['#attached']['drupalSettings']['headroomjs'] = $settings;
    $page['#attached']['library'][] = 'headroomjs/headroomjs';
  }
}