<?php

/**
 * @file
 * JS Callback Handler module.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;

/**
 * Implements hook_element_info_alter().
 *
 * {@inheritdoc}
 */
function js_element_info_alter(array &$info) {
  foreach (array_keys($info) as $type) {
    if (!isset($info[$type]['#pre_render'])) {
      $info[$type]['#pre_render'] = [];
    }
    array_unshift($info[$type]['#pre_render'], 'js.callback:preRenderJsCallback');

    if (!isset($info[$type]['#process'])) {
      $info[$type]['#process'] = [];
    }
    array_unshift($info[$type]['#process'], '\Drupal\js\Js::processJsCallback');
  }
}

/**
 * Implements hook_js_settings_build().
 *
 * {@inheritdoc}
 */
function js_js_settings_build(array &$settings, AttachedAssetsInterface $assets) {
  /** @var \Drupal\js\Js $js */
  $js = \Drupal::service('js.callback');
  $settings['js'] = [
    'endpoint' => $js->getEndpoint(),
    'tokens' => $js->getToken(),
  ];
}
