<?php

/**
 * @file
 * The hook implementation for the entity content export module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_form_BASE_FORM_alter().
 *
 * @param array $form
 *   The form elements.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state instance.
 */
function entity_content_export_form_entity_view_display_form_alter(
  array &$form,
  \Drupal\Core\Form\FormStateInterface $form_state
) {
  $display = $form_state->getFormObject()->getEntity();

  if (! $display instanceof EntityViewDisplayInterface) {
    return;
  }
  $bundle_type = $display->getTargetBundle();
  $entity_type = $display->getTargetEntityTypeId();

  if (!entity_content_export_has_bundle_config_display_mode(
    $entity_type,
    $bundle_type,
    $display->getMode())
  ) {
    return;
  }
  $settings = $display->getThirdPartySettings('entity_content_export');

  /** @var \Drupal\Core\Entity\EntityFieldManager $entity_field_manager */
  $entity_field_manager = \Drupal::service('entity_field.manager');
  $entity_base_fields = $entity_field_manager
    ->getBaseFieldDefinitions($entity_type);

  $form['entity_content_export'] = [
    '#type' => 'details',
    '#title' => new TranslatableMarkup('Entity content export'),
    '#tree' => TRUE,
    '#open' => FALSE,
  ];
  $base_fields = isset($settings['base_fields'])
    ? $settings['base_fields']
    : [];

  $form['entity_content_export']['base_fields'] = [
    '#type' => 'select',
    '#title' => new TranslatableMarkup('Base Field'),
    '#options' => entity_content_export_get_entity_base_field_options(
      $entity_type
    ),
    '#multiple' => TRUE,
    '#description' => new TranslatableMarkup(
      'Select multiple entity base fields that should be included in the export.'
    ),
    '#default_value' => $base_fields
  ];
  $form['entity_content_export']['components'] = [
    '#type' => 'table',
    '#header' => [
      new TranslatableMarkup('Field'),
      new TranslatableMarkup('Name'),
      new TranslatableMarkup('Render')
    ],
    '#empty' => new TranslatableMarkup(
      'No fields have been selected to be exported.'
    )
  ];

  foreach ($display->getComponents() as $field_name => $component_info) {
    if (isset($entity_base_fields[$field_name])
      && !isset($base_fields[$field_name])) {
      continue;
    }
    $component_settings = isset($settings['components'][$field_name])
      ? $settings['components'][$field_name]
      : [];

    $form['entity_content_export']['components'][$field_name]['field'] = [
      '#plain_text' => $field_name
    ];
    $form['entity_content_export']['components'][$field_name]['name'] = [
      '#type' => 'textfield',
      '#description' => new TranslatableMarkup(
        'Input the name that is used when exporting.'
      ),
      '#required' => TRUE,
      '#default_value' => isset($component_settings['name'])
        ? $component_settings['name']
        : $field_name
    ];
    $form['entity_content_export']['components'][$field_name]['render'] = [
      '#type' => 'select',
      '#options' => [
        'field' => new TranslatableMarkup('Field'),
        'value' => new TranslatableMarkup('Value'),
      ],
      '#required' => TRUE,
      '#default_value' => isset($component_settings['render'])
        ? $component_settings['render']
        : 'value'
    ];
  }

  $form['#entity_builders'][] = 'entity_content_export_entity_view_display_builder';
}

/**
 * Entity view display builder callback.
 *
 * @param $entity_type
 *   The entity type.
 * @param \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display
 *   The entity view display.
 * @param array $form
 *   An array of form elements.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form states.
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function entity_content_export_entity_view_display_builder(
  $entity_type,
  EntityViewDisplayInterface $display,
  array &$form,
  FormStateInterface $form_state
) {
  $module = 'entity_content_export';

  if (!$form_state->hasValue($module)) {
    return;
  }

  // Set all the entity content export settings.
  foreach ($form_state->getValue($module) as $key => $value) {
    $display->setThirdPartySetting($module, $key, $value);
  }

  $display->save();
}

/**
 * Get bundle configuration display mode.
 *
 * @param $entity_type
 *   The entity type.
 * @param $bundle_type
 *   The entity bundle type.
 *
 * @return string
 *   The fully defined entity bundle display mode.
 */
function entity_content_export_get_bundle_config_display_mode(
  $entity_type,
  $bundle_type
) {
  $settings = entity_content_export_settings();
  $configuration = $settings->get('entity_bundle_configuration');

  if (!isset($configuration[$entity_type][$bundle_type])) {
    return NULL;
  }
  $bundle = $configuration[$entity_type][$bundle_type];

  return isset($bundle['display_mode']) && !empty($bundle['display_mode'])
    ? $bundle['display_mode']
    : "{$entity_type}.{$bundle_type}.default";
}

/**
 * Entity content export has bundle config display mode.
 *
 * @param $entity_type
 *   The entity type.
 * @param $bundle_type
 *   The entity bundle.
 * @param $current_mode
 *   The current view mode.
 *
 * @return bool
 *   Determine if export has bundle config display mode selected.
 */
function entity_content_export_has_bundle_config_display_mode(
  $entity_type,
  $bundle_type,
  $current_mode
) {
  $bundle_display_mode = entity_content_export_get_bundle_config_display_mode(
    $entity_type,
    $bundle_type
  );
  $current_display_mode = "{$entity_type}.{$bundle_type}.{$current_mode}";

  if ($bundle_display_mode === $current_display_mode) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Get entity base field options.
 *
 * @param $entity_type_id
 *   The entity type identifier.
 *
 * @return array
 *   An array of base field options.
 */
function entity_content_export_get_entity_base_field_options($entity_type_id) {
  $options = [];
  $base_fields = \Drupal::service('entity_field.manager')
    ->getBaseFieldDefinitions($entity_type_id);

  /** @var \Drupal\Core\Field\BaseFieldDefinition $field */
  foreach ($base_fields as $name => $field) {
    if ($field->isComputed()) {
      continue;
    }
    $options[$name] = $field->getLabel();
  }

  return $options;
}

/**
 * Get entity content export settings.
 *
 * @return mixed
 *   The configuration instance for the entity content export settings.
 */
function entity_content_export_settings() {
  return entity_content_export_get_config(
    'entity_content_export.settings'
  );
}

/**
 * Get get configuration object.
 *
 * @param $name
 *   The configuration name.
 *
 * @return mixed
 *   The configuration instance.
 */
function entity_content_export_get_config($name) {
  return \Drupal::service('config.factory')->get($name);
}
