<?php

/**
 * @file
 * Webform component which renders a "shs" field.
 */

use Drupal\taxonomy\TermInterface;
use Drupal\webform_shs\Element\ShsTermSelect;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function webform_shs_taxonomy_term_presave(TermInterface $term) {
  ShsTermSelect::invalidateOptionsCache($term->bundle());
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function webform_shs_taxonomy_term_delete(TermInterface $term) {
  ShsTermSelect::invalidateOptionsCache($term->bundle());
}
