<?php

/**
 * @file
 * Contains Hooks.
 */

use Drupal\iots_device\Hook\Theme;
use Drupal\iots_device\Hook\ThemeSuggestionsIotsDevice;
use Drupal\iots_device\Hook\EntityView;

/**
 * Implements hook_theme().
 */
function iots_device_theme() {
  return Theme::hook();
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function iots_device_theme_suggestions_iots_device(array $variables) {
  return ThemeSuggestionsIotsDevice::hook($variables);
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function iots_device_iots_device_view(array &$build, $entity, $display, $view_mode) {
  EntityView::hook($build, $entity, $view_mode);
}
