<?php

/**
 * @file
 * Show the drush commands information in the module help page.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Constants defined by drush in the includes/bootstrap.inc file.
 *
 * @see https://drupal.stackexchange.com/q/250786/28275
 */
if (!defined('DRUSH_BOOTSTRAP_DRUPAL_LOGIN')) {
  define('DRUSH_BOOTSTRAP_NONE', -1);
  define('DRUSH_BOOTSTRAP_MAX', -2);
  define('DRUSH_BOOTSTRAP_DRUSH', 0);
  define('DRUSH_BOOTSTRAP_DRUPAL_ROOT', 1);
  define('DRUSH_BOOTSTRAP_DRUPAL_SITE', 2);
  define('DRUSH_BOOTSTRAP_DRUPAL_CONFIGURATION', 3);
  define('DRUSH_BOOTSTRAP_DRUPAL_DATABASE', 4);
  define('DRUSH_BOOTSTRAP_DRUPAL_FULL', 5);
  define('DRUSH_BOOTSTRAP_DRUPAL_LOGIN', 6);
}

/**
 * Implements hook_help().
 */
function drush_help_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help.
    case 'help.page.drush_help':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("To see the drush commands help you need to use drush help COMMAND_NAME from the command line, but if you want to see this information in Drupal you'll can't do it. This module improves the module help page showing information about the module drush commands. The drush command help section only will be added if the module for which you are viewing the help have drush commands defined.");

      return $output;
  }
}

/**
 * Wrapper function for call_user_func() function.
 *
 * This is a wrapper function used from the from the help page controller
 * because in the DRUPAL scope the dt() drush function is not defined.
 *
 * @param string $callback
 *   The callable to be called.
 *
 * @return mixed
 *   The return value of the callback, or FALSE on error.
 *
 * @see call_user_func()
 */
function _drush_help_call_user_func($callback) {
  if (!function_exists('dt')) {

    /**
     * Alias for dt() function.
     *
     * Is used when the MODULE_NAME_drush_command() function is called
     * from the controller, because in this scope the dt() drush
     * function is not defined.
     *
     * @param string $string
     *   The string to translate.
     *
     * @return string
     *   The translated string.
     */
    function dt($string) {
      return t($string);
    }

  }
  return call_user_func($callback);
}
