<?php

/**
 * @file
 * Contains views_natural_sort_test.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_natural_sort_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the views_natural_sort_test module.
    case 'help.page.views_natural_sort_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Set up module for Views Natural Sort testing.') . '</p>';
      return $output;

    default:
  }
}
