# Products routing definition

entity.products.canonical:
  route_name: entity.products.canonical
  base_route: entity.products.canonical
  title: 'View'

entity.products.edit_form:
  route_name: entity.products.edit_form
  base_route: entity.products.canonical
  title: 'Edit'

entity.products.version_history:
  route_name: entity.products.version_history
  base_route: entity.products.canonical
  title: 'Revisions'

entity.products.delete_form:
  route_name:  entity.products.delete_form
  base_route:  entity.products.canonical
  title: Delete
  weight: 10

