<?php

/**
 * @file
 * Allows entities to be translated into different languages.
 */

/**
 * Implements hook_entity_type_alter().
 *
 * @see \Drupal\Core\Entity\Annotation\EntityType
 */
function translation_outdated_entity_type_alter(array &$entity_types) {
  // Provide defaults for translation info.
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  foreach ($entity_types as $entity_type) {
    if ($entity_type->isTranslatable()) {
      if ($entity_type->id() == 'node') {
        $entity_type->setHandlerClass('translation', 'Drupal\translation_outdated\CustomContentTranslationHandler');
      }
    }
  }
}
