<?php

/**
 * @file
 * Hook implementations for views filter clear module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views_filter_clear\Form\FilterClear;
use Drupal\views_filter_clear\Form\ViewsUiFormHelper;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function views_filter_clear_form_views_ui_config_item_form_alter(array &$form, FormStateInterface $form_state) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(ViewsUiFormHelper::class)
    ->viewsUiFormAlter($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function views_filter_clear_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(FilterClear::class)
    ->addClearLinks($form, $form_state);
}
