<?php

/**
 * @file
 * Provides Mason integration to create a perfect gapless grid of elements.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function mason_theme() {
  $themes = [];
  foreach (['mason', 'box'] as $item) {
    $key = $item == 'mason' ? 'mason' : 'mason_' . $item;
    $themes[$key] = [
      'render element' => 'element',
      'file' => 'templates/mason.theme.inc',
    ];
  }
  return $themes;
}

/**
 * Implements hook_library_info_build().
 */
function mason_library_info_build() {
  $libraries = [];
  if ($skins = \Drupal::service('mason.manager')->getSkins()) {
    foreach ($skins as $key => $skin) {
      $provider = isset($skin['provider']) ? $skin['provider'] : 'mason';
      $id = $provider . '.' . $key;
      if (isset($skin['css']) && is_array($skin['css'])) {
        $libraries[$id]['css'] = $skin['css'];
      }
      if (isset($skin['js']) && is_array($skin['js'])) {
        $libraries[$id]['js'] = $skin['js'];
      }
    }
  }
  return $libraries;
}

/**
 * Implements hook_hook_info().
 */
function mason_hook_info() {
  $hooks['mason_skins_info'] = ['group' => 'mason'];
  return $hooks;
}

/**
 * Implements hook_help().
 */
function mason_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.mason':
      return check_markup(file_get_contents(dirname(__FILE__) . '/README.txt'));
  }
}
