<?php

/**
 * @file
 * Contains fitbit.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fitbit_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fitbit module.
    case 'help.page.fitbit':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Fitbit API wrapper module for connecting to Fitbit.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function fitbit_theme($existing, $type, $theme, $path) {
  $items = [];

  $items['fitbit_badge'] = [
    'variables' => [
      'raw_badge' => NULL,
      'image' => NULL,
    ],
  ];

  return $items;
}

/**
 * Template preprocessor for fitbit_badge.
 *
 * @param $variables
 */
function template_preprocess_fitbit_badge(&$variables) {
  $raw_badge = $variables['raw_badge'];

  $variables['image'] = [
    '#theme' => 'image',
    '#uri' => $variables['image'],
    '#alt' => $raw_badge['name'],
  ];

  $variables['name'] = $raw_badge['name'];
}
