<?php

/**
 * @file
 * Form Protect module main file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\Unicode;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */
function form_protect_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  // Exit if this form isn't protected.
  if (!in_array($form_id, \Drupal::config('form_protect.settings')->get('form_ids'))) {
    return;
  }

  if (Unicode::strpos($form['#action'], 'form_action_') === 0) {
    // Forms where no explicit #action are using a placeholder for cacheability
    // reasons. We replace the placeholder with the real action attribute.
    $render_array = \Drupal::formBuilder()->renderPlaceholderFormAction();
    $action = $render_array['#markup'];
    // Remove the lazy loader placeholder. We changed #action to a real path, so
    // the value no more contains a placeholder to be replaced later.
    unset($form['#attached']['placeholders'][$form['#action']]);
  }
  else {
    $action = $form['#action'];
  }

  $form['#attached']['library'][] = 'form_protect/form-script';
  $form['#attached']['drupalSettings']['formProtect'][$form['#id']] = $action;
  $form['#action'] = Url::fromRoute('form_protect.submit')->toString();
}
