<?php

/**
 * @file
 * Module file.
 */

use Drupal\views\Plugin\views\display\Block as CoreBlock;
use Drupal\views_block_placement_exposed_form_defaults\ExposedFormBlockDisplay;

/**
 * Implements hook_views_plugins_display_alter().
 */
function views_block_placement_exposed_form_defaults_views_plugins_display_alter(&$displays) {
  if (!empty($displays['block']['class']) && $displays['block']['class'] == CoreBlock::class) {
    $displays['block']['class'] = ExposedFormBlockDisplay::class;
  }
}

/**
 * Implements hook_config_schema_info_alter().
 */
function views_block_placement_exposed_form_defaults_config_schema_info_alter(&$definitions) {
  $definitions['views.display.block']['mapping']['customizable_exposed_filters'] = [
    'type' => 'sequence',
    'sequence' => [
      'type' => 'string',
    ],
  ];
  $definitions['views_block']['mapping']['exposed_filter_values'] = [
    'type' => 'sequence',
    'sequence' => [
      // We do not know how all filter form elements will store data.
      'type' => 'ignore',
    ],
  ];
}
