<?php

/**
 * @file
 * A collection on module hooks for the flot module.
 */

/**
 * Implements hook_theme().
 */
function flot_theme(array $existing, $type, $theme, $path) {
  return [
    'flot_element' => [
      'variables' => [
        'id' => NULL,
      ],
      'flot' => [
        'render element' => 'flot',
      ],
    ],
  ];
}

/**
 * Implements theme_hook().
 *
 * Should this be moved to a theme.inc file?
 */
function theme_flot($variables) {
  $output = $variables['flot'];
  return $output;
}
