<?php

/**
 * @file
 * Code for the nextpre module.
 */

/**
 * @file
 * This is the module to create a drop-down menu for the core toolbar.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nextpre_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.nextpre':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Drupal plug-in will allow the website visitors to jump on the next or previous post without going back to the main page to see all the posts. Drupal developers can use this plug-in for particular content types. Suppose, there are many large content bundles, then the developer can apply the plug-in for a specific bunch of content.') . '</p>';

      return $output;
  }
}
