<?php

/**
 * @file
 * Module file for Remove meta tag headers reponse for Generator/X-Generator.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function remove_meta_and_headers_page_attachments_alter(array &$attachments) {
  // Get config settings for Remove META tag and Response header (Generator)
  $config = \Drupal::config('remove_meta_and_headers.settings');

  foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
    if ($attachment[1] == 'system_meta_generator') {
      if (1 == $config->get('meta_generator')) {
        unset($attachments['#attached']['html_head'][$key]);
      }
    }
  }
}
