<?php

/**
 * @file
 * Contains akv_pagepeels.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Config;


/**
 * Implements hook_help().
 */
function akv_pagepeels_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the akv_pagepeels module.
    case 'help.page.akv_pagepeels':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Displays a pagepeel for the german movement against "Vorratsdatenspeicherung", www.vorratsdatenspeicherung.de') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_bottom().
 *
 * Inserts the html snippet before closing body tag
 *
 * Used instead of hook_init() in d7
 *
 * @see https://www.drupal.org/node/2013014
 */
function akv_pagepeels_page_bottom(array &$page_bottom) {
  $akv_pagepeels_info = \Drupal::config('akv_pagepeels.settings')->get('akv_pagepeels_info');
  $akv_pagepeels_html_file = drupal_get_path('module', 'akv_pagepeels') . '/html/' . $akv_pagepeels_info . '.html';
  $page_bottom['akv_pagepeels'] = ['#markup' => file_get_contents($akv_pagepeels_html_file)];
}

/**
 * Implements hook_page_attachments().
 *
 * Adds the in the selected style from settings form..
 *
 * Used instead of drupal_add_css() and drupal_add_js() in d7
 *
 * @see https://www.drupal.org/node/2169605
 * @see akv_pagepeels.libraries.yml
 */
function akv_pagepeels_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'akv_pagepeels/akv_pagepeels_expanded';
  $akv_pagepeels_type = \Drupal::config('akv_pagepeels.settings')->get('akv_pagepeels_type');
  $attachments['#attached']['library'][] = 'akv_pagepeels/' . $akv_pagepeels_type;
}
