<?php

/**
 * Implements hook_entity_presave().
 */
function entity_slug_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof \Drupal\Core\Entity\FieldableEntityInterface) {
    foreach ($entity->getFieldDefinitions() as $field_name => $field_definition) {
      if (in_array($field_definition->getType(), ['slug', 'slug_path'])) {
        if ($field_definition->getSetting('force_default')) {
          /** @var \Drupal\entity_slug\Plugin\Field\FieldType\SlugItemInterface $field */
          $field = $entity->get($field_name);
          $input = $field_definition->getDefaultValueLiteral()[0]['input'];
          $field->input = $input;
          $field->preSave();
        }
      }
    }
  }
}
