<?php

/**
 * @file
 * Install, update, and uninstall functions for Registration validation module.
 */

/**
 * Implements hook_requirements().
 */
function registration_validation_requirements($phase) {
  $requirements = [];

  if ($phase == 'runtime') {
    // Show the validation blocked counter on the status report page.
    $requirements['registration_validation_counter'] = [
      'title' => t('Registration Validation'),
      'value' => \Drupal::translation()->formatPlural(
        \Drupal::config('registration_validation.settings')->get('validation_counter'),
        '1 blocked registration',
        '@count blocked registrations'
      ),
      'severity' => REQUIREMENT_INFO,
    ];
  }

  return $requirements;
}

/**
 * Implements hook_install().
 */
function registration_validation_install() {
  // Be friendly to your users: what should they to do after install?
  drupal_set_message(t('You can now <a href="/admin/config/people/registration-validation">configure</a> the Registration validation module for your site.'), 'status');
}
