<?php
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_operation().
 */
function a12_best_bets_entity_operation(EntityInterface $entity) {
    if (!(Drupal::currentUser()->hasPermission('administer a12 connector'))) return;
    $entites = ['node', 'user'];
    $entityTypeId = $entity->getEntityTypeId();
    if (in_array($entityTypeId, $entites)) {
        $operations = [];
        $nodeId = $entity->id();
        $route_name = sprintf("a12_best_bets.%s_overview", $entityTypeId);
        $url = \Drupal\Core\Url::fromRoute($route_name, [$entityTypeId => $nodeId]);
        $operations['a12_bets_bets'] = [
          'title' => t('A12 Best Bets'),
          'url' => $url,
          'weight' => 100
        ];
        return $operations;
    };
}