<?php

namespace Drupal\commerce_adyen\Adyen;

/**
 * Notification events.
 *
 * @link https://github.com/Adyen/php/blob/master/3.Notifications/httppost/notification-server.php
 */
abstract class Notification {

  const AUTHORISATION = 'AUTHORISATION';
  const CANCELLATION = 'CANCELLATION';
  const REFUND = 'REFUND';
  const PENDING = 'PENDING';
  const CANCEL_OR_REFUND = 'CANCEL_OR_REFUND';
  const CAPTURE = 'CAPTURE';
  const REFUNDED_REVERSED = 'REFUNDED_REVERSED';
  const CAPTURE_FAILED = 'CAPTURE_FAILED';
  const REQUEST_FOR_INFORMATION = 'REQUEST_FOR_INFORMATION';
  const NOTIFICATION_OF_CHARGE_BACK = 'NOTIFICATION_OF_CHARGEBACK';
  const CHARGE_BACK = 'CHARGEBACK';
  const CHARGE_BACK_REVERSED = 'CHARGEBACK_REVERSED';
  const REPORT_AVAILABLE = 'REPORT_AVAILABLE';
  const REFUND_FAILED = 'REFUND_FAILED';
  const PAIDOUT_REVERSED = 'PAIDOUT_REVERSED';
  const NOTIFICATION_OF_FRAUD = 'NOTIFICATION_OF_FRAUD';
  const MANUAL_REVIEW_ACCEPT = 'MANUAL_REVIEW_ACCEPT';
  const MANUAL_REVIEW_REJECT = 'MANUAL_REVIEW_REJECT';
  const RECURRING_CONTRACT = 'RECURRING_CONTRACT';
  const PAYOUT_EXPIRE = 'PAYOUT_EXPIRE';
  const PAYOUT_DECLINE = 'PAYOUT_DECLINE';
  const PAYOUT_THIRDPARTY = 'PAYOUT_THIRDPARTY';
  const REFUND_WITH_DATA = 'REFUND_WITH_DATA';
  const AUTHORISE_REFERRAL = 'AUTHORISE_REFERRAL';
  const EXPIRE = 'EXPIRE';
  const FRAUD_ONLY = 'FRAUD_ONLY';
  const FUND_TRANSFER = 'FUND_TRANSFER';
  const HANDLED_EXTERNALLY = 'HANDLED_EXTERNALLY';
  const OFFER_CLOSED = 'OFFER_CLOSED';
  const ORDER_OPENED = 'ORDER_OPENED';
  const ORDER_CLOSED = 'ORDER_CLOSED';
  const PROCESS_RETRY = 'PROCESS_RETRY';

}
