<?php

/**
 * @file
 * Contains pfm.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pfm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pfm module.
    case 'help.page.pfm':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Permissions filtered by modules') . '</p>';
      return $output;

    default:
  }
}
