<?php
/**
 * @file
 * To make searchbox autocomplete.
 *
 */

/**
 * Implements hook_help().
 */
function autocomplete_searchbox_help($path, $arg) {
  switch ($path) {
    case 'admin/help#autocomplete_searchbox' :
      return check_markup(file_get_contents(dirname(__FILE__) . "/README.txt"));
      break;
  }
}

/*
* Implements hook_init().
 */
function autocomplete_searchbox_init() {
  if (variable_get('autocomplete_searchbox_auto_select', '0')) {
    if (current_path() != 'admin/config/search/autocomplete-search-config') {
      drupal_add_js(drupal_get_path('module', 'autocomplete_searchbox') . '/js/autocomplete_searchbox.js');
    }
  }
}