<?php

/**
 * @file
 * Contains editor_md.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function editor_md_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the editor_md module.
    case 'help.page.editor_md':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('It&#039;s a great markdown editor.') . '</p>';
      return $output;

    default:
  }
}
