<?php

/**
 * @file
 * Image Tools Module.
 */

/**
 * Implements hook_theme().
 */
function image_tools_theme() {
  $theme['overview_page'] = [
    'variables' => [
      'name' => NULL,
    ],
    'template' => 'overview',
  ];

  $theme['show_convertible_pngs_page'] = [
    'variables' => ['rows' => []],
    'template' => 'show_convertible_pngs',
  ];

  $theme['show_resizable_jpgs_page'] = [
    'variables' => [
      'max_width' => NULL,
      'rows' => [],
      'form' => NULL,
      'png' => NULL,
    ],
    'template' => 'show_resizable_jpgs',
  ];

  return $theme;
}
