<?php

/**
 * @file
 * Defines simple country field type.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function country_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.country':
      $output = '';
      $output .= '<h3>' . t('Country') . '</h3>';
      $output .= '<p>' . t('The Country module defines a simple country field type for the Field module. It provides 2 widgets - select options and autocomplete textfield - for this purpose.  See the <a href=":field">Field module help page</a> for more information about fields.', [':field' => \Drupal::url('help.page', ['name' => 'field'])]) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function country_field_widget_country_default_form_alter(&$element, FormStateInterface $form_state, $context) {
  $country =& $element['value'];
  $country_code = '';

  if (!empty($country['#default_value'])) {
    return FALSE;
  }

  if (!\Drupal::moduleHandler()->moduleExists('ip2country')) {
    return FALSE;
  }

  if (\Drupal::currentUser()->isAuthenticated()) {
    $uid = \Drupal::currentUser()->id();
    $user_data = \Drupal::service('user.data')->get('ip2country', $uid);
    if (isset($user_data)) {
      $country_code = $user_data['country_iso_code_2'];
    }
  }
  else {
    $ip = \Drupal::request()->getClientIp();
    $country_code = ip2country_get_country($ip);
  }

  if (in_array($country_code, array_keys($country['#options']))) {
    $country['#default_value'] = $country_code;
  }
}

/**
 * Implements hook_field_widget_info_alter().
 */
function country_field_widget_info_alter(array &$info) {
  // Allow boxes/radio buttons widget to be used for country field.
  $info['options_buttons']['field_types'][] = 'country';
}
