<?php

/**
 * @file
 * Smart Login functionalities.
 *
 * Inspired by IN2PIRE (contact@inspire.vn).
 */

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\Core\ParamConverter\ParamNotConvertedException;

/**
 * Get admin theme for smart login.
 */
function smart_login_get_admin_theme() {
  static $theme = NULL;

  if (NULL === $theme) {
    $theme = \Drupal::configFactory()->get('smart_login.settings')->get('admin.theme');

    switch (TRUE) {
      case (empty($theme) || 'theme:admin' == $theme):
        $theme = \Drupal::configFactory()->get('system.theme')->get('admin');
        break;

      case 'theme:default' == $theme:
        $theme = \Drupal::configFactory()->get('system.theme')->get('default');
        break;
    }
  }

  return $theme;
}

/**
 * Get destination for smart login.
 */
function smart_login_destination($routeName = NULL) {
  global $base_path;
  $destination = \Drupal::request()->get('destination', NULL);
  $routeName = \Drupal::routeMatch()->getRouteName();

  if ('smart_login.admin_login' == $routeName) {
    // Backend.
    $defaul_variable = 'admin.destination';
    $default_path = 'system.admin';
  }
  else {
    // Frontend.
    $defaul_variable = 'front.destination';
    $default_path = 'user.page';
  }

  if (empty($destination)) {
    $destination = \Drupal::config('smart_login.settings')->get($defaul_variable);
  }

  if ($destination == '' || $destination == 'user/login' || $destination == 'admin/login' || UrlHelper::isExternal($destination)) {
    $destination = $default_path;
  } else {
    try {
      $interalDestination = str_replace($base_path, '/', '/' . ltrim($destination, '/'));
      $url = Url::fromUri('internal:' . $interalDestination);
      $destination = $url->getRouteName();
    }
    catch (\Exception $e) {
      $destination = $default_path;
    }
  }

  return $destination;
}

/**
 * Alter form and inject css.
 */
function _smart_login_form_alter(&$form, FormStateInterface $form_state) {
  $adminTheme = smart_login_get_admin_theme();
  $cssFile = drupal_get_path('module', 'smart_login') . '/css/' . $adminTheme . '.css';

  if (file_exists($cssFile)) {
    $form['#attached']['library'][] = 'smart_login/' . $adminTheme . '-admin-login';
  }
}

/**
 * Alter user_login() form.
 *
 * @see user_login()
 * @see smart_login_user_login_submit()
 */
function smart_login_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $form['#submit'][] = 'smart_login_user_login_submit';
  $routeName = \Drupal::routeMatch()->getRouteName();

  if ('smart_login.admin_login' != $routeName) {
    return;
  }

  _smart_login_form_alter($form, $form_state);

  $form['actions']['link'] = [
    '#type' => 'link',
    '#title' => t('Forgot password?'),
    '#url' => Url::fromUri('internal:/admin/password'),
  ];
}

/**
 * Submit handler.
 *
 * @see smart_login_form_user_login_alter()
 */
function smart_login_user_login_submit($form, FormStateInterface $form_state) {
  $form_state->setRedirect(smart_login_destination());
}

/**
 * Alter user_pass() form.
 *
 * @see user_pass()
 * @see smart_login_user_pass_submit()
 */
function smart_login_form_user_pass_alter(&$form, FormStateInterface $form_state) {
  $routeName = \Drupal::routeMatch()->getRouteName();

  if ('smart_login.admin_password' != $routeName) {
    return;
  }

  _smart_login_form_alter($form, $form_state);

  $form['actions']['link'] = [
    '#type' => 'link',
    '#title' => t('Login'),
    '#url' => Url::fromUri('internal:/admin/login'),
  ];

  $form['#submit'][] = 'smart_login_user_pass_submit';
}

/**
 * Submit handler.
 *
 * @see smart_login_form_user_pass_alter()
 * @see smart_login_form_user_login_block_alter()
 */
function smart_login_user_pass_submit(&$form, FormStateInterface $form_state) {
  $form_state->setRedirect('smart_login.admin_login');
}

/**
 * Alter system_site_information_settings() form.
 *
 * @see smart_login_form_system_site_information_settings_submit()
 */
function smart_login_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state) {
  $moduleConfig = \Drupal::configFactory()->get('smart_login.settings');

  $form['error_page']['site_403']['#default_value'] = $moduleConfig->get('page.403');
  $form['#submit'][] = 'smart_login_form_system_site_information_settings_submit';
}

function smart_login_form_system_site_information_settings_submit($form, $form_state) {
  $siteConfig = \Drupal::configFactory()->getEditable('system.site');
  $moduleConfig = \Drupal::configFactory()->getEditable('smart_login.settings');

  $siteConfig->set('page.403', 'error/403')->save();
  $moduleConfig->set('page.403', $form_state->getValue('site_403'))->save();
}
