<?php

/**
 * @file
 * Redmine Connector base module file.
 */

use Drupal\node\Entity\Node;

/**
 * Implements hook_cron().
 */
function redmine_connector_cron() {
  \Drupal::service('redmine_connector.synchronization')->synchronizeProjects();
  \Drupal::service('redmine_connector.synchronization')->synchronizeUsers();
  \Drupal::service('redmine_connector.synchronization')->synchronizeIssues();
}

/**
 * Implements hook_uninstall().
 */
function redmine_connector_uninstall() {
  // Deleting all nodes of type Project, Issue, Employee from site after uninstalling module.
  $result = \Drupal::entityQuery('node')
    ->condition('type', 'project')
    ->execute();
  foreach (Node::loadMultiple($result) as $node) {
    $node->delete();
  }
  $result = \Drupal::entityQuery('node')
    ->condition('type', 'issue')
    ->execute();
  foreach (Node::loadMultiple($result) as $node) {
    $node->delete();
  }
  $result = \Drupal::entityQuery('node')
    ->condition('type', 'redmine_user')
    ->execute();
  foreach (Node::loadMultiple($result) as $node) {
    $node->delete();
  }
}

function redmine_connector_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'redmine_connector/table_styles';
}
