<?php

/**
 * @file
 * Install, update, and uninstall functions for the Server Disk Space Notification module.
 */

/**
 * Implements hook_uninstall().
 */
function server_disk_space_notification_uninstall() {
	\Drupal::state()->delete('server_space');
	\Drupal::state()->delete('server_space_email_to');
	\Drupal::state()->delete('server_space_email_from_address');
	\Drupal::state()->delete('server_space_email_from_name');
	\Drupal::state()->delete('server_space_cron');
}
