<?php

/**
 * @file
 * sets up twig theme
 */

use Symfony\Component\HttpFoundation\Response;

 function simplepodcast_theme($existing, $type, $theme, $path) {
   return [
    'simplepodcast_xml' => [
      'variables' => ['channel_title'       => NULL,
                      'channel_link'        => NULL,
                      'channel_lang'        => NULL,
                      'channel_copyright'   => NULL,
                      'channel_description' => NULL,
                      'channel_rss_url'     => NULL,
                      'channel_explicit'    => NULL,
                      'channel_owner_name'  => NULL,
                      'channel_owner_author'=> NULL,                      
                      'channel_owner_email' => NULL,
                      'channel_image_url'   => NULL,
                      'channel_category'    => NULL,
                      'channel_lang'        => NULL,
                      'channel_categories'  => NULL,
                      'items'               => NULL,
   ],],];
}


