<?php

/**
 * @file
 * Contains user_agent_class.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user_agent_class\EventSubscriber\UserAgentSubscriber;

/**
 * Implements hook_help().
 */
function user_agent_class_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_agent_class module.
    case 'help.page.user_agent_class':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Device &amp; Browser Detect Class') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function user_agent_class_preprocess_html(&$variables) {

  $methodProvide = \Drupal::config('user_agent_class.provide')->get('user_agent_class.responsibility_frontend_backend');
  if ($methodProvide) {
    $variables['attributes']['class'][] = UserAgentSubscriber::getUserAgentClass();
    $variables['#cache']['contexts'][] = 'headers:user-agent';
  }
  else {
    $listDevicesAndBrowsers = \Drupal::service('user_agent_class.check')->getListBrowsersDevices();
    $variables['#attached']['library'][] = 'user_agent_class/user-agent-class-check';
    $variables['#attached']['drupalSettings']['user_agent_class']['ListDevicesAndBrowsers'] = $listDevicesAndBrowsers;
    $variables['#attached']['drupalSettings']['user_agent_class']['methodProvide'] = $methodProvide;
  }
}
