<?php

/**
 * @file
 * Multiple siteamp module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\multiple_sitemap\Plugin\QueueWorker\MultipleSitemapUpdateXml;

/**
 * Implements hook_help().
 */
function multiple_sitemap_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'multiple_sitemap.add_multiple_sitemap' || $route_name == 'multiple_sitemap.dashboard') {
    return t("
      <p>This module provides a multiple xml sitemap functionality.</p>
      <p>Create sub files and it will create a main file for all subfiles.</p>
      <p>Link of main file would be 'sites/default/files/multiple_sitemap/sitemap.xml'.</p>
    ");
  }
}

/**
 * Implements hook_cron().
 */
function multiple_sitemap_cron() {
  $queue = \Drupal::queue('ms_update_xml');
  $queue->createItem('sitemap_xml');
}
