<?php

/**
 * @file
 * CiviMember Roles Sync module code.
 */

use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_user_login().
 */
function civicrm_member_roles_user_login(AccountInterface $account) {
  $config = \Drupal::config('civicrm_member_roles.settings');
  if (!in_array('login', $config->get('sync_method'))) {
    return;
  }

  /** @var \Drupal\civicrm_member_roles\CivicrmMemberRoles $civicrm_member_roles */
  $civicrm_member_roles = \Drupal::service('civicrm_member_roles');
  $civicrm_member_roles->syncUser($account);
}

/**
 * Implements hook_user_login().
 */
function civicrm_member_roles_user_logout(AccountInterface $account) {
  $config = \Drupal::config('civicrm_member_roles.settings');
  if (!in_array('login', $config->get('sync_method'))) {
    return;
  }

  /** @var \Drupal\civicrm_member_roles\CivicrmMemberRoles $civicrm_member_roles */
  $civicrm_member_roles = \Drupal::service('civicrm_member_roles');
  $civicrm_member_roles->syncUser($account);
}

/**
 * Implements hook_cron().
 */
function civicrm_member_roles_cron() {
  $config = \Drupal::config('civicrm_member_roles.settings');
  if (in_array('cron', $config->get('sync_method'))) {
    /** @var \Drupal\civicrm_member_roles\CivicrmMemberRoles $civicrm_member_roles */
    $civicrm_member_roles = \Drupal::service('civicrm_member_roles');
    $civicrm_member_roles->sync($config->get('cron_limit'));
  }
}

/**
 * CiviCRM hook_civicrm_post().
 *
 * @param string $op
 *   The operation being performed.
 * @param string $objname
 *   The name of the object.
 * @param int $objid
 *   The ID of the object.
 * @param mixed $objref
 *   The object.
 */
function civicrm_member_roles_civicrm_post($op, $objname, $objid, &$objref) {
  // Only act on memberships.
  if ($objname != "Membership") {
    return;
  }

  // Only act when configured for "update".
  $config = \Drupal::config('civicrm_member_roles.settings');
  if (!in_array('update', $config->get('sync_method'))) {
    return;
  }

  /** @var \Drupal\civicrm_member_roles\CivicrmMemberRoles $civicrm_member_roles */
  $civicrm_member_roles = \Drupal::service('civicrm_member_roles');
  if ($account = $civicrm_member_roles->getContactAccount($objref->contact_id)) {
    $civicrm_member_roles->syncContact($objref->contact_id, $account);
  }
}
