<?php
/**
 * @file
 * Node and term data to test updates with data.
 *
 * @see head2head_1314214()
 * This file was generated by the dump-database-d8.php script, from an
 * installation of Drupal 8. It has the following modules installed:
 *
 *  - block
 *  - block_content
 *  - breakpoint
 *  - ckeditor
 *  - color
 *  - comment
 *  - config
 *  - contact
 *  - contextual
 *  - datetime
 *  - dblog
 *  - editor
 *  - entity_reference
 *  - field
 *  - field_ui
 *  - file
 *  - filter
 *  - help
 *  - history
 *  - image
 *  - link
 *  - menu_link_content
 *  - menu_ui
 *  - node
 *  - options
 *  - page_cache
 *  - path
 *  - quickedit
 *  - rdf
 *  - search
 *  - shortcut
 *  - standard
 *  - system
 *  - taxonomy
 *  - text
 *  - toolbar
 *  - tour
 *  - update
 *  - user
 *  - views
 *  - views_ui
 *
 * @see https://www.drupal.org/node/2544972
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->insert('node')
->fields(array(
  'nid',
  'vid',
  'type',
  'uuid',
  'langcode',
))
->values(array(
  'nid' => '1',
  'vid' => '1',
  'type' => 'article',
  'uuid' => 'cb9458fa-7a29-4672-9428-40dfc2073780',
  'langcode' => 'en',
))
->execute();

$connection->insert('node__comment')
->fields(array(
  'bundle',
  'deleted',
  'entity_id',
  'revision_id',
  'langcode',
  'delta',
  'comment_status',
))
->values(array(
  'bundle' => 'article',
  'deleted' => '0',
  'entity_id' => '1',
  'revision_id' => '1',
  'langcode' => 'en',
  'delta' => '0',
  'comment_status' => '2',
))
->execute();

$connection->insert('node__field_tags')
->fields(array(
  'bundle',
  'deleted',
  'entity_id',
  'revision_id',
  'langcode',
  'delta',
  'field_tags_target_id',
))
->values(array(
  'bundle' => 'article',
  'deleted' => '0',
  'entity_id' => '1',
  'revision_id' => '1',
  'langcode' => 'en',
  'delta' => '0',
  'field_tags_target_id' => '1',
))
->execute();

$connection->insert('node_field_data')
->fields(array(
  'nid',
  'vid',
  'type',
  'langcode',
  'title',
  'uid',
  'status',
  'created',
  'changed',
  'promote',
  'sticky',
  'default_langcode',
))
->values(array(
  'nid' => '1',
  'vid' => '1',
  'type' => 'article',
  'langcode' => 'en',
  'title' => 'Test article',
  'uid' => '1',
  'status' => '1',
  'created' => '1439419364',
  'changed' => '1439419364',
  'promote' => '1',
  'sticky' => '0',
  'default_langcode' => '1',
))
->execute();

$connection->insert('node_field_revision')
->fields(array(
  'nid',
  'vid',
  'langcode',
  'title',
  'uid',
  'status',
  'created',
  'changed',
  'promote',
  'sticky',
  'default_langcode',
))
->values(array(
  'nid' => '1',
  'vid' => '1',
  'langcode' => 'en',
  'title' => 'Test article',
  'uid' => '1',
  'status' => '1',
  'created' => '1439419364',
  'changed' => '1439419364',
  'promote' => '1',
  'sticky' => '0',
  'default_langcode' => '1',
))
->execute();

$connection->insert('node_revision')
->fields(array(
  'nid',
  'vid',
  'langcode',
  'revision_timestamp',
  'revision_uid',
  'revision_log',
))
->values(array(
  'nid' => '1',
  'vid' => '1',
  'langcode' => 'en',
  'revision_timestamp' => '1439419364',
  'revision_uid' => '1',
  'revision_log' => '',
))
->execute();

$connection->insert('node_revision__comment')
->fields(array(
  'bundle',
  'deleted',
  'entity_id',
  'revision_id',
  'langcode',
  'delta',
  'comment_status',
))
->values(array(
  'bundle' => 'article',
  'deleted' => '0',
  'entity_id' => '1',
  'revision_id' => '1',
  'langcode' => 'en',
  'delta' => '0',
  'comment_status' => '2',
))
->execute();

$connection->insert('node_revision__field_tags')
->fields(array(
  'bundle',
  'deleted',
  'entity_id',
  'revision_id',
  'langcode',
  'delta',
  'field_tags_target_id',
))
->values(array(
  'bundle' => 'article',
  'deleted' => '0',
  'entity_id' => '1',
  'revision_id' => '1',
  'langcode' => 'en',
  'delta' => '0',
  'field_tags_target_id' => '1',
))
->execute();

$connection->insert('taxonomy_index')
->fields(array(
  'nid',
  'tid',
  'status',
  'sticky',
  'created',
))
->values(array(
  'nid' => '1',
  'tid' => '1',
  'status' => '1',
  'sticky' => '0',
  'created' => '1439419364',
))
->execute();

$connection->insert('taxonomy_term_data')
->fields(array(
  'tid',
  'vid',
  'uuid',
  'langcode',
))
->values(array(
  'tid' => '1',
  'vid' => 'tags',
  'uuid' => 'ffa69efc-3690-4714-b200-e288ad802580',
  'langcode' => 'en',
))
->execute();

$connection->insert('taxonomy_term_field_data')
->fields(array(
  'tid',
  'vid',
  'langcode',
  'name',
  'description__value',
  'description__format',
  'weight',
  'changed',
  'default_langcode',
))
->values(array(
  'tid' => '1',
  'vid' => 'tags',
  'langcode' => 'en',
  'name' => 'Test tag',
  'description__value' => NULL,
  'description__format' => NULL,
  'weight' => '0',
  'changed' => '1439419375',
  'default_langcode' => '1',
))
->execute();

$connection->insert('taxonomy_term_hierarchy')
  ->fields(array(
    'tid',
    'parent',
  ))
  ->values(array(
    'tid' => '1',
    'parent' => '0',
  ))
  ->execute();

// Add a file.
$connection->insert('file_managed')
  ->fields(array(
    'fid',
    'uuid',
    'langcode',
    'uid',
    'filename',
    'uri',
    'filemime',
    'filesize',
    'status',
    'created',
    'changed',
  ))
  ->values(array(
    'fid' => 1,
    'uuid' => '99216d61-a7dc-4a44-bd00-cf0c79b99699',
    'langcode' => 'en',
    'uid' => 1,
    'filename' => 'yinyang.png',
    'uri' => 'public://pictures/yinyang.png',
    'filemime' => 'image/png',
    'filesize' => 6727,
    'status' => 1,
    'created' => 1439581402,
    'changed' => 1439581405,
  ))
  ->execute();
