<?php

/**
 * @file
 * Blocks comments from anonymous users that contain links.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\filter\Plugin\Filter\FilterUrl;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function blockanonymouslinks_form_comment_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  $form['#validate'][] = 'blockanonymouslinks_comment_validate';
}

/**
 * Check the comment for any link, if submitted anonymously.
 *
 * @see \Drupal\comment\CommentForm::validate()
 * @see _filter_url()
 */
function blockanonymouslinks_comment_validate($form, FormStateInterface $form_state) {
  if (\Drupal::currentUser()->isAnonymous()) {
    $filter = new FilterUrl(array(), 'filter_url', NULL);
    $raw_comment = $form_state->getValue('comment_body')[0]['value'];
    $filtered_comment = $filter->process($raw_comment, '')->getProcessedText();

    if ($raw_comment !== $filtered_comment) {
      $form_state->setErrorByName('comment_body', t('You have to be logged in to post links. This is an anti-spam measure.'));
    }
  }
}
