<?php

/**
 * @file
 * This is the module to implement perfect scrollbar JS Library integration
 */

function perfect_scrollbar_preprocess_page(&$var) {
  $config = \Drupal::service('config.factory')->getEditable('perfect_scrollbar.settings');
  $variables = array();
  $perfect_scrollbar =  $config->get('perfect_scrollbar');
  $settings =  $config->get('perfect_scrollbar_settings');
  $scrollbar_attributes = explode(',', $settings);
  $counter = 0;
  foreach($scrollbar_attributes as  $attributes) {
    $scroll_attribute = explode('|', rtrim(ltrim($attributes,'{'),'}'));
    foreach($scroll_attribute as $v) {
      $value = explode(':', $v);
      $scroll_attributes[$counter][$value[0]] = $value[1];
      ($value[0] == 'class')? $classes[] = $value[1] : (($value[0] == 'id')? $id[] = $value[1] : 1);
    }
    $counter++;
  }
  $variables = array(
    'perfect_scrollbar_status' => $perfect_scrollbar,
    'perfect_scrollbar_classes' => $classes,
    'perfect_scrollbar_ids' => $id,
    'perfect_scrollbar' => $scroll_attributes
    );
  $var['#attached']['library'][] = 'perfect_scrollbar/perfect_scrollbar';
  $var['#attached']['library'][] = 'perfect_scrollbar/add_perfect_scrollbar';
  $var['#attached']['drupalSettings']['perfect_scrollbar_setting'] = $variables;
}
