<?php

/**
 * Implements hook_theme().
 */
function dut_views_theme($existing, $type, $theme, $path) {
  $theme_suggestions_path = implode('/', [
    $path, 'templates', 'views-view-theme-suggestions'
  ]);
  return [
    'views_view_theme_suggestions' => [
      'path' => $theme_suggestions_path,
      'variables' => [
        'suggestions' => []
      ],
    ],
    'views_view_theme_suggestions_important' => [
      'path' => $theme_suggestions_path,
      'variables' => [],
    ],
    'views_view_theme_suggestions_important_new_id' => [
      'path' => $theme_suggestions_path,
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function dut_views_theme_suggestions_views_view(array $variables) {
  $original_hook_theme = $variables['theme_hook_original'];
  $suggestions = $variables['theme_hook_suggestions'];
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  if (empty($suggestions)) {
    $suggestions = $view->buildThemeFunctions($original_hook_theme);
    $index = array_search($original_hook_theme, $suggestions);
    if ($index !== FALSE) {
      unset($suggestions[$index]);
    }

    $suggestions = array_reverse($suggestions);
  }

  return $suggestions;
}
