<?php

/**
 * @file
 * Install, update and uninstall functions for the smartlook_tracking module.
 */

/**
 * Updating configuration.
 */
function smartlook_tracking_update_8001() {
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('smartlook_tracking.settings');
  $config->set('visibility.request_path_mode', 0);
  $config->set('visibility.request_path_pages', '/admin
/admin/*
/batch
/node/add*
/node/*/*
/user/*/*');
  $config->save(TRUE);
}

