<?php

/**
 * @file
 * Contains hooks functions for node_view_published_override.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_node_access().
 */
function node_view_published_override_node_access(NodeInterface $node, $op, AccountInterface $account) {
  // Override view published permissions provided by core.
  if ($op == 'view') {
    if ($node->isPublished() && $account->hasPermission('access content')) {
      if ($account->hasPermission('view any published ' . $node->getType() . ' content')) {
        return AccessResult::allowed();
      }
      elseif ($account->hasPermission('view own published ' . $node->getType() . ' content') && $node->getOwnerId() == $account->id()) {
        return AccessResult::allowed();
      }
      else {
        return AccessResult::forbidden();
      }
    }
  }
}
