<?php

/**
 * @file
 * Story Chief module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view() for node entities.
 *
 * @param array $build
 * @param EntityInterface $node
 * @param EntityViewDisplayInterface $display
 * @param $view_mode
 */
function storychief_node_view(array &$build, EntityInterface $node, EntityViewDisplayInterface $display, $view_mode) {
	$config = \Drupal::config('storychief.settings');
	$node_type = $config->get('node_type');
	if ($view_mode == 'full' && !empty($node_type) && $node->getType() == $node_type) {
		$database = \Drupal\Core\Database\Database::getConnection();
		$result = $database
			->query("SELECT render_key, render_array FROM {storychief_meta_tags} WHERE nid = :nid AND langcode = :langcode AND render_key != 'title'", [
				':nid'      => $node->id(),
				':langcode' => $node->language()->getId(),
			])
			->fetchAll();

		foreach ($result as $meta) {
			$render_key = $meta->render_key;
			$render_array = json_decode($meta->render_array, true);
			$build['#attached']['html_head'][] = [$render_array, $render_key];
		}
	}
}


/**
 * Implements hook_preprocess_node().
 *
 * Overwrite title with seo title
 */
function storychief_preprocess_html(&$vars) {
	// Load the node entity from current route
	if ($node = \Drupal::routeMatch()->getParameter('node')) {
		$config = \Drupal::config('storychief.settings');
		$node_type = $config->get('node_type');

		if (!empty($node_type) && is_object($node) && $node->getType() == $node_type) {
			$database = \Drupal\Core\Database\Database::getConnection();
			$result = $database
				->query("SELECT render_key, render_array FROM {storychief_meta_tags} WHERE nid = :nid AND langcode = :langcode AND render_key = 'title'", [
					':nid'      => $node->id(),
					':langcode' => $node->language()->getId(),
				])
				->fetch();

			if ($result) {
				$site_config = \Drupal::config('system.site');
				$render_array = json_decode($result->render_array, true);
				$head_title = array(
					// Marking the title as safe since it has had the tags stripped.
					'title' => $render_array['content']['#plain_text'],
					'name'  => $site_config->get('name'),
				);
				$vars['head_title'] = $head_title;
			}
		}
	}
}