<?php
function instawidget_preprocess_page(array &$page) {
    $config = \Drupal::config('config.instawidget_settingsconfig');
    $config_token = \Drupal::config('config.instawidget_tokensettingsconfig');
    $page['#attached']['drupalSettings']['userid'] = $config->get('insta_user_id');
    $page['#attached']['drupalSettings']['access_token_string'] = $config_token->get('access_token_string');
}

/**
 * Hook_theme.
 */
function instawidget_theme($existing, $type, $theme, $path) {
    return array(
      'instawidget' =>
      array(
        'variables' => array(
            'data' => NULL,
        ),
      )
    );
}