<?php

/**
 * @file
 * Contains cielo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cielo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cielo module.
    case 'help.page.cielo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Cielo Integration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function cielo_theme() {
  return [
    'cielo' => [
      'render element' => 'children',
    ],
  ];
}
