<?php

/**
 * @file
 * Main behat_ui file.
 */

use Behat\Testwork\ServiceContainer\Configuration\ConfigurationLoader;

/**
 * Given a form_state, return a Behat scenario.
 */
function _behat_ui_generate_scenario($form_state) {
  $scenario = "@api";
  if ($form_state['values']['behat_ui_javascript']) {
    $scenario .= " @javascript";
  }
  $title = $form_state['values']['behat_ui_title'];
  $scenario .= "\nScenario: $title\n";

  $steps_count = count($form_state['values']['behat_ui_steps']);

  for ($i = 0; $i < $steps_count; $i++) {
    $type = $form_state['values']['behat_ui_steps'][$i]['type'];
    $step = $form_state['values']['behat_ui_steps'][$i]['step'];

    if (!empty($type) && !empty($step)) {
      // Blocks.
      $step = preg_replace('/\n\|/', "\n  |", preg_replace('/([:\|])\|/', "$1\n|", $step));
      $scenario .= "  $type $step\n";
    }
  }

  return $scenario;
}

/**
 * Behat UI get behat bin path.
 */
function _behat_ui_get_behat_bin_path() {
  return preg_replace('/[ ;&|,]/', '', \Drupal::config('behat_ui.settings')->get('behat_ui_behat_bin_path'));
}

/**
 * Behat UI get behat config path.
 */
function _behat_ui_get_behat_config_path() {
  return preg_replace('/[ ;&|,]/', '', \Drupal::config('behat_ui.settings')->get('behat_ui_behat_config_path'));
}

/**
 * Run a single test.
 */
function _behat_ui_run_single_test($form, &$form_state) {
  global $user, $base_root;

  $behat_bin = _behat_ui_get_behat_bin_path();
  $behat_config = _behat_ui_get_behat_config_path();

  // Write to temporary file.
  $file_user_time = 'user-' . $user->uid . '-' . date('Y-m-d_h-m-s');
  $file = $behat_config . '/features/tmp/' . $file_user_time . '.feature';
  $feature = $form_state['values']['behat_ui_feature'];
  $test = "Feature: $feature\n  In order to test \"$feature\"\n\n";
  $test .= _behat_ui_generate_scenario($form_state);
  $handle = fopen($file, 'w+');
  fwrite($handle, $test);
  fclose($handle);

  // Run file.
  $report_dir = $behat_config . '/reports/report-' . $file_user_time;
  $output = shell_exec("cd $behat_config; $behat_bin $file --format html --out $report_dir");

  $report_html_file_name_and_path = $report_dir . '/index.html';

  $report_html_handle = fopen($report_html_file_name_and_path, 'r');
  $report_html = fread($report_html_handle, filesize($report_html_file_name_and_path));
  fclose($report_html_handle);

  $output .= $report_html;

  unlink($file);
  return '<div id="behat-ui-output-inner">' . $output . '</div>';
}

/**
 * Behat Ui add step AJAX.
 */
function behat_ui_ajax_add_step($form, $form_state) {
  return $form['behat_ui_new_scenario']['behat_ui_steps'];
}


/**
 * Get available steps.
 */
function _behat_ui_steps() {
//  if ($cache = \Drupal::cache()->get('behat_ui_steps')) {
//    return $cache->data;
//  }

  $behat_bin = _behat_ui_get_behat_bin_path();
  $behat_config_path = _behat_ui_get_behat_config_path();

  global $base_root;
  $cmd = "cd $behat_config_path; $behat_bin -dl | sed 's/^\s*//g' | sort";
  $output = shell_exec($cmd);
  $output = nl2br(htmlentities($output));
//  \Drupal::cache('cache')->set('behat_ui_steps', $output);
  return $output;
}

/**
 * Get existing features.
 */
function _behat_ui_features() {
  $behat_config_path = \Drupal::config('behat_ui.settings')->get('behat_ui_behat_config_path');
  $features_path = 'features';

  // Attempt to load the config with Composer library first.
  $behat_config = load_behat_config();

  $features = array();

  if ($handle = opendir($behat_config_path . '/' . $features_path)) {
    while (FALSE !== ($file = readdir($handle))) {
      if (preg_match('/\.feature$/', $file)) {
        $feature = preg_replace('/\.feature$/', '', $file);
        $name = ucfirst(str_replace('_', ' ', $feature));
        $features[$feature] = $name;
      }
    }
  }
  return $features;
}

/**
 * Helper function to check if a process with given PID is running or not.
 *
 * @param $pid
 *
 * @return bool
 */
function behat_ui_process_running($pid) {
  $isRunning = FALSE;
//  if(strncasecmp(PHP_OS, "win", 3) == 0) {
//    $out = [];
//    exec("TASKLIST /FO LIST /FI \"PID eq $pid\"", $out);
//    if(count($out) > 1) {
//      $isRunning = TRUE;
//    }
//  }
  if (posix_kill(intval($pid), 0)) {
    $isRunning = TRUE;
  }
  return $isRunning;
}

/**
 * Load Behat Config.
 *
 * Adding support for the Symfony yaml parser so everything can be setup
 * through Composer.
 *
 * @return array
 *   Behat config.
 */
function load_behat_config() {

  $behat_config = array();

  $config = \Drupal::config('behat_ui.settings');

  $behat_bin = $config->get('behat_bin_path');
  $behat_config_path = $config->get('behat_config_path');

  try {
    if (is_file($autoload = $behat_config_path . '/vendor/autoload.php')) {
      require $autoload;
    }
    else {

      $error_message = t('You must set up the project dependencies, run the following commands:') . PHP_EOL .
          'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
          'php composer.phar install' . PHP_EOL;

      drupal_set_message($error_message, 'error');
      \Drupal::logger('behat_ui')->notice($error_message, []);
    }

    $behat_config_factory = new ConfigurationLoader();
    $behat_config_factory->setConfigurationFilePath($behat_config_path . '/behat.yml');
    $behat_config = $behat_config_factory->loadConfiguration();

  }
  catch (ParseException $e) {
    drupal_set_message(t('Extension yaml is not loaded. Could not parse behat.yml file.'), 'error');
    $watchdog_message = t('Could not parse Behat config file, check Composer libraries, file permissions and Behat config: Error = @error', array('@error' => $e));
    \Drupal::logger('behat_ui')->notice($watchdog_message, []);
  }
  return ($behat_config);
}
