<?php

/**
 * @file
 * Contains pagedesigner_layout.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pagedesigner_layout_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pagedesigner_layout module.
    case 'help.page.pagedesigner_layout':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pagedesigner layout extension') . '</p>';
      return $output;
    default:
  }
}
