<?php

/**
 * @file
 * Contains reference_map.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function reference_map_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the reference_map module.
    case 'help.page.reference_map':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("Defines complex relationships between entities based on entity reference fields. This module provides a default type that simply defines the relationship between two entities.\n\nThis module provides no functionality for using the map. The map must be implemented in code.") . '</p>';
      return $output;

    default:
  }
}
