<?php

/**
 * Implements hook_theme().
 */
function geolocation_2gis_theme($existing, $type, $theme, $path)
{
  return [
    'geolocation_2gis_map' => [
      'variables' => [
        'locations' => []
      ]
    ],
    'geolocation_2gis_map_formatter' => [
      'variables' => [
        'locations' => []
      ]
    ],
    'geolocation_2gis_latlng_formatter' => [
      'variables' => [
        'lat' => '',
        'lng' => ''
      ]
    ],
  ];
}
