<?php

/**
 * @file
 * Functions and hooks for FullCalendar API module.
 */

/**
 * Implements hook_theme().
 */
function fullcalendar_api_theme($existing, $type, $theme, $path) {
  return array(
    'fullcalendar_calendar' => array(
      'template' => 'fullcalendar',
      'variables' => array(
        'calendar_id' => NULL,
        'calendar_settings' => array(NULL),
      ),
    ),
    'fullcalendar_calendar_datasource' => array(
      'file' => 'theme.inc',
      'path' => "$path/theme",
      'variables' => array(
        'datasource_uri' => NULL,
        'calendar_id' => NULL,
        'calendar_settings' => array(NULL),
      ),
    ),
    'fullcalendar_calendar_entity' => array(
      'file' => 'theme.inc',
      'path' => "$path/theme",
      'variables' => array(
        'entities' => array(NULL),
        'date_field_map' => array(NULL),
        'calendar_id' => NULL,
        'calendar_settings' => array(NULL),
      ),
    ),
  );
}

/**
 * Prepares variables for fullcalendar_calendar.
 *
 * Default template: fullcalendar.html.twig.
 *
 * @params array $vars
 *   an associative array containing:
 *   - calendar_id: string the CSS id of the calendar DOM object
 *   - calendar_settings: array of settings to override FullCalendar.js defaults
 */
function template_preprocess_fullcalendar_calendar(&$vars) {
  $calendar_id = $vars['calendar_id'];
  $user_settings = $vars['calendar_settings'];

  // Default settings.
  $settings = array(  
    'header' => array(
      'left' => 'month,agendaWeek',
      'right' => 'prev title next',
    ),
    'defaultDate' => date('Y-m-d'),
    'businessHours' => TRUE,
    'editable' => TRUE,
    'events' => array(),
  );

  // Override defaults with user submitted data.
  $settings = array_replace_recursive($settings, $user_settings);

  // Have to make sure that html id and id in settings are identical.
  $calendar_id = \Drupal\Component\Utility\Html::getId($calendar_id);

  $vars['#attached']['library'][] = 'fullcalendar_api/fullcalendar_load';
  $vars['#attached']['drupalSettings']['fullcalendar_api']['instances'][$calendar_id] = $settings;
}
