<?php

/**
 * @file
 * Contains image_format_cover.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function image_format_cover_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the image_format_cover module.
    case 'help.page.image_format_cover':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module for a "cover" image format') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function image_format_cover_theme($existing, $type, $theme, $path) {
  return [
    'image_cover_summary' => [
      'variables' => ['data' => NULL, 'effect' => []],
    ],
  ];
}
