<?php

use Drupal\Core\Entity\ContentEntityFormInterface;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * @file
 * Creates a button on node form that allows to create a node and translate it.
 */

/**
 * Implements hook_form_alter().
 */
function create_and_translate_form_alter(&$form, FormStateInterface $form_state) {
  $current_path = \Drupal::service('path.current')->getPath();
  $route_name = Url::fromUserInput($current_path)->getRouteName();

  $route_names = [
    'node.add',
    'entity.node.edit_form',
    'entity.node.content_translation_add',
  ];

  if (isset($route_name) && in_array($route_name, $route_names)) {
    $form_object = $form_state->getFormObject();
    if (!($form_object instanceof ContentEntityFormInterface)) {
      return;
    }

    $entity = $form_object->getEntity();

    if ($entity instanceof ContentEntityInterface && $entity->isTranslatable()) {
      $form['actions']['create_and_translate'] = $form['actions']['submit'];
      $form['actions']['create_and_translate']['#value'] = t('Save and translate');
      $form['actions']['create_and_translate']['#submit'][] = 'create_and_translate_submit';
    }
  }

}

/**
 * Submit callback to set the redirect.
 *
 * @param array $form
 * @param $form_state
 */
function create_and_translate_submit(array &$form, FormStateInterface $form_state) {
  $trigger = $form_state->getTriggeringElement();

  if (isset($trigger['#id']) && $trigger['#id'] == 'edit-create-and-translate') {
    $nid = $form_state->getValue('nid');

    if (isset($nid)) {
      $form_state->setRedirectUrl(Url::fromUri('internal:/node/' . $nid . '/translations'));
    }
  }

}
