<?php

/**
 * @file
 * Contains build_hooks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function build_hooks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the build_hooks module.
    case 'help.page.build_hooks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Build Hooks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function build_hooks_cron() {
  // Deploy all environments marked for cron deployment:
  build_hooks_get_trigger_service()->deployFrontendCronEnvironments();
}

/**
 * Implements hook_entity_update().
 */
function build_hooks_entity_update(EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface) {
    if (!$entity->isNew() && build_hooks_get_logger_service()->isEntityTypeLoggable($entity)) {
      build_hooks_get_logger_service()->logEntityUpdated($entity);
      build_hooks_get_trigger_service()->deployFrontendEntityUpdateEnvironments();
      build_hooks_get_trigger_service()->invalidateToolbarCacheTag();
    }
  }
}

/**
 * Implements hook_entity_insert().
 */
function build_hooks_entity_insert(EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface) {
    if (build_hooks_get_logger_service()->isEntityTypeLoggable($entity)) {
      build_hooks_get_logger_service()->logEntityCreated($entity);
      build_hooks_get_trigger_service()->deployFrontendEntityUpdateEnvironments();
      build_hooks_get_trigger_service()->invalidateToolbarCacheTag();
    }
  }
}

/**
 * Implements hook_entity_delete().
 */
function build_hooks_entity_delete(EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface) {
    if (build_hooks_get_logger_service()->isEntityTypeLoggable($entity)) {
      build_hooks_get_logger_service()->logEntityDeleted($entity);
      build_hooks_get_trigger_service()->deployFrontendEntityUpdateEnvironments();
      build_hooks_get_trigger_service()->invalidateToolbarCacheTag();
    }
  }
}

/**
 * Implements hook_toolbar().
 */
function build_hooks_toolbar() {
  $items = [];
  if (build_hooks_get_trigger_service()->showMenu()) {
    /** @var \Drupal\Core\Entity\EntityTypeManager $entityTypeManager */
    $entityTypeManager = \Drupal::service('entity_type.manager');
    // Load all defined environments:
    $allEnvironments = $entityTypeManager->getStorage('frontend_environment')
      ->loadMultiple();

    if (!empty($allEnvironments)) {
      $items = [];
      foreach ($allEnvironments as $environment) {
        /** @var \Drupal\build_hooks\Entity\FrontendEnvironment $environment */
        $items[$environment->id()] = [
          '#cache' => [
            'tags' => [build_hooks_get_trigger_service()->getToolbarCacheTag()],
            'contexts' => ['user.permissions'],
          ],
          '#weight' => $environment->getWeight() + 999,
          '#type' => 'toolbar_item',
          'tab' => [
            '#type' => 'link',
            '#title' => t('Env: @envName (@num changes)', [
              '@envName' => $environment->label(),
              '@num' => build_hooks_get_logger_service()->getNumberOfItemsSinceLastDeploymentForEnvironment($environment),
            ]),
            '#url' => Url::fromRoute('build_hooks.deployment_form', ['frontend_environment' => $environment->id()]),
          ],
        ];
      }
    }
  }
  return $items;
}

/**
 * Implements hook_toolbar_alter().
 */
function build_hooks_toolbar_alter(&$items) {
  // Not that great, but it works:
  // We add our own cache tag to the home element of the toolbar
  // which we can be sure is always there.
  $items['home']['#cache'] = [
    'tags' => ['config:frontend_environment_list', build_hooks_get_trigger_service()->getToolbarCacheTag()],
  ];
}

/**
 * Get the trigger service.
 *
 * @return \Drupal\build_hooks\Trigger
 *   The trigger service.
 */
function build_hooks_get_trigger_service() {
  return \Drupal::service('build_hooks.trigger');
}

/**
 * Get the deploy logger service.
 *
 * @return \Drupal\build_hooks\DeployLogger
 *   The deploy logger service.
 */
function build_hooks_get_logger_service() {
  return \Drupal::service('build_hooks.deploylogger');
}
