<?php

/**
 * @file
 * Youtube API module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 *
 * Display help page.
 */
function youtubeapi_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.youtubeapi') {

    $current_url = Url::fromRoute('<current>');
    if (strstr($current_url->toString(), '/admin/help/youtubeapi') === FALSE) {
      return TRUE;
    }

    $output = '';
    $output .= '<h3>About</h3>';
    $output .= '<p>Youtubeapi is a toolkit for the developers, help to use google youtube api V3.</p>';

    return $output;
  }
}
