<?php
/*
 *
 * make drupal knows the templates are located in the module
 *
 * */
function monetization_placements_theme(&$variables) {
    $theme['block__block_content__zan_placement_block'] = [
        'template' => 'block--block-content--monetization-placement-block',
        'base hook' => 'block',
    ];
    $theme['zan__demo_page__theme'] = [
        'template' => 'zan--demo-page--theme',
    ];
    return $theme;
}

function monetization_placements_form_alter(&$form, $form_state, $form_id) {
    if ($form_id == 'block_content_monetization_placement_block_edit_form' || $form_id == 'block_content_monetization_placement_block_form') {
      
       // die();
    }
    return;
}