/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/"use strict";

(function (wp, Drupal) {
  var components = wp.components,
      editPost = wp.editPost;
  var Fragment = wp.element.Fragment;
  var PanelBody = components.PanelBody;
  var PluginSidebar = editPost.PluginSidebar,
      PluginSidebarMoreMenuItem = editPost.PluginSidebarMoreMenuItem;


  function AdditionalFieldsPluginSidebar() {
    return React.createElement(
      Fragment,
      null,
      React.createElement(
        PluginSidebarMoreMenuItem,
        {
          target: "gutenberg-boilerplate-sidebar" },
        "Gutenberg Boilerplate"
      ),
      React.createElement(
        PluginSidebar,
        {
          name: "additional-fields",
          title: "Additional fields",
          icons: "forms",
          isPinnable: "false"
        },
        React.createElement(PanelBody, null)
      )
    );
  }

  window.DrupalGutenberg = window.DrupalGutenberg || {};
  window.DrupalGutenberg.Plugins = window.DrupalGutenberg.Plugins || {};
  window.DrupalGutenberg.Plugins.AdditionalFieldsPluginSidebar = AdditionalFieldsPluginSidebar;
})(wp, Drupal);