<?php

/**
 * @file
 * Contains workflow_moderation.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\workflow_moderation\EntityOperations;

/**
 * Implements hook_entity_presave().
 */
function workflow_moderation_entity_presave(EntityInterface $entity) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EntityOperations::class)
    ->entityPresave($entity);
  
}

/**
 * Implements hook_entity_insert().
 */
function workflow_moderation_entity_insert(EntityInterface $entity) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EntityOperations::class)
    ->entityInsert($entity);

}

/**
 * Implements hook_node_update().
 */
function workflow_moderation_entity_update(EntityInterface $entity) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EntityOperations::class)
    ->entityUpdate($entity);

}

/**
 * Implements hook_theme().
 */
function workflow_moderation_theme() {
  $theme = [];
  $theme['entity_latest_revision'] = [
    'render element'    => 'element',
    'variables'         => ['latest_revision_view' => ''],
  ];
  return $theme;

}
