<?php


/**
 * Implements hook_preprocess_HOOK().
 */
function calltracking_preprocess_page(&$variables) {
  $utms = [];
  $route = \Drupal::routeMatch()->getRouteName();
  $config = \Drupal::config('calltracking.settings');
  $values = $config->get('fields');

  // Each all UTM labels.
  foreach ($values as $value) {
    $name = $value['key'];
    $source = $value['val'];
    $from = $value['from'];
    $to = $value['to'];

    $utms[$name][$source][$from] = $to;
  }

  // Add libraries.
  $variables['#attached']['library'][] = 'calltracking/main';
  $variables['#attached']['drupalSettings']['telephones'] = $utms;
  if ($route == 'calltracking.admin_settings') {
    $variables['#attached']['library'][] = 'calltracking/forms';
  }
}

