<?php

/**
 * @file
 * Metatag: Head title module file.
 */

/**
 * Replace page HEAD title with head_title metatag value.
 *
 * Implements template_preprocess_html().
 */
function metatag_head_title_preprocess_html(&$variables) {
  if (!metatag_is_current_route_supported()) {
    return NULL;
  }

  $attachments = &drupal_static('metatag_attachments');
  if (is_null($attachments)) {
    $attachments = metatag_get_tags_from_route();
  }

  if (!$attachments) {
    return NULL;
  }

  // Load the page HEAD title.
  if (!empty($attachments['#attached']['html_head'])) {
    foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
      if (!empty($attachment[1]) && $attachment[1] == 'head_title') {
        // It's safe to access the value directly because it was already
        // processed in MetatagManager::generateElements().
        $variables['head_title_array'] = [];
        // Empty head_title to avoid the site name and slogan to be appended to
        // the meta title.
        $variables['head_title'] = [];
        $variables['head_title']['title'] = html_entity_decode($attachment[0]['#attributes']['content'], ENT_QUOTES);
      }
    }
  }

  if (isset($variables['page']['#attached']['html_head'])) {
    foreach ($variables['page']['#attached']['html_head'] as $key => $attachment) {
      if (!empty($attachment[1]) && $attachment[1] == 'head_title') {
        // Do not display virtual head_title tag.
        unset($variables['page']['#attached']['html_head'][$key]);
      }
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function metatag_head_title_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'preprocess_html') {
    // Disable metatag_preprocess_html(). We replaced it with
    // metatag_head_title_preprocess_html().
    if (isset($implementations['metatag'])) {
      unset($implementations['metatag']);
    }
  }
}
