<?php

/**
 * Implements hook_entity_type_alter().
 * Extends the menu form so that it only allows content menu items reordering in
 * case read-only mode is on.
 */
function config_readonly_menu_ui_entity_type_alter(array &$entity_types) {
  // We change the form even if readonly is off, because it's cached. We want
  // to alter the form if readonly is switched on, even if it was off on last
  // cache clear.

  // See menu_ui_entity_type_build().
  $entity_types['menu']
    ->setFormClass('add', 'Drupal\config_readonly_menu_ui\ContentMenuForm')
    ->setFormClass('edit', 'Drupal\config_readonly_menu_ui\ContentMenuForm');
}

/**
 * Implements hook_config_readonly_whitelist_patterns().
 */
function config_readonly_menu_ui_config_readonly_whitelist_patterns() {
  return [
    'system.menu.*',
  ];
}
