<?php

/**
 * @file
 * Contains react_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function react_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the react_block module.
    case 'help.page.react_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create blocks for React components.') . '</p>';
      return $output;

    default:
  }
}
