<?php

/**
 * @file
 * Contains lightspeed_ecom.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lightspeed_ecom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.lightspeed_ecom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrate with the Lightspeed eCom platform') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_modules_installed().
 */
function lightspeed_ecom_modules_installed() {
  /** @var \Drupal\Core\Entity\EntityTypeManagerInterface $entityTypeManager */
  $entityTypeManager = Drupal::service('entity_type.manager');
  /** @var \Drupal\lightspeed_ecom\Service\WebhookRegistry $webhook_registry */
  $webhook_registry = Drupal::service('lightspeed.ecom.webhook_registry');
  /** @var \Drupal\Core\Entity\EntityStorageInterface */
  $entityStorage = $entityTypeManager->getStorage('lightspeed_ecom_shop');
  /** @var \Drupal\lightspeed_ecom\ShopInterface $shop */
  foreach ($entityStorage->loadMultiple() as $shop) {
    $webhook_registry->synchronize($shop);
  }
}

/**
 * Implements hook_modules_uninstalled().
 */
function lightspeed_ecom_modules_uninstalled() {
  /** @var \Drupal\Core\Entity\EntityTypeManagerInterface $entityTypeManager */
  $entityTypeManager = Drupal::service('entity_type.manager');
  /** @var \Drupal\lightspeed_ecom\Service\WebhookRegistry $webhook_registry */
  $webhook_registry = Drupal::service('lightspeed.ecom.webhook_registry');
  /** @var \Drupal\Core\Entity\EntityStorageInterface */
  $entityStorage = $entityTypeManager->getStorage('lightspeed_ecom_shop');
  /** @var \Drupal\lightspeed_ecom\ShopInterface $shop */
  foreach ($entityStorage->loadMultiple() as $shop) {
    $webhook_registry->synchronize($shop);
  }
}
