<?php

/**
 * @file akismet_test.module: Main module file for hooks related to testing
 * Akismet.
 */

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_akismet_form_list().
 */
function akismet_test_akismet_form_list() {
  $forms['akismet_test_post_form'] = array(
    'title' => 'Akismet test form',
    'entity' => 'akismet_test_post',
    'moderation callback' => 'akismet_test_akismet_form_moderation',
    'delete form' => 'akismet_test_delete_form',
  );
  // The basic test form is identical to the akismet_test_form, but only
  // registers minimal information (e.g., no entity or moderation callback) to
  // integrate with Akismet.
  $forms['akismet_basic_test_form'] = array(
    'title' => 'Akismet basic test form',
  );
  // Same as above, but supports elements for text analysis.
  $forms['akismet_basic_elements_test_form'] = array(
    'title' => 'Akismet basic elements test form',
  );
  // Same as akismet_test_form, but supports an entity delete callback.
  $forms['akismet_entity_test_form'] = array(
    'title' => 'Akismet entity test form',
    'entity' => 'akismet_test_post',
    'entity delete callback' => 'akismet_test_delete',
  );
  return $forms;
}

/**
 * Implements hook_akismet_form_info().
 */
function akismet_test_akismet_form_info($form_id) {
  if ($form_id == 'akismet_basic_test_form') {
    return array();
  }
  $form_info = array(
    'bypass access' => array('administer akismet'),
    'elements' => array(
      'title' => 'Title',
      'body' => 'Body',
      'exclude' => 'Some other field',
      'parent][child' => 'Nested element',
      'field' => 'Multiple value field',
    ),
    'mapping' => array(
      'post_id' => 'mid',
      'post_title' => 'title',
      'author_name' => 'name',
    ),
  );
  return $form_info;
}

/**
 * Implements hook_form_alter().
 */
function akismet_test_form_alter(array &$form, FormStateInterface $form_state) {
  if (\Drupal::state()->get('akismet_test.disable_akismet', FALSE)) {
    $form['#akismet'] = ['require_analysis' => FALSE, 'require_captcha' => FALSE];
  }
}

/**
 * Akismet form moderation callback for a akismet_test record.
 */
function akismet_test_akismet_form_moderation(array &$form, FormStateInterface $form_state) {
  $form_state->setValue('status', 0);
}

/**
 * Deletes a {akismet_test} data record.
 *
 * @param int $mid
 *   The mid to delete.
 */
function akismet_test_delete($mid) {
  $record = \Drupal::entityManager()->getStorage('akismet_test_post')->load($mid);
  if (!empty($record)) {
    \Drupal::moduleHandler()->invokeAll('entity_delete', array($record, 'akismet_test'));
    $record->delete();
  }
}
