<?php

/**
 * @file
 * Contains install and update functions for Front-End Administration - Menu.
 */

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_install().
 */
function feadmin_menu_install() {
  // Because the Menu module upon installation unconditionally overrides all
  // HTML output by selecting a different page display variant, we must
  // invalidate all cached HTML output.
  Cache::invalidateTags(['rendered']);
}