<?php

/**
 * @file
 * Contains membership_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function membership_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the membership_entity module.
    case 'help.page.membership_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create and manage memberships.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_toolbar_alter().
 */
function membership_entity_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'membership_entity/toolbar';
}

/**
 * Implements hook_theme().
 */
function membership_entity_theme() {
  $theme = [];
  $theme['membership_entity'] = [
    'render element' => 'children',
  ];
  $theme['membership_entity'] = [
    'render element' => 'elements',
    'file' => 'membership_entity.page.inc',
    'template' => 'membership_entity',
  ];
  $theme['membership_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'membership_entity.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function membership_entity_theme_suggestions_membership_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#membership_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'membership_entity__' . $sanitized_view_mode;
  $suggestions[] = 'membership_entity__' . $entity->bundle();
  $suggestions[] = 'membership_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'membership_entity__' . $entity->id();
  $suggestions[] = 'membership_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
