<?php

/**
 * @file
 * Contains sceditor.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sceditor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sceditor module.
    case 'help.page.sceditor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to edit source code online for development.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sceditor_theme() {
  return [
    'sceditor_directories' => [
      'variables' => [
        'links' => NULL,
      ],
    ],
    'sceditor' => [
      'variables' => [
        'ext' => NULL,
        'data' => NULL,
        'path' => NULL,
        'return' => NULL,
      ],
    ],
  ];
}
