<?php

/**
 * @file
 * Provides an API for managing entity permissions.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_permission_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.entity_permission':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides an API for managing entity permissions.') . '</p>';
      return $output;
  }
}
