query ($path: String!) {
  route(path: $path) {
    node: entity {
      entityLabel
      ... on NodeTest {
        testAddress {
          countryCode
          contact
          phone
          province {
            ...Subdivision
          }
          city {
            ...Subdivision
          }
          district {
            ...Subdivision
          }
          postCode
          streetAddress
        }
      }
    }
  }
}

fragment Subdivision on AddressSubdivision {
  code
  name
  hasChildren
}
