query addressSubdivisions($parents: [String!] = ["CN"]) {
  addressSubdivisions (parents: $parents) {
    ...Subdivision
  }
}

fragment Subdivision on AddressSubdivision {
  code
  name
  hasChildren
}
