<?php

/**
 * @file
 * Module file of the Translation Management Capita module.
 */

use Drupal\tmgmt\Entity\Job;
use Drupal\tmgmt\JobInterface;
use Drupal\tmgmt\JobItemInterface;

/**
 * Implements hook_cron().
 */
function tmgmt_capita_cron() {
  // Get available Capita translators.
  $capita_translator_ids = \Drupal::entityQuery('tmgmt_translator')
    ->condition('plugin', 'capita')
    ->execute();
  if (empty($capita_translator_ids)) {
    return;
  }

  // Then fetch all active jobs using those translators.
  $job_ids = \Drupal::entityQuery('tmgmt_job')
    ->condition('translator', $capita_translator_ids, 'IN')
    ->condition('state', JobInterface::STATE_ACTIVE)
    ->execute();

  // Fetch translations for a job that have at least one active job item.
  foreach ($job_ids as $job_id) {
    $item_ids = \Drupal::entityQuery('tmgmt_job_item')
      ->condition('tjid', $job_id)
      ->condition('state', JobItemInterface::STATE_ACTIVE)
      ->sort('tjid', 'DESC')
      ->sort('tjiid', 'DESC')
      ->range(0, 1)
      ->execute();

    if ($item_ids) {
      $job = Job::load($job_id);
      $job->getTranslatorPlugin()->fetchTranslations($job);
    }
  }
}
