<?php

/**
 * @file
 * Main functions for "oil.js" module.
 */

use Drupal\Component\Serialization\Json;

/**
 * Implements hook_page_attachments().
 */
function oiljs_page_attachments(array &$attachments) {
  $config = \Drupal::config('oiljs.settings');
  if (empty($config->get('script_url'))) {
    // Script source is not configured properly.
    return;
  }

  // Check exclude paths.
  $path_match = FALSE;
  if (!empty($config->get('exclude_paths'))) {
    $path = Drupal::service('path.current')->getPath();
    $exclude_paths = $config->get('exclude_paths');
    \Drupal::moduleHandler()->alter('oiljs_path_match', $path_match, $path, $exclude_paths);
    $path_match = Drupal::service('path.matcher')->matchPath($path, $exclude_paths);
  }

  // Check if we need to hide the banner on admin theme.
  $admin_theme_match = FALSE;
  if ($config->get('exclude_admin_theme') && \Drupal::service('router.admin_context')->isAdminRoute()) {
    $admin_theme_match = TRUE;
  }

  $config_data = $config->get();

  // Allow other modules to alter the configuration data.
  \Drupal::moduleHandler()->alter('oiljs_configuration', $config_data);

  $banner_enabled = !isset($config_data['banner_enabled']) ? TRUE : $config_data['banner_enabled'];

  // Remove values from configuration object not necessary for oil.js.
  unset($config_data['_core']);
  unset($config_data['langcode']);
  unset($config_data['exclude_paths']);
  unset($config_data['exclude_admin_theme']);
  unset($config_data['banner_enabled']);

  if (!$banner_enabled || $admin_theme_match || $path_match) {
    // Do not display the banner.
    return;
  }

  // Add oil.js configuration.
  $attachments['#attached']['html_head'][] = [
    [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#attributes' => [
        'id' => 'oil-configuration',
        'type' => 'application/configuration',
      ],
      '#value' => Json::encode($config_data),
    ],
    'oiljs-configuration',
  ];
  // Add oil.js script.
  $attachments['#attached']['html_head'][] = [
    [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#attributes' => [
        'src' => $config->get('script_url'),
      ],
    ],
    'oiljs-src',
  ];
}
