<?php

/**
 * @file
 * Contains jquery_timepicker.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function jquery_timepicker_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jquery_timepicker module.
    case 'help.page.jquery_timepicker':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('jquery.timepicker polyfill') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 *
 * @param [type] $form
 * @param [type] $form_state
 * @param [type] $form_id
 * @return void
 */
function jquery_timepicker_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('jquery_timepicker.settings');
  $form['#attached']['library'][] = 'jquery_timepicker/polyfill';
  $form['#attached']['drupalSettings']['jquery_timepicker'] = $config->get();
}