<?php

use \Drupal\user\Entity\User;

/**
 * implements masquerade hook masquerade_access(),
 * whether the current user can masquerade as the target account
 *
 * @returns boolean
 */
function masquerade_nominate_masquerade_access($currentUser, $target_account) {
  $allowed_as = masquerade_nominate_masquerade_as($currentUser);
  return isset($allowed_as[$target_account->id()]);
}

/**
 * get the users which the given user can masquerade as
 * @returns AccountInterface[]
 */
function masquerade_nominate_masquerade_as($account) {
  return \Drupal::entityQuery('user')
    ->condition('masquerade_nominees', $account->id())
    ->execute();
}

