<?php

/**
 * @file
 * Module file for instagram_display.
 */

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * @defgroup instagram_display Example: Block
 * @ingroup examples
 * @{
 * Demonstrates code creation of blocks.
 *
 * This is an example outlining how a module can define blocks that can be
 * displayed on various pages of a site, or how to alter blocks provided by
 * other modules.
 */

/**
 * Implements hook_block_view_alter().
 *
 * This hook allows you to modify the output of any block in the system.
 *
 * In addition, instead of hook_block_view_alter(), which is called for all
 * blocks, you can also use hook_block_view_BASE_BLOCK_ID_alter() to alter a
 * specific block. To change only our block using
 * hook_block_view_BASE_BLOCK_ID_alter, we would use the function:
 * instagram_display_block_view_example_uppercase_alter()
 *
 * We are going to uppercase the subject (the title of the block as shown to the
 * user) of any block if the string "uppercase" appears in the block title or
 * subject. Default block titles are set programmatically in the subject key;
 * titles created through the UI are saved in the title key. This module creates
 * an example block to demonstrate this effect (default title set
 * programmatically as subject).  You can also demonstrate the effect of this
 * hook by creating a new block whose title has the string 'uppercase' in it
 * (set as title through the UI).
 */
function instagram_display_block_view_alter(array &$build, BlockPluginInterface $block) {
  // We'll search for the string 'uppercase'.
  $definition = $block->getPluginDefinition();
  if ((!empty($build['#configuration']['label']) && stristr($build['#configuration']['label'], 'uppercase')) || (!empty($definition['subject']) && stristr($definition['subject'], 'uppercase'))) {
    // This will uppercase the block title.
    $build['#configuration']['label'] = Unicode::strtoupper($build['#configuration']['label']);
  }
}


/**
 * {@inheritdoc}
 */
function instagram_display_build_display($category) {

    $html = instagram_display_fetch_posts();
    return $html;
}


/**
 * {@inheritdoc}
 */
function instagram_display_fetch_posts() {
    $userId = \Drupal::config('instagram_display.settings')->get('userId');
    if( !isset($userId) ) { // if no good value, use byu by default
        $userId = '458495252';
    }
    $username = \Drupal::config('instagram_display.settings')->get('username');
    if( !isset($username) ) { // if no good value, use byu by default
        $username = 'brighamyounguniversity';
    }
    $access_token = \Drupal::config('instagram_display.settings')->get('accessToken');
    if( !isset($access_token) ) {
        // return an error.
    }


    $userid_url = 'https://api.instagram.com/v1/users/' . $userId . '/media/recent/?access_token='.$access_token;


    $userid_json = file_get_contents($userid_url);
    $userid_array = json_decode($userid_json,true);
    $html = '';

    if(!empty($userid_array)) {

        $count=0;
        foreach($userid_array['data'] as $id) {


            error_reporting(0);

            $instagram_url = "https://api.instagram.com/v1/users/" . $userId . "/media/recent/?access_token="
                .$access_token;
            $instagram_json = file_get_contents($instagram_url);

            $instagram_array = json_decode($instagram_json,true);

            if(!empty($instagram_array)) {

                foreach($instagram_array['data'] as $post) {
                    $link = $post['link'];
                    $images = $post['images'];
                    $low = $images['standard_resolution'];
                    $imgUrl = $low['url'];
                    $count++;
                    if($count==6) {
                        // add last one differently, then break
                        $html .= '<a class="instagram-image last-image-link" target="_blank" href="https://www.instagram.com/' . $username . '/"><div class="h7 white see-more-text">SEE MORE</div></a>';

                        break;
                    } else if($count > 6) {
                        break;
                    }
                    $html .= '<div><a class="instagram-link instagram-' . $count . '" href="' . $link . '" target="_blank"><img class="img-responsive instagram-image image-' . $count . '" style="padding-left:35px;" src="' . $imgUrl . '" alt="Instagram Photos"><div class="instagram-logo-watermark"></div></a></div>';

                }
            }
        }
    }
    return $html;
}
