<?php
use \Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function nested_grafs_theme_suggestions_paragraph_alter(array &$suggestions, array $variables) {
  $graf = $variables['elements']['#paragraph'];
  if($graf->get('parent_type')->value == "paragraph") {
    $parent_graf = Paragraph::load($graf->get('parent_id')->value);
    $suggestions[] = 'paragraph__' . $parent_graf->getType() . '__' . $graf->getType();
  }
}