<?php

/**
 * @file
 * Code for the access conditions commerce payment module.
 */

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 */
function access_conditions_commerce_payment_commerce_checkout_pane_info_alter(&$definitions) {
  // The access_conditions_payment_information pane replaces the
  // access_conditions_billing_information one.
  unset($definitions['access_conditions_billing_information']);
}
