<?php

/**
 * @file
 * Install, update and uninstall functions for the cloudmersiveantivirus module.
 */

use Drupal\cloudmersiveantivirus\Config;
use Drupal\cloudmersiveantivirus\Scanner;


/**
 * Implements hook_requirements().
 */
function cloudmersiveantivirus_requirements($phase) {
  $requirements = array();
  // Report Drupal version
  if ($phase == 'runtime') {
    $config = new Config;

    switch ($config->scan_mode()) {
      case Config::MODE_DAEMON:
        $scanner = new Scanner\DaemonTCPIP($config);
        break;

      case Config::MODE_EXECUTABLE:
        $scanner = new Scanner\Executable($config);
        break;

      case Config::MODE_UNIX_SOCKET:
        $scanner = new Scanner\DaemonUnixSocket($config);
        break;
    }
  
    if ($version = $scanner->version()) {
      $requirements['cloudmersiveantivirus'] = array(
        'title' => t('CloudmersiveAntivirus version'),
        'value' => $scanner->version(),
        'severity' => REQUIREMENT_INFO,
      );
    }
    else {
      $requirements['cloudmersiveantivirus'] = array(
        'title' => t('CloudmersiveAntivirus version'),
        'value' => t('Unable to connect to CloudmersiveAntivirus service.'),
        'severity' => REQUIREMENT_ERROR,
      );
    }
  }

  return $requirements;
}

// @TODO: how to port D7 config to D8?
