<?php

/**
 * @file
 * Contains cloudsight.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Field\WidgetInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldConfigInterface;

/**
 * Implements hook_help().
 */
function cloudsight_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cloudsight module.
    case 'help.page.cloudsight':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Automatically get alternative text for images') . '</p>';
      return $output;

    default:
  }
}
