<?php

use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function taxonomy_move_form_taxonomy_overview_terms_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  $form['move_button'] = [
    '#weight' => -2,
    '#type' => 'markup',
    '#markup' => sprintf(
      '<a href="/%s?vid=%s" class="button button--primary button--small">%s</a>',
      Url::fromRoute('taxonomy_move.move_form')->getInternalPath(),
      $form_state->getBuildInfo()['args'][0]->id(),
      t('Move terms')
    ),
  ];

  foreach ($form['terms'] as $key => $value) {
    if (is_array($value) && isset($value['#term'])) {
      /** @var \Drupal\taxonomy\Entity\Term $term */
      $term = $value['#term'];
      if ('unmanaged' === $term->getVocabularyId()) {
        $form['delete_button'] = [
          '#weight' => -1,
          '#type' => 'markup',
          '#markup' => sprintf(
            '<a href="/%s" class="button button--primary button--small">%s</a>',
            Url::fromRoute('taxonomy_move.delete_form')->getInternalPath(),
            t('Delete terms')
          ),
        ];
      }
    }
  }
}
