<?php

/**
 * @file
 * Module file for workflow_sms_notification.
 */

use Drupal\Core\Utility\Token;
use Drupal\user\UserInterface;
use Drupal\workflow\Entity\WorkflowTransitionInterface;
use Drupal\sms\Entity\SmsMessage;

/**
 * Implements hook_workflow().
 */
function workflow_sms_notification_workflow($op, WorkflowTransitionInterface $transition, UserInterface $user) {
  if ($op == 'transition pre') {
    $entity = $transition->getTargetEntity();
    $user = $entity->getOwner();

    // Get the previous and current states of the content.
    $current_state = $transition->getToSid();
    $previous_state = $transition->getFromSid();
    $notifications = Drupal::service('entity_type.manager')
      ->getStorage('workflow_sms_notification')
      ->loadMultiple();

    foreach ($notifications as $notification) {
      if ($notification->getState() == $current_state && $current_state !== $previous_state) {
        $token = Drupal::token();
        // Setup the sms message content.
        $message = $notification->getMessage();
        $message['value'] = $token->replace(
          $message['value'],
          [$entity->getEntityTypeId() => $entity,
          'workflow_transition' => $transition,
          'workflow_scheduled_transition' => $transition]
        );
        $message = (string) check_markup($message['value'], $message['format']);

        // Figure out who the email should be going to.
        $to = [];

        // Authors.
        if ($notification->isAuthor()) {
          $to[] = $entity->getOwner()->mail->value;
        }

        // Remove any null values that have crept in.
        $to = array_filter($to);

        // Remove any duplicates.
        $to = array_unique($to);

        if (!empty($to)) {
          try {
            $sms_message = SmsMessage::create()
              ->setMessage($message);
            $phone_number_service = \Drupal::service('sms.phone_number');
            $phone_number_service->sendMessage($user, $sms_message);
          }
          catch (Exception $e) {
            drupal_set_message(t('SMS not sent, please contact site administrator'), 'error', FALSE);
          }
        }
      }
    }
  }
}
