<?php

/**
 * @file
 * JavaScript breakpoints module file.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function js_bp_page_attachments_alter(array &$attachments) {
  /** @var \Drupal\Core\Theme\ActiveTheme $activeTheme */
  $activeTheme = \Drupal::service('theme.manager')->getActiveTheme();
  $group = $activeTheme->getName();
  /** @var \Drupal\breakpoint\BreakpointManagerInterface $breakpointManager */
  $breakpointManager = \Drupal::service('breakpoint.manager');
  $breakpoints = $breakpointManager->getBreakpointsByGroup($group);
  if (!empty($breakpoints)) {
    $mediaQueries = [];
    /** @var \Drupal\breakpoint\Breakpoint $breakpoint */
    foreach ($breakpoints as $id => $breakpoint) {
      $mediaQueries[$id] = $breakpoint->getMediaQuery();
    }
    $attachments['#attached']['drupalSettings']['jsBp'] = $mediaQueries;
  }
}
