<?php

/**
 * @file
 * Helper module for testing async_script_shim module.
 */

/**
 * Implements hook_init().
 *
 * This adds two synchronous scripts and a synchronous script to the site so we
 * have scripts to test for.
 */
function async_script_shim_test_init() {
  drupal_add_js(drupal_get_path('module', 'async_script_shim_test') . '/async_script_shim_test_async_1.js', array(
      'type' => 'file',
      'async' => TRUE,
    ));
  drupal_add_js(drupal_get_path('module', 'async_script_shim_test') . '/async_script_shim_test_async_2.js', array(
      'type' => 'file',
      'async' => TRUE,
    ));
  drupal_add_js(drupal_get_path('module', 'async_script_shim_test') . '/async_script_shim_test_sync_1.js', array(
      'type' => 'file',
      'async' => FALSE,
    ));
}
