<?php

/**
 * @file
 * Navbar filter main module file.
 */

/**
 * Implements hook_toolbar_alter().
 */
function navbar_filter_toolbar_alter(&$items) {
  // dsm($items);
  $items['administration']['tray']['toolbar_administration']['links_filter'] = array(
    '#type' => 'textfield',
    '#name' => 'navbar_filter',
    '#weight' => -10000,
    '#attributes' => array(
      'placeholder' => t('Type to filter menu...'),
      'class' => array('navbar-filter'),
      'autofocus' => '',
    ),
    // Custom CSS, JS or a library can be associated with the navbar item.
    '#attached' => array(
      'library' => array(
        'navbar_filter/filter',
      ),
    ),
  );
}
