<?php
/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\spectra_expire\Entity\EntityExpirationPolicy;

/**
 * Implements hook_help().
 */
function spectra_expire_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.spectra_expire':
      $ret = '<h2>' . t('Spectra Entity Expiration') . '</h2>';
      $ret .= '<h3>' . t('Expiring Entity Selection Methods Provided') . '</h3>';
      $ret .= '<p>' . t('Spectra Entity Expiration provides a method for selecting Statements from expiring data. 
      A later version of the Policy-based Entity Expiration Method module will enable fine-grained selection of data 
      types, so that one may expire satements with a particular data_type.') . '</p>';
      $ret .= '<h3>' . t('Expiration Methods Provided') . '</h3>';
      $ret .= '<p>' . t('Spectra Entity Expiration provides a method specific to Spectra Statements, which allows for the
      deletion of Spectra Entities (Actors, Actions, Objects, and Contexts) when those entities are not used by any other
      statements. Note that when a Statement is deleted, its corresponding Data is always also deleted.') . '</p>';
      return $ret;
  }
}