<?php

/**
 * @file
 * Contains content_type_dependency.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\core\Form;
use Drupal\user\Entity;
use Drupal\user\Entity\Role;
use Drupal\Core\Render\Element;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_help().
 */
function content_type_dependency_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the content_type_dependency module.
    case 'help.page.content_type_dependency':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Content Type Dependency Module') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form().
 */
function content_type_dependency_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Loading Content type enabled by rule &
  // which opened by current logged in user.
  $bundle = $form['#process'][1][0]->get('bundle');
  $db = \Drupal::database();
  $result = $db->select('content_type_dependency','c')
    ->fields('c')
    ->condition('to_create', $bundle)
    ->execute();
  if ($record = $result->fetchObject()) {
    // Checks for user number of nodes created & role assigned for particular Content Type Dependency.
    if ((content_type_dependency_node_count($record->must_have) < $record->no_of) && (content_type_dependency_user_roles(unserialize($record->role)))) {
      // Sets destination for drupal_goto function.
      // Redirecting if all conditions are satisfied.
      $url = $record->must_have .'?destination=node/add/' . $record->to_create;
      $response = new RedirectResponse($url);
      drupal_set_message(t('@msg', array('@msg' => $record->message)));
      $response->send();
      exit();
    }
  }
}

/**
 * Returns number of nodes created by user current logged in user 0 to n.
 * @param $c_t
 * @return int
 */
function content_type_dependency_node_count($c_t) {
  // Get Current logged in user id.
  $uid = \Drupal::currentUser()->id();

  $query = \Drupal::entityQuery('node')
    ->condition('status', 1)
    ->condition('uid', $uid)
    ->condition('type', $c_t)
    ->execute();
  return count($query);
}


/**
 * Returns user role for content type dependency rule.
 * @param $roles_from_rule
 * @return bool
 */
function content_type_dependency_user_roles($roles_from_rule) {
  $roles = Role::loadMultiple();
  $avail_type = array_keys($roles);
  foreach ($roles_from_rule as $keys => $values) {
    if ($values) {
      if (in_array ($keys,$avail_type)) {
        return TRUE;
      }
    }
  }
  return FALSE;
}

