<?php

/**
 * @file
 * Description.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function disable_route_normalizer_form_redirect_settings_form_alter(array &$form, FormStateInterface $form_state) {
  $form['globals']['route_ignore_neutral_nodes'] = array(
    '#type' => 'checkbox',
    '#title' => t('Ignore nodes with undefined or without language.'),
    '#description' => t('Enabling this will ignore redirect when accessing a neutral language entity.'),
    '#default_value' => \Drupal::config('disable_route_normalizer.settings')->get('route_ignore_neutral_nodes'),
    '#states' => array(
      // Only show this field when the 'redirect_route_normalizer_enabled'
      // checkbox is enabled.
      'visible' => array(
        ':input[name="redirect_route_normalizer_enabled"]' => array(
          'checked' => TRUE,
        ),
      ),
    ),
    '#weight' => 0,
  );
  $form['#submit'][] = 'disable_route_normalizer_form_redirect_settings_form_submit';
}

/**
 * Custom submit handler for redirect_settings_form.
 */
function disable_route_normalizer_form_redirect_settings_form_submit($form, FormStateInterface $form_state) {
  // Save our custom variable.
  $config = \Drupal::configFactory()->getEditable('disable_route_normalizer.settings');
  $config->set('route_ignore_neutral_nodes', $form_state->getValue('route_ignore_neutral_nodes'));
  $config->save();
}


