<?php

/**
 * @file
 * Add an Base64 formatter for image field
 */

/**
 * Implements hook_theme().
 */
function image_base64_formatter_theme() {
    return array(
        'image_base64_formatter' => array(
            'variables' => array(
                'item' => NULL,
                'item_attributes' => NULL,
                'url' => NULL,
                'image_style' => NULL,
                'url_type' => NULL,
            ),
        ),
    );
}

/**
 * Returns HTML for an image base64 field formatter.
 *
 * @param array $variables
 *   An associative array containing:
 *   - item: An array of image data.
 *   - image_style: An optional image style.
 *   - path: An optional array containing the link 'path' and link 'options'.
 *
 * @ingroup themeable
 */
function template_preprocess_image_base64_formatter(&$variables) {

    // if you need additional functionality

}
