<?php

/**
 * @file
 * Contains simple_a_b_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\simple_a_b\SimpleAB;

// This will be the id of the simple AB Type
// - src/Plugin/SimpleABReport/BlockCustom.php.
define('SIMPLE_A_B_BLOCKS_CONFIG_NAME', 'block_custom');

/**
 * Implements hook_help().
 */
function simple_a_b_blocks_help($route_name, RouteMatchInterface $route_match) {
}

/**
 * Implements hook_preprocess_block().
 */
function simple_a_b_blocks_preprocess_block(&$variables) {
  // Found out the the provider is of type block_content.
  $provider = isset($variables['configuration']['provider']) ? $variables['configuration']['provider'] : FALSE;
  $is_block_content = $provider === "block_content" ? TRUE : FALSE;

  // If we have a block_content block.
  if ($is_block_content) {

    // dpm($variables);
    // Load the block content.
    $block_content = $variables['content']['#block_content'];

    // Disable the default caching.
    $variables['content']['#cache']['max-age'] = 0;
    $variables['#cache']['max-age'] = 0;

    // TODO: I did not want to have to use this, seems like a "hack"
    // See issue #2352009 (https://www.drupal.org/node/2352009).
    \Drupal::service('page_cache_kill_switch')->trigger();

    // Get the custom block id.
    $id = $block_content->id();

    // Load a list of the enabled custom blocks.
    $config = \Drupal::service('simple_a_b.storage.config')
      ->fetch(SIMPLE_A_B_BLOCKS_CONFIG_NAME);
    $eids = isset($config->data) ? $config->data : [];

    // Look for the id in the list of eids
    // and return the tid (the key of the array).
    if (FALSE !== $tid = array_search($id, $eids)) {

      // If we have a tid we can look it
      // up to try and get the data for the this a/b test.
      $test_data = \Drupal::service('simple_a_b.storage.data')->fetch($tid);

      // Get the content and try and get its
      // value check if is array for input value ckeditor.
      // TODO: this could be put in its on function as things get more complex.
      $content = $test_data->content;
      if (is_array($content) && isset($content['value'])) {
        $content = $content['value'];
      }

      // Calculate the experience.
      if (SimpleAB::calculateExperience($test_data)) {

        // Replace the content.
        $variables['content']['body']['0']['#text'] = $content;
      }
    }
  }
}
