<?php

/**
 * @file
 * Contains gamabhana.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\HtmlResponseAttachmentsProcessor;

function gamabhana_help($route_name, RouteMatchInterface $route_match) {
  switch($route_name) {
    case 'help.page.gamabhana':
      // appears on the admin module help page
      return t('
        <p>This module enables users to type in the context phonetically with sevaral Indic languages,scripts using
           <a href="http://www.var-x.com/gamabhana" target="_new">gamabhana</a>. <br />Administrators can configure the settings for gamabhana. Configure gamabhana to:
           <ul><li>Enable/disable phonetics</li><li>Edit/Update element-ids for which gamabhana phonetics to be configured</li><li>Set default and secondary typing language/script</li><li>Set language selection block with its display texts</li></ul>
      ');
    case 'gamabhana.settings':
      return '<p><b>' . t('Gamabhana Settings.') . '</b></p>';
  }
}

/**
 * Implements hook_theme().
 */
function gamabhana_theme() {
  $theme = [];
  return $theme;
}

/**
 * Implements hook_page_top().
 */
function gamabhana_page_top(array &$page_top) {
  $page_top['gamabhana'] = [
    '#attached' => [
      'library' => [
        'gamabhana/drupal.gamabhana'
      ]
    ]
  ];
}

function gamabhana_page_attachments(array &$attachments) {
  // Unconditionally attach an asset to the page.
  $default_lag_key = \Drupal::config('gamabhana.settings')->get('gamabhana_phonetic_default_lang');
  $secondery_lag_key = \Drupal::config('gamabhana.settings')->get('gamabhana_phonetic_secondary_lang');
  $all_lang = \Drupal::config('gamabhana.settings')->get('gamabhana_mls_ind');
  
  // getting all elements ids form config settins
  $gamabhana_phonetic_id_value = \Drupal::config('gamabhana.settings')->get('gamabhana_phonetic_ids');
  $gamabhana_phonetic_ids = explode(' ', $gamabhana_phonetic_id_value);
  $languages = gamabhana_getLanguages();
  
  // Conditionally attach an asset to the page.
  $attachments['#attached']['drupalSettings']['field_ids'] = $gamabhana_phonetic_ids;
  $attachments['#attached']['drupalSettings']['default_lang'] = $default_lag_key;
  $attachments['#attached']['drupalSettings']['secondery_lang'] = $secondery_lag_key;
  $attachments['#attached']['drupalSettings']['languages'] = $languages;
  $attachments['#attached']['drupalSettings']['all_lang'] = $all_lang;
}

function gamabhana_element_info_alter(array &$types) {
  $types['search']['#process'] = array(
    'gamabhana_process_text_format'
  );
  $types['textfield']['#process'] = array(
    'gamabhana_process_text_format'
  );
  $types['texarea']['#process'] = array(
    'gamabhana_process_text_format'
  );
  return $types;
}

function gamabhana_process_text_format(&$form_element) {
  // skip disabled text fields
  if(isset($form_element['#attributes']['disabled']) && $form_element['#attributes']['disabled'] == 'disabled') {
    return $form_element;
  }
  
  if(!_gamabhana_element_check($form_element['#id'])) {
    return $form_element;
  }
  // add the gamabhan-enabled class so gamabhan will bind the key events
  $form_element['#attributes']['class'][] = 'gamabhan-enabled';
  
  return $form_element;
}

/**
 * This function helper function.
 */
function _gamabhana_element_check($element_id) {
  $result = 0;
  // getting all elements ids form config settings
  $gamabhana_phonetic_id_value = \Drupal::config('gamabhana.settings')->get('gamabhana_phonetic_ids');
  $excl_fields = explode(' ', $gamabhana_phonetic_id_value);
  
  if(in_array($element_id, $excl_fields)) {
    $result = 1;
  }
  
  return $result;
}

// function returns language array
function gamabhana_getLanguages() {
  $languages = array(
    '__devanagari__' => 'Hindi/Marathi',
    '__gujarati__' => 'Gujarati',
    '__gurumukhi__' => 'Gurumukhi',
    '__bengoli__' => 'Bengoli',
    '__kannada__' => 'Kannada',
    '__malayalam__' => 'Malayalam',
    '__tamil__' => 'Tamil',
    '__telugu__' => 'Telugu',
    '__urdu__' => 'Urdu',
    '__roman__' => 'English'
  );
  
  return $languages;
}
