<?php

/**
 * @file
 * Contains owlcarousel2.module.
 */

use Drupal\Core\Entity\EntityMalformedException;
use Drupal\Core\Render\Markup;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\owlcarousel2\Util;

/**
 * Implements hook_help().
 */
function owlcarousel2_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the owlcarousel2 module.
    case 'help.page.owlcarousel2':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OwlCarousel2 Implementation, full featured with youtube support, and tons of slide effects.') . '</p>';
      $output .= '<p>' . t('See the script repository on <a href="https://github.com/OwlCarousel2/OwlCarousel2">Github</a>') . '</p>';
      $output .= '<p>' . t('<a href="https://github.com/OwlCarousel2/OwlCarousel2/archive/2.3.4.zip">Click here to download the script</a> and copy the <strong><code>dist</code></strong> folder under <strong><code>{Drupal Installation}/libraries/OwlCarousel2</code></strong>') . '</p>';

      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function owlcarousel2_theme() {
  $themes = [
    'owlcarousel2'             => [
      'render element' => 'elements',
    ],
    'owlcarousel2_image_item'  => [
      'render element' => 'elements',
    ],
    'owlcarousel2_custom_text' => [
      'render element' => 'elements',
    ],
    'owlcarousel2_node'        => [
      'template'  => 'owlcarousel2-node',
      'base hook' => 'node',
    ],
    'owlcarousel2_block'       => [
      'variables' => [
        'content'             => NULL,
        'id'                  => NULL,
        'nav_titles'          => NULL,
        'carousel_navigation' => NULL,
        'nav_ratio'           => NULL,
        'nav_height'          => NULL,
        'nav_width'           => NULL,
      ],
      'template'  => 'block--owlcarousel2',
    ],
  ];

  return $themes;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function owlcarousel2_preprocess_owlcarousel2(&$variables) {
  $elements = $variables['elements'];
  /** @var \Drupal\owlcarousel2\Entity\OwlCarousel2 $carousel */
  $carousel = $elements['#owlcarousel2'];
  try {
    $data = Util::getCarouselData($carousel->id());
  }
  catch (EntityMalformedException $e) {
    return $e;
  }
  $content    = $data['content'];
  $nav_titles = $data['navigation_titles'];
  $nav_ratio  = $data['nav_ratio'];
  $nav_height = $data['nav_height'];
  $nav_width  = $data['nav_width'];
  $settings   = $carousel->get('settings')->getValue()[0];

  $carousel_navigation = isset($settings['carouselNavigation']) ? ($settings['carouselNavigation'] == 'true') : FALSE;
  // If it is a carousel navigation, include a setting navigation size and set
  // the items per slide to 1.
  if ($carousel_navigation) {
    $settings['carouselNavigationSize'] = $settings['items_per_slide'];
    $settings['items_per_slide']        = 1;
  }

  $variables['content']['#markup']     = Markup::create($content);
  $variables['id']                     = $carousel->id();
  $variables['nav_titles']             = $nav_titles;
  $variables['carousel_navigation']    = $carousel_navigation;
  $variables['nav_ratio']              = $nav_ratio;
  $variables['nav_height']             = $nav_height;
  $variables['nav_width']              = $nav_width;
  $variables['#attached']['library'][] = 'owlcarousel2/owlcarousel2';

  $container = \Drupal::getContainer();
  /** @var \Drupal\Core\KeyValueStore\KeyValueExpirableFactoryInterface $key_value */
  $key_value = $container->get('keyvalue.expirable');
  $key_value->get('owlcarousel2')->set($carousel->id(), $settings);
  $keyed_settings = $key_value->get('owlcarousel2')->getAll();

  $variables['#attached']['drupalSettings']['owlcarousel_settings'] = $keyed_settings;

}

/**
 * Implements hook_preprocess_HOOK().
 */
function owlcarousel2_preprocess_html(&$variables) {
  // Clear the carousel key/par settings to avoid garbage.
  $container = \Drupal::getContainer();
  /** @var \Drupal\Core\KeyValueStore\KeyValueExpirableFactoryInterface $key_value */
  $key_value = $container->get('keyvalue.expirable');
  $key_value->get('owlcarousel2')->deleteAll();

}

/**
 * Implements hook_theme_suggestions_node_alter().
 */
function owlcarousel2_theme_suggestions_node_alter(array &$suggestions, array $variables) {
  // Make the owlcarousel2_node template the weakest choice.
  if (in_array('owlcarousel2_node', $suggestions)) {
    $key = array_search('owlcarousel2_node', $suggestions);
    if ($key) {
      array_unshift($suggestions, $suggestions[$key]);
      unset($suggestions[$key]);
    }
  }
}
