<?php

/**
 * @file
 * Contains form_element_states.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function form_element_states_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the form_element_states module.
    case 'help.page.form_element_states':
      $output = '';
      $output .= '<h3>' . t('About form element states') . '</h3>';
      $output .= '<p>' . t('Provide a widget for core field type where user can able to add  states properties in form element') . '</p>';
      return $output;
  }
}
