<?php

/**
 * @file
 * Contains missyou.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function missyou_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the missyou module.
    case 'help.page.missyou':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Simple module to change the title & favicon of the page when the user is not viewing your website') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function missyou_page_attachments_alter(&$page) {
  // Attach jquery.iMissYou.js to all pages.
  $page['#attached']['library'][] = 'missyou/missyou';

  // Get module configurations.
  $config = \Drupal::config('missyou.settings');

  // Attach value for tab title to use it in JS.
  $page['#attached']['drupalSettings']['missyou']['missyou_title'] = $config->get('missyou_tab_title');

  // Check if favicon field is empty or not.
  if (!empty($config->get('missyou_favicon'))) {
    // Attach value for ether show favicon or not to use it in JS.
    $page['#attached']['drupalSettings']['missyou']['missyou_show_favicon'] = TRUE;

    // Get file ID, load file and get URL to file.
    $fid = $config->get('missyou_favicon');
    foreach ($fid as $value) {
      $id = $value;
    }

    // $id will be defined since we checked if file exists in the field.
    $file = File::load($id);
    $path = $file->getFileUri();

    $url = file_create_url($path);
    $url = parse_url($url);
    $url = $url['path'];

    // Attach value for url to the favicon image to use it in JS.
    $page['#attached']['drupalSettings']['missyou']['missyou_favicon'] = $url;
  }
  else {
    // Attach value for ether show favicon or not to use it in JS.
    $page['#attached']['drupalSettings']['missyou']['missyou_show_favicon'] = FALSE;
    // Attach NULL value for url to the favicon image to use it in JS
    // since there is no image in field.
    $page['#attached']['drupalSettings']['missyou']['missyou_favicon'] = NULL;
  }
}
