<?php
/**
 * @file
 * required_field_display functionality
 */

/**
 * Implements hook_form_FORM_ID_alter() for entity_form_display_edit_form().
 */
function required_field_display_form_entity_form_display_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $entity = $form['#entity_type'];
  $bundle = $form['#bundle'];
  $field_info = \Drupal::getContainer()->get('entity_field.manager')->getFieldDefinitions($entity, $bundle);

  foreach (array_keys($form['fields']) as $field) {
    // skip attributes
    if (substr($field, 0, 1) == '#') {
      continue;
    }
    if (isset($field_info[$field]) && $field_info[$field]->isRequired()) {
      if (!isset($form['fields'][$field]['#cell_attributes']['class'])) {
        $form['fields'][$field]['human_name']['#cell_attributes']['class'] = [];
      }
      $form['fields'][$field]['human_name']['#cell_attributes']['class'][] = 'form-required';
    }
  }
}

/**
 * Implements hook_preprocess_table().
 */
function required_field_display_preprocess_table(array &$table) {
  if (isset($table['attributes']['id']) && $table['attributes']['id'] == 'field-overview') {
    $field_info = NULL;
    foreach ($table['rows'] as $row_id => $row) {
      list($type, $bundle, $field) = explode('.', $row_id);
      if (empty($field_info)) {
        $field_info = \Drupal::getContainer()->get('entity_field.manager')->getFieldDefinitions($type, $bundle);
      }

      if (isset($field_info[$field]) && $field_info[$field]->isRequired()) {
        $table['rows'][$row_id]['cells']['label']['attributes']->addClass('form-required');
      }
    }
  }
}
