<?php 




function maestro_taskconsole_theme($existing, $type, $theme, $path) {
  return [
    'taskconsole_status_bar' => [
      'variables' => [
        'stage_count' => 0,
        'stage_messages' => [],
        'current_stage' => 0,
        'current_stage_message' => ''],
    ],
    
    'taskconsole_views' => [
      'variables' => [
        'task_information' => '',  //the html string of task information
        'title' => '',
      ],
    ],
    
  ];
}
