<?php

/**
 * @file
 * Contains devel_snippet.module..
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function devel_snippet_form_devel_snippet_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($_SESSION['devel_execute_code'])) {
    // @todo Better way to set this value?
    $form['code']['widget'][0]['value']['#default_value'] = $_SESSION['devel_execute_code'];

    unset($_SESSION['devel_execute_code']);
  }

  // @todo Why rows value from setDisplayOptions doesn't working?
  $form['code']['widget'][0]['value']['#rows'] = 20;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function devel_snippet_form_devel_snippet_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($_SESSION['devel_snippet_execute_code'])) {
    // @todo Better way to set this value?
    $form['code']['widget'][0]['value']['#default_value'] = $_SESSION['devel_snippet_execute_code'];

    unset($_SESSION['devel_snippet_execute_code']);
  }

  // @todo Why rows value from setDisplayOptions doesn't working?
  $form['code']['widget'][0]['value']['#rows'] = 20;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function devel_snippet_form_devel_execute_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['execute']['devel_snippet_save'] = [
    '#type' => 'submit',
    '#value' => t('Save as snippet'),
    '#submit' => ['devel_snippet_form_save_submit'],
  ];
}

/**
 * Form submit. Save code as new snippet.
 */
function devel_snippet_form_save_submit(&$form, FormStateInterface $form_state) {
  $_SESSION['devel_execute_code'] = $form_state->getValue('code');

  $form_state->setRedirect('entity.devel_snippet.add_form');
}
