<?php

/**
 * @file
 * Contains sponsor_event.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\taxonomy\Entity\Vocabulary;

/**
 * Implements hook_entity_insert().
 */
function sponsor_event_entity_insert(EntityInterface $entity) {
  $tids = NULL;
  if ($entity->getEntityTypeId() == 'event') {
    $title = $entity->get('name')->getValue();
    $name = $title[0]['value'];
    $vocabulary_name = str_replace(" ", "_", strtolower($name));
    $name = $title[0]['value'] . " Sponsorship Levels";
    $query = \Drupal::entityQuery('taxonomy_term');
    $query->condition('vid', $vocabulary_name);
    $query->sort('weight');
    $tids = $query->execute();
    if ($tids == NULL) {
      $vocabulary = Vocabulary::create(
        [
          'vid' => $vocabulary_name,
          'description' => '',
          'name' => $name,
        ]);
      $vocabulary->save();
      \Drupal::logger('sponsor_event')->notice("Automatically created Vocabulary for '$name.'");;
    }
  }
}
