<?php

/**
 * @file
 * Contains main module functions.
 */

/**
 * Implements hook_field_widget_info_alter().
 */
function field_union_field_widget_info_alter(array &$info) {
  _field_union_expand_field_types($info);
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function field_union_field_formatter_info_alter(array &$info) {
  _field_union_expand_field_types($info);
}

/**
 * Expands widget or formatter information.
 *
 * @param array $info
 *   Widget or formatter info.
 */
function _field_union_expand_field_types(array &$info) {
  $field_unions = \Drupal::entityTypeManager()
    ->getStorage('field_union')
    ->getQuery()
    ->execute();
  $info['field_union']['field_types'] = array_map(function ($id) {
    return 'field_union:' . $id;
  }, $field_unions);
}
