query {
  route(path: "http://graphql.drupal/xml") {
    ... on ExternalUrl {
      request {
        xml {
          ... on XMLElement {
            xpath(query:"a") {
              content
            }
          }
        }
      }
    }
  }
}
