<?php

/**
 * @file
 * Contains redacted.module.
 */

/**
 * Implements hook_page_attachments().
 */
function redacted_page_attachments(array &$page) {
  if (\Drupal::currentUser()->isAnonymous()) {
    $page['#attached']['library'][] = 'redacted/redacted';
  }

  $noindex = [
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => [
      'name' => 'robots',
      'content' => 'noindex,nofollow',
    ],
  ];
  $page['#attached']['html_head'][] = [$noindex, 'robots'];
}
