<?php

/**
 * @file
 * Install, update, and uninstall functions for content serialization.
 */

/**
 * Enable the bulkentity module.
 */
function contentserialize_update_8101() {
  /** @var \Drupal\Core\Extension\ModuleInstallerInterface $installer */
  $installer = \Drupal::service('module_installer');
  if ($installer->install(['bulkentity'])) {
    return 'Bulk Entity API module was installed.';
  }
  else {
    return 'There was an error installing the Bulk Entity API module.';
  }
}
