<?php

/**
 * @file
 * Module code for doccheck_basic module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Theme code for doccheck_basic module.
 */
function doccheck_basic_theme($existing, $type, $theme, $path) {
  return [
    'doccheck_basic' => [
      'variables' => [
        'loggedin' => NULL,
        'dctemplate' => NULL,
        'width' => NULL,
        'height' => NULL,
        'language' => NULL,
        'loginid' => NULL,
        'devmode' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_help().
 */
function doccheck_basic_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.doccheck_basic':
      $text = file_get_contents(dirname(__FILE__) . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}
