<?php

/**
 * @file
 * Email validation by BytePlant service.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function byteplant_email_validation_form_alter(&$form, &$form_state, $form_id) {
  $config = \Drupal::config('byteplant_email_validation.byteplant_settings');
  if (!empty($config->get('forms'))) {
    $forms = preg_split('/[\r\n]+/', $config->get('forms'), -1, PREG_SPLIT_NO_EMPTY);
    if (in_array($form_id, $forms)) {
      $form['#validate'][] = 'byteplant_email_validation';
    }
  }
}

/**
 * Email validation by BytePlant service.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function byteplant_email_validation(&$form, FormStateInterface $form_state) {
  $email_validator = \Drupal::service('byteplant_email_validation');
  // Find status details in https://www.email-validator.net/email-verification-results.html.
  $valid_status = [
    BYTEPLANT_OK_VALID_ADDRESS,
    BYTEPLANT_OK_CATCH_All_ACTIVE,
    BYTEPLANT_OK_CATCH_All_TEST_DELAYED,
  ];
  foreach ($form['elements'] as $id => $element) {
    if (!empty($element['#type']) && in_array($element['#type'], [
        'webform_email_confirm',
        'email',
      ])
    ) {
      if ($form_state->hasValue($id)) {
        $email = $form_state->getValue($id);
        $content = $email_validator->verifyEmail($email);
        // Test email validation by status provided by byteplant.
        if ($content && !empty($content->status) &&
          !in_array($content->status, $valid_status)
        ) {
          $form_state->setErrorByName($id, $email_validator->getMessage($content));
        }
      }
    }
  }
}
