<?php

/**
 * @file
 * Parameter Message - Main functions.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function parameter_message_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.parameter_message':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Parameter Message module displays messages in CMS as an URL parameter. For more information, see the online handbook entry for <a target="_blank" href="@parameter_message">Parameter Message module</a>.', ['@parameter_message' => 'https://www.drupal.org/project/parameter_message/']) . '</p>';
      $output .= '<h3>' . t('Usage') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Displaying messages') . '</dt>';
      $output .= '<dd>' . t('The Parameter Message module can be accessed in <i>Configuration</i>  » <i>User interface</i>  » <i>Parameter Message</i> screen. When followed the correct pattern (see online handbook), the message can be displayed on screen very easily by using the parameter in the URL.');
      $output .= t('&nbsp;<a target="_blank" href="@parameter_message_configuration">Click here</a> to redirect to Parameter Message configuration.', ['@parameter_message_configuration' => base_path() . 'admin/config/user-interface/parameter-message/settings']) . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}
