<?php

/**
 * @file
 * Contains chat_channels.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_element_info_alter().
 */
function chat_channels_element_info_alter(array &$types) {
  // Attach our extra CSS for toolbar icons.
  if (isset($types['toolbar'])) {
    $types['toolbar']['#attached']['library'][] = 'chat_channels/toolbar';
  }
}

/**
 * Implements hook_help().
 */
function chat_channels_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chat_channels module.
    case 'help.page.chat_channels':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Chat channels provides communication channels that users can use to communicate with multiple users.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function chat_channels_theme() {
  $theme = [];
  $theme['chat_channel'] = [
    'render element' => 'elements',
    'file' => 'chat_channel.page.inc',
    'template' => 'chat_channel',
  ];
  $theme['chat_channel_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'chat_channel.page.inc',
  ];

  $theme['chat_channel_message'] = [
    'render element' => 'elements',
    'file' => 'chat_channel_message.page.inc',
    'template' => 'chat_channel_message',
  ];

  $theme['chat_channel_message_divider'] = [
    'render element' => 'elements',
    'file' => 'chat_channel_message.page.inc',
    'template' => 'chat_channel_message_divider',
  ];

  $theme['chat_channel_new_message_indicator'] = [
    'render element' => 'elements',
    'file' => 'chat_channel.page.inc',
    'template' => 'chat_channel-new-message-indicator',
  ];

  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function chat_channels_theme_suggestions_chat_channel(array $variables) {
  $suggestions = [];

  return $suggestions;
}
