<?php

/**
 * @file Module file for aframe.
 */

/**
 * Implements hook_theme().
 */
function aframe_theme() {
  $items['aframe_coords'] = [
    'render element' => 'element',
    'file'           => 'aframe.theme.inc',
  ];

  $items['aframe_field'] = [
    'render element' => 'element',
  ];

  $items['aframe_tag'] = [
    'render element' => 'element',
    'file'           => 'aframe.theme.inc',
  ];

  $items['views_view_aframe'] = [
    'variables' => [
      'view'    => NULL,
      'options' => NULL,
      'rows'    => NULL,
      'title'   => NULL,
    ],
    'file'      => 'aframe.theme.inc',
  ];

  return $items;
}

/**
 * Implements hook_element_info_alter().
 */
function aframe_element_info_alter(array &$types) {
  // Add '<a-scene>' element.
  $types['aframe_scene'] = $types['aframe_tag'];
  $types['aframe_scene']['#attached'] = [
    'library' => ['aframe/aframe'],
  ];
  $types['aframe_scene']['#tag'] = 'scene';

  // Add primitives.
  $primitives = [
    'box',
    'camera',
    'collada_model',
    'cone',
    'cursor',
    'curvedimage',
    'cylinder',
    'image',
    'light',
    'obj_model',
    'plane',
    'ring',
    'sky',
    'sphere',
    'torus',
    'video',
    'videosphere',
  ];
  foreach ($primitives as $primitive) {
    $types["aframe_{$primitive}"] = $types['aframe_tag'];
    $types["aframe_{$primitive}"]['#tag'] = str_replace('_', '-', $primitive);
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function aframe_theme_suggestions_field_alter(array &$suggestions, array $variables) {
  $element = $variables['element'];
  if (strpos($element['#formatter'], 'aframe_') === 0) {
    $suggestions = ['aframe_field'];
  }
}

/**
 * Implements hook_library_info_build().
 */
function aframe_library_info_build() {
  $libs['aframe'] = [
    'js' => []
  ];
  // Get the latest version of aframe.
  $aframe_versions = \Drupal::service('aframe.library.discovery')->aframeScanLibraryVersions();
  if (!empty($aframe_versions)) {
    $aframe_js = array_shift($aframe_versions);
    $libs['aframe']['header'] = TRUE;
    $libs['aframe']['js'] = [
      $aframe_js => [],
    ];
  }
  return $libs;
}
