<?php

/**
 * @file
 * Main module file for the forgot_username module.
 */

/**
 * Implements hook_mail().
 */
function forgot_username_mail($key, &$message, $params) {
  switch ($key) {
    case 'notice':
      $site_name = \Drupal::config('system.site')->get('name');
      $email = \Drupal::state()->get('forgot_username_mail');
      $params['user'] = user_load_by_mail($email)->getDisplayName();
      $message['subject'] = t('Your username from @site', ['@site' => \Drupal::config('system.site')->get('name')]);
      $message['body'][] = t('You, or someone pretending to be you, requested your username from @site. Your username is @user.', ['@site' => $site_name, '@user' => $params['user']]);
      $message['body'][] = '';
      $message['body'][] = t('Thanks, @site', ['@site' => $site_name]);
      break;
  }
}
