<?php

/**
 * @file
 * Module file which implements some changes on core form.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function image_export_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.image_export_import':
      $output = '<p>' . t('In the help of this module, user can create/update node for selected image field (single value field as well as multi value) with ALT and Title. User can also create new node (with Title, Body fields) and attach images with new nodes.') . '</p>';
      $output .= '<p>' . t('User can also export nodes for selected image field in csv file with respected columns (nid, node_title, image_name (Pipe separated incase of multiple),IMG_alt, IMG_title, summary, body).') . '</p>';

      $output .= '<p>' . t('Body field is optional in csv.If user will check "Body and Summary" option on form then body will export in csv.') . '</p>';

      $output .= '<p>' . t('User can also delete unused files from CMS. after installation goes to "/admin/content/unused-files" page, and see all unused file in cms.') . '</p>';

      $output .= '<p><strong>How to Use:</strong> </p><p>' . t('User need to execute export operation first, after that you got csv file which have following columns (Nid, Node_Title, Image_file_name (Pipe separated in case of multi value)). and all images backuped under
  "sites/default/files/migrate_images" directory automatically.') . '</p>';

      $output .= '<p>' . t('Then you need to update existing csv file with image_filename, image_alt, image_title in csv file, and execute import operation with updated file. Please upload images zip file for new images.') . '</p>';

      $output .= '<p>' . t('Admin can truncate/delete "sites/default/files/migrate_images" directory manually after export/import/delete operation for reduce server space.') . '</p>';

      $output .= '<p><strong>FOR EXPORT:</strong> </p><p>' . t('Using export operation user will got a csv file which have following columns (Nid, Node_Title, Image_file_name (Pipe separated in case of multi value)). Images will automatically exported under "sites/default/files/migrate_images" directory.') . '</p>';

      $output .= '<p>' . t('If user will check "Body and Summary" option on form then body will export in csv.') . '</p>';

      $output .= '<p><strong style="color:red !important;">FOR IMPORT:</strong> </p><p>' . t('  CSV columns order should be as per exported csv (got from export operation),
  Please do not change CSV file column order, Please use exported CSV file
  and update content in this file to Export operation.') . '</p>';

      $output .= '<p><strong>Update existing node:</strong> </p><p>' . t('User can update exiting image, just update image name, Alt, title (pipe(|)
  separated in case of multi value).') . '</p>';

      $output .= '<p><strong>Create new node :</strong> </p><p>' . t('User can create new node and attached images with node, for that just use exported CSV and add new row in csv and leave empty NID column for new node. Just check "Create new node" option during image import, it\'s required for new node creation.') . '</p>';

      $output .= '<p><strong>Body and Summary :</strong> </p><p>' . t('User can update body and summary for new node as well as existing node, For that need to check "Body and Summary" option during import.') . '</p>';

      $output .= '<p><strong>FOR DELETE UNUSED FILES:</strong> </p><p>' . t('Open "/admin/content/unused-files" page to check unused files in CMS. If you want to delete these files then execute "Delete unused files" Operation.') . '</p>';
      $output .= '<p><strong>Note:</strong> </p>';
      $output .= '<p>' . t('(1) Select multiple images files and compress directly, means do not compress image folder.Otherwise node will not create/update.') . '</p>';
      $output .= '<p>' . t('(2) If your CSV file have new row (empty NID column), Then use one time import operation with this CSV file, Otherwise due to empty NID column duplicate node will create in CMS.') . '</p>';
      $output .= '<p>' . t('(3) Not required: Backup your Database before executing Import operation. Using Backup and Migrate (https://www.drupal.org/project/backup_migrate).') . '</p>';

      return $output;
  }
}

/**
 * Implements hook_form_alter().
 */
function image_export_import_form_alter(&$form, FormStateInterface $form_state, $form_id) {

}

/**
 * Alter views query for date field in Drupal.
 *
 * @param mixed|ViewExecutable $view
 *   View object need to alter.
 * @param mixed|QueryPluginBase $query
 *   Query object need to alter query here.
 */
function image_export_import_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  // Get orphaned files from CMS.
  if ($view->id() == 'orphan_files') {
    // Add Where condition in views.
    $query->addWhere(1, 'file_usage.fid', NULL, "IS");
  }
}
