<?php

use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

function node_delete_redirect_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    $config = \Drupal::configFactory()
        ->getEditable('node_delete_redirect.admin_settings_form')
        ->get('ndr_admin_form_settings');

    if ($config['ndr_check']) {
        foreach ($config['ndr_settings'] as $type => $values) {
            if ($values['is_enabled']) {
                if ($form_id == "node_{$type}_delete_form") {
                    $form['#attributes']['node_delete_redirect_to'] = $values['redirect'];
                    $form['actions']['submit']['#submit'][] = 'node_delete_redirect_form_submit';
                }
            }
        }
    }
}


function node_delete_redirect_form_submit(array &$form, FormStateInterface $form_state)
{
    $response = new RedirectResponse('/' . $form['#attributes']['node_delete_redirect_to']);
    $response->send();
    exit();
}