<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function social_connect_form_alter(&$form, FormStateInterface $form_state, $form_id){
  if(in_array($form_id, ['user_login_form' , 'user_register_form'])){
    $configs = \Drupal::configFactory()->get('social_connect.settings');
    
    $global_settings = $configs->get('global');
    // social icons will only be shown if checked to show
    if(($form_id == 'user_login_form' && $global_settings['show_on_signin_form'] === 1) ||
        ($form_id == 'user_register_form' && $global_settings['show_on_signup_form'] === 1)){
      $icon = 'login_page_icons';
      $above_caption = 'login_page_above_caption';
      $below_caption = 'login_page_below_caption';
      if($form_id == 'user_register_form'){
        $icon = 'registration_page_icons';
        $above_caption = 'registration_page_above_caption';
        $below_caption = 'registration_page_below_caption';
      }
      if($global_settings[$icon] != 'disable'){
        $connection_settings = $configs->get('connections');
        $items = [];
        foreach($connection_settings as $source => $connection_setting){
          if($connection_setting['enable']){
            $button_text = (string) $connection_setting['button_text'];
            $items[] = [
              'source' => $source,
              'button_text' => t('@button_text', ['@button_text' => $button_text]),
              'id' => 'sc-id-' . $source
            ];
          }
        }
        if(!empty($items)){
          // Add js library and settings.
          $fb_settings = $connection_settings['facebook'];
          $google_settings = $connection_settings['google'];
          $form['#attached']['library'][] = 'social_connect/libraries';
          $form['#attached']['drupalSettings']['social_connect'] = [
            'debug' => $global_settings['debug'],
            'redirect_to' => $global_settings['redirect_to'],
            'facebook' => [
              'app_id' => $fb_settings['app_id'],
              'api_version' => $fb_settings['api_version']
            ],
            'google' => [
              'client_id' => $google_settings['client_id'],
            ],
          ];
          $position = $global_settings[$icon];
          $above_caption_text = t($global_settings[$above_caption]);
          $below_caption_text = t($global_settings[$below_caption]);
          if($position == 'above'){
            $form['social_connect_above_markup'] = [
              '#type' => 'markup',
              '#theme' => 'social_connect',
              '#position' => $position,
              '#above_caption' => t('@above_caption_text', ['@above_caption_text' => $above_caption_text]),
              '#below_caption' => t('@below_caption_text', ['@below_caption_text' => $below_caption_text]),
              '#items' => $items,
              '#weight' => -100
            ];
          }
          else {
            $form['social_connect_above_markup'] = [
              '#type' => 'markup',
              '#theme' => 'social_connect',
              '#position' => $position,
              '#above_caption' => $above_caption_text,
              '#below_caption' => NULL,
              '#items' => [],
              '#weight' => -100
            ];

            $form['social_connect_below_markup'] = [
              '#type' => 'markup',
              '#theme' => 'social_connect',
              '#position' => $position,
              '#above_caption' => NULL,
              '#below_caption' => $below_caption_text,
              '#items' => $items,
              '#weight' => 100
            ];
          }
        }
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function social_connect_theme(){
  return [
    'social_connect' => [
      'variables' => [
        'position' => NULL,
        'above_caption' => NULL,
        'below_caption' => NULL,
        'items' => [],
      ]
    ],
    'social_connect_block' => [
      'variables' => [
        'items' => [],
      ]
    ]
  ];
}
