<?php

/**
 * @file
 * Provides installation functions.
 */

/**
 * Implements hook_uninstall().
 */
function cloudinary_stream_wrapper_uninstall() {
  // Remove config.
  $config = \Drupal::configFactory()->getEditable('cloudinary.settings');
  $config->clear('cloudinary_stream_wrapper_folders');
  $config->clear('cloudinary_stream_wrapper_logging');
  $config->save();
}

/**
 * Remove cloudinary_stream_wrapper_enable_api_folder_creation config.
 */
function cloudinary_stream_wrapper_update_8001() {
  // Remove config.
  $config = \Drupal::configFactory()->getEditable('cloudinary_sdk.settings');
  $config->clear('cloudinary_stream_wrapper_enable_api_folder_creation');
  $config->save();
}
