<?php

/**
 * @file
 * Contains client_connection.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function client_connection_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the client_connection module.
    case 'help.page.client_connection':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage client connections and configuration to allow reusablility and consistancy with external clients.') . '</p>';
      return $output;

    default:
  }
}
