<?php
use Drupal\taxonomy\Entity\Term;


function registry_examples_namespaces_install() {
  
  $voc = 'namespaces';
  $example = Term::create([
    'name' => 'Beispiel',
    'field_description' => 'ein Namensraum an den Beispile aufgehängt werden',
    'field_namespace' => 'ex',
    'field_shortcut' => 'ex',
    'vid' => $voc,
  ]);
  $example->save();
   
  $germany = Term::create([
    'name' => 'Deutschland',
    'field_description' => 'obereste deutsche Namespace-Ebene',
    'field_namespace' => 'de',
    'field_shortcut' => 'de',
    'vid' => $voc,
  ]);
  $germany->save();
  
  $bund = Term::create([
    'name' => 'Bund',
    'field_description' => 'übergeordneter Namespace für die Bundesverwaltung',
    'field_namespace' => 'de.bund',
    'field_shortcut' => 'bund',
    'field_parent' => $germany->id(),
    'vid' => $voc,
  ]);
  $bund->save();
  
  $by = Term::create([
    'name' => 'Bayern',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Bayern',
    'field_namespace' => 'de.by',
    'field_shortcut' => 'by',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $by->save();
  
  $bw = Term::create([
    'name' => 'Baden-Württemberg',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Baden-Württemberg',
    'field_namespace' => 'de.bw',
    'field_shortcut' => 'bw',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $bw->save();
  
  $bb = Term::create([
    'name' => 'Brandenburg',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Brandenburg',
    'field_namespace' => 'de.bb',
    'field_shortcut' => 'bb',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $bb->save();
  
  $ber = Term::create([
    'name' => 'Berlin',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Berlin',
    'field_namespace' => 'de.ber',
    'field_shortcut' => 'ber',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $ber->save();
  
  $hb = Term::create([
    'name' => 'Bremen',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Bremen',
    'field_namespace' => 'de.hb',
    'field_shortcut' => 'hb',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $hb->save();
  
  $hh = Term::create([
    'name' => 'Hamburg',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Hamburg',
    'field_namespace' => 'de.hh',
    'field_shortcut' => 'hh',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $hh->save();
  
  $he = Term::create([
    'name' => 'Hessen',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Hessen',
    'field_namespace' => 'de.he',
    'field_shortcut' => 'he',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $he->save();
  
  $mv = Term::create([
    'name' => 'Mecklenburg-Vorpommern',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Mecklenburg-Vorpommern',
    'field_namespace' => 'de.mv',
    'field_shortcut' => 'mv',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $mv->save();
  
  $ni = Term::create([
    'name' => 'Niedersachsen',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Niedersachsen',
    'field_namespace' => 'de.ni',
    'field_shortcut' => 'ni',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $ni->save();
  
  $nw = Term::create([
    'name' => 'Nordrhein-Westfalen',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Nordrhein-Westfalen',
    'field_namespace' => 'de.nw',
    'field_shortcut' => 'nw',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $nw->save();
  
  $rp = Term::create([
    'name' => 'Rheinland-Pfalz',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Rheinland-Pfalz',
    'field_namespace' => 'de.rp',
    'field_shortcut' => 'rp',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $rp->save();
  
  $sl = Term::create([
    'name' => 'Saarland',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Saarland',
    'field_namespace' => 'de.sl',
    'field_shortcut' => 'sl',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $sl->save();
  
  $sn = Term::create([
    'name' => 'Sachsen',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Sachsen',
    'field_namespace' => 'de.sn',
    'field_shortcut' => 'sn',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $sn->save();
  
  $sn = Term::create([
    'name' => 'Sachsen-Anhalt',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Sachsen-Anhalt',
    'field_namespace' => 'de.sn',
    'field_shortcut' => 'sn',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $sn->save();
  
  $sh = Term::create([
    'name' => 'Schleswig-Holstein',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Schleswig-Holstein',
    'field_namespace' => 'de.sh',
    'field_shortcut' => 'sh',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $sh->save();
  
  $th = Term::create([
    'name' => 'Thüringen',
    'field_description' => 'übergeordneter Namespace für die Landesverwaltung von Thüringen',
    'field_namespace' => 'de.th',
    'field_shortcut' => 'th',
    'vid' => $voc,
    'field_parent' => $germany->id(),
  ]);
  $th->save();
  
}

function registry_examples_namespaces_uninstall() {
   
}

