<?php

/**
 * @file
 * Reading time module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_extra_field_info().
 */
function node_read_time_entity_extra_field_info() {

  $config = \Drupal::config('node_read_time.settings');
  $bundles = $config->get('reading_time')['container'];
  $extra = NULL;

  if ($bundles) {
    foreach ($bundles as $machine_name => $bundle) {
      if ($bundle['is_activated']) {
        $extra['node'][$machine_name]['display']['reading_time'] = [
          'label' => t('Reading time'),
          'description' => t('This field is used to display the reading time of a node.'),
          'weight' => 100,
          'visible' => TRUE,
        ];
      }
    }
  }

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function node_read_time_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('reading_time')) {
    $config = \Drupal::config('node_read_time.settings')
      ->get('reading_time')['container'];

    if ($config[$entity->getType()]['is_activated']) {
      $words_per_minute = \Drupal::config('node_read_time.settings')->get('reading_time')['words_per_minute'];
      $reading_time_service = \Drupal::service('reading_time');
      $reading_time = $reading_time_service
        ->setWordsPerMinute($words_per_minute)
        ->collectWords($entity)
        ->calculateReadingTime()
        ->getReadingTime();

      //Clear the words variable.
      $reading_time_service->setWords(0);

      $build['reading_time'] = [
        '#theme' => 'reading_time',
        '#reading_time' => $reading_time,
      ];
    }

  }
}

/**
 * Implements hook_theme().
 */
function node_read_time_theme() {
  return [
    'reading_time' => [
      'variables' => [
        'reading_time' => NULL,
        'template' => 'reading-time',
      ],
    ],
  ];
}
