/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  'use strict';

  Drupal.behaviors.plotlyjs = {
    attach: function attach(context, settings) {

      $.each(settings.plotlyjs, function (key, graph) {
        $.each($(context).find('#' + graph.unique_id).once('generate-plotly'), function (index, item) {

          if (typeof graph.mapbox_access_token !== 'undefined' && graph.mapbox_access_token !== '') {
            Plotly.setPlotConfig({
              mapboxAccessToken: graph.mapbox_access_token
            });
          }

          Plotly.newPlot(graph.unique_id, graph.series, graph.layout, {responsive: graph.layout.responsive})
        });
      });

    }
  };
})(jQuery, Drupal);
