<?php

/**
 * @file
 * Contains gitlab_time_tracker.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gitlab_time_tracker_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gitlab_time_tracker module.
    case 'help.page.gitlab_time_tracker':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Timetracking information fetcher') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function gitlab_time_tracker_cron() {
  \Drupal::service('gitlab_time_tracker.migration_controller')->migrateUsers();
  \Drupal::service('gitlab_time_tracker.migration_controller')->migrateProjects();
}

/**
 *
 */
function gitlab_time_tracker_migrate_timetracks($issue_id) {
  $node = node_load($issue_id);
  \Drupal::service('gitlab_time_tracker.migration_controller')->migrateTimeTrack(
    $node->field_project->entity->field_gitlab_id->value,
    $node->field_gitlab_iid->value,
    FALSE
  );
}
