<?php

/**
 * @file
 * The hook implementations for the entity import module.
 */

use Drupal\Core\Link;

/**
 * Implements hook_theme().
 */
function entity_import_theme($existing, $type, $theme, $path) {
  return [
    'entity_import_list' => [
      'variables' => ['content' => NULL],
    ],
  ];
}

/**
 * Prepares variables for list of available entity importers.
 *
 * Default template: entity-import-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: An array of entity importers.
 *
 */
function template_preprocess_entity_import_list(&$variables) {
  $variables['importers'] = [];

  if (!empty($variables['content'])) {
    /** @var \Drupal\entity_import\Entity\EntityImporter $importer */
    foreach ($variables['content'] as $importer) {
      $variables['importers'][$importer->id()] = [
        'type' => $importer->id(),
        'link' => Link::createFromRoute(
            $importer->label(),
            'entity_import.importer.page.import_form',
            ['entity_importer' => $importer->id()]
          )->toRenderable(),
        'description' => [
          '#markup' => $importer->getDescription(),
        ],
      ];
    }
  }
}
