<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wow" nsURI="http://wow/1.0" nsPrefix="wow">
  <eClassifiers xsi:type="ecore:EClass" name="Realm" eSuperTypes="#//WoW\Core\Entity/Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="#//WoW\Core\Entity/Entity #//WoW\Core\Entity/Data"/>
  <eClassifiers xsi:type="ecore:EClass" name="Guild" eSuperTypes="#//WoW\Core\Entity/Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Achievement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id"/>
  </eClassifiers>
  <eSubpackages name="WoW\Core\Entity">
    <eClassifiers xsi:type="ecore:EClass" name="Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="region"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastFetched"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Data">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="language"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="WoW\Character\Entity">
    <eClassifiers xsi:type="ecore:EClass" name="Character" eSuperTypes="#//WoW\Core\Entity/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="Race" eSuperTypes="#//WoW\Core\Entity/Data">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mask"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="side"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//WoW\Core\Entity/Data">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mask"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="powerType"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
