<?php

/**
 * @file
 * Contains chatwindow.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function chatwindow_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chatwindow module.
    case 'help.page.chatwindow':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Chat window for the rasa NLP, rasa core') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function chatwindow_theme() {
  return [
    'chatwindow' => [
      'render element' => 'children',
    ],
   'chatwindowjsdata' => [		
		'template' => 'block--chatwindowjs',
		'variables' => ['modulepath' => NULL, 'baseurl' => NULL , 'dontaddcssforbot' => NULL]
	],
	
	
  ];
}
