<?php

/*
 * @file
 *
 */

use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_help().
 */
function pe_academic_year_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.pe_academic_year':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('TODO') . '</p>';
      return $output;
  }
}
