<?php
use \Drupal\Core\Datetime\Entity\DateFormat;

module_load_include('inc', 'shamsi', 'jDateTime');


/**
 * Implements template_preprocess_node().
 */ 
function shamsi_preprocess_node(&$variables){

	$language = \Drupal::languageManager()->getCurrentLanguage()->getId();

	if($language == 'fa'){
		$date = $variables['node']->getCreatedTime();
		$format = DateFormat::load('medium')->getPattern();
		$variables['date'] = jDateTime::date($format, $date, null, null, drupal_get_user_timezone());
	
	}


}

/**
 * Implements template_preprocess_comment().
 */ 
function shamsi_preprocess_comment(&$variables){

	$language = \Drupal::languageManager()->getCurrentLanguage()->getId();

	if($language == 'fa'){
		$date = $variables['elements']['#comment']->getCreatedTime();
		$format = DateFormat::load('medium')->getPattern();
		$variables['created'] = jDateTime::date($format, $date, null, null, drupal_get_user_timezone());
	
	}


}
