<?php

/**
 * @file
 * Contains bs_git.module.
 */

// Define constants.
const BS_GIT_FILE_NEW = '?';
const BS_GIT_FILE_ADDED = 'A';
const BS_GIT_FILE_CHANGED = 'M';
const BS_GIT_FILE_DELETED = 'D';

use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function bs_git_help($route_name) {
  $output = '';
  switch ($route_name) {
    // Main module help for the bs_git module.
    case 'help.page.bs_git':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Be sure about integrity of your files (git)') . '</p>';

    default:
  }

  return $output;
}

/**
 * Implements hook_sure_info_alter().
 */
function bs_git_sure_info_alter(&$items) {
  if (isset($items['security']) && $git_command = bs_git_get_command()) {
    array_unshift($items['security']['elements'][0]['items'], [
      'ok' => 'No changed files',
      'nok' => 'Files were changed, see more !link',
      'callback' => 'bs_git_check',
      'args' => [
        '!link' => \Drupal::l(
          t('here'),
          Url::fromRoute('bs_git.files_status')
        ),
      ],
    ]);
  }
}

/**
 * Check if git is used in current project.
 *
 * @return bool|string
 */
function bs_git_get_command() {
  $git_command = &drupal_static(__FUNCTION__);

  if (!is_null($git_command)) {
    return $git_command;
  }

  if (function_exists('exec')) {
    exec('command -v git', $output, $retval);
    if ($retval != 0) {
      $git_command = FALSE;
    }
    else {
      $git_command = $output[0];

      exec(escapeshellcmd($git_command) . ' status > /dev/null 2>&1', $output, $retval);
      if ($retval != 0) {
        $git_command = FALSE;
      }
    }
  }
  else {
    $git_command = FALSE;
  }

  return $git_command;
}

/**
 * Get status of local git repo.
 */
function _bs_git_get_status() {
  $git_command = bs_git_get_command();
  $output = [];

  exec(escapeshellcmd($git_command) . ' status --porcelain', $output, $return_val);

  return $output;
}

/**
 * Check status of changed files.
 */
function bs_git_check() {
  return !_bs_git_get_status();
}
