<?php
/**
 * @file
 * Save Form State
 * This module periodically saves your form state to local storage.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function form_save_state_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_ids = \Drupal::configFactory()->getEditable('form_save_state.settings')->get('form_ids');

  if (!empty($form_ids[$form_id])) {
    $form['#attached']['library'][] = 'form_save_state/save';
    $form['#attached']['drupalSettings']['form_save_state']['form_id'] = str_replace('_', '-', $form_id);
  }
}
