<?php

/**
 * Implements hook_theme().
 */
function smart_glossary_theme($existing, $type, $theme, $path) {
  return array(
    // The Header: A-Z, languages, ...
    'smart_glossary_header' => array(
      'variables' => array(
        'glossary_id' => '',
        'glossary_path' => '',
        'character_list' => NULL,
        'current_language' => '',
      ),
    ),
    // The start page of the glossary.
    'smart_glossary_start' => array(
      'variables' => array(
        'module_path' => drupal_get_path('module', 'smart_glossary'),
        'glossary_id' => '',
        'glossary_path' => '',
        'visual_mapper_available' => FALSE,
        'visual_mapper_settings' => '',
        'current_language' => '',
      ),
    ),
    // A list of concepts to choose from.
    'smart_glossary_list' => array(
      'variables' => array(
        'list' => NULL,
      ),
    ),
    // A detailed view of a concept with the visual mapper.
    'smart_glossary_detail' => array(
      'variables' => array(
        'module_path' => drupal_get_path('module', 'smart_glossary'),
        'glossary_id' => '',
        'glossary_path' => '',
        'visual_mapper_available' => FALSE,
        'term' => NULL,
        'visual_mapper_settings' => '',
        'current_language' => '',
        'rdf_url' => '',
        'endpoint_url' => '',
      ),
    ),
    // The Visual Mapper.
    'smart_glossary_visual_mapper' => array(
      'variables' => array(
        'glossary_id' => '',
        'glossary_path' => '',
        'visual_mapper_available' => FALSE,
        'concept_uri' => '',
        'visual_mapper_settings' => '',
        'current_language' => '',
      ),
    ),
  );
}