<?php

/**
 * Implements hook_menu().
 */
function qunit_menu() {
  $items['admin/config/development/qunit'] = array(
    'title' => 'JavaScript testing',
    'description' => "Run the tests for Drupal's JavaScript code, which will make sure that the JavaScript works properly your browser.",
    'page callback' => 'qunit_run_tests',
    'access arguments' => array('administer unit tests'),
  );

  $items['qunit/ajax'] = array(
    'page callback' => 'qunit_ajax',
   // @TODO. 'access arguments' => array('administer unit tests'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['qunit/test'] = array(
    'page callback' => 'qunit_test',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu callback. Displays static HTML as prepared by a test.
 */
function qunit_test() {
  $db_prefix = $_COOKIE['simpletest_db_prefix'];

  // Push our database prefix onto the global database connection configuration
  // and update the static variable cache.
  $connection_info = Database::getConnectionInfo('default');
  if ($db_prefix != $connection_info['default']['prefix']['default']) {
    Database::renameConnection('default', 'simpletest_original_default');
    foreach ($connection_info as $target => $value) {
      $connection_info[$target]['prefix'] = array(
        'default' => $value['prefix']['default'] . $db_prefix,
      );
    }
    Database::addConnectionInfo('default', 'default', $connection_info['default']);
    cache('bootstrap')->expire();
    cache_clear_all();
    $GLOBALS['conf'] = variable_initialize();
  }

  $content = variable_get('qunit_test_content_' . $db_prefix, '');
  $js = variable_get('qunit_test_js_' . $db_prefix, array());
  $library = variable_get('qunit_test_library_' . $db_prefix, array());
  foreach ($js as $js_file) {
    drupal_add_js($js_file);
  }
  foreach ($library as $lib) {
    drupal_add_library($lib[0], $lib[1]);
  }
  return $content;
}

/**
 * Implements hook_library_info().
 */
function qunit_library_info() {
  $libraries['qunit'] = array(
    'title' => 'QUnit',
    'website' => 'http://docs.jquery.com/QUnit',
    'version' => '20110420',
    'js' => array(
      // The QUnit JavaScript library.
      drupal_get_path('module', 'qunit') . '/qunit/qunit/qunit.js' => array('weight' => JS_LIBRARY),
      // The QUnit Drupal behavior.
      drupal_get_path('module', 'qunit') . '/qunit.admin.js' => array(),
    ),
    'css' => array(
      // The QUnit library CSS framework.
      drupal_get_path('module', 'qunit') . '/qunit/qunit/qunit.css' => array(),
      // CSS fixes to make QUnit look nicer when in Drupal.
      drupal_get_path('module', 'qunit') . '/qunit.admin.css' => array(),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_library_info_alter().
 */
function qunit_library_info_alter(&$libraries, $module) {
  // Add available JavaScript tests and dependencies.
  if ($module == 'qunit') {
    $libraries['qunit']['js'][drupal_get_path('module', 'qunit') . '/tests/collapse.test.js'] = array();
    $libraries['qunit']['js'][drupal_get_path('module', 'qunit') . '/tests/autocomplete.test.js'] = array();
    $libraries['qunit']['js'][drupal_get_path('module', 'qunit') . '/tests/drupal.test.js'] = array();
    $libraries['qunit']['js'][drupal_get_path('module', 'qunit') . '/tests/jquery.once.test.js'] = array();
  }
}

/**
 * Menu callback; Page to run all the JavaScript tests.
 */
function qunit_run_tests() {
  drupal_add_library('qunit', 'qunit');
  $settings = array('formToken' => drupal_get_token('qunit'));
  drupal_add_js($settings, 'setting');
  $output = '<div id="qunit-wrapper"><h1 id="qunit-header">QUnit Test Suite</h1><h2 id="qunit-banner"></h2><div id="qunit-testrunner-toolbar"></div><h2 id="qunit-userAgent"></h2><ol id="qunit-tests"></ol><div id="qunit-fixture">test markup</div><iframe id="qunit-test-iframe" /></div>';
  return $output;
}

/**
 * Menu callback: run setUp or tearDown to support a JavaScript class.
 */
function qunit_ajax($class, $action) {
  if ($action != 'setUp' && $action != 'tearDown') {
    return drupal_not_found();
  }
  if (!drupal_valid_token($_POST['token'], 'qunit')) {
   // @TODO: this needs to happen, but causees bugs. return drupal_access_denied();
  }
  $instance = new $class();
  if (!($instance instanceof DrupalQUnitTestCase)) {
    return drupal_not_found();
  }
  if (method_exists($instance, $action)) {
    $instance->$action();
  }
  if ($action == 'setUp') {
    drupal_json_output(array('dbPrefix' => $instance->getDbPrefix()));
 }
}
