<?php

/**
 * @file hookalyzer.module
 */

/**
 * Implements hook_theme().
 */
function hookalyzer_theme() {
  return array(
    'hookalyzer_html_table' => array(
      'variables' => array('cid' => NULL, 'collections' => NULL),
      'template' => 'hookalyzer_html_table',
    ),
  );
}

function template_preprocess_hookalyzer_html_table(&$variables) {
  drupal_add_css(drupal_get_path('module', 'hookalyzer') . '/css/hookalyzer.css');
  foreach ($variables['collections'] as $id => $collection) {
    foreach ($collection as $name => $diff) {
      switch ($diff->getChangeType() & 0x07) {
        case 0x00:
          $diff->class = 'unchanged';
          break;

        case 0x01:
          $diff->class = 'added';
          break;

        case 0x02:
          $diff->class = 'removed';
          break;

        case 0x04:
          $diff->class = 'changed';
          break;
      }
    }
  }
}
