<?php

/**
 * @file
 * Install, update and uninstall functions for the dea_request module.
 */

/**
 * Rename path to request_path avoiding special treatment of path field, e. g. by pathauto
 * https://www.drupal.org/node/2673628
 *
 */
function dea_request_update_8001() {
  $schema = \Drupal\Core\Database\Database::getConnection()->schema();
  $schema->changeField('dea_request', 'path', 'request_path',  array('type' => 'varchar', 'length' => 255));
}