<?php

/**
 * @file
 * File utility module files.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_page_attachments().
 */
function file_utility_page_attachments(array &$attachments) {
  // Get open modal form value.
  $attachments['#attached']['library'][] = 'file_utility/file_utility_js';
  $file_utility_obj = \Drupal::config('file_utility.fileutilityconfigurations');
  $open_model_file = $file_utility_obj->get('open_model_file');
  $attachments['#attached']['drupalSettings']['open_model_file'] = $open_model_file;
  $force_download = $file_utility_obj->get('file_force_download');
  $attachments['#attached']['drupalSettings']['file_force_download'] = $force_download;
  $allowed_extensions = $file_utility_obj->get('allowed_extensions');
  if (!empty($allowed_extensions)) {
    $allowed_extensions = str_replace([',', ' '], ['|', ''], $allowed_extensions);
  }
  $attachments['#attached']['drupalSettings']['allowed_file_extensions'] = $allowed_extensions;
}

/**
 * Implements hook_help().
 */
function file_utility_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the file_utility module.
    case 'help.page.file_utility':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide additional file feature such as popup form for private file system') . '</p>';
      $output .= '<pre>' . file_get_contents(__DIR__ . '/README.txt') . '</pre>';
      return $output;

    default:
  }
}

/**
 * File utility download permission;.
 */
function file_utility_entity_access($entity, $operation, $account) {
  if ($operation == 'download' && !$account->hasPermission('file download access')) {
    return AccessResult::forbidden();
  }
}

/**
 * Implements hook_form_alter().
 */
function file_utility_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Control fields access.
  if ('content_entity_file_utility_add_form' == $form_id) {
    $form['file_path']['#access'] = FALSE;
    $form['ip_address']['#access'] = FALSE;
    $form['count']['#access'] = FALSE;
    $form['user_id']['#access'] = FALSE;
    $form['fid']['#access'] = FALSE;
  }
}
