<?php

/**
 * @file
 * Localize Drupal websites with the help of professional translation tools.
 *
 * Translate pages and posts while preserving images, layouts
 * and any custom HTML.
 * The plugin pulls posts and pages from Drupal, parses text
 * and presents it to the translator in a clean view.
 * After translation, the pages and posts are rebuilt with graphics.
 */

use Symfony\Component\HttpFoundation\Request;

/**
 * A global function to check the token validity for each request.
 *
 * @param Request $request
 *   HTTP request object.
 *
 * @return array|mixed
 *   An authentication token or error message.
 */
function memsource_connector_check_auth(Request $request) {
  $token = $request->get('token');
  if ($token !== memsource_connector_get_token()) {
    return array('error' => 'Invalid token: ' . $token);
  }
  return $token;
}

/**
 * Get the generated authentication token from the config.
 *
 * @return array|mixed|null
 *   An authentication token.
 */
function memsource_connector_get_token() {
  return \Drupal::configFactory()
    ->get('config.memsource_config')
    ->get('connector_token');
}
