<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nasa_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.nasa':
      return t('
        <h2>NASA</h2>
        <h3>Instructions</h3>
        <p>Unpack in the <em>modules</em> folder (currently in the root of your Drupal 8 installation) and enable in <strong>/admin/modules</strong>.</p>
        <p>Then, visit <strong>/admin/config/development/nasa</strong> and enter your own NASA API key.</p>
      ');
  }
}

/**
 * Implements hook_theme().
 */
function nasa_theme($existing, $type, $theme, $path) {
  $variables = array(
    'nasa_apod_block' => array(
      'variables' => array(
        'title' => NULL,
        'image' => NULL,
        'apod_title' => NULL,
        'explanation' => NULL
      ),
    ),
  );
  return $variables;
}