<?php

/**
 * @file
 * Contains timetable_cron.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function timetable_cron_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the timetable_cron module.
    case 'help.page.timetable_cron':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extend core cron functionality with timetable') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_operation().
 */
function timetable_cron_entity_operation(EntityInterface $entity) {
  $operations = [];
  $info = $entity->getEntityType();
  if ($info->id() == 'timetable_cron') {
    $operations['force'] = [
      'title' => t('Force'),
      'weight' => -1,
      'url' => Url::fromRoute('entity.timetable_cron.force_form', [$entity->getEntityTypeId() => $entity->id()]),
    ];
  }

  return $operations;
}

/**
 * Implements hook_entity_operation_alter().
 */
function timetable_cron_entity_operation_alter(array &$operations, EntityInterface $entity) {
  $info = $entity->getEntityType();
  if ($info->id() == 'timetable_cron') {
    // Remove translate from operations.
    unset($operations['translate']);
  }

  return $operations;
}
