<?php

/**
 * @file
 * Contains entity_backreference.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\entity_backreference\Utility\EntityBackReferenceHelper;

/**
 * Implements hook_help().
 */
function entity_backreference_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_backreference module.
    case 'help.page.entity_backreference':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Back Reference fields for Entities') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function entity_backreference_theme() {
  return [
    'entity_backreference' => [
      'template' => 'entity_backreference',
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_entity_insert().
 */
function entity_backreference_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  EntityBackReferenceHelper::checkForIndex($entity,'insert');
}

/**
 * Implements hook_entity_update().
 */
function entity_backreference_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
  EntityBackReferenceHelper::checkForIndex($entity,'update');
}

/**
 * Implements hook_entity_delete().
 */
function entity_backreference_entity_delete(Drupal\Core\Entity\EntityInterface $entity) {
  EntityBackReferenceHelper::checkForIndex($entity,'delete');
}

