<?php

/**
 * @file
 * Youtube formatter module, to display a youtube shortlink as a video or imagepreview.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function youtube_formatter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.youtube_formatter':
      $output = '<h3>' . t('Youtube preview') . '</h3>';
      $output .= '<p>' . t('This formatter will display the preview image, provided by youtube, in a selected image_style.') . '</p>';
      $output .= '<h3>' . t('Youtube video') . '</h3>';
      $output .= '<p>' . t('Embed the video via iframe. The size and some options are avalible to configure the video.') . '</p>';
      return $output;
  }
}
