<?php

/**
 * @file
 * File for the cloudinary_storage_db module.
 */

use Drupal\cloudinary_storage_db\CloudinaryStorageDb;

/**
 * Implements hook_cloudinary_storage_info().
 */
function cloudinary_storage_db_cloudinary_storage_info() {
  return array(
    'cloudinary_storage_db' => array(
      'title' => t('Database'),
      'class' => '\Drupal\cloudinary_storage_db\CloudinaryStorageDb',
    ),
  );
}
