<?php

/**
 * @file
 * Builds help for Community Funded campaigns.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function community_funded_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.community_funded':
      $output = '<h3>' . t('About Community Funded') . '</h3>';
      $output .= '<p>' . t('This module allows you to use your user ID from CommunityFunded.com to display your campaign page via a block.') . '</p>';
      $output .= '<h4>' . t('To display your campaigns:') . '</h4>';
      $output .= '<p>' . t('Download module and install as usual. Once enabled, the module will provide a custom block called "Community Funded." Place this block where you would like to display your campaigns.') . '</p>';
      $output .= '<p>' . t('Once placed, the block will display, "No user ID set" until you input your Data User ID from Community Funded.') . '</p>';
      $output .= '<p>' . t('Navigate to the Community Funded block\'s configuration and enter your User ID into the textarea labelled "Community Funded User ID" in the Community Funded block and click "Save configuration." Your campaigns should now display within the Community Funded block that you\'ve placed.') . '</p>';
      $output .= '<h4>' . t('Quick troubleshooting:') . '</h4>';
      $output .= '<p>' . t('If your campaigns do not display:') . '</p>';
      $output .= '<ul><li>' . t('Check "Administer Community Funded" permission (admin/people/permissions)') . '</li>';
      $output .= '<li>' . t('Check the console for JS errors') . '</li>';
      $output .= '<li>' . t('Check block placement and block permissions/display options') . '</li></ul>';
      $output .= '<p>' . t('Check existing issues in the issue queue before opening a new one to make sure your question hasn\'t already been asked and/or answered.') . '</p>';
      return $output;
  }
}
