<?php

/**
 * @file
 *
 * This module provides comment follow-up e-mail notification for anonymous and registered users.
 */

use Drupal\comment\CommentInterface;
use Drupal\Component\Render\PlainTextOutput;
use Drupal\Component\Utility\Html;
use Drupal\Component\Utility\Unicode;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Language\LanguageInterface;
use Drupal\node\Entity\NodeType;
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\SafeMarkup;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Drupal\Core\Form\ConfigFormBase;



/**
 * Implements hook_form_alter()
 */
function comment_notification_form_alter(&$form, FormStateInterface $form_state, $form_id){
    if($form_id == 'comment_comment_form'){
      $form['actions']['submit']['#submit'][] = 'comment_notification_details';
	}
}

function comment_notification_details($form, FormStateInterface $form_state){
    $anonymous_content = \Drupal::config('comment_notification.mail_settings')->get('comment_notification.anonymous_usermail');
    $comment_approver = \Drupal::config('comment_notification.mail_settings')->get('comment_notification.mail_approver');
    $aunthenticated_user_content = \Drupal::config('comment_notification.mail_settings')->get('comment_notification.authenticated_usermail');
    $author_notification = \Drupal::config('comment_notification.mail_settings')->get('comment_notification.author_notification');

	$current_user = \Drupal::currentUser();
    $roles = $current_user->getRoles();
	$mail = $form_state->getValue('field_email_address');
	$commenter_mail = $mail[0]['value'];
    
	
	$path = \Drupal::service('path.current')->getPath();
	$path_args = explode('/', $path);
	$node_authorid = db_query("select uid from node_field_data  where nid = :nid",array(':nid' => $path_args[4]))->fetchField();
    $node_author_details = \Drupal::service('entity_type.manager')->getStorage('user')->load($node_authorid);
    $author_mail =  $node_author_details ->get('mail')->value;
    $langcode = \Drupal::languageManager()->getCurrentLanguage()->getName();
    
    $mailManager = \Drupal::service('plugin.manager.mail');
    $module = 'comment_notification';
    
    //Notification mail for anonymous and Node author.
    if(($key = 'comment_notify_commenter') && (in_array('anonymous',$roles))){
        $anonymous_params = array(
    		'body' => $anonymous_content,
    		'subject' => t('Comment for Approval'),
        );
    
        $send = true;
        $anonymous_result = $mailManager->mail($module, $key, $commenter_mail, $langcode, $anonymous_params, NULL, $send);

        $node_author_params = array(
    		'body' => $comment_approver,
    		'subject' => t('Comment Submission'),
        );
        $node_author_result = $mailManager->mail($module, $key, $author_mail, $langcode, $node_author_params, NULL, $send);
    }
    
    //Notifiaction for Authenticated user and Node author.
    else {
    	$authenticated_params = array(
    		'body' => $aunthenticated_user_content ,
        	'subject' => t('Comment Notification'),
        );
        $send = true;
        $authenticated_result = $mailManager->mail($module, $key, $commenter_mail, $langcode, $authenticated_params, NULL, $send);


        $authenticated_node_author_params = array(
    		'body' => $author_notification,
    		'subject' => t('Comment Submission'),
        );
       $authenticated_node_author_result = $mailManager->mail($module, $key, $author_mail, $langcode, $authenticated_node_author_params, NULL, $send);
    }
}

/**
 * Implements hook_mail().
 */
function comment_notification_mail($key, &$message, $params) {
    $options = array(
		'langcode' => $message['langcode'],
	);
	switch ($key) {
		case 'comment_notify_commenter':
		$message['from'] = \Drupal::config('system.site')->get('mail');
        $message['subject'] = $params['subject'];
        $message['body'][] = $params['body'];
        $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
        break;
    }
}