<?php

/**
 * @file
 * Custom Powered By Module.
 */

use Drupal\Core\Block\BlockPluginInterface;

/**
 * {@inheritdoc}
 */
function custom_poweredby_block_view_alter(array &$build, BlockPluginInterface $block) {
  if ($block->getBaseId() === 'system_powered_by_block') {
    $build['#pre_render'][] = '_custom_poweredby_block_poweredby_prerender';
  }
}

/**
 * {@inheritdoc}
 */
function _custom_poweredby_block_poweredby_prerender(array $build) {
  $my_config = \Drupal::config('custom_poweredby.settings')->get('poweredby_text');
  $build['content']['#markup'] = $my_config;
  return $build;
}
