<?php

/**
 * @file metatag_current_page_title_override.module
 * Allows users to override the [current-page:title] token in the Basic Metatags
 * section when editing entities that use the MetatTags forms.
 */

/**
 * Implements hook_tokens_alter().
 */
function metatag_current_page_title_override_tokens_alter(array &$replacements, array $context, \Drupal\Core\Render\BubbleableMetadata $bubbleable_metadata) {
  if ($context['type'] === 'current-page' && array_key_exists('title', $context['tokens'])) {
    $metatag_manager = \Drupal::service('metatag.manager');
    if (array_key_exists('node', $context['data'])) {
      $metatags = $metatag_manager->tagsFromEntity($context['data']['node']);
    }
    elseif (array_key_exists('taxonomy_term', $context['data'])) {
      $metatags = $metatag_manager->tagsFromEntity($context['data']['taxonomy_term']);
    }

    if (array_key_exists('current-page-title-override', $metatags)) {
      $replacements[$context['tokens']['title']] = $metatags['current-page-title-override'];
    }
  }
}
