<?php

use Drupal\Core\Url;
use Drupal\node\NodeInterface;


/**
 *
 * Helper function
 *
 * @param $div
 * @param string $lang
 * @param $url
 * @return array
 */
function gplus_comments_block_render_content_block($div,  $url) {
  $content['#attached']['js'][] = array(
    'data' => drupal_get_path('module', 'gplus_comments_block') . '/js/gplus_comments_block.js',
  );
  $content['#attached']['js'][] = array(
    'type' => 'external',
    'data' => 'https://apis.google.com/js/plusone.js',
  );
  $content['#attached']['js'][] = array(
    'type' => 'inline',
    'data' => "window.___gcfg = {lang: 'en'};",
  );
  $content['#attached']['js'][] = array(
    'type' => 'setting',
    'data' => array('gplus_comments_block' => array($div => array('url' => $url))),
  );

  drupal_process_attached($content);

  return array(
    '#markup' => "<div id='$div'></div>"
  );
}

/**
 * Implement hook_theme()
 */
function gplus_comments_block_block_theme() {
  return array(
    'gplus_comments_block_count' => array(
      'variables' => array('url' => NULL),
      'template' => 'gplus_comments_block_count'
    ),
  );
}

/**
 * Implements hook_node_links_alter().
 */
function gplus_comments_block_node_links_alter(array &$node_links, NodeInterface $node, array &$context) {
  $view_mode = $context['view_mode'];

  switch ($view_mode) {
    case 'teaser':
      $current_url = Url::fromRoute('entity.node.canonical', array(
        'node' => $node->id(),
      ), array('absolute' => TRUE));
      $links = array();
      $links['gplus_comments_block_count'] = array(
        'title' => array('#theme' => 'gplus_comments_block_count', '#url' => $current_url),
        'url' => $current_url,
        'html' => TRUE,
      );
      $node_links['gplus_comments_block_count'] = array(
        '#theme' => 'links__node__gplus_comments_block',
        '#links' => $links,
        '#attributes' => array('class' => array('links', 'inline')),
      );

      break;
  }
}
