<?php

/**
 * @file
 * Contains sinceago.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */
function sinceago_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sinceago module.
    case 'help.page.sinceago':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Converts dynamic timestamps to a &#039;time ago&#039; format using jQuery with graceful degredation.') . '</p>';
      $output .= check_markup(file_get_contents(dirname(__FILE__) . "/README.txt"));
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function sinceago_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'sinceago/drupal.sinceago';

  $config = \Drupal::config('sinceago.sinceago');

  $settings = [
    'refreshMillis' => $config->get('refresh_timeago'),
    'allowFuture' => $config->get('allow_future'),
    'localeTitle' => FALSE,
    'cutoff' => 0,
    'strings' => $config->get('strings'),
  ];

  $attachments['#attached']['drupalSettings']['sinceago'] = $settings;
}

/**
 * Implements hook_preprocess_field().
 */
function sinceago_preprocess_field__node__created(&$variables) {
  // Get a few convenient handles.
  $sinceago_node = \Drupal::config('sinceago.sinceago')->get('sinceago_node');
  if ($sinceago_node) {
    $create = $variables['element']['#object']->get('created')->getValue();
    if (is_array($create)) {
      foreach ($create as $key => $val) {
        $variables['attributes']['title'][] = date('c', $val['value']);
      }
    }
    $variables['attributes']['class'][] = Html::escape('node-sinceago');
  }

  $entity = $variables['element']['#object'];
  $field_name = $variables['element']['#field_name'];
  $view_mode = $variables['element']['#view_mode'];
}

/**
 * Implements hook_preprocess_field().
 */
function sinceago_preprocess_field__comment(&$variables) {
  $timeago_comment = \Drupal::config('sinceago.sinceago')->get('timeago_comment');
  if (!$timeago_comment) {
    $variables['attributes']['class'][] = Html::escape('comment-sinceago-wrapper');
  }
}

/**
 * Implements hook_preprocess_comment().
 */
function sinceago_preprocess_comment(&$variables) {
  $date = $variables['comment']->getCreatedTime();
  $timeago_comment = \Drupal::config('sinceago.sinceago')->get('timeago_comment');
  if (!$timeago_comment) {
    $create = $variables['comment']->getCreatedTime();
    $cid = $variables['comment']->id();
    $variables['attributes']['title'][] = date('c', $create);
    $variables['attributes']['class'][] = Html::escape('comment-sinceago');
  }
}

/**
 * Implements hook_preprocess_field().
 */
function sinceago_preprocess_field__node_post_date(&$variables) {

  $sinceago_node = \Drupal::config('sinceago.sinceago')->get('sinceago_node');
  if ($sinceago_node) {
    $create = $variables['element']['#object']->get('created')->getValue();
    if (is_array($create)) {
      foreach ($create as $key => $val) {
        $variables['attributes']['title'][] = date('c', $val['value']);
      }
    }
    $variables['attributes']['class'][] = Html::escape('node-sinceago');
  }

  $entity = $variables['element']['#object'];
  $field_name = $variables['element']['#field_name'];
  $view_mode = $variables['element']['#view_mode'];
}
