<?php

/**
 * @file
 * Contains purest_recaptcha.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function purest_recaptcha_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the purest_recaptcha module.
    case 'help.page.purest_recaptcha':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('PuRest Recaptcha adds a service and configuration options for validating Recaptcha.') . '</p>';
      return $output;

    default:
  }
}
