<?php

/**
 * @file
 * Contains dcat_landingpage.module.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 *
 * Fix dataset_landingpage view title.
 */
function dcat_views_pre_render(ViewExecutable $view) {
  if ($view->id() === 'dataset_landingpage' && !empty($view->args[0])) {
    $dataset = \Drupal\dcat\Entity\DcatDataset::load($view->args[0]);
    if (!empty($dataset)) {
      $view->build_info['title'] = $dataset->label();
    }
  }
}
