<?php

/**
 * @file
 * Contains commerce_shopping_hours.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function commerce_shopping_hours_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_shopping_hours module.
    case 'help.page.commerce_shopping_hours':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Define shopping hours of your Drupal 8 Commerce shop.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function commerce_shopping_hours_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $current_route = \Drupal::routeMatch()->getRouteName();
  $commerce_shopping_hours_service = \Drupal::service('commerce_shopping_hours.commerce_shopping_hours_service');
  $is_open = $commerce_shopping_hours_service->isShopOpen();
  if ($current_route == 'commerce_checkout.form' && !$is_open) {
    $form['#action'] = '/shop-closed';
  }
}

/**
 * Implements hook_theme().
 */
function commerce_shopping_hours_theme($existing, $type, $theme, $path) {
  return [
    'commerce_shopping_hours' => [
      'variables' => [
        'is_open' => TRUE,
        'message' => '',
        'show_shopping_hours' => TRUE,
        'shopping_hours' => '',
      ],
    ],
  ];
}
