<?php

/**
 * @file
 * Debug module.
 */

use Drupal\dbg\Debug;

/**
 * Helper function for simple debugging.
 *
 * @param mixed $variable
 *   The variable to be debugged.
 * @param string $group
 *   The group of the debug information.
 *
 * @return \Drupal\dbg\Debug
 *   New Debug object.
 */
function dbg($variable, string $group = '_none'): Debug {
  return new Debug($variable, $group);
}

/**
 * Implements hook_page_attachments().
 */
function dbg_page_attachments(array &$attachments): void {
  // Attach dbg css, js to all of the pages.
  if (\Drupal::currentUser()->hasPermission('view dbg output') && isset($_SESSION['dbg_information'])) {
    $attachments['#attached']['library'][] = 'dbg/assets';
  }
}

/**
 * Implements hook_page_top().
 */
function dbg_page_top(array &$page_top) {
  // Render debug message if the user has permission.
  if (\Drupal::currentUser()->hasPermission('view dbg output')) {
    $message = '';
    if (isset($_SESSION['dbg_information'])) {
      foreach ($_SESSION['dbg_information'] as $tag => $dbg) {
        $message .= "<div class='dbg-tag tag-{$tag}'>";

        if ($tag != '_none') {
          $message .= "<div class='tag-name'>{$tag}</div>";
        }

        foreach ($dbg as $key => $info) {
          $message .= $info;
          unset($_SESSION['dbg_information'][$key]);
        }
        unset($_SESSION['dbg_information'][$tag]);

        $message .= '</div>';
      }
      unset($_SESSION['dbg_information']);
    }
    $page_top['dbg'] = ['#markup' => $message];
  }
  // Otherwise just simply unset the set dbg_information.
  elseif (isset($_SESSION['dbg_information'])) {
    unset($_SESSION['dbg_information']);
  }
}
