<?php

/**
 * @file
 * Class it up module provides classes based on information Drupal knows about.
 */

use Drupal\block\Entity\Block;

/**
 * Implements hook_preprocess_block().
 *
 * Add the region for the block as a class on the block.
 */
function classitup_preprocess_block(&$variables) {
  // Prevent PHP notices if contrib modules create blocks without this ID.
  if (!empty($variables['elements']['#id'])) {
    $variables['attributes']['class'][] = Block::load($variables['elements']['#id'])->getRegion();
  }
}
