<?php

/**
 * @file
 * Contains micro_sitemap.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function micro_sitemap_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the micro_sitemap module.
    case 'help.page.micro_sitemap':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrate sitemap module with micro sites') . '</p>';
      return $output;

    default:
  }
}
