<?php

/**
 * @file
 * Contains hook implementations.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_view().
 */
function generic_page_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Unset the title in case that display title is not checked.
  if ($entity->getEntityTypeId() == 'paragraph' && $entity->bundle() == 'gp_section') {
    $paragraph = $build['#paragraph'];
    if (empty($paragraph->get('field_gp_section_display_title')->value)) {
      unset($build['field_gp_section_title']);
    }
  }
}
