<?php

/**
 * @file
 * Contains healthcheck.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function healthcheck_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the healthcheck module.
    case 'help.page.healthcheck':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Checks your site to keep it healthy!') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function healthcheck_cron() {
  // Get the Healthcheck service.
  $hc = \Drupal::service('healthcheck');

  // Run cron.
  $hc->cron();
}

/**
 * Implements hook_theme().
 */
function healthcheck_theme($existing, $type, $theme, $path) {
  return [
    'healthcheck_finding'=> [
      'variables' => [
        'finding' => NULL,
        'status' => NULL,
        'key' => NULL,
        'message' => NULL,
        'check' => NULL,
        'check_id' => NULL,
        'tags' => NULL,
        'data' => NULL,
      ],
      'file' => 'healthcheck.theme.inc',
    ],
    'healthcheck_filter_list' => [
      'variables' => [
        'filters' => NULL,
      ],
      'file' => 'healthcheck.theme.inc',
    ],
    'healthcheck_filter' => [
      'variables' => [
        'filter' => NULL,
        'filter_id' => NULL,
        'label' => NULL,
        'description' => NULL,
      ],
      'file' => 'healthcheck.theme.inc',
    ],

    'healthcheck_status' => [
      'variables' => [
        'status' => NULL,
        'label' => NULL,
        'count' => NULL,
        'findings' => NULL
      ],
      'file' => 'healthcheck.theme.inc',
    ],
    'healthcheck_report' => [
      'variables' => [
        'report' => NULL,
      ],
      'file' => 'healthcheck.theme.inc',
    ],
  ];
}

/**
 * Implements hook_healthcheck_tags_alter().
 */
function healthcheck_healthcheck_tags_alter(&$tags) {
  $tags['performance']['label'] = 'Performance';
  $tags['performance']['description'] = t('Check performance and caching configuration.');

  $tags['security']['label'] = 'Security';
  $tags['security']['description'] = t('Perform security and user configuration checks.');

  $tags['content']['label'] = 'Content';
  $tags['content']['description'] = t('Check content for common problems.');

  $tags['seo']['label'] = 'SEO & Analytics';
  $tags['seo']['description'] = t('Examine site for Search Engine Optimization (SEO) and Analytics configuration.');

  $tags['site code']['label'] = 'Site code';
  $tags['site code']['description'] = t('Check site code base.');

  $tags['infrastructure']['label'] = 'Infrastructure';
  $tags['infrastructure']['description'] = t('Check for site hosting infrastructure and operational configuration.');

  $tags['front end']['label'] = 'Front-end & UX';
  $tags['front end']['description'] = t('Theme and user exerience (UX) checks.');
}
