<?php

/**
 * @file
 * Contains commerce_ecpay.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_ecpay_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_ecpay module.
    case 'help.page.commerce_ecpay':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Commerce integration for ECPay') . '</p>';
      return $output;

    default:
  }
}
