<?php

/**
 * @file
 * The Zendesk module helps you to interact with zendesk using Drupal.
 */

require 'vendor/autoload.php';

use Drupal\zendesk;
use Zendesk\API\Client as ZendeskAPI;
use Drupal\user\Entity;

/**
 * Implements hook_permission().
 */
function zendesk_permission() {
  return array(
    'configure zendesk' => array(
      'title'       => t('Configure Zendesk'),
      'description' => t('Configure Drupal settings to communicate with Zendesk.'),
    ),
  );
}

/**
 * Initialization of the zendesk library.
 */
function zendesk_initialize_library() {
  $config    = Drupal::config('zendesk.settings');
  $api_key   = $config->get('zendesk_api_token');
  $user      = $config->get('zendesk_api_mail');
  $subdomain = $config->get('zendesk_subdomain');

  $client = new ZendeskAPI($subdomain, $user);
  $client->setAuth('token', $api_key);

  return $client;
}

/**
 * Check if the user may be be authenticated or synced with zendesk.
 */
function zendesk_user_has_access($account) {
  $zendesk_roles = \Drupal::config('zendesk.settings')->get('zendesk_roles');
  if (!array_sum($zendesk_roles)) {
    // No roles are set, give access.
    return TRUE;
  }
  else {
    $keys = array_keys($account->getRoles);
    foreach ($keys as $key) {
      if ($zendesk_roles[$key] > 0) {
        return TRUE;
      }
    }
  }

  return FALSE;
}
