<?php

/**
 * @file
 * Contains webform_send_multiple_emails.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_send_multiple_emails_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_send_multiple_emails module.
    case 'help.page.webform_send_multiple_emails':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Sends a webform submission via an email to each recipient individually. Creates a "Send Multiple Emails" Webform Handler.') . '</p>';
      return $output;

    default:
  }
}
