<?php

/**
 * @file
 * Provides a small, modern, dependency-free smooth scrolling library.
 */

/**
 * Implements hook_help().
 */
function jumper_help($route_name) {
  if ($route_name == 'help.page.jumper') {
    $output = file_get_contents(dirname(__FILE__) . '/README.md');
    // @todo remove check once Blazy has stable release.
    return function_exists('blazy_parse_markdown') && blazy_parse_markdown($output) ? blazy_parse_markdown($output) : '<pre>' . $output . '</pre>';
  }
  return '';
}
